### ISSUE TITLE
cms_page.publisher_is_draft column doesn't exist with sqlite

### ISSUE THREAD

**Issue by franckbret** [django-cms/django-cms#138]
Hello
I encounter the following error when trying to initialize a new project or when launching example project.

sqlite3.OperationalError
OperationalError: no such column: cms_page.publisher_is_draft

This error occurs even when launching migrate command

This error doesn't occurs with posqtgres

**Comment by rando305** [comment]
how does one go about 'reseting the db?'  I'm using postgres

**Comment by yakky** [comment]
@rando305 unless you use very old django CMS version, it's unlikely that this issue is related to your problem.
Could you open a new issue providing a full description of the problem?
