### ISSUE TITLE
Text plugin removes Microdata

### ISSUE THREAD

**Issue by MichaelMauderer** [django-cms/django-cms#1709]
Microdata entered in a text plugin will be stripped. 
This happens independently of the editor.

Example:

```
<div itemscope itemtype ="http://schema.org/Organisation">
    <h1 itemprop="name">The Spanish Inquisition</h1>
</div>
```

will be reduced to

```
<div>
    <h1>The Spanish Inquisition</h1>
</div>
```

**Comment by FabriceSalvaire** [comment]
We have to add `TEXT_ADDITIONAL_ATTRIBUTES = ('itemscope', 'itemtype', 'itemprop')` in settings
