### ISSUE TITLE
Server error 500 if no accept_language header is present

### ISSUE THREAD

**Issue by o-zander** [django-cms/django-cms#2179]
If a bot like the google bots who does not set the accept_language header is visiting the page without a language prefix and i18n is activated, following error is thrown:

NoReverseMatch: Reverse for 'pages-details-by-slug' with arguments '()' and keyword arguments '{'slug': ''}' not found.

Only happens if DEBUG is False.

**Comment by LiliyaOtchenash** [comment]
debug tool bar - my home tack

'debug_toolbar' -> INSTALLED_APPS
'debug_toolbar.middleware.DebugToolbarMiddleware' -> MIDDLEWARE_CLASSES (at first position)
define STATIC_ROOT and ./manage.py collectstatic
DEBUG_TOOLBAR_PATCH_SETTINGS = False
INTERNAL_IPS = ('127.0.0.1',)
