### ISSUE TITLE
Integrity Error: update or delete on table 'cms_cmsplugin' violates foreign key constraint

### ISSUE THREAD

**Issue by eressler** [django-cms/django-cms#2197]
I've never run into this issue before so I was hesitant to post it here in case it's user error on my part, but I cannot see what is causing this.

Here's a rundown of my setup:

I have a Project Model.  I then have a ProjectCollection model with a m2m relationship to Project.

I have a ProjectCollectionCMSPluginModel which subclasses CMSPlugin and has a fk relationship to ProjectCollection.

And finally I have a ProjectCollectionPlugin which subclasses CMSPluginBase with:
model = ProjectCollectionCMSPluginModel

This setup lets me select a Project collection plugin in the admin and select which collection I want the plugin to display.

How the issue occurs:
1. Add a new Project Collection plugin to a page in the admin.
2. Select which ProjectCollection to display in the plugin from the dropdown menu.
3. Click save and publish the page.
4. Go back into the admin and attempt to delete the Project Collection plugin from the page.

The following error message is then given in the console and the plugin is not deleted:

```
Internal Server Error: /admin/cms/page/13/remove-plugin/
IntegrityError: update or delete on table "cms_cmsplugin" violates foreign key constraint "cmsplugin_ptr_id_refs_id_6702e4c7" on table "cmsplugin_projectcollectioncmspluginmodel"
DETAIL:  Key (id)=(68) is still referenced from table "cmsplugin_projectcollectioncmspluginmodel".
```

It would appear that the one-to-one relation between CMSPlugin and my ProjectCollectionCMSPluginModel is causing a foreign key constraint error when attempting to delete the plugin.

The thing that I don't understand is why this error would be occurring when that relationship setup is built into django.  I don't see what I could be doing wrong that would cause this error this time, when I've never encountered this error before when creating custom plugins.  It seems that deleting the plugin should properly cascade delete.

Here's my full code so you can see what's going on:

Django==1.5.2
django-cms==2.4.2
mptt==0.5.2

PostgreSQL 9.1.4

models.py

```
class Project (models.Model):
    title = models.CharField(max_length=255)
    description = models.CharField(max_length=1000)
    ...

class ProjectCollection (models.Model):
    projects = models.ManyToManyField(Project, related_name='collection')

class ProjectCollectionCMSPluginModel (CMSPlugin):
    collection = models.ForeignKey(ProjectCollection, blank=True, null=True, related_name='plugin_model')
```

cms_plugins.py

```
@plugin_pool.register_plugin
class ProjectCollectionPlugin (CMSPluginBase):
    name = 'Project Collection'
    model = ProjectCollectionCMSPluginModel
    render_template = 'plugins/collections/project.html'

    def render(self, context, instance, placeholder):
        context['instance'] = instance
        context['placeholder'] = placeholder
        return context
```

I've been beating my head against the desk trying to figure this out for half a day and any help would be greatly appreciated.

**Comment by glic3rinu** [comment]
Stumbled here after googling for this error. My app produces a very similar error, not fully understanding why yet, but what I've seen is that the *order* in which Django ORM deletes related objects is non-deterministic, and I believe this explains why some times breaks and sometimes don't.

**Comment by zypro** [comment]
> Stumbled here after googling for this error. My app produces a very similar error, not fully understanding why yet, but what I've seen is that the _order_ in which Django ORM deletes related objects is non-deterministic, and I believe this explains why some times breaks and sometimes don't.

Same here. Locally in my dev enviornment it never appears. And also I can't reproduce it on the server. Sometimes a touch of the wsgi.py helps. Sometimes not...

**Comment by gaster300** [comment]
Okay so for everyone who is having this issue and need a proper solution as to why this happens here it is. IntegrityError SOLVED. So I have been hunting down the internet for some time trying to find the solution to this problem without having to wipe my database and then starting over and I finally did.
the reason why this issue occurs is because the plugin has been placed on your page structure and then you uninstall the plugin without removing it from the page structure. Then when you try to run a 
`./manage cms uninstall plugins "pluginname" `
or any other uninstall method it gives you the integrity error. In addition if you try the solutions above 
`from myapp.models import ProjectCollectionCMSPluginModel`
you may get a "importError:  cannot import name" even if you specified everything correctly. I know this specifically because I had the issue with a cmsplugin_feedback plugin which I had installed. in order to fix this you have to reinstall the exact same plugin or create a plugin with the exact same name make the migrations and and migrate it back into your project. Then after you have done so you would be able to perform a 
`./manage cms uninstall plugins "pluginname" `
or even the solutions from above.
hopefully this solves the issue for anyone who is having it.

**Comment by AllToTheX** [comment]
As a reference for future users, I ran into this same error for a different reason.

CMS uses `models.query.QuerySet.delete(plugins)` to delete plugins on publish.
If your models are in a sub-module of your apps models (eg. `myapp.models.my_awesome_cms_models.FooCMSPluginModel`) and you forgot to add `FooCMSPluginModel` to `myapp.models.__init__`, CMS will happily work with this as you registered the CMSPlugin explicitly.

But once you try to publish a page with this plugin, django can't find the actual model, won't delete the `FooCMSPluginModel` instance and try to delete the CMSPlugin instance resulting in the error mentioned above.

**Comment by tschale** [comment]
> As a reference for future users, I ran into this same error for a different reason.
> 
> CMS uses `models.query.QuerySet.delete(plugins)` to delete plugins on publish.
> If your models are in a sub-module of your apps models (eg. `myapp.models.my_awesome_cms_models.FooCMSPluginModel`) and you forgot to add `FooCMSPluginModel` to `myapp.models.__init__`, CMS will happily work with this as you registered the CMSPlugin explicitly.
> 
> But once you try to publish a page with this plugin, django can't find the actual model, won't delete the `FooCMSPluginModel` instance and try to delete the CMSPlugin instance resulting in the error mentioned above.
> 
> (django-cms == 3.7.1)

I can confirm this.
