### ISSUE TITLE
Selecting the same page for plugin inheritance causes infinite recursion 

### ISSUE THREAD

**Issue by SachaMPS** [django-cms/django-cms#2452]
We'll actually this action by an editor makes no sense i know... But it could happen by accident therefor should be catched.

Steps to reproduce:
- create a page
- add some plugins
- select cms.plugins.inherit from the menu and in it's settings the current page

Result:
maximum recursion depth exceeded while calling a Python object

**Comment by scardine** [comment]
Made this change: https://github.com/scardine/djangocms-inherit/commit/f48b73ac16ad4874207b8f36b6827a3dbfe632b7

Not really fixes the problem but makes the plugin fail more gracefully (and makes the problem fixable by an end-user). May be it is useful for someone.
