### ISSUE TITLE
TemplateDoesNotExist "INHERIT"

### ISSUE THREAD

**Issue by stefanocrosta** [django-cms/django-cms#2608]
I updated to the very last code, and am now getting "INHERIT template does not exist".

I even tried with a blank db creating a first new page...

```
TemplateDoesNotExist at /en/admin/cms/page/add/
INHERIT
Request Method: POST
Request URL:    http://grigio.vm:8000/en/admin/cms/page/add/?language=en&
Django Version: 1.6.2
Exception Type: TemplateDoesNotExist
Exception Value:    
INHERIT
```

**Comment by mollyStark** [comment]
hello, did you solve this problem? cause I've got this problem too and I've no idea why....

**Comment by vandorjw** [comment]
in your project's ```settings.py``` check if you have set the ```CMS_TEMPLATES``` variable.
```
CMS_TEMPLATES = (
    ('page.html', 'Page'),
)
```

If you did, ensure the path to that template is correct
