### ISSUE TITLE
Better support for custom models

### ISSUE THREAD

**Issue by DylannCordel** [django-cms/django-cms#2639]
We, [WebU](/webu) (www.webu.coop), are using DjangoCMS and we need some custom model
support improvments. We would be happy if it could be done in DjangoCMS.
Here is the features we ([ollb](/ollb) an [I](/DylannCordel)) would like to develop :
## CMS page like integration of custom models in admin interface

Purpose :
- Add a link in change_list to load the detail view in the main iframe
- Add an icon link in change_list to edit the model without placeholder

Technical notes :
- The idea is to add a CustomModelAdmin class.
## Easy use of models in Pages

When manipulating a lots of custom models, it would be very handy to have
generic list plugin and generic detail view.
### Generic custom model list plugin

Provide a way to create generic plugin that displays a list of custom models instances.

Available dynamic options to configure the display of the list :
- max number of instances to display
- use a pager or not (is so define a min number of instances per page)
- title of the list
- define parameters for dynamic filters (cf [filters](#filters))
- enable a search form and choose fields available
- enable a sort form and choose fields available
- link to the view page

Available static options to configure the display of the list :
- define a static filter
- define the dynamic filters
- define fields available for search
- define fields available for sort
- enable or not a "create new" link

<a name="filters"></a>Dynamic and static filters

We may want to restrict the displaid list of instances (ie : news.published = True) :
- When creating the Plugin Class, to have a base restriction (static filter)
- When creating the Plugin instance, to have a "contextual" restriction 
  (dynamic filter). ie : 
  - on home page, we only want news.home = True
  - on news page, we want all news from this year
  - on archive page, we want all news from past years.
### Generic custom model detail view
- Provide a generic DetailView with specific permission verification from model, else
  generic permission fallback.
- URL configuration should be automagically discovered if not specified 
  (ie : find a slugfield, else a unique (combination of) field(s).)
## Add a generic way to integrate a custom model in cms_toolbar

Purpose :
- One click access to the custom model admin change list
- Remove page specific stuff menu in cms_toolbar on a detail custom model view  
  In a detail custom model view, the page menu missleads the user because actions
  are related to the app hook page (not the current one, whicho doens't exist in
  fact.
- Add optionaly a custom model specific menu like the page one
- Improve language menu to support hvad if custom model use it
- Improve history menu to support custom model

**Comment by mkoistinen** [comment]
Hey all, this looks like it'd be a nice addition. @DylannCordel whats the status from your side? Been nearly a year since this was opened now.

**Comment by DylannCordel** [comment]
Hi all,

I'll have some "free" days to work on this PR this week :-). But it would be great if I could have some advices or feed-back on the already done code in PR #3034

**Comment by DylannCordel** [comment]
Still a WIP, but I updated [documentation](https://github.com/webu/django-cms/blob/0ff5c76593f49fc63012331922077fe067e3a512/docs/how_to/custom_models.rst) and [tests specifications](https://github.com/webu/django-cms/commit/0ff5c76593f49fc63012331922077fe067e3a512#diff-bb044eb42d669c06165dad8b1802e647) about this feature (and some code but the "how" is less important than the "what")

Feedbacks are welcome : do you think this is coherent with the "Django-CMS way" to help dev to integrate their Custom Model in Django-CMS ?
For exemple, I'm not sure this is a good idea to manage search form and sort form in a CMSPlugin : I think developper should use a view if he needs this type of feature. I would remove those both features.

**Comment by yakky** [comment]
This is just my opinion and has not been discussed within the technical board, but I'd like to have the least amount of code into the CMS core as possible, only the minimum required to get the things simpler for applications like the one you propose or ``aldryn-apphooks-config``. Monolithic projects can be very complicated to maintain and become more and more slow at evolving over the time.
Looking at the PR I see that no core part of the CMS is changed, but it consists of additions, which makes me think that it can be an external application that improves the overall django CMS experience without being a fundamental part of it.

It's just my 2 cents (for real: I'm up to discuss this in details with no prejudice)

**Comment by yakky** [comment]
Sorry, I pressed the wrong button :)

**Comment by FinalAngel** [comment]
If its feasible it should me a separate addon and not core. If the addon performs very good we can consider it being a core addon.

**Comment by auvipy** [comment]
https://github.com/divio/django-cms/pull/3034 should the proposed changes stay on a 3rd party app?

**Comment by FinalAngel** [comment]
@DylannCordel can this be achieved as separate addon from your end?
