### ISSUE TITLE
impossible to modify upload handlers

### ISSUE THREAD

**Issue by czpython** [django-cms/django-cms#3367]
What follows is an hour long error hunt  :smile: 
### Intro

So sometimes it's useful (or necessary) to modify the request's [upload handlers](https://docs.djangoproject.com/en/dev/topics/http/file-uploads/#id1) on the go, one of the main use cases is to tell django to use the temporary file handler instead of in memory, for example when receiving a file that will be parsed (say xls), it's easier to work with a file saved in the file system, than an in memory uploaded file, the way to go about this is simple:

``` python
from django.core.files.uploadhandler import TemporaryFileUploadHandler

def upload_xls(request):
    request.upload_handlers.insert(0, TemporaryFileUploadHandler())
    # view magic here
```

this would tell django to try and upload the file to temporary file in disk.
This approach (encouraged by django) has worked for me on versions less than `3.x` but CMS 3 introduced a refactor of the toolbar which breaks the code above, reason why is that the code above will only work as long as no one calls `request.POST` or `request.FILES` **before** calling `request.upload_handlers` because it doesn't make sense to change upload handlers after upload handling has already started (as stated in docs), so django will raise an `AttributeError` when this happens.
### Issue

When using the required `ToolbarMiddleware`, this middleware will then instantiate  `cms.toolbar.toolbar.CMSToolbar` which then on it's `__init__` method calls `get_language_from_request`, who calls `request.REQUEST.get('language', None)` on the first [line](https://github.com/divio/django-cms/blob/develop/cms/utils/__init__.py#L44), this causes django to merge both `request.GET` and `request.POST` into one, thus breaking the condition of not accessing `request.POST`.

Normally since it's not really a 'bug' it's ok, but this has undocumented and very annoying side effects when working with upload handlers, so I think would be very useful to fix this.
### Proposed solutions

1 - We use a decorator like django's `csrf_exempt` which sets an attribute on the view function called `csrf_exempt` that then tells the `CsrfViewMiddleware` middleware to skip csrf validation for this request.
This is how django solved this same problem because `CsrfViewMiddleware` accesses `request.POST` to check for `csrf` token. So we could have an attribute `cms_toolbar_exempt` that gets checked [here](https://github.com/divio/django-cms/blob/develop/cms/middleware/toolbar.py#L83) and tells cms to not instantiate toolbar. 

2 - We could 'maybe' make [this](https://github.com/divio/django-cms/blob/develop/cms/toolbar/toolbar.py#L55) a lazy object, but think that could get quite complicated.

3 - Simply don't call `request.REQUEST` in `get_language_from_request`, and just call `request.GET` explicitly, or call `request.GET` first and then **as fallback** call `request.POST`, this would then allow me to pass language explicitely to avoid `request.POST` being accessed. Not best solution but easiest.

@digi604 @stefanfoulis

**Comment by fsto** [comment]
It seems like the required middleware 'cms.middleware.toolbar.ToolbarMiddleware' removes any uploaded file (sent via a multipart form request) in request.data which then is just an empty QueryDict. When commenting out ToolbarMiddleware everything works like it should - I get the QueryDict in request.data containing the uploaded file.

A simple setup to reproduce this is to:

1. set up a django project with django-cms and django rest framework.
2. Use ToolbarMiddleware
3. Set up a POST handler inheriting APIView (django rest framework) with `parser_classes = (MultiPartParser, )`
4. Any multipart form data will be removed (which is the issue). request.data is a `<QueryDict: {}>`
5. Comment out 'cms.middleware.toolbar.ToolbarMiddleware' and the file upload handler works as intended.

**Comment by vstoykov** [comment]
@fsto This is because django-rest-framework is using `request.body` directly to construct `request.data` because django-rest-framework supports not only `application/x-www-form-urlencoded` and `multipart/form-data` but allso `application/json' and `application/xml`.

For reference: https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/request.py#L271
