### ISSUE TITLE
CMS.API.Helpers.reloadBrowser not actually reloading the page if url has hash parameter.

### ISSUE THREAD

**Issue by ghost** [django-cms/django-cms#3413]
This happens when editing model using frontend editing form.
When i click the Save button after all the work is done, script passes _window.location.href_(with hash parameter) to reloadBrowser:
https://github.com/divio/django-cms/blob/develop/cms/static/cms/js/modules/cms.modal.js#L550

``` javascript
// ...
// also check that no delete-confirmation is required
if(that.saved && !contents.find('.delete-confirmation').length) {
    that.reloadBrowser(window.location.href, false, true);
} else {
    iframe.show();
// ...
```

It sends ajax request which returns such a result, so none of conditions but the last matches:
https://github.com/divio/django-cms/blob/develop/cms/static/cms/js/modules/cms.base.js#L64

``` javascript
} else if(url) {
    // on_close can also provide a url, reload to the new destination
    that.reloadBrowser(url);
}
```

which just call the same function without ajax parameter, where window.location.href is set to provided url (with hash parameter) 

``` javascript
parent.setTimeout(function () {
    (url) ? parent.location.href = url : parent.location.reload();
}, timeout || 0);
```

As a result I see inifinite spinner in model editing window, because location is not reloaded.

I think, that function which called "reloadBrowser" must reload page on any condition, so parent.location.reload() has to be called regardless whether is there a hash parameter or not.

``` javascript
parent.setTimeout(function () {
    if(url) {
        parent.location.href = url;
    }
    parent.location.reload(); // Explicitly reloading page, not only when empty url passed
    // (url) ? parent.location.href = url : parent.location.reload();
}, timeout || 0);
```

**Comment by thrix** [comment]
Hi, on my site I see that url = 'REFRESH_PAGE' and I end up with 404. So I had to fix the 'if statement' from this fix to:

    if (url && url != parent.location.href && url != 'REFRESH_PAGE') {

to get the page nicely refreshed. Any idea what could be wrong in my case? This mostly happens to me after logout via the cms toolbar on any page ...
