### ISSUE TITLE
Misleading database table name

### ISSUE THREAD

**Issue by czpython** [django-cms/django-cms#3417]
Hello all,

I've noticed an issue when using plugin models outside of the request/response cycle (i.e. in shell or management command)

Basically on plugin models that have not migrated to the new database table name format, the db_table attribute points to the new table name (default from django), this will then cause a DatabaseError when doing something like:

``` python
In [4]: from cmsplugin_filer_image.models import FilerImage

In [5]: images = FilerImage.objects.all()
Out[5]: images

DatabaseError: relation "cmsplugin_filer_image_filerimage" does not exist
LINE 1: ...lugin_filer_image_filerimage"."target_blank" FROM "cmsplugin...
```

This is because the model points to the non patched table name, which causes django to look up the wrong table name in the database.

``` python
In [5]: FilerImage._meta.db_table
Out[5]: u'cmsplugin_filer_image_filerimage'
```

As a temporary fix, I manually import plugin pool and run the patch, like so:

``` python
from cms.plugin_pool import plugin_pool

plugin_pool.set_plugin_meta()
```

I think a better way could be using the model prepared signal to patch individual models as they are registered by django.

/cc @stefanfoulis

**Comment by mitchellrj** [comment]
This however requires the database connection to be present every time Django is started, in situations that are completely unnecessary. For example, during collectstatic. It should catch OperationalError and fail gracefully.

**Comment by yakky** [comment]
The compatibility code will go away in 3.1
