### ISSUE TITLE
Swapped User logic incorrect in Django 1.7

### ISSUE THREAD

**Issue by kevingill1966** [django-cms/django-cms#3436]
in permissionmodels.py there is a piece of logic to determine if the user is swapped. There are two paths through the code, one for Django 1.6 and one for other versions of Django. The wrong branch is taken in Django 1.7. The logic should, in my opinion be, 

if DJANGO_1_6 or DJANGO_1_7:

and DJANGO_1_7 should be imported at the top.

**Comment by linix-mod** [comment]
Moved mentioned migration-models 
> "PageUserGroup" and "PagePermission" 

from original origin in file 

> cms/migrations/0002_auto_20140816_1918.py 

to initial file:

> cms/migrations/0001_initial.py 

and did a sqlmigrate on both files (sqlmigrate cms 0001_initial & sqlmigrate cms 0002_auto_20140816_1918).

Works like a charm without any more modifications!

At https://docs.djangoproject.com/en/1.7/topics/auth/customizing/#substituting-a-custom-user-model  its described that: 

> "AUTH_USER_MODEL is created in the first migration of its app (usually called 0001_initial); otherwise, you will have dependency issues"

 "PageUserGroup" and "PagePermission" access "AUTH_USER_MODEL" thats the reason why they need to be moved to 0001_initial.py file.
