### ISSUE TITLE
Plugin modal window height

### ISSUE THREAD

**Issue by quiqueporta** [django-cms/django-cms#3465]
The height of the plugins modal window is not calculated correctly into the cms.modal.js.
I need to replace this line

``` javascript
var screenHeight = $(window).height();
```

with this

``` javascript
var screenHeight = window.innerHeight;
```

https://github.com/divio/django-cms/blob/develop/cms/static/cms/js/modules/cms.modal.js#L131

**Comment by chris-rose-one** [comment]
I added <!DOCTYPE html> to my template and it worked for a moment but then it didn't.
@m05quit0 setting html css height and width to 100% has done the trick
