### ISSUE TITLE
CMS Menu is only attached in "Draft" mode

### ISSUE THREAD

**Issue by alsoicode** [django-cms/django-cms#3518]
I'm experiencing a strange issue with a CMSAttachMenu - the nodes will only attach when the page is viewed in "draft" mode. I'm using Python 3.4, Django 1.7.

Page Settings:
![page-settings](https://cloud.githubusercontent.com/assets/86738/4664088/20d61720-5541-11e4-86fd-328cb6da8acb.jpg)

"Service" model change list demonstrating that there are "service" instances present. The `is_published` field is not being used to limit nodes that are added:
![services](https://cloud.githubusercontent.com/assets/86738/4664092/2f6a9d74-5541-11e4-8dd7-7f2b5191b5f2.jpg)

Page in "live" mode. Notice there are no navigation nodes added to the "Additional Services" page:
![live-page](https://cloud.githubusercontent.com/assets/86738/4664098/3e816392-5541-11e4-8523-34ea4c91ab9a.jpg)

Page in "draft" mode. Now the navigation nodes are attached:
![draft-page](https://cloud.githubusercontent.com/assets/86738/4664104/45c1f04a-5541-11e4-8889-0c23e1f10bc1.jpg)

Terminal output showing navigation node instances:
![terminal](https://cloud.githubusercontent.com/assets/86738/4664291/da0db5d0-5542-11e4-9535-c91c0f6e9bc7.jpg)

My menu class is as follows. I have hard-coded the url parameter for testing:

```
from cms.menu_bases import CMSAttachMenu
from menus.base import NavigationNode
from menus.menu_pool import menu_pool

from .models import Service

class ServicesMenu(CMSAttachMenu):
    name = 'Services Menu'

    def get_nodes(self, request):
        nodes = []
        services = Service.objects.all()
        for service in services:
            node = NavigationNode(service.title, '/', service.id)
            nodes.append(node)
        return nodes

menu_pool.register_menu(ServicesMenu)
```

What am I doing wrong?

**Comment by JoeJasinski** [comment]
I'm seeing this issue too. I'm only seeing my attached menu in Draft mode.  I'm going to try to publish different ways to see if I can get it to publish.  (The pages that I'm editing has a lot of content, so I don't really want to re-create it)

**Comment by JoeJasinski** [comment]
Looks like I had to publish the page that the menu was attached, and not the subpages ... which is obvious, but less so when the page that the menu is attached had a cms redirect set and is not browseable by the end user.  Visiting the page while already in edit mode, and then publishing did the trick.  Just mentioning in case anyone else encounters this.
