### ISSUE TITLE
Homographs in slugs for different pages and different languages should not raise MultipleObjectsReturned 

### ISSUE THREAD

**Issue by evildmp** [django-cms/django-cms#3548]
Your site has two sibling pages:

```
# a page about sticks
/it/bastone
/fr/canne
/en/cane

# a page about dogs
/it/cane
/fr/chien
/en/dog
```

At present, as soon as you try to publish (it will let you save a draft) the Italian translation, you'll get:

```
MultipleObjectsReturned at /it/cane/
get() returned more than one Page -- it returned 2!
```

Issues to be decided:
- [ ] should we allow the creation of the slug? We would need to stop ignoring the language prefix when processing URLs.
- [ ] if we do, how would we decide what serve when the user asked for `/fr/cane/` - should it serve up `chien` or `canne` (see #3547 on django CMS's page-guessing behaviour)
- [ ] if we don't, we should advise the user of a slug conflict, instead of raising the `MultipleObjectsReturned` error.

**Comment by yakky** [comment]
@evildmp @ojii @mkoistinen further opinion on this?
I don't think we could handle this in 3.1

**Comment by mkoistinen** [comment]
I have no further opinion, the way you outlined it above is the correct way this should be done, IMO.
