### ISSUE TITLE
Document how plugins should 'clean' child plugins on save

### ISSUE THREAD

**Issue by jsma** [django-cms/django-cms#3731]
I found a data corruption error in djangocms-text-ckeditor where it attempts to clean up child plugins (aka plugins that have been removed from the wysiwyg editor). See the ticket for more details on the bug https://github.com/divio/djangocms-text-ckeditor/issues/212

This ticket is to make sure there is a documented path for all plugins (divio or custom) to handle child plugin cleanup correctly without corrupting the database. This will likely require code changes in django-cms but am keeping this to a documentation ticket for the moment until consensus is reached on what needs to be done to resolve this.

**Comment by jsma** [comment]
The ticket mentioned above was fixed by moving the order of operations around. This seems error prone. We should strive to make this simpler so that it's foolproof. This may require users to write their own `clean_plugins` method but have this be called automatically at the bottom of `CMSPlugin.save()` instead of in `CMSPluginBase.save_model()`. This would mean that any API calls would also benefit from the post save cleanup, not just admin/front-end users.

**Comment by yakky** [comment]
While text plugin is really the only one that I know of needing this "special" cleanup, I like the idea of having a documented and supported way to do this, and your suggestion looks sensible

**Comment by Aiky30** [comment]
@yakky Do you have any plans to implement this documentation? I have implemented an invisible fix for this because the ghosting broke the new position based plugin architecture in v4.

**Comment by Aiky30** [comment]
This is fixed in a future version of ckeditor for Django CMS v4: https://github.com/django-cms/djangocms-text-ckeditor/tree/support/4.0.x
