### ISSUE TITLE
Provide documentation on technical architecture of django-cms

### ISSUE THREAD

**Issue by miraculixx** [django-cms/django-cms#4045]
There is ample documentation on how to _use and extend_ django-cms. However, as a novice django-cms developer (with ample django/python experience) I find it quite difficult to debug, let alone fix bugs in the system, e.g. for such cases as #3665.

Questions such as 
- how does a request get resolved, and which view is called (in general, for plugins, for apphooks, for admin in particular)?
- are there any loggers/traces that can be enabled? where to set useful debugging breakpoints?
- how are permissions checked?
- what is the architecture of the javascript front-end? how are user clicks resolved and which part of the system generates a new request, which parts use ajax? 
- is there middleware involved, where?

Specifically I'd like to suggest creating a separate repository to this end, e.g. `django-cms-techdocs`.

Any hints, tips that you guys have from either hard-learned experience or quite simply from designing and developing this otherwise amazing cms are most welcome.

**Comment by yakky** [comment]
@evildmp assigning you to this to elaborate a strategy to cover this

**Comment by Aiky30** [comment]
@evildmp What are your thoughts on this issue, is it still relevant and if so do we need to discuss this further?

**Comment by Aiky30** [comment]
The documentation has come along way since this ticket was opened: http://docs.django-cms.org/en/latest/
