### ISSUE TITLE
cms pages should be ordered by ('site', 'tree_id', 'lft') by default

### ISSUE THREAD

**Issue by stefanfoulis** [django-cms/django-cms#409]
currently they are ordered by ('tree_id','lft'). but then handling a list of pages from multiple sites the pages from the same site are not together.

**Comment by macropin** [comment]
@stefanfoulis what is `lft`?

**Comment by stefanfoulis** [comment]
ha. ``lft`` was from back when we had mptt for the page tree. now we have treebeard and that field no longer exists.

**Comment by macropin** [comment]
Yes, I realise it's removed. I'm trying to export pages from a legacy version and need to get the correct sort order for pages. Does `lft` contribute to page ordering? is `lft + tree_id` the correct calculation for `page weight` for the purposes of ordering?
