### ISSUE TITLE
The menu system sometimes decides that the selected node is the one associated with a draft page, and then "forgets" what is selected.

### ISSUE THREAD

**Issue by lddubeau** [django-cms/django-cms#4118]
### Versions

Django CMS: 3.1.0
Django: 1.7.8
### Steps to reproduce

See the "Observations" section below.
### Expected behavior.

When I click on a navigation menu item, I expect the corresponding `NavigationNode` to have its `selected` field set to `True`. (So that when I render the menu, I can indicate where the user is on the site.)
### Actual behavior.

The `selected` field of the `NavigationNode` which _should_ be set to `True` is not set to `True.`
### Observations

I typically try to submit steps to reproduce the problem but I'm at a bit of a loss here as to how I would reproduce this specific problem. If the developers need a reproducible case, please advise me as what would be the plainest way to provide the desired data.

For diagnosis purposes, I've instrumented `cms.menu.NavExtender.modify`. After the `home=None` line I've added:

```
        class Foo(object):
            publisher_is_draft = None

        fake = Foo()
        print "XXX +++"
        print
        print "MENUS:", "\n".join(
            [repr((m, getattr(menu_pool.menus[m], 'instance', fake)
                   .publisher_is_draft,
                   getattr(menu_pool.menus[m],
                           'cms_enabled', None))) for m in
             menu_pool.menus])
        print
        print "NODES:", "\n".join(
            [repr((n,
                   n.namespace,
                   n.attr.get("navigation_extenders", None)))
             for n in nodes])
        print
        print "SELECTED NODES:", "\n".join(
            [repr((n,
                   n.namespace,
                   n.attr.get("navigation_extenders", None)))
             for n in nodes if n.selected])
        print
        print "XXX ---"
```

Before `removed = []` I've added:

```
        print "YYY +++"
        print
        print "EXTS:", exts
        print
        print "YYY ---"
```

(In an appendix in this report, I've copied and pasted the entire modified `NavExtender`.)

The output I get is:

```
XXX +++

MENUS: ('CMSMenu', None, None)
('UserMenu', None, None)
('BibliographyMenu:5', True, True)
('BibliographyMenu:6', False, True)
('LexicographyMenu:4', False, True)
('LexicographyMenu:3', True, True)

NODES: (<Navigation Node: Home>, 'CMSMenu', None)
(<Navigation Node: Lexicography>, 'CMSMenu', ['LexicographyMenu:4'])
(<Navigation Node: Bibliography>, 'CMSMenu', ['BibliographyMenu:6'])
(<Navigation Node: <django.utils.functional.__proxy__ object at 0x7f7a45b21090>>, 'UserMenu', None)
(<Navigation Node: admin>, 'UserMenu', None)
(<Navigation Node: <django.utils.functional.__proxy__ object at 0x7f7a45b21890>>, 'UserMenu', None)
(<Navigation Node: <django.utils.functional.__proxy__ object at 0x7f7a45b21390>>, 'UserMenu', None)
(<Navigation Node: General Search>, 'BibliographyMenu:5', None)
(<Navigation Node: Manage>, 'BibliographyMenu:5', None)
(<Navigation Node: General Search>, 'BibliographyMenu:6', None)
(<Navigation Node: Manage>, 'BibliographyMenu:6', None)
(<Navigation Node: Search>, 'LexicographyMenu:4', None)
(<Navigation Node: New Entry>, 'LexicographyMenu:4', None)
(<Navigation Node: Search>, 'LexicographyMenu:3', None)
(<Navigation Node: New Entry>, 'LexicographyMenu:3', None)

SELECTED NODES: (<Navigation Node: General Search>, 'BibliographyMenu:5', None)

XXX ---
YYY +++

EXTS: ['LexicographyMenu:4', 'BibliographyMenu:6']

YYY ---
```
#### Some context

`LexicographyMenu` is associated with an apphook. And `BibliographyMenu` is associated with a different apphook.
#### What I see in the data above

For each apphook, there is a `LexicographyMenu` which is associated with a draft page and a `LexicographyMenu` which is associated with a page which is not a draft. Same with `BibliographyMenu`.

For `LexicographyMenu` the menu associated with the draft page appears _after_ the menu associated with the non-draft page.

However, for `BibliographyMenu` the menu associated with the draft page appears **before** the menu associated with the non-draft page.
#### What happens, given the data above

A. The `navigation_extenders` attributes are populated with values referring only to the menus that are associated with the non-draft pages. (I presume this is correct.)

B. When `_mark_selected` runs, it marks as selected the node that belong to the menu item associated with the **draft page**. Note that `_mark_selected` will see the nodes associated with the draft page and with the non-draft page but because the node associated with the draft page comes _first_, and has the same url as the node associated with the non-draft page, the latter is ignored.

C. When `NavExtender` starts removing nodes, it removes the nodes that are associated with the draft pages. (I presume this is correct.)

D. However, the combination of B and C makes it so that the node which was selected by `_mark_selected` is removed, and so by the time `NavExtender` is done, there is no selected node.

The immediate problem is that iterating the keys of a `MenuPool`'s `self.menus` does not have a guaranteed order so sometimes a draft page may come before its non-draft version and sometimes it can be the other way around. Should the order be guaranteed? Or should `_expand_menus` be modified to disallow the presence of nodes for draft pages? I noticed that `_expand_menus` is a [very recent addition to `MenuPool`](https://github.com/divio/django-cms/commit/cf82e7d0d7b7bb59bbeb479fad63db95e54284b4).
### Appendix: the entire instrumented `NavExtender`

In case it is useful. Note that my editor normalizes spaces and other stylistic features, so there may be more modifications than just the instrumentation I've added.

```
class NavExtender(Modifier):

    def modify(self, request, nodes, namespace, root_id, post_cut, breadcrumb):
        if post_cut:
            return nodes
        exts = []
        # rearrange the parent relations
        home = None

        class Foo(object):
            publisher_is_draft = None

        fake = Foo()
        print "XXX +++"
        print
        print "MENUS:", "\n".join(
            [repr((m, getattr(menu_pool.menus[m], 'instance', fake)
                   .publisher_is_draft,
                   getattr(menu_pool.menus[m],
                           'cms_enabled', None))) for m in
             menu_pool.menus])
        print
        print "NODES:", "\n".join(
            [repr((n,
                   n.namespace,
                   n.attr.get("navigation_extenders", None)))
             for n in nodes])
        print
        print "SELECTED NODES:", "\n".join(
            [repr((n,
                   n.namespace,
                   n.attr.get("navigation_extenders", None)))
             for n in nodes if n.selected])
        print
        print "XXX ---"

        for node in nodes:
            if node.attr.get("is_home", False):
                home = node
            extenders = node.attr.get("navigation_extenders", None)
            if extenders:
                for ext in extenders:
                    if ext not in exts:
                        exts.append(ext)
                    for extnode in nodes:
                        if extnode.namespace == ext and not extnode.parent_id:
                            # if home has nav extenders but home is not visible
                            if (node.attr.get("is_home", False)
                                    and not node.visible):
                                extnode.parent_id = None
                                extnode.parent_namespace = None
                                extnode.parent = None
                            else:
                                extnode.parent_id = node.id
                                extnode.parent_namespace = node.namespace
                                extnode.parent = node
                                node.children.append(extnode)
        print "YYY +++"
        print
        print "EXTS:", exts
        print
        print "YYY ---"
        removed = []
        # find all not assigned nodes
        for menu in menu_pool.menus.items():
            if (hasattr(menu[1], 'cms_enabled')
                    and menu[1].cms_enabled and not menu[0] in exts):
                for node in nodes:
                    if node.namespace == menu[0]:
                        removed.append(node)
        if breadcrumb:
            # if breadcrumb and home not in navigation add node
            if breadcrumb and home and not home.visible:
                home.visible = True
                if request.path_info == home.get_absolute_url():
                    home.selected = True
                else:
                    home.selected = False
        # remove all nodes that are nav_extenders and not assigned
        for node in removed:
            nodes.remove(node)
        return nodes
```

**Comment by czpython** [comment]
Hello @lddubeau,
Thanks for the thorough description.

I'm unable to reproduce this on 3.4.x.
Do you still have access to the environment where you can reproduce this bug?

**Comment by Aiky30** [comment]
Hello @lddubeau, 

Thank you very much for your contribution to the django CMS project. The django CMS project has recently joined forces under the banner of the newly founded django CMS Association to revive the development of django CMS. For this reason we have analyzed all pull requests and issues in detail and decided which ones fit the product vision we want to go with django CMS. 

Due to the age of this issue we are unable to safely accept the contribution. If you feel this issue is still required please inform a member of our technical committee: [nicolai@django-cms.org](mailto:nicolai@django-cms.org ).

Nevertheless we thank you for your participation and would like to emphasize that we do not want to discourage you in your contribution to the django CMS project. On the contrary, we encourage everyone who is interested in the success of django CMS to join us!

If you want to learn more about the work of the technical committee, our product vision and how you can become a member of the dCA, you can find all information here:

- [The Technical Committee of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/tech-committee/about.md)
- [Technical Roadmap and Product Vision for django CMS](https://github.com/django-cms/django-cms-mgmt/blob/master/django-cms/roadmap.md)
- [How to become a member of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/association/about.md)

We are looking forward to every companion who would like to shape the future of django CMS together with us! 

If you have any questions, feel free to reach out to Nicolai, our Community Manager: nicolai@django-cms.org 


Sign up for the Association now!
