### ISSUE TITLE
Consider to replace cms_app.py against apps.py

### ISSUE THREAD

**Issue by jrief** [django-cms/django-cms#4600]
CMS developers wishing to use Apphooks, have to add a file named `cms_app.py` to their source root. This in my opinion adds a layer of magic, and should be avoided; 2nd ZEN of Python: “Explicit is better than implicit.”

With the advent of [Django Applications](https://docs.djangoproject.com/en/1.7/ref/applications/), there is no more need to use specially named files. Django, since 1.7 offers this kind of functionality right out of the box for third party apps.

So please consider this issue as a point to start discussion about moving this magic into its indented place.

**Comment by auvipy** [comment]
++1++

**Comment by evildmp** [comment]
I think this is a reasonable idea.

**Comment by czpython** [comment]
Marking this as _Needs expert opinion_ for us to discuss on the board meeting.

I personally am against this change, the reason being that both files do different things.
One (`apps.py`) stores certain metadata for django's use of the app and already has fields which are internal to it like `name` and so on. The other (`cms_apps.py`) registers an application, the same way plugins are registered with the cms, its format is specific to django-cms and as this file keeps evolving (plans are underway to improve application integration), we should keep these separate.

**Comment by yakky** [comment]
I am adding my -1 to @czpython . Files serves different purposes and they are loaded at different times during django startup.

**Comment by jrief** [comment]
@czpython That's not the point that ``apps.py`` and ``cms_apps.py`` serve different purposes. The point is that we should prevent thing happening in magic ways. The name ``cms_apps.py``, for django-CMS has a special meaning and adds a kind of magicness to the project, which can confuse and create errors.

**Comment by yakky** [comment]
I'm ok with removing magic, this should apply to ``cms_toolbars.py``, ``cms_plugins.py``, ``cms_menus.py`` also.
Could you elaborate on your idea @jrief regarding a possible solution?
Declaring the module for appooks, menus, toolbars and plugins in the django app config and iterate over all these during our discovery phase?

**Comment by Aiky30** [comment]
The "magic" of django CMS app configuration and various pools have been replaced by the new App registration / configuration system in v4, here is the logic keeping backward compatibility for < v4 packages configurations: https://github.com/django-cms/django-cms/blob/release/4.0.x/cms/app_registration.py#L152

The idea is to move all of the pools and configuration loading into the cms app configuration. I believe that there is still work to be done to complete the port, but it is very much a stable implementation of the feature.

Closing as this issue appears to be addressed in v4.0.x
