### ISSUE TITLE
Page cache invalidated excessively?

### ISSUE THREAD

**Issue by Jc2k** [django-cms/django-cms#4627]
We've recently upgraded to Django 1.8. We were using `django.contrib.admin.apps.SimpleAdminConfig` (with `admin.autodiscover()` in urls.py). However that doesn't let `django check` detect problems with admin models so we switched to the modern way of doing it.

Unfortunately this means every management command now initialises django cms. This invalidates the page cache.

For us that just outright explodes - if you build AMI's or docker containers in a dedicated build environment (i.e. with no prod access - no postgres, no redis, etc - literally just an isolated box that builds containers or vm images) that means you get an exception like this:

```
   File "/app/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
     utility.execute()                                                         
   File "/app/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 325, in execute
     django.setup()                                                            
   File "/app/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
     apps.populate(settings.INSTALLED_APPS)                                    
   File "/app/local/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
     app_config.ready()                                                        
   File "/app/local/lib/python2.7/site-packages/django/contrib/admin/apps.py", line 22, in ready
     self.module.autodiscover()                                                
   File "/app/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
     autodiscover_modules('admin', register_to=site)                           
   File "/app/local/lib/python2.7/site-packages/django/utils/module_loading.py", line 74, in autodiscover_modules
     import_module('%s.%s' % (app_config.name, module_to_search))              
   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module  
     __import__(name)                                                          
   File "/app/local/lib/python2.7/site-packages/cms/admin/__init__.py", line 11, in <module>
     plugin_pool.plugin_pool.discover_plugins()                                
   File "/app/local/lib/python2.7/site-packages/cms/plugin_pool.py", line 32, in discover_plugins
     invalidate_cms_page_cache()                                               
   File "/app/local/lib/python2.7/site-packages/cms/cache/__init__.py", line 69, in invalidate_cms_page_cache
     version = _get_cache_version()                                            
   File "/app/local/lib/python2.7/site-packages/cms/cache/__init__.py", line 15, in _get_cache_version
     version = cache.get(CMS_PAGE_CACHE_VERSION_KEY)                           
   File "/app/local/lib/python2.7/site-packages/redis_cache/backends/base.py", line 32, in wrapped
     return method(self, client, key, *args, **kwargs)                         
   File "/app/local/lib/python2.7/site-packages/redis_cache/backends/base.py", line 245, in get
     value = client.get(key)                                                   
   File "/app/local/lib/python2.7/site-packages/redis/client.py", line 863, in get
     return self.execute_command('GET', name)                                  
   File "/app/local/lib/python2.7/site-packages/redis/client.py", line 570, in execute_command
     connection.send_command(*args)                                            
   File "/app/local/lib/python2.7/site-packages/redis/connection.py", line 556, in send_command
     self.send_packed_command(self.pack_command(*args))                        
   File "/app/local/lib/python2.7/site-packages/redis/connection.py", line 532, in send_packed_command
     self.connect()                                                            
   File "/app/local/lib/python2.7/site-packages/redis/connection.py", line 436, in connect
     raise ConnectionError(self._error_message(e))                             
 redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:6379. Connection refused.
```

I supposed our build environment could disable the cache or using a dummy in memory one. For now we will revert our change (and lose `manage.py check` functionality) to work around this but I thought it was worth reporting - obviously in our case it flat out doesn't work, but I don't imagine people expect their page cache to be invalidated if they run `manage.py --help`?

Even with the old way of doing this, some gunicorn setups would invalidate their page cache for every worker thread/process/greenlet that is started. I believe some WSGI containers cycle their worker processes every X requests, again causing the page cache to be invalidated. And if you deploy on a platform with autoscaling then starting a new worker to handle extra load is going to invalidate caches?

**Comment by yakky** [comment]
Well, plugins must be discovered whenever the django environment is set up, or you could not reliably run commands, and for good reason you'd ant to invalidate page cache whenever you discover plugins. I think we can only document this behavior
@mkoistinen @FinalAngel ?

**Comment by Jc2k** [comment]
i haven't dug into how plugin discovery interacts with the page cache. Is there an overview somewhere of how it works?

There must be some way of improving this even if we can't fix my use case - I can't believe that running 'manage.py --version' should need to invalidate the cache!

If I was making a page cache I'd make a hash of all my plugins and their versions and use it as a cache key prefix/postfix. This way I'd only seem to clear the page cache when I upgraded or installed a new plugin. and I wouldn't even touch the cache at all to do 'manage.py --help'. Would something like that even remotely work with cms?

**Comment by yakky** [comment]
Plugins do not have a version (not necessarily) and I don't know a way to reliably hash their **code**.
A possibility here, is to move the plugin loading phase from the ``admin.py``

**Comment by Jc2k** [comment]
Delaying plugin loading would certainly fix this for my use case, so :+1: for that!

It will still purge the cache though, just later. So when my web cluster autoscales due to load it will purge the cache. Not the best time to purge caches! So hypothetically, if i could set a key prefix manually at the right time (when ive deployed?), could i remove the call to purge the cache during plugin discovery?

What i'm thinking is, wrap that particular purge with a settings check - `settings.CACHE_PESSIMISTIC`. It would default to `True` and maintain the current behaviour. Or alternatively `settings,CACHE_AGRESSIVE` default to `False`. Then i would set my own cache prefix using one of these:

a) I only use tags and my project is tagged as well. So I can use setuptools foo to freeze my environment an hash it. As i know the name of my projects egg/wheel/etc I can:

    {p.project_name: p.version for p in pkg_resources.require('myproject')}

I just need to sort and hash.

b) For an autoscaling AWS environment i would prebake AMI's with packer. So there i would probably use the id of the packer image as the cache key. New AMI = new software = new cache.

c) For heroku i would look into getting the release number or the sha that is deployed.

So after a new deployment the page cache would effectively be purged, and the plugin pool purge doesn't need to happen. If another node is brought online with the same exact code, no purge is required. For existing users it would continue to purge every time a process is started unless they looked at the cache docs.

Does that sound like something that might work?

**Comment by yakky** [comment]
@Jc2k it sounds way too depending on the deployment environment and it's not something that django CMS can handle
Probably we can discuss whether to add a setting to invalidate cache on project restart or not (enabled by default)
Then it's up to the project owner to provide a way to properly invalidate the cache upon deployment

@mkoistinen @FinalAngel what's your opinion here?

**Comment by Jc2k** [comment]
@yakky totally agree that it's project specific, and what you say sounds like exactly what i'm thinking. What i'm imagining is a new section in the cache documentation that gives some examples of how you can tie your cache invalidation to your deployment environment - which i'm happy to do a PR for. That would be accompanied by the setting that you described.

But i don't know enough about the page cache to know if thats enough - hopefully @FinalAngel and @mkoistinen can help!

**Comment by mkoistinen** [comment]
@Jc2k, I'm happy to help if I can. I recently did a ton of work on the placeholder cache, so, while its fresh in my mind, let me know how I can help. Interesting use-case and sounds like it may become more and more relevant so, let's figure this out.

**Comment by Jc2k** [comment]
@mkoistinen thanks for replying.

I guess the first thing is I want to test my assumptions about the problem:

 * If the page plugins change or are upgraded we *must* purge the cache
 * There is no reliable way to turn the discovered page plugins into a stable cache key - no way to hash the code, and no reliable versions we can use
 * Currently loading page plugins *always* 'purges' the page cache - which is reliable but potentially frequent
 * If using `django.contrib.admin` then even running `manage.py --help` will purge the page cache
 * In docker/Amazon AMI style build environments builds fail because they don't have access to a page cache to purge.
 * In an autoscaling environment adding more instances will also purge the page cache, right when its needed the most!

Does that cover everything?

I don't know if there is some way to improve the page plugin infrastructure so that it does not need to purge the cache at load time - it seems like it would be very hard!

So my suggestion was that the cache key should be something the user can set as a setting:

 * Setting this setting would turn off the mechanism that purges the cache at startup
 * The setting would act as a cache prefix. The user would be responsible for setting this when they deploy:
  * Use anisble/etc to update settings.py with a git sha or other reliable deployment version indicator as teh cache prefix.
  * For AWS, maybe the deployment can reference the AMI ID?
  * For heroku maybe the deployment number can be accessed somehow?
  * In both of these cases you could use the git sha of the project that is being deployed (or the first 8 characters) as a cache prefix
 * The current behaviour is retained as the default.

And the result should be:

 * A new version getting deployed will result in a new cache prefix being used. As far as cms is concerned it will be like it was started with an empty cache.
 * Spinning up more instances will result in the same cache key being used. So they will benefit from the existing page cache instead of purging it.
 * Users can use `django.contrib.admin` without `mange.py` purging the cache even for things like `--help`

Does this sound sane and like something that could be merged?

**Comment by mkoistinen** [comment]
OK, so, in scaled environments, are you attempting to deploy new instances *with their cache pre-populated*? So, for example, if you're using a shared cache server (db cache backend, memcache server or Redis server, etc.), new instances should just start accessing existing content in this cache and certainly should not clear it on startup.

1. I think this is not only very reasonable, but if its not possible to do this now, I think it needs attention. It isn't immediately why the cache "must be cleared on startup". I would say that if this is the current behavior, we should seek to ~~remove~~ fix it.

2. Regarding the cache prefixes, etc. We do currently use a cache prefix in all of the caches I am aware of in the cms. This is set by `CMS_CACHE_PREFIX` and could easily be set by your provisioning scripts and would be a great way to slot in new instances that point to the existing caches, or even to slot in upgraded deployments that all start accessing a fresh cache. This is here already. Provided we fix point 1 above, this is done (to the best of my knowledge).

3. There is caching all over the CMS. In general, this is a good thing =). However, they're not all implemented the same way and I would argue that this is also a good thing. Here's a couple of different implementations that I am aware of:

    1. There are many ad-hoc cache systems througout the cms that use pretty "normal" Django object-level caching. By normal, I mean, compute some key, prefix the key with the value of `CMS_CACHE_PREFIX`, then store/retrieve/invalidate using `cache.get()`/`cache.set()`/`cache.delete()`.

    2. The menu system uses a fairly "normal" cache system, except that it uses the DB to store its keys. While at first glance this seems nonsensical, its not really, because the keys are rather compound and need to be fetched using various sorts of lookups and SQL is pretty ideal for this. I think some performance gains could be made here, however, by shifting the keystore into some intelligent `manager` that permitted the sort of access that we need. But, this doesn't seem that relevant here =)

    3. The page and now the placeholder caches both use a Cache Versioning Strategy. This uses the cache itself to store cache versions. The key to fetch this version is computed in the more classic way using the `CMS_CACHE_PREFIX` et al. Cache invalidation is done by simply changing the version key, this effectively renders all the cached content inaccessible, and it will be left to expire naturally. This strategy is, IMO, the best for this, because we do often get numerous cache invalidation requests in rapid fire succession and with this strategy, we're about as close to a `noop` as we can get. However, even if you deploy a new instance, it should just pick up the correct version if provided the same `CMS_CACHE_PREFIX` string, and march right along with the other instances.

    4. The plugins are currently cached against their parent placeholder object, not using the cache backend at all, but rather attribute injection onto the placeholder on a per-request basis. (I think this needs some attention.)

Getting back to your issue at hand, I think that all we have to do is figure out why the cache is cleared on startup and fix it, or at least make it switchable behavior.

**Comment by Jc2k** [comment]
From the traceback I see when build AMI images i'm hitting this `invalidate_cms_page_cache`:

https://github.com/divio/django-cms/blob/develop/cms/plugin_pool.py#L31

Which i'm hitting via this module level invocation of `discover_plugins()`:

https://github.com/divio/django-cms/blob/develop/cms/admin/__init__.py

Which is imported by django admin autodiscovery. Which means it happens it happens `AppConfig` loads `django.contrib.admin`. (If you use the old backwards compatible version of admin, it will happen when you call `admin.autodiscover()` in urls.py.

This means that `invalidate_cms_page_cache()` is called every time the AppConf registry is fired up or urls.py is loaded (in compat mode). This will increment the version number you describe. In the AppConf case, calling `manage.py check` will do it. And i'm pretty sure ive seen `manage.py --help` do it.

**Comment by mkoistinen** [comment]
As @yakky says above, we do need to discover the plugins for a number of reasons. But, it isn't immediately clear to me why we must invalidate the page cache when discovering plugins. I wonder if this could be fixed simply by removing lines 30 and 31 from the plugin_pool, a lot has changed in caching since they were added. Obviously, testing needs to be done to ensure this is OK, but I would start there.

**Comment by Jc2k** [comment]
So my understanding was that you invalidated the page cache so that any new code that had been deployed that might affect how things are rendered would be applied. If that is the desired behaviour then I can see that you might defer the invalidation to later in the rendering process (and that would stop things like `mange.py --help` invalidating the page cache). But surely it would still need to happen - and without a way to tell "has a deployment happened" it would happen too frequently.

So in my mind, if we remove that `invalidate_cms_page_cache()` call from the plugin_pool code then either:

1. All users of django cms must now bump `CMS_CACHE_PREFIX` when they deploy cms changes.
2. We would need some heuristic to conditionally invalidate the cache.
3. Add a `CMS_CACHE_PURGE_ON_START` setting that defaults to True to retain the current behaviour. If set to `False` then proceed as (1).

What do you think?

**Comment by Jc2k** [comment]
I have probably been making assumptions about what is actually stored in the page cache - could you clarify that?

And point (iv) are you talking about the plugin itself? (Python object instances) Or are you talking about html fragments rendered by said plugins?
