### ISSUE TITLE
Plugins from deleted translation remain available in 'published' mode

### ISSUE THREAD

**Issue by Moini** [django-cms/django-cms#4983]
I'm not sure if this is a problem we've created for ourselves, a wrong setting or a real bug, but I really hope that you can help.

When I delete a translation of a page via the cms toolbar: 'Language -> Delete <language> translation', then in the pages overview in the admin, the little dot goes white (no translation). 
In Edit mode for the corresponding language's page, there's a button for the 'Page settings' (again, as if no translation exists), but in Live mode, the plugins shown are still those that I intended to delete. Breadcrumbs / Page title are the English ones.

Screenshot of the problem: https://launchpadlibrarian.net/236056894/inkscape-autosave-1000-2016_02_02_18_54_54-001.svg

Publishing the English page doesn't help (I've seen a bug report about moderation causing a similar issue, where this was mentioned as a workaround, and we've got a moderation app installed - but it's probably not the same app, or at least it's not used for moderating pages).

We are currently using Django 1.8.7. and Django-cms 3.2.0. The problem was also there with Django 1.7.7 and Django-cms 3.1.3 (that's where the screenshot is from).

The relevant part of our settings file starts here: http://bazaar.launchpad.net/~inkscape-webadmin/inkscape-web/inkscape-web/view/head:/inkscape/settings.py#L194

The intent is that 
1. Pages that are not translated are still available in the menu for that language, so that all menues in all languages are complete.
2. Pages that are not translated are filled in with their English counterpart, but the users still stay in their own language on the website, so they can access other, translated pages via the menu.

This works fine.

Our own bug for this is https://bugs.launchpad.net/inkscape-web/+bug/1539992

**Comment by Moini** [comment]
For others who encounter this problem:
It works correctly if you 'Empty all' in structure mode before deleting the language.

(Empty all in 3.1.3 does no longer empty all plugins in all translations, so it's a safe operation again).

**Comment by czpython** [comment]
@Moini 
Hello,

Sorry for the delayed response.. we've been quite busy with the 3.3 release.

There's a link in the ticket description to your settings, have they been updated since the posting of this ticket? If so can you provide us with the settings at the time of the issue?

I'm a bit confused about the steps to reproduce, can you clarify a bit more?
Here's what I've tried:

1. Created english page
2. Added english content to page
3. Published english translation
4. Created german translation
5. Added german content to page
6. Published german translation
7. Deleted german translation using the "Delete translation" menu option
8 Opened deleted german translation url and got 404 (expected).

**Comment by Moini** [comment]
@czpython : Sorry for the late reply (I've been busy, too ;-) ), and thank you for taking a look into this!

Settings at the time of the issue (but it still happens just like before):
http://bazaar.launchpad.net/~inkscape-webadmin/inkscape-web/inkscape-web/view/1065/inkscape/settings.py

So this is what I do:

- Go to a page in a different language (say, French this time)
- Select to edit the page
- Select to 'Delete French translation', get confirmation dialog that says something about plugins being deleted, confirm. Page is now in edit mode, but empty.
- Leave edit mode by adding ?edit_off to the url (can't leave it directly any other way, there's no button for it in the toolbar)

Result:
Page contents is still there in French, toolbar offers to 'Create' the page, in the django-cms admin interface for 'Pages', the little dot is white, as if no translation exists. This is not a caching issue, as locally, we do not use any caching.

If useful, I can upload the development db or the full project directory (but the pythonenv and dependencies will need to be re-installed).

**Comment by czpython** [comment]
@Moini 
Thanks for the update.
I've been quite busy with permissions, will try to get to this no later than next week.
