### ISSUE TITLE
Unable to run tests with postgres

### ISSUE THREAD

**Issue by ghost** [django-cms/django-cms#5262]
I'm slowly adding tests to a project and getting it to run on travis. It works fine with sqlite, but fails with postgres. The postgres and sqlite database backends raise different exceptions in the following block, and only the sqlite one is caught:

[premissionsadmin.py](https://github.com/divio/django-cms/blob/develop/cms/admin/permissionadmin.py#L48)

```
try:
    threshold = threshold and get_user_model().objects.count() > threshold
except OperationalError:
    threshold = False
```

When starting tests (and the database is empty), this operation throws an error. It is not caught in postgres.
### Postgres:

```
django.db.utils.ProgrammingError: relation "accounts_user" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "accounts_user"
```
### Sqlite (patched code to see actual exception):

```
django.db.utils.OperationalError: no such table: accounts_user
```

Now I'm not sure if this is a django issue or cms, but I thought I'd start here.

Potential fix: catch both `OperationalError` and `ProgrammingError` in that catch block.

CMS: 3.2.5
Django: 1.9.6
Postgres: 9.4.7

**Comment by Aiky30** [comment]
As the test suite runs the tests using Postgres I'm assuming this is now rectified.
