### ISSUE TITLE
django CMS should support Unicode slugs

### ISSUE THREAD

**Issue by evildmp** [django-cms/django-cms#5297]
Django has recently implemented support for Unicode slugs.

See https://github.com/django/django/pull/4518 for the implementation and https://code.djangoproject.com/ticket/16501 for the original ticket.

**Comment by evildmp** [comment]
The [SlugField](https://docs.djangoproject.com/en/1.9/ref/forms/fields/#slugfield) now has an optional ``allow_unicode`` parameter (default is ``False``).

Would it be possible to provide a CMS setting that controls whether django CMS slugs can accept Unicode? This way, the user of a site with Django 1.9 and newer can enable Unicode slugs, but it won't affect older versions.

**Comment by czpython** [comment]
@evildmp 
As with other features, would you mind moving this to the djangoCMS developers list for us to discuss there? Thanks!

**Comment by Alir3z4** [comment]
Any news or update on this ?
we still can't set unicode slugs on cms pages which is annoying.

I found this issue link from google and http://support.divio.com/project-types/django-cms/unicode-characters-in-url-slugs and so far I couldn't find any other information.

Supporting unicode slugs is very important

**Comment by evildmp** [comment]
As Django 1.8, the last version not to support `allow_unicode`, is now long in the past, I think that this is small but significant question that should be re-opened here. It doesn't seem to be the kind of thing that should require much deliberation.

**Comment by petersiucom** [comment]
***django CMS should support Unicode slugs***

Hi All,

I tried to modified it in my project to allows unicode slugs.
cms/models/titlemodels.py
slug = models.SlugField(_("slug"), max_length=255, db_index=True, unique=False, allow_unicode=True)

it doesn't work, ** it complaint 'Slug must not be empty.' **
django version: 1.11.26
Django-CMS version: 3.7

**any update for this issue?**
thanks all
