### ISSUE TITLE
Copying pages does not update overwrite-URL

### ISSUE THREAD

**Issue by petrklus** [django-cms/django-cms#5311]
When a page is copied, the overwrite-URL is copied as well. This causes the page to stop working as there are multiple matches for the URL:

```
MultipleObjectsReturned: get() returned more than one Page -- it returned 2!
  File "django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "cms/views.py", line 43, in details
    page = get_page_from_request(request, use_path=slug)
  File "cms/utils/page_resolver.py", line 118, in get_page_from_request
    page = get_page_from_path(path, preview, draft)
  File "cms/utils/page_resolver.py", line 74, in get_page_from_path
    return get_page_queryset_from_path(path, preview, draft).get()
  File "django/db/models/query.py", line 338, in get
    (self.model._meta.object_name, num)
```

[More info](https://app.getsentry.com/share/issue/37353838372e313239333335323933/)

Changing the overwrite URL to something different fixes the issue, however, it is very counter-intuitive for our users.

I have also seen errors in the slug generation for the same page - maybe there is an edge case connected to the overwrite URL as well?

```
RuntimeError: maximum recursion depth exceeded
  File "django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "django/views/decorators/http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "cms/admin/pageadmin.py", line 1030, in move_page
    page.move_page(tb_target, tb_position)
  File "cms/models/pagemodel.py", line 228, in move_page
    page_utils.check_title_slugs(moved_page)
  File "cms/utils/page.py", line 95, in check_title_slugs
    title.slug = get_available_slug(title)
  File "cms/utils/page.py", line 84, in get_available_slug
    return get_available_slug(title, slug)
  File "cms/utils/page.py", line 84, in get_available_slug
    return get_available_slug(title, slug)
...repeated
```

[More info](https://app.getsentry.com/share/issue/37353838372e313239333335303938/)

**Comment by petrklus** [comment]
The path check probably needs to be added here:

https://github.com/divio/django-cms/blob/develop/cms/models/pagemodel.py#L518

Thoughts @czpython ?

**Comment by petrklus** [comment]
@czpython  - proposed fix: https://github.com/cnk-digital-solutions/django-cms/commit/c35ab4459dc1a20a27db029053d0de1eacbdfb92 
(not thoroughly tested)

**Comment by petrklus** [comment]
Could you guys please confirm if this is indeed a recognised issue?

**Comment by czpython** [comment]
@petrklus 
Hey, I can confirm the maximum recursion issue.
It's preventing me from copying a page with overwrite url.
Did you use the admin UI to copy the page?

**Comment by petrklus** [comment]
@czpython that's correct - I've used the copy function in the admin UI. Does my fix make sense? I have not had a chance to test it out properly but I do not see a reason to copy overwrite URLs, feels safe to remove to me. From the user's perspective, they copy pages to get the content, not the URL structure/settings (our users at least).

**Comment by czpython** [comment]
@petrklus 
The proposed fix looks ok however I'd like to confirm with the others if removing the url override is the way to go. Honestly I'd like to keep the url override and treat the path the same as a slug where we add ``-x`` to the end. /cc @divio/django-cms-core

**Comment by petrklus** [comment]
Just following up on this, is this still unresolved issue?

**Comment by petrklus** [comment]
@czpython Any progress on this? I am getting a bit tired of explaining to our clients that they cannot simply copy any page but they need to check into overwrite URLs first.

**Comment by czpython** [comment]
Hello @petrklus,
I'll put this on the agenda for next week's board meeting.
Thanks for the follow-up

**Comment by petrklus** [comment]
Thank you very much @czpython, much appreciated!

**Comment by czpython** [comment]
Hello @petrklus,

We had a long discussion about this.
The conclusion was to go with your suggestion (setting the override to false), there were many other suggestions but each brought on more complications.

Would you be able to contribute this with tests?

**Comment by petrklus** [comment]
Hello,

sorry for the delay in replying @czpython - is there any quick-start guide to get me set up with Django CMS test environment? I am afraid I've not been exposed to this side much.

**Comment by czpython** [comment]
Hello @petrklus,
We can land this on 3.3.x and 3.4.x.
So your PR should use 3.4.x as a base.
Here's a quick guide to setting up the tests:

1. Fork the repo
2. Create a virtualenv
3. Activate virtualenv
3. Clone your cms fork
4. Install test dependencies (``pip install -r django-cms/test_requirements/django-1.8.txt``)
5. Go into the django-cms folder and run `python manage.py test`

You can find more information in our [docs](http://docs.django-cms.org/en/release-3.4.x/contributing/testing.html#running-tests).

**Comment by petrklus** [comment]
@czpython on branch develop, I am getting this when installing reqs:

```django-cms petr$ pip install -r test_requirements/django-1.8.txt
You are using pip version 7.0.3, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting https://github.com/fladi/django-treebeard/archive/django-1.10.zip (from -r test_requirements/requirements_base.txt (line 5))
  HTTP error 404 while getting https://github.com/fladi/django-treebeard/archive/django-1.10.zip
  Could not install requirement https://github.com/fladi/django-treebeard/archive/django-1.10.zip (from -r test_requirements/requirements_base.txt (line 5)) because of error 404 Client Error: Not Found
Could not install requirement https://github.com/fladi/django-treebeard/archive/django-1.10.zip (from -r test_requirements/requirements_base.txt (line 5)) because of HTTP error 404 Client Error: Not Found for URL https://github.com/fladi/django-treebeard/archive/django-1.10.zip
```

Any tips?

**Comment by czpython** [comment]
@petrklus Please use release/3.4.x as the base branch.

**Comment by Aiky30** [comment]
Hello @petrklus 

Thank you very much for your contribution to the django CMS project. The django CMS project has recently joined forces under the banner of the newly founded django CMS Association to revive the development of django CMS. For this reason we have analyzed all pull requests and issues in detail and decided which ones fit the product vision we want to go with django CMS. 

Due to the age of this issue we are unable to safely accept the contribution. If you feel this issue is still required please inform a member of our technical committee: [nicolai@django-cms.org](mailto:nicolai@django-cms.org ).

Nevertheless we thank you for your participation and would like to emphasize that we do not want to discourage you in your contribution to the django CMS project. On the contrary, we encourage everyone who is interested in the success of django CMS to join us!

If you want to learn more about the work of the technical committee, our product vision and how you can become a member of the dCA, you can find all information here:

- [The Technical Committee of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/tech-committee/about.md)
- [Technical Roadmap and Product Vision for django CMS](https://github.com/django-cms/django-cms-mgmt/blob/master/django-cms/roadmap.md)
- [How to become a member of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/association/about.md)

We are looking forward to every companion who would like to shape the future of django CMS together with us! 

If you have any questions, feel free to reach out to Nicolai, our Community Manager: nicolai@django-cms.org 


Sign up for the Association now!
