### ISSUE TITLE
Creating a User Page for an existing user.

### ISSUE THREAD

**Issue by Eraldo** [django-cms/django-cms#5328]
How can I add a `CMS user page` for an already existing user?

**Comment by FinalAngel** [comment]
Hello, please make sure to submit questions within the appropriate channels on either the [User Mailing List](https://groups.google.com/forum/#!forum/django-cms), IRC (freenode#django-cms) or [Stackoverflow](http://stackoverflow.com/questions/tagged/django-cms).

You can find additional information on our [support](django-cms.org/support) page.

**Comment by czpython** [comment]
@FinalAngel 
This is a bug.

**Comment by Eraldo** [comment]
I see. Thank you for the reply.

I took a closer look and am a little confused now. My question of how to do what I asked is answered by your reply. However I am confused about the intent of User Pages in general.
I thought user pages where there so that cms users could create other users.
I might have misunderstood the concept.
Now I think it is there to create agents which are able to do stuff in the cms which just happen to use the user model to authenticate since that is how permissions are implemented in the cms. Is that so? (trying to grasp the purpose and intention of it)
