### ISSUE TITLE
Clarify PlaceholderField usage

### ISSUE THREAD

**Issue by czpython** [django-cms/django-cms#5342]
We should document that a PlaceholderField only creates the placeholder when the object it's
attached to is saved.

This means if the placeholder field is added to a model that had existing objects, all those objects
need to be resaved for the CMS to create the necessary placeholders.

Source https://github.com/divio/django-cms/issues/4265

**Comment by Aiky30** [comment]
As placeholder field is deprecated in V4 closing this for now.

**Comment by useHTML5** [comment]
> As placeholder field is deprecated in V4 closing this for now.

Where I can read about new in v4 and deprecations?

**Comment by Aiky30** [comment]
@useHTML5 v4 is still heavily in the development phase with no fully agreed approach to a community release just yet. We are however currently trying to clean the codebase and Github for the 3.x release stream. To keep up to date you may find the following information useful. :-)

If you want to learn more about the work of the technical committee, our product vision and how you can become a member of the dCA, you can find all information here:

- [The Technical Committee of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/tech-committee/about.md)
- [Technical Roadmap and Product Vision for django CMS](https://github.com/django-cms/django-cms-mgmt/blob/master/django-cms/roadmap.md)
- [How to become a member of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/association/about.md)

We are looking forward to every companion who would like to shape the future of django CMS together with us! 

If you have any questions, feel free to reach out to Nicolai, our Community Manager: nicolai@django-cms.org 


Sign up for the Association now!
