### ISSUE TITLE
Alias plugin is always cached

### ISSUE THREAD

**Issue by sunfirester** [django-cms/django-cms#5403]
I have been using the alias plugin to duplicate two different headers across pages on my site. I have user specific data in the header itself, which means I can't cache the header placeholder. It seems that when I create an alias to my header placeholder, all the user data is cached.

I can confirm this is happening on pages with the alias plugin, and not on pages with original placeholders.

Thanks in advance.

**Comment by sunfirester** [comment]
I created a PR for this: #5404

**Comment by FinalAngel** [comment]
@divio/django-cms-core is this okay to merge?

**Comment by yakky** [comment]
I think there might be a way to "inherit" caching setting from contained plugins, as a more general solution

**Comment by mkoistinen** [comment]
@sunfirester I'm delighted that you're providing a proposed fix for your issue! Thank you! However, please note that 3.2.5 introduced the get_cache_expiration() method that works along side the cache attribute (which was retained for convenience and backwards compatibility. I've made a similar note on your PR, but perhaps we can work together to find the best solution here. I was planning to do some work on the Alias plugin soon anyway. =)
