### ISSUE TITLE
PlaceholderAdminMixin is required for placeholders outside of CMS

### ISSUE THREAD

**Issue by czpython** [django-cms/django-cms#5410]
When implementing placeholders outside the CMS using a `PlaceholderField`, it's required for the model with the `PlaceholderField` to have a registered admin class that subclasses from `PlaceholderAdminMixin`.

The documentation mentions `PlaceholderAdminMixin` but does not emphasize that it's required.

Original report comes from https://github.com/divio/django-cms/issues/5178

**Comment by yakky** [comment]
Just as we are at this, we can document the fact that if the model with ``PlaceholderField`` uses ``django-polymorphic`` the parent model must be registered for ``PlaceholderAdminMixin`` to work

**Comment by mkoistinen** [comment]
I agree. It isn't entirely clear *anywhere* what the purpose of the PlacholderAdminMixin is (short of reading code), so thanks for making this into an Issue.

**Comment by Aiky30** [comment]
PlacholderAdminMixin is removed in v4.0.x, this issue will become irrelevant in the future. Closing for now.
