### ISSUE TITLE
Get rid of thread user

### ISSUE THREAD

**Issue by czpython** [django-cms/django-cms#5411]
Public discussion https://groups.google.com/forum/#!topic/django-cms-developers/T9OtsDl8qcQ

Related tickets:

https://github.com/divio/django-cms/issues/5328
https://github.com/divio/django-cms/issues/3532
https://github.com/divio/django-cms/issues/3863

**Comment by paulhtremblay** [comment]
Any update on this? Or there any quick fix so I can get on with unit testing?

**Comment by paulhtremblay** [comment]
No update?
