### ISSUE TITLE
We're still using the removed SEND_BROKEN_LINK_EMAILS settings.

### ISSUE THREAD

**Issue by evildmp** [django-cms/django-cms#5417]
In our code: https://github.com/divio/django-cms/search?utf8=✓&q=SEND_BROKEN_LINK_EMAILS

But, `SEND_BROKEN_LINK_EMAILS` was [removed in Django 1.8](https://docs.djangoproject.com/en/1.9/internals/deprecation/#deprecation-removed-in-1-8).

Instead, developers should add `django.middleware.common.BrokenLinkEmailsMiddleware` to the `MIDDLEWARE_CLASSES` setting.

**Comment by evildmp** [comment]
When this is resolved, an updated note needs to be added to https://github.com/divio/django-cms/blob/develop/docs/reference/templatetags.rst#page_url

**Comment by Aiky30** [comment]
I imagine that this was resolved long ago due to the fact that this feature was deprecated in Dj 1.8 and we're now supporting 3.1.

**Comment by Aiky30** [comment]
I'm wrong, this is still an issue. Checked our docs and this isn't documented anywhere. Reopening for now.

**Comment by fsbraun** [comment]
Will create a PR in October.

**Comment by fsbraun** [comment]
Fixed by #7401 now mentioning the Django middleware settings. PR to cover the middleware settings in tests is coming up ...
