### ISSUE TITLE
Contributing documentation issues

### ISSUE THREAD

**Issue by jsma** [django-cms/django-cms#5445]
There are currently some significant issues with following the "Contributing documentation" guide. 

I've fixed a couple in #5444 but there are others that have less obvious solutions.

For example, most of the `make` commands fail unless the virtualenv is in docs/env (I happen to use `pyenv` to manage my virtualenvs). 

I realize that the existing hard-coded paths make some of the magic `make` commands possible, but what balance should be struck between compatibility with other environments? As an occasional docs contributor, I'd be content with the usual `sphinx-build` commands that I could copy and paste from the documentation vs `make` shortcuts that don't work in my environment. But that's just me. What do others need/want?

There are also bugs with some of the dependencies in docs/requirements.txt.

`pyenchant` is not currently PY3 compatible but looks to be on the verge of releasing a [PY3 compatible release](https://github.com/rfk/pyenchant/commit/edc6895f0ab733fcc9a0209bb4e11325dc6caacd). 

There is a bug in sphinxcontrib-spelling that affects all Python versions and I've submitted a quick [pull request](https://bitbucket.org/dhellmann/sphinxcontrib-spelling/pull-requests/5/use-https-with-pypipythonorg/diff) to fix it.

I'm not well versed in the testing infrastructure in place here. Is there a reasonably simple way to include tests that confirm that the documentation build instructions work across all supported versions of Python?

**Comment by FinalAngel** [comment]
Thanks for the report @jsma Is this something you can checkout @evildmp ? Or @jsma would you be able to open a PR to address those issues?

**Comment by jsma** [comment]
I realize this isn't a very focused issue. I'm looking for feedback/guidance on the preferred path forward on the following items:

- Should the Makefile shortcuts assume responsibility for creating the virtualenv? Or can we merely document this as the first step so users can manage virtual environments using their preferred tools?
- How do we go about testing that the documentation builds on supported platforms?

For the issues with the external requirements, is it worth noting in the documentation that there are currently issues with these two packages? Or cross our fingers that we see new releases soon? I could update the pyenchant requirement to point to `git+https://github.com/rfk/pyenchant.git`, is that acceptable? We'd still have the broken sphinxcontrib-spelling package though.

**Comment by jsma** [comment]
FYI, sphinxcontrib-spelling is [now fixed](https://bitbucket.org/dhellmann/sphinxcontrib-spelling/pull-requests/5/use-https-with-pypipythonorg/diff#comment-20174001) but no official PyPI release yet.

**Comment by evildmp** [comment]
@jsma Still no official release yet. Happy to have a chat about all this on IRC at some point if you like.

**Comment by jsma** [comment]
Traveling for work at the moment. Btw, @dhellmann just released an update on PyPI for sphinxcontrib-spelling, so that's working again. There's also an open ticket for https://github.com/rfk/pyenchant/issues/84 requesting a new release.

**Comment by jsma** [comment]
A new version of pyenchant has been released (1.6.7). So now all issues with the requirements file should be resolved (should those requirements be pinned though?).

The remaining TODOs are:

1. Determine whether the documentation for *building* documentation should be more general rather than dependent on an opinionated Makefile.
1. If possible, enable automatic testing of building the docs on supported platforms.

With feedback, I can make a PR to address # 1. For # 2, I'm not familiar with Travis or the django-cms testing infrastructure to know whether this is possible.
