### ISSUE TITLE
Refactor PageUser and PageUserGroup

### ISSUE THREAD

**Issue by czpython** [django-cms/django-cms#5517]

**Comment by gignosko** [comment]
Is there an update on this? We're getting the same issue mentioned in 4225 and would love some kind of work around.

**Comment by mkoistinen** [comment]
@czpython @yakky Is there any plans for this issue at this time? Is this field `PageUser.created_by` actually used by anything? (AKAICT, no) Can we deprecate this field starting the next release and plan to remove it in a near-term subsequent release?

**Comment by creyD** [comment]
@gignosko Could you create another PR for this? @mkoistinen As far as I can see it is used for some of the permissions. So I am not quite sure about entire removal, but we could definitely rename it or opt for the One-To-One-Field instead of the PageUser inheriting from the default user.

**Comment by creyD** [comment]
Further discussed in #7225 7225
