### ISSUE TITLE
Error when running migrations on MySQL 8+ or MariaDB

### ISSUE THREAD

**Issue by LouWii** [django-cms/django-cms#5716]
Hi there,

I have an error I'm unable to fix.

Brand new virtualenv, new database. Mysql 5.5.42

When I'm trying to run migrations for django cms, I keep having an issue with `0008_auto_20150121_0059`

Error message is `ValueError: Found wrong number (0) of constraints for cms_page(publisher_is_draft, application_namespace)`

Stack trace

```
(env) iMac-de-Louis:mysite louis$ python manage.py migrate cms 0008_auto_20150121_0059
Operations to perform:
  Target specific migration: 0008_auto_20150121_0059, from cms
Running migrations:
  Rendering model states... DONE
  Applying cms.0008_auto_20150121_0059...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/louis/Documents/WebProjects/Python/carspotter_beta2/carspotterbeta2/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/Users/louis/Documents/WebProjects/Python/carspotter_beta2/carspotterbeta2/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/louis/Documents/WebProjects/Python/carspotter_beta2/carspotterbeta2/env/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/louis/Documents/WebProjects/Python/carspotter_beta2/carspotterbeta2/env/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/Users/louis/Documents/WebProjects/Python/carspotter_beta2/carspotterbeta2/env/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/Users/louis/Documents/WebProjects/Python/carspotter_beta2/carspotterbeta2/env/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/Users/louis/Documents/WebProjects/Python/carspotter_beta2/carspotterbeta2/env/lib/python2.7/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/louis/Documents/WebProjects/Python/carspotter_beta2/carspotterbeta2/env/lib/python2.7/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/Users/louis/Documents/WebProjects/Python/carspotter_beta2/carspotterbeta2/env/lib/python2.7/site-packages/django/db/migrations/operations/models.py", line 359, in database_forwards
    getattr(new_model._meta, self.option_name, set()),
  File "/Users/louis/Documents/WebProjects/Python/carspotter_beta2/carspotterbeta2/env/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 320, in alter_unique_together
    self._delete_composed_index(model, fields, {'unique': True}, self.sql_delete_unique)
  File "/Users/louis/Documents/WebProjects/Python/carspotter_beta2/carspotterbeta2/env/lib/python2.7/site-packages/django/db/backends/mysql/schema.py", line 80, in _delete_composed_index
    return super(DatabaseSchemaEditor, self)._delete_composed_index(model, fields, *args)
  File "/Users/louis/Documents/WebProjects/Python/carspotter_beta2/carspotterbeta2/env/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 349, in _delete_composed_index
    ", ".join(columns),
ValueError: Found wrong number (0) of constraints for cms_page(publisher_is_draft, application_namespace)
```

Pip freeze

```
cmsplugin-filer==1.0.1
Django==1.8.8
django-appconf==1.0.2
django-classy-tags==0.8.0
django-cms==3.2.5
django-compressor==2.1
django-extensions==1.6.1
django-filer==1.1.1
django-formtools==1.0
django-mptt==0.8.6
django-polymorphic==0.8.1
django-rest-swagger==0.3.10
django-reversion==1.8.7
django-sekizai==0.10.0
Django-Select2==4.3.2
django-treebeard==4.0.1
djangocms-admin-style==1.2.4
djangocms-attributes-field==0.1.1
djangocms-column==1.7.0
djangocms-googlemap==0.5.2
djangocms-inherit==0.2.2
djangocms-link==2.0.1
djangocms-style==1.7.0
djangocms-text-ckeditor==3.2.1
djangorestframework==3.2.5
drf-nested-routers==0.11.1
easy-thumbnails==2.3
html5lib==1.0b8
MySQL-python==1.2.5
Pillow==3.3.1
pytz==2016.6.1
PyYAML==3.12
rcssmin==1.0.6
rjsmin==1.0.12
six==1.10.0
Unidecode==0.4.19
wheel==0.26.0
```

The migration file content (relevant part):

```
migrations.AlterUniqueTogether(
            name='page',
            unique_together=set([('reverse_id', 'site', 'publisher_is_draft'), ('publisher_is_draft', 'site', 'application_namespace')]),
        )
```

What am I missing ? Packages incompatibility ? MySQL version issue ? Django version issue ?
I even updated to Django 1.8.14 but still the same error.

Thanks !

**Comment by LouWii** [comment]
I've installed Django CMS 3.4 on a new virtualenv, same issue when running `migrate` for the first time.

I wonder if that's an issue with MySQL.

**Comment by derek-adair** [comment]
Did you use the djangocms-installer or did you install this manually?

If you did so manually, this is almost certainly a config issue.  I believe if you [install manually](http://docs.django-cms.org/en/release-3.3.x/how_to/install.html) you need to define at least one page (and i think) one template associated with said page.

**Comment by Doormouse2House** [comment]
I think that there is something more fundamental with this issue.  I have hit it as well, on an automated installation, using Ubuntu, MySQL & mysqlclient.  I'll keep looking, but if anyone has some suggestions as to what could have caused this I would appreciate that.

**Comment by czpython** [comment]
Hello @Doormouse2House,
Can you post django, python, cms and mysql versions?

**Comment by Doormouse2House** [comment]
CMS is 3.4.1
--------
(venv) $ mysql --version
mysql  Ver 14.14 Distrib 5.7.16, for Linux (x86_64) using  EditLine wrapper
(venv) $ django-admin --version
1.8.17
(venv) $ python --version
Python 3.5.2

**Comment by Doormouse2House** [comment]
I'm new to Django.  Given the description of [the migration that causes this](https://github.com/divio/django-cms/blob/47912ae61a703acdaaf87ad8c42e45ded486afda/cms/migrations/0008_auto_20150121_0059.py) is it possible to skip it despite it's position in the migration dependency chain?

**Comment by Doormouse2House** [comment]
In the interest of making progress to see if DjangoCMS is right for me, I've side-stepped this problem and moved to Postgres (a preference over SQLlite).  My offer of attempting to help find the cause still stands as I can replicate this at will on my environment.

**Comment by ursomniac** [comment]
If you hack the migration file 0002_auto_20140816_1918.py and change line 67 from:

`unique_together=set([('publisher_is_draft', 'application_namespace'), ('reverse_id', 'site', 'publisher_is_draft')]),`

to

`unique_together=set([('publisher_is_draft', 'site', 'application_namespace'), ('reverse_id', 'site', 'publisher_is_draft')]),`

the issue goes away.    (For some reason the problem ONLY happened if I used MariaDB:  MySQL and Postgres installed out-of-the-box.)

**Comment by adamth** [comment]
I was having the same issue and found that migrations will run using MySQL 5.7. I would get the error when using MySQL 8. HTH

**Comment by JMaio** [comment]
Same issue here, running Django 2.1.8 + django CMS 3.6.0 + MySQL 8.0.16
Performing @ursomniac's workaround works up to migration `cms.0018_create_pagenode`, at which point the same error as OP appears (this migration is dated 2018-01-03 19:50). 
Will retry with MySQL 8.0.11 as it seems to work on AWS with that version.

**Comment by JMaio** [comment]
I've given this another try, and it looks as though setting `'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"` in `DATABASES['default']` made it work (in conjunction with @ursomniac's hack) in MySQL 8.0.11. 
This was, however, not a 100% fix as it only seems to work once every few tries... Can't find a clear reason why it fails though. 
I played around with partial migrations (`migrate cms 0007`, then `migrate cms 0019`) and this worked like a charm. However, after this, doing the full `migrate` procedure no longer fails anymore (new schema every time), so I'm not really sure what the issue is. Even reverting the `0002` hack it still works... Very obscure issue indeed

**Comment by ivjuris** [comment]
The fastest way to solve this problem is to reset the computer and restart the migration.

**Comment by zhangliu520** [comment]
during migrating,django checks  the constraint (publisher_is_draft, application_namespace) of your database .the error shows that the database have nothing of  the constraint.so manually create the constraint on the database,or   make  makemigrations and migrate      after  removing the migration files of the app
