### ISSUE TITLE
Django's "The content was successfully published" message isn't visible when user publishes it via AJAX

### ISSUE THREAD

**Issue by bentappin** [django-cms/django-cms#5732]
Hello

I noticed when using the CMS toolbar to publish a page there is an AJAX `POST` to the admin controller which publishes/rejects the request, adds a Django message and [returns an `HttpResponseRedirect`](https://github.com/divio/django-cms/blob/release/3.4.x/cms/admin/pageadmin.py#L910).

It appears that the Django message (e.g. 'The content was successfully published.') gets "eaten" by the Javascript following the redirect, so when the toolbar Javascript redirects in the [`success` handler](https://github.com/divio/django-cms/blob/release/3.4.x/cms/static/cms/js/modules/cms.toolbar.js#L365) there is no message to display.

This happens on a fresh project setup with `djangocms-installer`.

Other messages popup fine, such as when editing a text field, e.g. 'The text "blah blah blah..." was changed successfully.'

Here's the output from the console showing the extra `GET` (line 2):

```
[19/Oct/2016 17:11:24] "POST /en/admin/cms/page/1/en/publish/ HTTP/1.1" 302 0
[19/Oct/2016 17:11:24] "GET /en/?edit_off HTTP/1.1" 200 15400
[19/Oct/2016 17:11:25] "GET /en/?edit_off=true HTTP/1.1" 200 15361
```

I used `pdb` in the [`details` view](https://github.com/divio/django-cms/blob/release/3.4.x/cms/views.py) to confirm that messages _are_ present, in the first `GET` but not the second.

So I _think_ this is a bug. But if anyone has any thoughts or things for me to try then please then let me know and I can test and hopefully either close this or make a more useful bug report.

Thanks
Ben.

**Comment by czpython** [comment]
Thanks for reporting this @mrben.
We'll investigate further.
