### ISSUE TITLE
Method CMSPluginBase._get_render_template raises wrong exception

### ISSUE THREAD

**Issue by jrief** [django-cms/django-cms#5831]
In class ``CMSPluginBase`` the method ``_get_render_template`` raises a ``ValidationError``, if the returned template is ``None``. In my opinion the correct exception should be a ``TemplateDoesNotExist`` exception, since a ``ValidationError`` shall only be used to reject invalid form data.

**Comment by czpython** [comment]
Agree but I think we should use `ImproperlyConfigured` instead.

**Comment by jrief** [comment]
Yes, ``ImproperlyConfigured`` presumably is the better exception.

**Comment by Kaushal-Dhungel** [comment]
Hello. I would like to work on this issue.

**Comment by TiredFingers** [comment]
@jrief

**Comment by jrief** [comment]
This should be rather easy to fix.

**Comment by NicolaiRidani** [comment]
@Kaushal-Dhungel do you have all the information you need?

**Comment by Kaushal-Dhungel** [comment]
@NicolaiRidani I think I can get started with this one.
