### ISSUE TITLE
When editing fields and djangocms side frame is accidentally closed you lose changes.

### ISSUE THREAD

**Issue by FilippoIOVINE** [django-cms/django-cms#5866]
Hi all.
Just describing something I guess it is a bug of the cms UI.
When I am in the process to change something in a django app fields (let's say a Zinnia article) and I close the frame (especially pressing esc key) all data is lost.
Even more annoying if, for example, using tinymce text editor and I choose to insert an image: when I close the tinymce image selector modal window pressing the esc key then side frame is closed too and I lose everything again.

* Python version: 2.7
* Django version: 1.10
* django CMS version: 3.3

**Comment by czpython** [comment]
Hello @FilippoIOVINE,
Would you mind providing us with a screenvideo that shows this?
Thanks

**Comment by FilippoIOVINE** [comment]
First video is when I change a field and I close the frame.
Second one is when a modal dialog popup and I press the esc key to close it and frame container closes too.

 
[sceenvideo.zip](https://github.com/divio/django-cms/files/745179/sceenvideo.zip)

**Comment by evildmp** [comment]
I've been bitten by this too. 

Closing the sideframe, or the modal window, is like closing a browser window. 

We could require confirmation before closing, but it's intrusive to interfere with that close operation from inside the window.

**Comment by FilippoIOVINE** [comment]
I really hope they might help us with that!
I guess this is not the proper way to handle editing UI in a CMS.
For example, I have customers demanding to get confirmation before closing the frame especially when you edit a page with lots of field to fill up. :(

**Comment by vxsx** [comment]
We already do something like this for the modal with https://github.com/divio/django-cms/blob/1ef83443e7d8be8439ae1f04bb9460246f000eb0/cms/static/cms/js/modules/cms.modal.js#L1105
We could try implementing it for the sideframe as well.
It'll likely won't catch everything (as [changetracker](https://github.com/divio/django-cms/blob/1ef83443e7d8be8439ae1f04bb9460246f000eb0/cms/static/cms/js/modules/cms.changetracker.js) itself is very simple) but it might be a nice 80/20 thing

**Comment by FilippoIOVINE** [comment]
thanks @vxsx, this would be acceptable... but still unconfy.
Do you think would be a way to really cover the 100%?
What would be missing things in case of you above mentioned 80/20?

**Comment by vxsx** [comment]
remaining 20% would be completely custom fields that we aren't aware of how to track in the cms core
