### ISSUE TITLE
Unpublished page shows in menu for multi language site

### ISSUE THREAD

**Issue by gmenih341** [django-cms/django-cms#6004]
### Summary
I have a page using Django CMS that has two different languages, EN and DE. I created a page in EN, and published it, but made sure it's unpublished in DE, as indicated by the gray circle in the page admin.

However, when I'm using the DE version of the site, I see the menu item appear, even though the page is not published in that language. Clicking on the link takes me to the EN version of the page (unless in edit mode).

This seems related to #4214 but that seems to have been fixed.

### Expected behaviour
The page should not show up in the menu, if it's not published in the language that's currently active.

#### Actual behaviour
Page shows up anyway.

#### Environment

* Python version: 3.5.6
* Django version: 1.8.15
* django CMS version: 3.4.2

**Comment by czpython** [comment]
Hello @gmenih341,
Did you try clearing the cache?

**Comment by gmenih341** [comment]
@czpython does restarting the server do this as well? Because then I have cleared the cache.

**Comment by czpython** [comment]
@gmenih341 
It does not.

Try running this in `manage.py` shell.

```
>>> from cms.menu_pool import menu_pool
>>> menu_pool.clear()
```

**Comment by gmenih341** [comment]
@czpython Couldn't import from `cms.menu_pool`, so I replaced that with `menus.menu_pool`, and cleared it. Still showing unpublished page.

**Comment by czpython** [comment]
@gmenih341 
does this happen when you see the page in edit mode? or also in published mode?
an unpublished page will always show in the menu on draft mode.

**Comment by czpython** [comment]
ping @gmenih341

**Comment by tschale** [comment]
@gmenih341 Were you able to resolve your issue? I'm seeing the exact same behavior. I have a site, for which I copied all pages to a new language (before there only existed one language). One page that appears in the menu is unpublished for the new language, but is still shown...

**Comment by gmenih341** [comment]
@tschale if I remember correctly, we added some if statements to the menu template, to filter out the problematic item, as we knew that it will never be published in the other language.

Hope this helps.

**Comment by tschale** [comment]
Thank you. Unfortunately I need a general solution, but I guess it's gonna be some hacky workaround to filter those out...

**Comment by tschale** [comment]
This seems to be a general problem beginning(?) in version 3.5.x. Before (I checked 3.4.6) `CMSMenu.get_nodes` used the attribute `published` of `Title` to filter out unpublished pages using the title. That seems to have been refactored in 3.5.x, the `published`-flag isn't used anymore. 
As a workaround I changed following code snipped (around lines 230) to filter by the titles `published` attribute, which solves my problem:
```
        if not self.renderer.draft_mode_active:
            # we're dealing with public pages.
            # FOLLOWING LINE IS NEW
            pages = pages.filter(title_set__language__in=languages, title_set__published=True)
            # prefetch the draft versions.
            pages = pages.select_related('publisher_public__node')
        pages = get_visible_nodes(request, pages, site)
```

@czpython is there a reason why the titles `published`-flag isn't used anymore? I've seen the changes in #6159, which also don't use that flag.

**Comment by tschale** [comment]
@czpython Can you please comment on the current state of this? This seems like a major bug, at least in our use-case. Authenticated (non staff, non superuser) users see pages in the menu that aren't published in their language. Those pages are published in the other language though. 
It seems like `CMSMenu`s queries pages that are published and that have a title in the current language. But it doesn't seem to filter whether that title is actually published in the current language.

Can you please confirm whether that actually is a bug, or whether we might be doing something wrong?

**Comment by lazdins** [comment]
Guys, I have given a website to administer and same issue on my side. Running on 3.4.4. Any help how to hide these unpublished pages for other languages would be really appreciated.

**Comment by Aiky30** [comment]
@lazdins This could be fixed in 3.7.1: "Fixed a bug where the menu would render draft pages even if the page on the request was a public page. This happens when a user without change permissions requests edit mode." 
https://github.com/divio/django-cms/blob/develop/CHANGELOG.rst#371-2019-11-26

3.4 I also no longer supported, It is advised that you move to 3.7 as it is an LTS release that is currently supported and the recommended version at the time of my comment: https://www.django-cms.org/en/roadmap/

**Comment by Aiky30** [comment]
Please advise on the progress of this, we're trying to get through the backlog of issues in the CMS.

**Comment by Aiky30** [comment]
Closing as no response and linked to a possible solution.

**Comment by stefanw** [comment]
If someone stumbles upon this issue of unpublished pages appearing in the menu when there is a published page in a different language: have a look at [the `CMS_LANGUAGES` setting](https://docs.django-cms.org/en/latest/reference/configuration.html?highlight=CMS_LANGUAGES#cms-languages), specifically make sure `hide_untranslated` and `fallbacks` are set to the values you need.
