### ISSUE TITLE
Alias Plugins on Page Types

### ISSUE THREAD

**Issue by FinalAngel** [django-cms/django-cms#6118]
### Summary

Alias plugins are not correctly working when used in Page Types and a multi site / language setup.

### Expected behaviour

Create a Page Type with 3 different languages. Create a new page from from the page type. Go to the Page Type manually and copy a plugin as alias and add it to the newly created page. Everything appears correct.

Now change the content in the Page Type and observe that the changes are not reflected onto the content page. Publishing the page doesn't help either.

### Actual behaviour

Make sure that the content is updates also when aliasing form a page type.

### Environment

* Django version: 1.8.x
* django CMS version: 3.5

**Comment by Aiky30** [comment]
As the core implementation of Alias is going to be replaced by djangocm-alias this will be irrelevant.
