### ISSUE TITLE
CMS wizard leaks session data

### ISSUE THREAD

**Issue by FinalAngel** [django-cms/django-cms#6194]
### Summary

Create newsblog app config A and B
Create newsblog article via wizard inside app config B targeting app A

Press on the wizard create button before toolbar loads
Create newsblog article targetting app A

### Expected behaviour

There should be no TypeError at /en/cms_wizard/create/

**Comment by victor-yunenko** [comment]
I would expect the issue to still be there, but would be nice to confirm with the latest CMS version.
