### ISSUE TITLE
Plugin cache = False ignored with Redis Backend

### ISSUE THREAD

**Issue by aubricus** [django-cms/django-cms#6241]
### Summary

When using a Redis caching backend, the plugin cache setting `cache = False` is ignored. 

### Expected Behavior

Plugin cache settings are expected when using a Redis cache backend.

### Actual Behavior

Plugin cache settings are ignored (seemingly) when using a Redis cache backend.

### Environment

* Python version: 3.5.4
* Django version: 1.10.x
* django CMS version: 3.4.4
* Redis Version: 3.2.4 (using `django-redis-cache==1.7.1`)
* Local Docker Container: Alpine 3.4.0
* Hosted Machine: Amazon Linux AMI 2017.03

### Some Additional Context

This is a strange one. I am seeing this issue on my production site and can also reproduce this locally by installing a Redis backend via docker-compose.

* Using the local Memcache `django.core.cache.backends.locmem.LocMemCache` I do not see this issue.
* Switch to the Redis backend `redis_cache.RedisCache`, I see this issue. 

In my case specifically, I am seeing this problem in:

1. A plugin that serves my site's navigation
2. Attempting to render, dynamically, the currently selected menu node (see below for example code)

__Example Code__:

> I am using the menu template tag here with a custom template.

```
# Renders a dynamic class of active for a CSS hook to display the current nav item.
{% if child.selected or child.ancestor %} active{% endif %}
```

I've pretty much narrowed it down to a problem in the placeholder cache by flipping the  `CMS_PLACEHOLDER_CACHE` setting on or off. 

* `CMS_PLACEHOLDER_CACHE=True` the problem occurs
* `CMS_PLACEHOLDER_CACHE=False` the problem seems to resolve itself

If it's helpful, here's the REDIS Keys (locally):

__Before disabling CMS_PLACEHOLDER_CACHE__

```
# Set CMS_PLACEHOLDER_CACHE = True
# Ran FLUSHDB then re-loaded the site
redis:6379[1]> KEYS *
 1) ":1:cms-|placeholder_cache_version|id:30|lang:en|site:1"
 2) ":1:menu_cache_menu_nodes_en_1:public"
 3) ":1:cms-|render_placeholder|id:32|lang:en|site:1|tz:America/Los_Angeles|v:1516669311391547"
 4) ":1:cms-|placeholder_cache_version|id:32|lang:en|site:1"
 5) ":1:cms-|placeholder_cache_version|id:41|lang:en|site:1"
 6) ":1:cms-CMS_PAGE_CACHE_VERSION"
 7) ":1:cms-|render_placeholder|id:80|lang:en|site:1|tz:America/Los_Angeles|v:1516669318377543"
 8) ":1:cms-page_url__page_lookup:[redacted]site:1_lang:en_type:absolute_url"
 9) ":1:cms-|placeholder_cache_version|id:80|lang:en|site:1"
10) ":1:cms-page_url__page_lookup:[redacted]_site:1_lang:en_type:absolute_url"
11) ":1:cms-page_url__page_lookup:home_site:1_lang:en_type:absolute_url"
12) ":1:cms-|render_placeholder|id:30|lang:en|site:1|tz:America/Los_Angeles|v:1516669308194907"
```

__After disabling CMS_PLACEHOLDER_CACHE__

```
# Set CMS_PLACEHOLDER_CACHE = False
# Ran FLUSHDB then re-loaded the site
redis:6379[1]> KEYS *
1) ":1:menu_cache_menu_nodes_en_1:public"
2) ":1:token"
```

I'm not intimately familiar with the Djangocms caching mechanisms so I was hoping someone on the team could chime in with any insight and/or confirm this as an actual bug (the main reason I didn't post this in the Google Group).

**Comment by czpython** [comment]
Hello @aubricus,
Can you post the code for the plugin in question?
Also have you tried moving all plugins out of the placeholder and leaving only the plugin in question?
To isolate the issue to that one plugin.

**Comment by aubricus** [comment]
@czpython 

Unfortunately, I can't share the plugin code. 

I guess the next best thing would be to try and reproduce this in a vanilla build + Redis. 

Thoughts?

**Comment by plamen-nikolov** [comment]
The same behavior with memcached
Python 2.7.10
Django 1.11.10
Django-CMS 3.5

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',
    }
}

It doesn't cache a plugin, it caches a whole CMS app page. It's a blank CMS app page, with small sidebar on the left.

**Comment by czpython** [comment]
I'm not following @plamen-nikolov.
What issue are you seeing on 3.5?
The cms caches entire pages if `CMS_PAGE_CACHE` is on.

**Comment by czpython** [comment]
@aubricus 
Yes if you can, please provide me with a vanilla project.
Just to make sure I understand the issue, you have a plugin with `cache = False` which renders the menu code and when placeholder cache is on, the plugin is cached even though its cache attribute is set to `False` and when placeholder cache is off, the plugin is correctly not cached.

**Comment by plamen-nikolov** [comment]
@czpython I notice full page cache, even CMS_PAGE_CACHE is False. When i disable CACHES = {} config entirely or kill memcached, than the issue disappears.

**Comment by czpython** [comment]
@plamen-nikolov are you sure the cached endpoint is handled by the cms? if so can you dump the cache keys with "cms" on them?

**Comment by czpython** [comment]
Also what part of the page is cached? is it the menu or the content too?

**Comment by plamen-nikolov** [comment]
> @plamen-nikolov are you sure the cached endpoint is handled by the cms?

yes, the cached page is a CMS page

> @plamen-nikolov Also what part of the page is cached? is it the menu or the content too?

I have no idea. I noticed the cache in the page content only. Will try to reproduce it in the menu as well

> if so can you dump the cache keys with "cms" on them?

> $ stats cachedump 3 100        
ITEM :1:cms_3.5.0_|placeholder_cache_version|id:79|lang:bg|site:1 [27 b; 1517854687 s]
ITEM :1:cms_3.5.0_|placeholder_cache_version|id:81|lang:bg|site:1 [27 b; 0 s]
ITEM :1:cms_3.5.0_|placeholder_cache_version|id:10|lang:bg|site:1 [27 b; 1517854687 s]

**Comment by czpython** [comment]
Hello @plamen-nikolov,
The dump you posted reveals that you're **not** using the page cache (`CMS_PAGE_CACHE` is False). Instead you're using the placeholder cache.

**Comment by plamen-nikolov** [comment]
It's interesting that I'm not using any placeholder on the page though. It's just a simple template

**Comment by czpython** [comment]
Using the page id, can you run the following in shell and post the output:

```python
from cms.models import Page
page = Page.objects.get(pk=page_id)
page.get_declared_placeholders()
```

Note that even if there's no plugins in the placeholder, the cms will hit the cache.

**Comment by czpython** [comment]
Ping @aubricus

**Comment by aubricus** [comment]
@czpython 

Thanks for your patience. 

> Just to make sure I understand the issue, you have a plugin with cache = False which renders the menu code and when placeholder cache is on, the plugin is cached even though its cache attribute is set to False and when placeholder cache is off, the plugin is correctly not cached.

I will try to clarify:

1. I have a plugin that renders some state determined at runtime and has `cache=False`
2. When `CMS_PLACEHOLDER_CACHE=True` (using a Redis cache backend), `cache=False` has no effect.
3. When `CMS_PLACEHOLDER_CACHE=False` the plugin seems to render the dynamic state appropriately. 

Hope that helps. 

I will try to put together a vanilla example in this weekend or the next, if possible.

**Comment by plamen-nikolov** [comment]
I just notice the same issue with django cms 3.4.5 & 3.4.6

- Python 2.7.10
- Django 1.10.8
- Django-CMS 3.4.5 / 3.4.6

`
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',
    }
}

CMS_PAGE_CACHE = False
CMS_PLUGIN_CACHE = False
CMS_PLACEHOLDER_CACHE = False
`

There is an app attached to a CMS page and the app's content is getting cached. There are no plugins in this app page.

If I disable CACHES = {...} setting and everything seems to be ok.

**Comment by plamen-nikolov** [comment]
Just experienced it again with the following configuration:

Django 1.10.8
django-cms 3.4.6

```
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',
    }
}

CMS_PAGE_CACHE = False
CMS_PLUGIN_CACHE = False
CMS_PLACEHOLDER_CACHE = False
```

No matter what changes I do with the CMS_* flags, it stops caching if I change the cache setting to:

```
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
    }
}
```
