### ISSUE TITLE
Document behavior change in static placeholders

### ISSUE THREAD

**Issue by TheDeadOne** [django-cms/django-cms#6290]
### Summary

After the upgrade to version 3.5, in the structure mode, plugins in static placeholders are no longer displayed.

### Expected behaviour

![structure_toolbar_normal](https://user-images.githubusercontent.com/5821459/36730506-a44501f8-1c02-11e8-9015-c6aa04207d88.png)

### Actual behaviour

![structure_toolbar_bug](https://user-images.githubusercontent.com/5821459/36730518-ad953886-1c02-11e8-87ba-227e6998d3c5.png)

### Environment

* Python version: 2.7.9
* Django version: 1.11.10
* django CMS version: 3.5.0

**Comment by vxsx** [comment]
It should be possible to click on a title of a static placeholder to expand things.

**Comment by TheDeadOne** [comment]
Oh, thanks! I feel stupid. It needs pointer cursor at least.

**Comment by Aiky30** [comment]
Closing as documentation has been added and no response since 2018.
