### ISSUE TITLE
Issue with  static_placeholder

### ISSUE THREAD

**Issue by dykyioleg** [django-cms/django-cms#6328]
Hi Everyone! 
I need help with a static placeholder.When I put my static placeholder on a page from a menu I don't see placeholder on a page.So, I can open the editor for edit placeholder but this place is empty.Yes ,i have {% load cms tags %}.
But, when I open  home page, always from the menu it works, I see a placeholder for edit.On my homepage, I have put custom application.And I have rewritten my menu in reason cause I need a dropdown menu.

* Python version:3.6
* Django version:1.11
* django CMS version:3.5.0

**Comment by czpython** [comment]
Hello @dykyioleg,
can you provide us with a screencast and the templates?

**Comment by dykyioleg** [comment]
hello  czpython! yes sure!
![screenshot from 2018-04-09 14-10-55](https://user-images.githubusercontent.com/30573460/38497128-5531f45e-3c00-11e8-9f14-143586c1f40d.png)
![screenshot from 2018-04-09 14-11-17](https://user-images.githubusercontent.com/30573460/38497148-674e9e3a-3c00-11e8-9592-2578edcbb13c.png)

**Comment by czpython** [comment]
Thanks!
Can you try using the develop branch of django CMS?
I think this might have been fixed already.

**Comment by dykyioleg** [comment]
Sorry i didn't understand,what do you mean?

**Comment by czpython** [comment]
You're using the released django CMS 3.5.0, we pushed a fix related to editing but haven't released it yet. The fix is on [this](https://github.com/divio/django-cms/tree/release/3.5.x) branch. Can you try that locally and see if it fixes this issue for you?

**Comment by dykyioleg** [comment]
Ok,thanks!I will try it!

**Comment by dykyioleg** [comment]
Can you help me, understand how I can put this branch in my
requirements.txt?

**Comment by dykyioleg** [comment]
i have tried it and it doesn't works.My issue is something like this https://github.com/divio/django-cms/issues/6157

**Comment by dykyioleg** [comment]
Hello! In my main tamplates folder i have revriten my menu.html because i have needed  dropdownmenu
Do you mean that ? 
Bellow  is my menu.html:

{% load  menu_tags staticfiles  cms_tags  utils %}

{% for child in children  %}

    {% if child.is_leaf_node  %}
        <li class="{% if child.title|lower in request.get_full_path|split|get_item or child.title == 'Home' and request.get_full_path|split|get_item == '' %} active{% endif %}"><a href="{{ child.get_absolute_url }}">{{child.get_menu_title }}</a></li>
    {% endif %}


    {% if not child.is_leaf_node or child.ancestor %}
        <li class="dropdown {% for subchild in child.children %}{% if subchild.selected %} active{% endif %}{% endfor %}">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            {{child.get_menu_title }}<b class="caret"></b></a>
            <ul class="dropdown-menu">
                {% if child.get_descendants %}
                    {% for kid in child.get_descendants %}
                        <li>
                            <a href="{{ kid.get_absolute_url }}">
                                {{ kid.get_menu_title }}
                            </a>
                        </li>
                    {% endfor %}
                {% endif %}
            </ul>
        </li>
    {% endif %}

{% endfor %} 


With home.html   and with another static page my static_placeholder works,with another page from menu don't works .

**Comment by czpython** [comment]
@dykyioleg 
Is very difficult to debug this without access to source code, I'm not 100% what the problem is.
Can you make a screen video showing the placeholder working and then switching to a page where it doesn't work?

**Comment by dykyioleg** [comment]
github doesn't support this functionality,maybe do you have  some email or another method to do it?video i have done with Nimbus.

**Comment by czpython** [comment]
sure, send it to commonzenpython@gmail.com

**Comment by dykyioleg** [comment]
perfect!

**Comment by dykyioleg** [comment]
my video
 nimbus-record-video-2018-04-10-15-03-32.webm
<https://drive.google.com/file/d/1e2qAeffvzgTK1YRkt_jEXmIrc5foifVr/view?usp=drive_web>
​

**Comment by czpython** [comment]
@dykyioleg Would you be able to provide us with a project where this is reproducible?

**Comment by dykyioleg** [comment]
Do you mean ,you need link of the project?

**Comment by dykyioleg** [comment]
Yes i can put this  test project to my repository GitHub.And than share you
link.Ok?

**Comment by czpython** [comment]
Perfect. Thanks!

**Comment by crsepulveda** [comment]
@dykyioleg Could you fix the problem?

**Comment by stasfilin** [comment]
Same problem for me

**Comment by stasfilin** [comment]
Try this https://github.com/divio/django-cms/issues/5760#issuecomment-339245382
It's helped me
