### ISSUE TITLE
Docs contains "aldryn_reversion"

### ISSUE THREAD

**Issue by jedie** [django-cms/django-cms#6337]
The docs page "Integrating a third-party application" still lists "aldryn_reversion":

http://docs.django-cms.org/en/latest/introduction/third_party.html

But https://github.com/aldryn/aldryn-reversion is archived and says:

> WARNING: This addon is now deprecated!

btw. whats about a proper replacement for django-reversion ?!?

**Comment by czpython** [comment]
Thanks for reporting this @jedie.
Currently there's no replacement for reversion, that said we do have djangocms-history app for undo/redo.

**Comment by SteinRobert** [comment]
@jedie - Here is a third party module which brings reversion support to django CMS:
https://github.com/Blueshoe/djangocms-reversion2

**Comment by jedie** [comment]
Thanks, but the disclaimer in the README says:

> This is an experimental plugin.

So it seems that's a bad idea for production use...

**Comment by marksweb** [comment]
Closing this as I can't find "aldryn-reversion" anywhere in the current develop branch.
