### ISSUE TITLE
PageTree becomes "white" while deleting "heavy" pages

### ISSUE THREAD

**Issue by SydorenkoSergiy** [django-cms/django-cms#6357]
If user deletes pages (heavy pages),after pressing “Yes, I’m sure”, at some point the Admin SideFrame becomes “white”. 
If going to PageTree - the deleting pages are still present. And you can interact with theme. 
After reloading the PageTree again - the pages are gone

**Comment by victor-yunenko** [comment]
Could it be caused by the http timeout?
