### ISSUE TITLE
Headers returned in get_vary_cache_on not present in Vary header

### ISSUE THREAD

**Issue by dkellner** [django-cms/django-cms#6373]
### Summary

Returning a custom header in `get_vary_cache_on` does not result in that header being added to the response's Vary header.

### Expected behaviour

The Vary header should also contain headers returned by `get_vary_cache_on`.

### Actual behaviour

The Vary header does not contain headers returned by `get_vary_cache_on`.

### Example

I've written a simple plugin displaying child plugins only when a custom `Store-Id` header matches a certain value (simplifed):

```python
from cms.models.pluginmodel import CMSPlugin
from cms.plugin_base import CMSPluginBase
from cms.plugin_pool import plugin_pool
from django.utils.translation import ugettext_lazy as _


class StoreDependentContentPluginPublisher(CMSPluginBase):
    model = CMSPlugin
    module = _('Control')
    name = _('Store Dependent Content')
    render_template = 'acme_catalog/plugins/store_dependent_content.html'
    allow_children = True
    cache = True

    def get_vary_cache_on(self, request, instance, placeholder):
        return ['Store-Id']

    def get_cache_expiration(self, request, instance, placeholder):
        return 600

    def render(self, context, instance, placeholder):
        context = super().render(context, instance, placeholder)
        store_id = context['request'].META.get('HTTP_STORE_ID')
        context['show_content'] = store_id == 'foobar'
        return context


plugin_pool.register_plugin(StoreDependentContentPluginPublisher)
```

```
{% load cms_tags %}
{% if show_content %}
  {% for child in instance.child_plugin_instances %}
    {% render_plugin child %}
  {% endfor %}
{% endif %}
```

Requesting a page with this plugin containing a simple heading, using `Store-Id: foobar`:
```
λ ~/ curl -s -H "Store-Id: foobar" URL | grep 'Welcome'
    <h1>Welcome to foobar!</h1>
```

Requesting a page with this plugin containing a simple heading, using `Store-Id: barfoo` after waiting `CACHE_MIDDLEWARE_SECONDS`:
```
λ ~/ curl -sk -H "Store-Id: barfoo" URL | grep 'Welcome'
```

So it basically works as intended. But sending the second request right after the first one yields the same result (as it is cached).

Furthermore, the Vary header does not contain `Store-Id`:
```
λ ~/ curl -Is URL
HTTP/2 200
cache-control: max-age=10
content-language: de
content-type: text/html; charset=utf-8
date: Wed, 16 May 2018 07:55:34 GMT
expires: Wed, 16 May 2018 07:55:44 GMT
server: WSGIServer/0.2 CPython/3.6.3
vary: Accept-Language, Cookie
x-frame-options: SAMEORIGIN
x-robots-tag: noindex, nofollow
content-length: 41697
```

### Environment

* Python version: 3.6
* Django version: 1.11.12
* django CMS version: 3.5.2
* (relevant) bits of `settings.py`:
```
CACHES = {
    'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
    'LOCATION': os.environ['ACME_CACHE_LOCATION'],
}
CACHE_MIDDLEWARE_SECONDS = 10
# no other CACHE-settings
```

**Comment by juanromerocortes** [comment]
Is this functionality working at all?
I also tried installing cmsplugin-header-control
but the cms does not seem to do anything with the value returned by get_vary_cache_on

**Comment by juanromerocortes** [comment]
any workaround for cms plugins?
