### ISSUE TITLE
Documentation: Core Plugins should be part of the django cms documentation

### ISSUE THREAD

**Issue by kinkerl** [django-cms/django-cms#6384]
as discuessed in person @evildmp

**Comment by czpython** [comment]
@kinkerl 
What are core plugins in this case?

**Comment by kinkerl** [comment]
afaik such a list already exist: djangocms-bootstrap4 for example

**Comment by kinkerl** [comment]
clarification: only a list of plugins to have a startingpoint for the user, not the documentation of plugins.

**Comment by czpython** [comment]
ok, would be good for this list to match the plugins installed by https://github.com/nephila/djangocms-installer /cc @evildmp
