### ISSUE TITLE
toolbar_off algorithm

### ISSUE THREAD

**Issue by 776166** [django-cms/django-cms#6392]
1) When using sticked to top menu (in Bootstrap for example) cms toolbar hides it by itself.
`<nav class="navbar fixed-top"/>`
2) ?toolbar_off do not kept on page change.

Suggestions:
1) May me toolbar_off algorithm can work on cookies?
2) May be you can make a button for instant hide of the toolbar without page reload?

**Comment by benzkji** [comment]
I also think it would be useful to be able to hide the toolbar, as it was possible in 3.4.x (suggestion 2. from @776166 ... ). Everytime I use it with somehow fixed or 100vh elements, it makes problems (nothing terrible, mostly optical, but still...) - when one can hide the toolbar (or collapse), I can tell the clients "just collapse the toolbar, and you'll see it works". Logout is always cumbersome...

**Comment by 776166** [comment]
It really pissed me off. :(

**Comment by 776166** [comment]
> That's my `.scss` solution to solve this nasty problem:
It do not resolves ”?toolbar_off do not kept on page change“ problem. It is more important than css.

To be honest, I do not find the practice of mixing page display and content editing handy. In addition, it periodically breaks pages in random places depending on the plugin used. And the display itself when the editor is on may be inadequate. In other words, conspicuous cons.

**Comment by Aiky30** [comment]
You can disable the toolbar using the following setting, it is stored in the server session so will stay disabled: `cms_toolbar_disabled` https://github.com/django-cms/django-cms/blob/develop/cms/toolbar/toolbar.py#L181

**Comment by benzkji** [comment]
@Aiky30 pre 3.5 allowed to collapse the toolbar with a single click. but yea...a minor issue. and for now, the structure button has taken the collapse's button position - so it would be kind of a usability issue as well...
