### ISSUE TITLE
Menu node not marked as selected

### ISSUE THREAD

**Issue by czpython** [django-cms/django-cms#6428]
When requesting a page in edit mode with a staff user with no permissions to change the page, the menu will not mark the current page as selected.

This is because the menu incorrectly renders the draft menu while the request page object is public because the user had no permission to change the draft.

**Comment by tschale** [comment]
What's the status here?

**Comment by tschale** [comment]
Seems also to be related to #6669

**Comment by tschale** [comment]
This also seems to solve #6669. Is there a reason why it was just closed? I only did a short test to see whether my menu-issues would be solved, which they are. Is there something I'm missing here, e.g. some sort of regression?

**Comment by czpython** [comment]
Hello @tschale,
It was reopened against [develop](https://github.com/divio/django-cms/pull/6549) a while back.
I'll rebase and land soon.

**Comment by tschale** [comment]
Thank you

**Comment by Aiky30** [comment]
Fixed in 3.7.1: 

> Fixed a bug where the menu would render draft pages even if the page on the request was a public page. This happens when a user without change permissions requests edit mode.

https://github.com/django-cms/django-cms/blob/develop/CHANGELOG.rst#371-2019-11-26
