### ISSUE TITLE
structureboard.js  breaks on IE11 after plugin save

### ISSUE THREAD

**Issue by SachaMPS** [django-cms/django-cms#6478]
It seems there is a one liner which leads to an unhandled exception in IE 11. 

https://github.com/divio/django-cms/blob/a210eb71d4a4d938a4af2f282398ccda5f711818/cms/static/cms/js/modules/cms.structureboard.js#L1302

"new Event" isnt supported by IE11. 

We are trying to solve this now with a polyfill first. Is there any hint in the djangocms docs which browsers are actually supported?

----

After a little test:
This one seems to do the trick
https://github.com/lifaon74/events-polyfill/blob/master/src/constructors/Event.js

**Comment by Aiky30** [comment]
This code appears to have been moved within a check for the length of a selector first. I'm also assuming that as no one else has added that this is an issue that is resolved. Closing due to the age, happy to reopen at anytime in the future if this is stil indeed and issue.
