### ISSUE TITLE
Breadcrumb only showing when requesting localhost not on 127.0.0.1

### ISSUE THREAD

**Issue by bykof** [django-cms/django-cms#6514]
### Summary

When I try to load a custom breadcrumb.html over 127.0.0.1:8000/site/slug it shows only the first breacrumb.
If I switch to localhost:8000/site/slug it shows all breadcrumbs.

### Environment

* Python version: 2.7.6
* Django version: 1.11.15
* django CMS version: 3.5.2

**Comment by vstoykov** [comment]
I also have problem with breadcrumb not showing correctly and I want to see if my problem is the same or not. Did you have custom menu attached to a page (by AppHook or only custom menu) and if this is happening only when you are not logged in?
