### ISSUE TITLE
Revert to Live available on previously published pages that are unpublished

### ISSUE THREAD

**Issue by afs2015** [django-cms/django-cms#6517]
### Summary

`Revert to Live` is available on previously published pages that are changed to unpublished, using it results in having a published blank page.

### Expected behaviour

I would expect the `Revert to Live` option to still be greyed out/unavailable if the page is unpublished to avoid users accidentally deleting progress on creating a page.

### Actual behaviour

When you create a new page and add some content, publish the page, and un-publish the page the command 'Revert to Live' in the CMS Toolbar becomes available. Selecting the command results in a published page that is completely blank.

### Environment

* Python version: 3.6.5
* Django version: 3.5.2
* django CMS version: 1.11.13

**Comment by victor-yunenko** [comment]
Hi @afs2015, thank you for submitting the issue! It might have been resolved in Django CMS 4.0, which uses versioning by default, hence it's worth verifying it before proceeding here.
