### ISSUE TITLE
Backend-Language for plugins changes when working on multi-language content

### ISSUE THREAD

**Issue by didierCH** [django-cms/django-cms#6539]
We have a Django-CMS 3.5.2 installation with languages German and French. When we work on french content the language of the plugings switches to french too (Backend stayes in German). See picture below. That behaviour is not desired. In Django-CMS 3.4.x I hadn't that problem. The user settings home > cms > User-Settings > Language are set to German.

Is there a new setting or does I overlook something?

Kind regards,
Didier

* Python version: 3.5.3
* Django version: 1.11.17
* django CMS version: 3.5.2

![language-problems](https://user-images.githubusercontent.com/7381262/46618191-2df11880-cb1f-11e8-9a25-31c113d210f0.png)

**Comment by didierCH** [comment]
Okay. I finally did a test with Django-CMS 3.4.6 and 3.5.2. With Django 3.4.6 I don't have that issue. If you choose a language in "User Settings" as your default language, the buttons, etc in the plugins will be properly displayed in the selected language. In Django-CMS 3.5.2 the plugin controlls are rendered in the language of the page (eg. fr, de, en, etc) rather than in the language of the Django-CMS user as set in the "User Settings".

**Comment by benzkji** [comment]
I did have this issue, but found out that adding the admin urls to the i18n_patterns (as the cms urls), it worked, but not if the admin was not "i18n'ed". didnt find the time to find out why, but you might try it...

**Comment by didierCH** [comment]
Explicit is better than implizit (and because I forgot it until I needed this setting today again :-) ). 
Here is the code you need to change in your `urls.py`:
From this:
```
urlpatterns += i18n_patterns(path("admin/", admin.site.urls), path("", include("cms.urls")))
```
To this:
```
urlpatterns = [
    path("admin/", admin.site.urls), 
    ...
]

urlpatterns += i18n_patterns(path("", include("cms.urls")))
```

**Comment by benzkji** [comment]
strange, for me it works the other way round ;-)

**Comment by didierCH** [comment]
yes, that's strange.
