### ISSUE TITLE
Recursive template extending does not work with placeholders

### ISSUE THREAD

**Issue by stefanw** [django-cms/django-cms#6563]
### Summary

Recursive template extending does not work in Django CMS, but works in Django itself.

### Expected behaviour

The following template setup with `template_name.html` twice (once in template dir and once in app templates) should render ([as it does in Django since Django 1.9](https://docs.djangoproject.com/en/dev/releases/1.9/#template-loader-apis-have-changed)).

```
# templates/template_name.html
{% extends "template_name.html" %}

# app/templates/template_name.html
{% extends "base.html" %}

# templates/base.html
{% placeholder ... %}
```

### Actual behaviour

A `Exception RuntimeError: 'maximum recursion depth exceeded'` error is raised, because the context for the extends node in [`cms/placeholder/utils.py`](https://github.com/divio/django-cms/blob/98300321806183c09fe612483511689eb2336f8e/cms/utils/placeholder.py#L28-L32) does not contain a proper template origin thus the resolution mechanism cannot skip the current template.

PR is #6564.

### Environment

* Python version: 3.6
* Django version: 1.11
* django CMS version: 3.5.3

**Comment by marksweb** [comment]
Hi @stefanw, just going over old issues.

Is this considering a `placeholder` to be like a `block` in that a block will be available in the inherited templates?

**Comment by stefanw** [comment]
Hey @marksweb, not quite sure what you mean. I stumbled upon this a while ago, but I worked around the problem.

Django supports recursive template extends: extend a template with one that has the same name, but is resolved as the next one in the template loader chain (e.g. see [skip argument to get_template](https://docs.djangoproject.com/en/3.2/ref/templates/api/#django.template.loaders.base.Loader.get_template)). For that you need an [origin on the template instance](https://docs.djangoproject.com/en/3.2/ref/templates/api/#template-origin). The PR adds that origin.

**Comment by marksweb** [comment]
Thanks @stefanw, I think I completely missed the PR when I was looking through here last night 🤦‍♂️
