### ISSUE TITLE
Static_placeholder in a main menu dropdown

### ISSUE THREAD

**Issue by leslieewing** [django-cms/django-cms#6574]
Am trying to display a `static_placeholder` within a menu.html file. I have a custom menu.html file that has a few `{% static_placeholder %}` tags to display a different image or some other type of content in the main menu drop down; however, I am not seeing an edit area for those when I click to Edit.

```
    {% if child.parent.get_menu_title == "Personal" %}
        {% static_placeholder 'personal_menu_content' %}
    {% elif child.parent.get_menu_title == "Business" %}
        {% static_placeholder 'business_menu_content' %}
    {% elif child.parent.get_menu_title == "Who We Are" %}
        {% static_placeholder 'who_menu_content' %}
    {% endif %}
```

Is this even doable? If not, is there another way to add an editable area within a main menu? 

### Expected behaviour
When I click the icon to show the different placeholders I would expect the "Personal Menu Content" and the other two static placeholders seen above to appear.

### Actual behaviour
I do not see any of the above placeholders in the edit area. I see regular placeholders and even a static placeholder I put in the footer, but none of the ones I have in the main menu are showing

### Environment

* Python version: 3.6.6
* Django version: 1.11.15
* django CMS version: 3.5.3

**Comment by jrief** [comment]
@leslieewing I would create a template for each menu title/static placeholder. Use template inheritance to avoid code duplication. In my projects, my base template specifies
```
<footer class="footer">
{% block footer %}{% endblock footer %}
</footer>
```

and inheriting templates then, for instance would use
``` 
{% block footer %}
    {% static_placeholder "personal_menu_content" %}
{% endblock footer %}
```

Create a such a template for each page requiring a special static placeholder.
