### ISSUE TITLE
Keep older cms.utils.compat version flags for third-party plugins

### ISSUE THREAD

**Issue by stefanw** [django-cms/django-cms#6578]
### Summary

Django CMS 3.6rc1 has removed older `DJANGO_*` version flags from the `cms.utils.compat` module.
[Third-party extensions still rely](https://github.com/search?p=1&q=cms.utils.compat+import+DJANGO&type=Code) on them which means an upgrade of 3.6.x also requires an upgrade of all plugins that rely on that version info via `cms.utils.compat`.

`cms.utils.compat` doesn't seem to be a documented API, but it would be an easy thing to keep this version info. Users of third-party plugins, that otherwise work fine, would appreciate it!

Otherwise the upgrade to Django CMS 3.6 will be slower, due to third-party extensions needing to upgrade either via breaking compatibility or each coming up with their own version info.

### Expected behaviour

```
from cms.utils.compat import DJANGO_1_10
```

This should still work, even though Django 1.10 is no longer supported.

### Actual behaviour

```
ImportError: cannot import name 'DJANGO_1_10'
```

### Environment

* Python version: 3.6
* Django version: 1.11
* django CMS version: 3.6rc1

**Comment by marksweb** [comment]
Closing as this appears to have been addressed in #6636
