### ISSUE TITLE
Slug collides when page moved to level that has same slug

### ISSUE THREAD

**Issue by air-hand** [django-cms/django-cms#6593]
### Summary

When page moved to level that has same slug, slug collision occurred without error.

I found a comment that "url conflicts are handled by updated check_title_slugs" in pagemodel.py, but
 there is no check_title_slugs or alternative.

### Expected behaviour

Validation error occur, or modify slug like "Copy page".

### Actual behaviour

Slug collision occurs.

### Environment

* Python version: 3.6.5
* Django version: 1.11.17
* django CMS version: 3.5.3

**Comment by marksweb** [comment]
Hi @air-hand, thanks for raising. However, I think managing content, including slugs, is the responsibility of the user/content creator.

I don't believe this should cause an error. Perhaps an enhancement here would be to add a message warning that there are duplicate slugs.

**Comment by air-hand** [comment]
@marksweb thanks for reply.
I agree your opinion.
At least I want to know if there are duplicates, so it doesn't have to be an error.

and, maybe #6840 is the same issue.

**Comment by marksweb** [comment]
@air-hand Yeah that does look the same, well spotted!

**Comment by air-hand** [comment]
@marksweb The issue looks like on going. should I close this?

**Comment by marksweb** [comment]
@air-hand yeah, please. The other has a PR attached as well so I've assigned that to me & I'll review that & take it from here 👍
