### ISSUE TITLE
Structureboard opens only after clicking three times on the button on 3.5.3 and 3.6

### ISSUE THREAD

**Issue by MacLake** [django-cms/django-cms#6600]
### Summary
On Django CMS 3.5.3 and 3.6 (edited) you have to click three times on the  on the icon on the top right to open the structureboard. (at least on our set up).

### Expected behaviour
Clicking once should be sufficient.

### Actual behaviour
1. After the first click on the structure board icon you can see the progress bar of the browser indicating some loading activity, `?structure`  is appended to the URL in the address bar of the browser.

2. After the second click `?structure` vanishes in the URL field.

3. After the third click `?structure` shows up shortly in the URL field while indicating loading in the progress bar, then '`?structure` vanishes and eventually the structure board opens.

4. After that the structure board can be closed and opened with a single click.

This issue doesn’t show on Django CMS 3.5.2.

### Environment

* Python version: 3.5.3
* Django version: 1.11.18
* django CMS version: 3.5.3 and 3.6 (edited)

**Comment by MacLake** [comment]
It’s the same for Django CMS 3.6.

**Comment by marksweb** [comment]
I think this was resolved recently
