### ISSUE TITLE
Garbled text shows up after saving plug-in instances from 3.5.3 on

### ISSUE THREAD

**Issue by MacLake** [django-cms/django-cms#6601]
### Summary
Often but not always on the top of the page many lines with some plug-in information show up after saving a plug-in instance after editing content.

### Expected behaviour
No garbled text.

### Actual behaviour
Garbled text confuses the editing person. Nevertheless the plug-in is saved and it doesn’t affect the readers. After reloading the page, the garbled text vanishes.

Downgrading to 3.5.2 makes this issue disappear.

![bildschirmfoto vom 2019-01-24 18-41-47](https://user-images.githubusercontent.com/9460962/51697329-d8764400-2007-11e9-86ea-651b6f4771a5.png)

### Environment

* Python version: 3.5.3
* Django version: 1.11.18
* django CMS version: 3.5.3

**Comment by MacLake** [comment]
Unfortunately this error occurs also on django CMS version 3.6. Am I the only one seeing this?

**Comment by marksweb** [comment]
Hi @MacLake, did you ever resolve this?

I've never had this happen or see it reported before.

**Comment by MacLake** [comment]
HI @marksweb , no, we never resolved this, and this issue is still getting on our nerves, in the meantime with djangoCMS 3.8.0 and Django 3.1.10. Well, you can live with it, since it doesn’t affect the readers, only the editors, but it’s not nice, and also for the acceptance within our company it would be better that my colleagues don’t get the impression of a buggy CMS.

**Comment by marksweb** [comment]
@MacLake Thanks for the feedback. I'll try to gather the thoughts of other maintainers to see if we can get to the bottom of this one.

**Comment by vinitkumar** [comment]
@MacLake Can you reliably reproduce the error? If so, can you please be kind enough to do a screen-recording and share it with us? It will greatly help us reproduce and possibly also fix it.

**Comment by MacLake** [comment]
@marksweb Thanks for taking care of this! One more thing: Our setup is a multi-site and multilingual instance. We have used the same database for all these sites. Recently we have added another site. Since we have external editors for this EU project, I use a new separate database for this new site in order to have a better separation, but still the same virtualenv. In this new site I haven’t seen this garbled text.

**Comment by marksweb** [comment]
@MacLake thanks for the additional info.

As a side note, I'm also running a multisite setup in multiple languages using 1 database as well 👍
This system is currently on python 3.7 or 3.8, Django 2.2 and cms 3.7 I believe.


Initially what this looks like to me is an issue related to javascript, so browser details would also be helpful.

**Comment by MacLake** [comment]
So here is my screen recording. It took some time to capture it, as this bug only occurs every now and then, not every time, but often enough to bother the editing users. So I can’t reliably reproduce it in the sense that you see it every time after doing certain actions.

https://user-images.githubusercontent.com/9460962/118189692-63caac00-b442-11eb-9025-546b49241d9f.mp4

I agree, it seems to be JavaScript related, and as mentioned, it didn’t occur until 3.5.2. I use mainly Firefox on Linux. I’m going to check out if I can reproduce it also on Chromium and Chrome. My colleagues have also encountered this bug. I’m going to ask what they used on their Windows systems.
