### ISSUE TITLE
Page cache key doesn't depend on language

### ISSUE THREAD

**Issue by sephii** [django-cms/django-cms#6607]
### Summary

The [docs for the `CMS_PAGE_CACHE` setting](http://docs.django-cms.org/en/latest/reference/configuration.html#std:setting-CMS_PAGE_CACHE) mention that the language is used to build the cache key:

> Should the output of pages be cached? **Takes the language,** and time zone into account. Pages for logged in users are not cached. If the toolbar is visible the page is not cached as well.

The [`_page_cache_key` function](https://github.com/divio/django-cms/blob/develop/cms/cache/page.py#L24) relies on `request.get_full_path()` to add the language to the cache key. However there are cases where the language is not in the path. For example you could create your own middleware that sets the language depending on the hostname, instead of the path (which is my case).

I think just adding `translation.get_language()` to the key would do the trick without any side effect.

### Expected behaviour

The cache includes the current active language instead of relying of the language being in the URL.

### Actual behaviour

The cache relies on the language being part of the URL.

### Environment

* Python version: N/A
* Django version: 2.0
* django CMS version: 3.6

**Comment by sephii** [comment]
I made a fix [here](https://github.com/sephii/django-cms/commit/2ae2b2c45d4fecc2079eaa70402095bfdc97a7dc). I'd be happy to submit it as a PR but I guess I should write a test first. I'll do it when I have more time.

**Comment by marksweb** [comment]
Resolved by #7354
