### ISSUE TITLE
Scrolling issues in admin sideframe

### ISSUE THREAD

**Issue by FSE-DEV** [django-cms/django-cms#6621]
There is no scrolling on some pages within the admin sideframe. E.g. the Pages > Advanced Settings Tab won't scroll. Only solution is to jump by tab key. See screenshot.

Expected behavior: Scrollable to bottom.

I am using the latest version directly from divio cloud.

![screen](https://user-images.githubusercontent.com/20705866/53286873-d58c8180-3774-11e9-8a18-557cb1005d18.jpg)

Other tabs do scroll, but they would not scroll all the way / far enough down, e.g. the user detail tab:
![screen2](https://user-images.githubusercontent.com/20705866/53287013-952e0300-3776-11e9-97b2-c7d07ae7d481.jpg)

**Comment by vThaian** [comment]
Hey, @FSE-DEV. I checked 3 ways of open advanced settings and you are right that is the problem with finding scrollbar for:
- open directly in full admin /admin/
- open admin in sideframe

I checked the last one when you go to advanced settings directly being on the page and there is a scrollbar.

I checked also other admin pages on full admin and modal admin and I figure out that is the issue with scroll after some actions on the page.

When you open advanced settings(via modal or full admin) then are you be able to hover on the scrollbar and use it(when you hover on the place where the scrollbar is then you will see it).

If you do some actions(such as select some field) you will not be able to see the scrollbar on hover.

**Comment by vxsx** [comment]
@FSE-DEV hi, does this happen in all the browsers for you? what OS / Browser are you using?

**Comment by FSE-DEV** [comment]
@vxsx Just checked. It does happen for me in all modern browsers. Problem occurs in (latest versions):
Chrome (72)
Firefox (65)
Edge

It does not happen / behavior is as expected in Internet Explorer (first time I can say something like that).

**Comment by vThaian** [comment]
I checked on other external pages such as stackoverflow. Behavior is the same - when you visit the page without any action is a possibility to hover on the scrollbar and use it.

When you click on text input etc. then you can't hover and use the scrollbar.

Checked on mac with Chrome browser. Seems to me to be just correct behavior.

How to test this on stackoverflow:
- open page and hover place where scrollbar is located (you should see it)
- now click textfield and try repeat point 1 (you shouldn't see scrollbar)

**Comment by FSE-DEV** [comment]
@vThaian I am not sure what exactly it is you are referring to by saying one could "hover on the scrollbar and use it" (maybe that is a Mac specific feature). This I also couldn't follow / reproduce what you suggested testing on the stackoverflow site (which works fully as expected for me).

As illustrated in the provided screen shot, there either is no scroll bar / area to hover over at all, or it does not scroll far enough down, irrespective of using the mouse wheel or hovering over and clicking on it.

Can anyone reproduce the issue presented in my screenshots? I am using Bootstrap 4 and the jQuery mmenu sidebar solution (https://mmenujs.com/).
