### ISSUE TITLE
The slugs of child pages are built incorrectly and return a 404 error when a user adds a custom slug for another language of the parent page

### ISSUE THREAD

**Issue by victor-yunenko** [django-cms/django-cms#6622]
### Summary

The slugs of child pages are breaking when a user adds a custom slug for another language of the parent page, this leads to incorrect urls being displayed and the correct urls return a 404 error.

### Actual behaviour

1. Create an empty website with 2 languages - English and German.
2. Create a Page with the slug `parent-en` in English and publish it, leave the German slug empty.
3. Create a child Page of the first page with the slug `child-en` in English and `child-de` in German
4. Confirm that the created child page has the url `parent-en/child-en` and the respective German url, all is fine for now.
5. Open the parent Page and add a custom German slug, specifically `parent-de` and publish all the unpublished pages.
6. Now open the German version of the website, and see in the menu that the link to the child page is `parent-en/child-de` instead of the correct `parent-de/child-de` url. Confirm that the expected url `parent-de/child-de` actually returns a 404 error.

### Expected behaviour

On the 6th the url in the menu should be `parent-de/child-de` , and the url `parent-de/child-de` shouldn't return a 404 error.

### Environment

* the first one
    * Python version: 3.5.3
    * Django version: 1.11.20
    * django CMS version: 3.6.0

* the second one
    * Python version: 2.7.6
    * Django version: 1.9.5
    * django CMS version: 3.5.1

The issue doesn't appear to be present in django-cms 3.4.5 though.

**Comment by christian-schneider** [comment]
I just experienced the same issue on a 3.5.3 installation. Glad I found this report, was quite worried for a moment ;)

**Comment by Foobartender** [comment]
A prerequisite for reproducing this is that at least one of the parent's (i.e. parent-(en|de)) ancestors (including the root page) does not have a German translation. If all pages in the chain have a German translation, it works fine.

If a translation in the chain is unpublished, all children of the page will show a tooltip "unpublished parent" in the page tree view for the publish icon of the translation.

I also have a page with an CMSApp hook and a CMSAttachMenu only in English. The CMSAttachMenu will raise NoReverseMatch errors if another language is selected, presumably because the urlpatterns have not been loaded.

So, I'd guess the fallback mechanism isn't working properly (I have configured fallbacks in CMS_LANGUAGES).

**Comment by Foobartender** [comment]
cms.models.pagemodel.mark_descendants_as_published() updates the paths of the published titles of its children:
unpublished_public.exclude(has_url_overwrite=True).update(path=new_path)

I think it should update all titles of its children:
Title.objects.filter(language=language, page__in=page_children, has_url_overwrite=False).update(path=new_path)

**Comment by zypro** [comment]
Facing almost same issue. If a parent page gets translated after child-pages exists, the translated slug is set incorrectly in the path of all child-pages. So there is a mixup in the url of 2 languages.

Manual fix: Move the parent page (with all children) to another place in the page tree and then move it back again. Then all paths (urls) get updated.

**Comment by mammuth** [comment]
> Manual fix: Move the parent page (with all children) to another place in the page tree and then move it back again. Then all paths (urls) get updated.

Thanks for sharing this fix @zypro (and nice to meet you on GitHub :blush:)!

Additional note to the proposed manual fix:
I had pages which were nested a couple of levels; here it wasn't enough to move the top-parent page. I instead had to move every page which had children (starting with the inner-most pages).

**Comment by zypro** [comment]
The Problem isn't the slug itself but the `path` in the title object. This contains all slugs until the root node. These aren't updated if a parent node's slug is changed...

**Comment by benzkji** [comment]
@zypro yes. THX. fix is a bit of a pain, when having many pages...would need investigation, when to update that path.

**Comment by zypro** [comment]
@benzkji probably you should update the `path` in the referenced title object if the according page got updated. Maybe triggered by an event like `post_publish`?

**Comment by victor-yunenko** [comment]
By the way here's a temporary fix that I'm adding to my projects for the time being:

https://gitlab.com/what-digital/djangocms-helpers/-/blob/master/djangocms_helpers/fixes/language_slug_fix.py

It's also available on pypi as `djangocms-helpers`

**Comment by benzkji** [comment]
ha, work already done! thanks! @victor-yunenko @zypro

**Comment by Foobartender** [comment]
I'll repost my comment from last March, that fixed it for me:

cms.models.pagemodel.mark_descendants_as_published() updates the paths of the published titles of its children:
unpublished_public.exclude(has_url_overwrite=True).update(path=new_path)

I think it should update all titles of its children:
Title.objects.filter(language=language, page__in=page_children, has_url_overwrite=False).update(path=new_path)

**Comment by zypro** [comment]
> I'll repost my comment from last March, that fixed it for me:
> 
> cms.models.pagemodel.mark_descendants_as_published() updates the paths of the published titles of its children:
> unpublished_public.exclude(has_url_overwrite=True).update(path=new_path)
> 
> I think it should update all titles of its children:
> Title.objects.filter(language=language, page__in=page_children, has_url_overwrite=False).update(path=new_path)

When and where do you call this snippet @Foobartender?

**Comment by Foobartender** [comment]
It's how to modify the function mark_descendants_as_published() in cms.models.pagemodel. It should be a pull request, but I'm not sure that it doesn't have any other implications.

**Comment by ochagnon** [comment]
This bug is still present in 3.6.0, I assume upgrade to 3.7.2 to work around this is useless?

**Comment by zypro** [comment]
> This bug is still present in 3.6.0, I assume upgrade to 3.7.2 to work around this is useless?

It is still present in 3.7.1

**Comment by victor-yunenko** [comment]
I'm not sure whether I can help here. I submitted a PR with an ugly workaround in #6813 that somebody else discovered here and personally I don't have issues with using it through djangocms-helpers. If the file pagemodel.py was highly maintainable and didn't have 1600 lines of code in it I could have invested more time perhaps.

@FinalAngel, @Aiky30, you can adjust #6813 of course if you wish 👌

**Comment by fp4code** [comment]
This bug is still present in 3.8.0.

First problem, when the parent page is created in the second language, the calling to _update_title_path_recursive should be not skipped
https://github.com/django-cms/django-cms/blob/5e99e69f6b70d0d4053552105c30506c0581fd9b/cms/admin/forms.py#L476

Second problem, _update_title_path_recursive is buggy, probably here https://github.com/django-cms/django-cms/blob/5e99e69f6b70d0d4053552105c30506c0581fd9b/cms/models/pagemodel.py#L351
Indeed, if the slug is changed, the children pages Title.path are computed using the other language slug instead of the new one.

**Comment by benzkji** [comment]
Any chance to add this fix (soon) in a 3.8.1 release?

**Comment by goutnet** [comment]
@benzkji we aim to have this merged in 3.8.1 (which is likely going to be a 3.9.0).

Could you help us testing last `develop`  branch?

**Comment by benzkji** [comment]
nice. yes, I will, ...Monday probably.

**Comment by goutnet** [comment]
ok, thanks. With that said we aim to close the merge window this weekend :)
