### ISSUE TITLE
Multilanguage redirect to 500

### ISSUE THREAD

**Issue by chris542** [django-cms/django-cms#6660]
### Summary

We have 'Remove URL language prefix for default language' turned on in Aldryn-Django addon from Divio Control Panel, which disables /en/ prefix from our url.

There are some pages we have no translations for, hence, we tried redirecting other languages to redirect to our default language by having `/en/blog` in page advanced settings.

When user is on other languages, for example Spanish, the link to blog page says `/en/blog`. This expects user to redirect to English version of our blog page, however, we get 500 error.
Though, when the page is refreshed, the page reloads successfully.

### Expected behaviour

When user clicks on a link that has a redirect to other language, they should be redirected to correct page without having to refresh after 500 error.

### Actual behaviour

When user clicks on a link that has a redirect to other language, they see error 500. They need to refresh the page again to be redirected successfully.

### Environment

* Python version: 3.6.3
* Django version: 1.11.20
* django CMS version:3.5.3

**Comment by Aiky30** [comment]
@chris542 This is very old now. If this is still an issue can you please provide your settings for languages.

**Comment by chris542** [comment]
@Aiky30  Thanks for yor response. I'm no longer working on this project :)
