### ISSUE TITLE
how to intsall cms in python3.7,i have some error

### ISSUE THREAD

**Issue by ghost** [django-cms/django-cms#6663]
djangocms -f -p . demo            yb@yb-pc
Creating the project
Please wait while I install dependencies
If I am stuck for a long time, please check for connectivity / PyPi issues
ERROR: cmd : ['/usr/bin/python', '-mpip', 'install', '-q', 'django-cms>=3.6,<3.7', 'djangocms-admin-style>=1.2,<1.3', 'django-treebeard>=4.0,<5.0', 'djangocms-text-ckeditor>=3.7,<3.8', 'djangocms-link>=2.3', 'djangocms-style>=2.1', 'djangocms-googlemap>=1.2', 'djangocms-snippet>=2.1,<2.2', 'djangocms-video>=2.0,<2.1', 'djangocms-column>=1.9', 'djangocms-file>=2.2,<3.0', 'djangocms-picture>=2.0,<2.1', 'easy_thumbnails', 'django-filer>=1.3', 'Django<2.0', 'django-mptt>0.9', 'django-classy-tags>=0.7', 'html5lib>=1.0.1', 'Pillow>=3.0', 'django-sekizai>=0.9', 'six', 'pytz'] :b"Could not install packages due to an EnvironmentError: [Errno 13] \xe6\x9d\x83\xe9\x99\x90\xe4\xb8\x8d\xe5\xa4\x9f: '/usr/bin/__pycache__/django-admin.cpython-37.pyc'\nConsider using the `--user` option or check the permissions.\n\n"
The installation has failed.

*****************************************************************

Check documentation at https://djangocms-installer.readthedocs.io

*****************************************************************

Traceback (most recent call last):
  File "/usr/bin/djangocms", line 10, in <module>
    sys.exit(execute())
  File "/usr/lib/python3.7/site-packages/djangocms_installer/main.py", line 36, in execute
    verbose=config_data.verbose
  File "/usr/lib/python3.7/site-packages/djangocms_installer/install/__init__.py", line 98, in requirements
    output = subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/python', '-mpip', 'install', '-q', 'django-cms>=3.6,<3.7', 'djangocms-admin-style>=1.2,<1.3', 'django-treebeard>=4.0,<5.0', 'djangocms-text-ckeditor>=3.7,<3.8', 'djangocms-link>=2.3', 'djangocms-style>=2.1', 'djangocms-googlemap>=1.2', 'djangocms-snippet>=2.1,<2.2', 'djangocms-video>=2.0,<2.1', 'djangocms-column>=1.9', 'djangocms-file>=2.2,<3.0', 'djangocms-picture>=2.0,<2.1', 'easy_thumbnails', 'django-filer>=1.3', 'Django<2.0', 'django-mptt>0.9', 'django-classy-tags>=0.7', 'html5lib>=1.0.1', 'Pillow>=3.0', 'django-sekizai>=0.9', 'six', 'pytz']' returned non-zero exit status 1.
-----------------------------------------

**Comment by Davydayveed** [comment]
you need a really strong Internet connection to start project,

**Comment by Aiky30** [comment]
Closing as the original user has deleted their account and this issue has gone stale.

**Comment by OneMillionCode** [comment]
Hi， Could you please tell me how to solve time problem? I has spent a lot of time on it and I still has no idea about it.
Thank you very much.

**Comment by vinitkumar** [comment]
@OneMillionCode Are you on a slow internet connection or perhaps behind a firewall, that doesn't let you install packages from pypi? And please add any errors that you got so that we can reply looking at it.

**Comment by OneMillionCode** [comment]
@vinitkumar I install packages form [https://pypi.tuna.tsinghua.edu.cn/simple]. Error as follows.

`
django-cms-study) lrc@ubuntu:~/cmsproject$ djangocms -f -p . mysite
Creating the project
Please wait while I install dependencies
If I am stuck for a long time, please check for connectivity / PyPi issues
ERROR: cmd : ['/home/lrc/.virtualenvs/django-cms-study/bin/python', '-mpip', 'install', '--disable-pip-version-check', '-q', 'django-cms>=3.8,<3.9', 'djangocms-admin-style>=2.0,<3.0', 'django-treebeard>=4.0,<5.0', 'djangocms-text-ckeditor>=4.0,<5.0', 'djangocms-link>=3.0,<4.0', 'djangocms-icon>=2.0,<3.0', 'djangocms-style>=3.0,<4.0', 'djangocms-googlemap>=2.0,<3.0', 'djangocms-video>=3.0,<4.0', 'djangocms-file>=3.0,<4.0', 'djangocms-picture>=3.0,<4.0', 'djangocms-bootstrap4>=2.0,<3.0', 'easy_thumbnails', 'django-filer>=1.3', 'Django<3.2', 'django-classy-tags>=2.0', 'django-sekizai>=2.0', 'django-mptt>0.9', 'html5lib>=1.0.1', 'Pillow>=3.0', 'six', 'pytz'] :b'ERROR: Exception:\nTraceback (most recent call last):\n  File "/home/lrc/.virtualenvs/django-cms-study/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 171, in _merge_into_criterion\n    crit = self.state.criteria[name]\nKeyError: \'django-cms\'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/lrc/.virtualenvs/django-cms-study/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher\n    yield\n  File "/home/lrc/.virtualenvs/django-cms-study/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 519, in read\n    data = self._fp.read(amt) if not fp_closed else b""\n  File "/home/lrc/.virtualenvs/django-cms-study/lib/python3.8/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 62, in read\n    data = self.__fp.read(amt)\n  File "/usr/lib/python3.8/http/client.py", line 458, in read\n    n = self.readinto(b)\n  File "/usr/lib/python3.8/http/client.py", line 502, in readinto\n    n = self.fp.readinto(b)\n  File "/usr/lib/python3.8/socket.py", line 669, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.8/ssl.py", line 1099, in read\n    return self._sslobj.read(len, buffer)\nsocket.timeout: The read operation timed out\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/lrc/.virtualenvs/django-cms-study/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 189, in _main\n    status = self.run(options, args)\n  File "/home/lrc/.virtualenvs/django-cms-study/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 178, in wrapper\n    return func(self, options, args)\n  File "/home/lrc/.virtualenvs/django-cms-study/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 316, in run\n    requirement_set = resolver.resolve(\n  File "/home/lrc/.virtualenvs/django-cms-study/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 121, in resolve\n    self._result = resolver.resolve(\n  File "/home/lrc/.virtualenvs/django-cms-study/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 453, in resolve\n    state = resolution.resolve(requirements, max_rounds=max_rounds)\n  File "/home/lrc/.virtualenvs/django-cms-study/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 318, in resolve\n    name, crit = self._merge_into_criterion(r, parent=None)\n  File "/home/lrc/.virtualenvs/django-cms-study/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _merge_into_criterion\n    crit = Criterion.from_requirement(self._p, requirement, parent)\n  File "/home/lrc/.virtualenvs/django-cms-study/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 82, in from_requirement\n    if not cands:\n  File "/home/lrc/.virtualenvs/django-cms-study/lib/python3.8/site-packages/pip/_vendor/resolvelib/structs.py", line 124, in __bool__\n    return bool(self._sequence)\n  File "/home/lrc/.virtualenvs/django-cms-study/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in __bool__\n    return any(self)\n  File "/home/lrc/.virtualenvs/django-cms-study/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 38, in _iter_built\n    candidate = func()\n  File "/home/lrc/.virtualenvs/django-cms-study/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 167, in _make_candidate_from_link\n    self._link_candidate_cache[link] = LinkCandidate(\n  File "/home/lrc/.virtualenvs/django-cms-study/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 300, in __init__\n    super().__init__(\n  File "/home/lrc/.virtualenvs/django-cms-study/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 144, in __init__\n    self.dist = self._prepare()\n  File "/home/lrc/.virtualenvs/django-cms-study/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 226, in _prepare\n    dist = self._prepare_distribution()\n  File "/home/lrc/.virtualenvs/django-cms-study/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 311, in _prepare_distribution\n    return self._factory.preparer.prepare_linked_requirement(\n  File "/home/lrc/.virtualenvs/django-cms-study/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 457, in prepare_linked_requirement\n    return self._prepare_linked_requirement(req, parallel_builds)\n  File "/home/lrc/.virtualenvs/django-cms-study/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 480, in _prepare_linked_requirement\n    local_file = unpack_url(\n  File "/home/lrc/.virtualenvs/django-cms-study/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 230, in unpack_url\n    file = get_http_url(\n  File "/home/lrc/.virtualenvs/django-cms-study/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 108, in get_http_url\n    from_path, content_type = download(link, temp_dir.path)\n  File "/home/lrc/.virtualenvs/django-cms-study/lib/python3.8/site-packages/pip/_internal/network/download.py", line 163, in __call__\n    for chunk in chunks:\n  File "/home/lrc/.virtualenvs/django-cms-study/lib/python3.8/site-packages/pip/_internal/network/utils.py", line 64, in response_chunks\n    for chunk in response.raw.stream(\n  File "/home/lrc/.virtualenvs/django-cms-study/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 576, in stream\n    data = self.read(amt=amt, decode_content=decode_content)\n  File "/home/lrc/.virtualenvs/django-cms-study/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 541, in read\n    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)\n  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__\n    self.gen.throw(type, value, traceback)\n  File "/home/lrc/.virtualenvs/django-cms-study/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher\n    raise ReadTimeoutError(self._pool, None, "Read timed out.")\npip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host=\'pypi.tuna.tsinghua.edu.cn\', port=443): Read timed out.\n'
The installation has failed.


*****************************************************************

Check documentation at https://djangocms-installer.readthedocs.io

*****************************************************************

Traceback (most recent call last):
  File "/home/lrc/.virtualenvs/django-cms-study/bin/djangocms", line 8, in <module>
    sys.exit(execute())
  File "/home/lrc/.virtualenvs/django-cms-study/lib/python3.8/site-packages/djangocms_installer/main.py", line 33, in execute
    install.requirements(
  File "/home/lrc/.virtualenvs/django-cms-study/lib/python3.8/site-packages/djangocms_installer/install/__init__.py", line 95, in requirements
    output = subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/lrc/.virtualenvs/django-cms-study/bin/python', '-mpip', 'install', '--disable-pip-version-check', '-q', 'django-cms>=3.8,<3.9', 'djangocms-admin-style>=2.0,<3.0', 'django-treebeard>=4.0,<5.0', 'djangocms-text-ckeditor>=4.0,<5.0', 'djangocms-link>=3.0,<4.0', 'djangocms-icon>=2.0,<3.0', 'djangocms-style>=3.0,<4.0', 'djangocms-googlemap>=2.0,<3.0', 'djangocms-video>=3.0,<4.0', 'djangocms-file>=3.0,<4.0', 'djangocms-picture>=3.0,<4.0', 'djangocms-bootstrap4>=2.0,<3.0', 'easy_thumbnails', 'django-filer>=1.3', 'Django<3.2', 'django-classy-tags>=2.0', 'django-sekizai>=2.0', 'django-mptt>0.9', 'html5lib>=1.0.1', 'Pillow>=3.0', 'six', 'pytz']' returned non-zero exit status 2.
`

**Comment by vinitkumar** [comment]
@OneMillionCode I think this has definitely something to do with your mirror. Not sure, if it's possible, have you tried doing it with the main pypi mirror?

**Comment by OneMillionCode** [comment]
> @OneMillionCode I think this has definitely something to do with your mirror. Not sure, if it's possible, have you tried doing it with the main pypi mirror?

@vinitkumar  Thank you for your help. when I switch to the originate pip source, It download successful. Thanks again.
