### ISSUE TITLE
NavigationNode of unpublished page shown for authenticated user without change permission

### ISSUE THREAD

**Issue by tschale** [django-cms/django-cms#6669]
### Summary

I have a website with diverse authorization groups, where the groups of a user determine whether a page can be edited or not. However an authenticated user that does not have the change-permission of a certain unpublished page can see that page in the menu. When clicking on the page, the expected and correct error occurs.
This seems to be related to #6428. The fix provided in #6429 seems to solve it.

### Expected behaviour
- NavigationNode of unpublished pages are only shown when the authenticated user has change permission of that page

### Actual behaviour
- NavigationNode of unpublished pages are shown for authenticated user without change permission of that page

### Environment

* Python version: 3.6.7
* Django version: 1.11.10
* django CMS version: 3.5.2

**Comment by Aiky30** [comment]
Fixed in 3.7.1: 

> Fixed a bug where the menu would render draft pages even if the page on the request was a public page. This happens when a user without change permissions requests edit mode.

https://github.com/django-cms/django-cms/blob/develop/CHANGELOG.rst#371-2019-11-26
