### ISSUE TITLE
Unable to Redirect to external URLs under Advanced Settings

### ISSUE THREAD

**Issue by quizy101** [django-cms/django-cms#6670]
### Summary

I am unable to use REDIRECT under Advanced Settings for Pages. Whenever I use an external URL, I get "Loading failed" below and I cannot hit enter to use the external URL.

### Expected behaviour

I should be able to use a URL with http:// or https:// in the address to get a page to redirect.

### Actual behaviour

![image](https://user-images.githubusercontent.com/2344507/56260180-3add5e80-60a4-11e9-9f2d-242ce1b4f4b5.png)

### Environment

* Python version: 3.5.2
* Django version: 1.11.20
* django CMS version: 3.6.0

**Comment by victor-yunenko** [comment]
True, that redirects field also has other issues, on top of that it's hard to know which pages have a redirect and which don't.

Few years ago we switched to djangocms-redirect for all redirects, where it's much easier to manage them. I would prefer to drop this redirect field completely from the core.
