### ISSUE TITLE
security@django-cms.org not available

### ISSUE THREAD

**Issue by moellering** [django-cms/django-cms#6681]
### Summary
security@django-cms.org not available 

### Expected behaviour
I can send Emails to security@django-cms.org and somebody can have a look at them.

### Actual behaviour
I receive a "Undelivered Mail Returned to Sender" Email:
'''
<security@django-cms.org>: host aspmx.l.google.com[173.194.76.27] said:
    550-5.1.1 The email account that you tried to reach does not exist. Please
    try 550-5.1.1 double-checking the recipient's email address for typos or
    550-5.1.1 unnecessary spaces. Learn more at 550 5.1.1
    https://support.google.com/mail/?p=NoSuchUser k18si1587585wrl.351 - gsmtp
    (in reply to RCPT TO command)
'''

### Remarks
Same goes for postmaster@django-cms.org 
I have not checked other default addresses

**Comment by czpython** [comment]
Strange.. @moellering if you have an issue to disclose, can you send it to:
Me - commonzenpython@gmail.com and Daniele - daniele.procida@divio.com

**Comment by FinalAngel** [comment]
Taking a look

**Comment by FinalAngel** [comment]
closing as the email is working again
