### ISSUE TITLE
New release for 3.6.1

### ISSUE THREAD

**Issue by DmytroLitvinov** [django-cms/django-cms#6684]
### Summary

Last version for release of django-cms 3.6 was published on PyPi on 29th of January, 2019.
[Here a link](https://github.com/divio/django-cms/compare/b2b35ca9d5564ee90b87a8f81c10d24f96304878...release/3.6.x) to what has been done since the last release on PyPi.

Maybe it is time to release 3.6.1. What do you think @vThaian @FinalAngel @czpython ?

**Comment by FinalAngel** [comment]
Thanks @DmytroLitvinov we're having it on our todos as we're also planning the next LTS release.

**Comment by Aiky30** [comment]
Closing as this has happened.
