### ISSUE TITLE
Plugin javascript code, not executed upon adding it

### ISSUE THREAD

**Issue by s-weigand** [django-cms/django-cms#6698]
### Summary
While writing integration tests for [my django-CMS plugin](https://github.com/s-weigand/djangocms-equation), which requires the execution of javascript code to be rendered properly, I found that the javascript code isn't executed when the plugin is added for the first time.
Instead the page needs to be published or refreshed, for the DOM to to use the scripts.

### Expected behaviour
The javascript code loads and executes, when the plugin is added to the page and it gets rendered properly.

### Actual behaviour
The html code of the updated page is requested via ajax and the innerHtml of the body is replaced with the updated innerHtml of the new body ([see](https://github.com/divio/django-cms/blob/8964d77b876ddb9221a12c64d1c4f5b5575b2049/cms/static/cms/js/modules/cms.structureboard.js#L1293)). This method leads for the scripts not to be executed (tested it with a minimal example in a static html file).
[djangocms-googlemap](https://github.com/divio/djangocms-googlemap) has the same problem.

### Environment

* Python version: All (Javascript issue)
* Django version: All (Javascript issue)
* django CMS version: All (Javascript issue)

**Comment by benzkji** [comment]
this was a breaking change in 3.5.0. also re-ordering or simply saving a plugin makes for the same behaviour! at the very least, this should be better documented (I stumbled upon it as well: #6343). one solution is to listen for a specific event the CMS's javascript is firing, as in my issue.

**Comment by benzkji** [comment]
though, your use case might be different. in mine, all js was already loaded in a minified js file, so listening to an event and calling some init functions was working...adding script tags in plugins is probably different, though.

**Comment by s-weigand** [comment]
As stated in the [docs](http://docs.django-cms.org/en/latest/topics/frontend-integration.html?highlight=cms-content-refresh) my code also listens for the 'cms-content-refresh' event. 
The problem is that the page needs to be published or refreshed for the code with the eventlistener in it to be executed.
The easiest way to reproduce this problem is to add a [djangocms-googlemap](https://github.com/divio/djangocms-googlemap) to an empty page, since it also depends on the js code to be executed for rendering (I have a PR [there](https://github.com/divio/djangocms-googlemap/pull/89) and [here](#6699) as well). On saving the plugin it won't be rendered, only after publishing or refresh it will.

**Comment by benzkji** [comment]
sorry, not reading carefully enough!
