### ISSUE TITLE
cms.utils.conf.get_templates order is not predictable

### ISSUE THREAD

**Issue by sephii** [django-cms/django-cms#6706]
### Summary

When using `CMS_TEMPLATES_DIR`, the [`cms.utils.conf.get_templates` function](https://github.com/divio/django-cms/blob/006367b6787b1ec884c1e5423a0cfc1a53305328/cms/utils/conf.py#L129) retrieves the list of templates using `os.listdir`, which, [according to the documentation](https://docs.python.org/3/library/os.html#os.listdir), doesn't guarantee any order. Should there be an `__init__.py` file in the `CMS_TEMPLATES_DIR` listing the available templates, the order is not predictable either on Python 3.5 since dict order is not preserved. This can cause issues, for example [in some 3rd party libraries](https://github.com/nephila/djangocms-apphook-setup/blob/9644a09eefd0d11434f2a70dee92258ef13f1089/djangocms_apphook_setup/base.py#L40) that rely on the templates order.

### Expected behaviour

The list returned by `get_templates` is predictable.

### Actual behaviour

The order of the items in the list is random.

### Environment

* Python version: 3.4
* Django version: 1.11
* django CMS version: 3.5.2

**Comment by Aiky30** [comment]
This is resolved as of Python 3.7:

> The insertion-order preservation nature of dict objects is now an official part of the Python language spec.
https://www.python.org/downloads/release/python-370/
