### ISSUE TITLE
editing nested object via TabularInline automatically published on page

### ISSUE THREAD

**Issue by lukaszjagodzinski** [django-cms/django-cms#6714]
### Summary
Nested object used as TabluraInline on save after add new or editing automatically are published. Request goes through admin page - TabluarInline open new window with editing as admin page. Same situation happen when nested object is editied via admin page.

```python
class CardsAdmin(admin.TabularInline):
    model = Card.card_section.through
    extra = 0


class CardsPlugin(CMSPluginBase):
    model = CardsModel
    name = __('Cards')
    inlines = (CardsAdmin, )
    render_template = 'cards.html'
    exclude = ('cards', )

    def render(self, context, instance, placeholder):
        context = super().render(context, instance, placeholder)
        context['section'] = instance
        context['cards'] = instance.cards.order_by('cardcardsmodel__id')
        return context
```

### Expected behaviour
After editing nested object, update should be change after hit publish button.

### Environment

* Python version: "3.6.8"
* Django version: "1.11.20"
* django CMS version: "3.4.6"

**Comment by Aiky30** [comment]
This is caused by not implementing the copy method, without the copy method the plugin model will just keep a link to the original model that you attached it to: http://docs.django-cms.org/en/latest/how_to/custom_plugins.html#handling-relations
