### ISSUE TITLE
Release notes list link is 404

### ISSUE THREAD

**Issue by jscontrust** [django-cms/django-cms#6716]
The link to the release notes on this page is a 404:

https://www.django-cms.org/en/blog/2019/08/14/django-cms-3-7-release-candidate-1/

Pleeeaase, I want to know what`s new :)

**Comment by jmhrovat** [comment]
This appears to be working? Do you want to close your issue?

**Comment by Aiky30** [comment]
Closing as this appears to have gone stale.
