### ISSUE TITLE
Is i18n get_current_language needed any more ?

### ISSUE THREAD

**Issue by stuaxo** [django-cms/django-cms#6720]
The [Django bug this references](https://code.djangoproject.com/ticket/9340) was shut 6 years ago, so maybe the function itself could be deprecated with a view to removing it ?

https://github.com/divio/django-cms/blob/develop/cms/utils/i18n.py#L75

```python
def get_current_language():
    """
    Returns the currently active language

    It's a replacement for Django's translation.get_language() to make sure the LANGUAGE_CODE will be found in LANGUAGES.
    Overcomes this issue: https://code.djangoproject.com/ticket/9340
    """
    language_code = translation.get_language()
    return get_language_code(language_code)

```

**Comment by stuaxo** [comment]
Hi @Aiky30 know if anybody in DjangoCMS land can look at this and decide to fix it?

Any improvements to the docs probably help.

**Comment by Aiky30** [comment]
Hi @stuaxo, Sure thing. I'll post it into the Slack channel and get it marked with a task todo.

**Comment by stuaxo** [comment]
Cheers, trying not to be a drive by Dev too much these days :)

**Comment by stuaxo** [comment]
Thanks for the fix @marksweb https://github.com/django-cms/django-cms/pull/7410

@marksweb @fsbraun it may worth adding the info to the docstring, but at least the info is there.
