### ISSUE TITLE
Get urls of many titles in one query, avoiding get_absolute_url()

### ISSUE THREAD

**Issue by stuaxo** [django-cms/django-cms#6722]
Using title.get_absolute_url() is not ideal, as it can't be incorporated into a query that gets many titles.

Given a query that returns a lot of tags, is there a way I can grab the urls from all of them, by doing something that runs purely in a queryset ?

**Comment by benzkji** [comment]
as `get_absolute_url()` needs to check various things, this probably wont work. for example, it must check: 

- am I a homepage, ie "/"?
- have I an "override_url" set
- get alle the slugs of the parent pages, construct slug

as far as I can judge, this will not work on a db level only.

**Comment by stuaxo** [comment]
It seems like the database + API are not setup easily for batch access.

The first two seem like they might be doable in a queryset.

The last one seems more difficult, I'm not quite sure what the database structure is here, or how the slug is constructed.

**Comment by benzkji** [comment]
the slug is constructed like this:

`/parent-slug/parent-slug/..../current-item-slug/ `

it is a tree, based on django-treebeard. short story: the tree structure is in its own table, having assigned a draft/public version the `Page`, and each of these has a `Title` object for every language configured.

dig into it: https://github.com/divio/django-cms/blob/develop/cms/models/pagemodel.py

**Comment by Aiky30** [comment]
Closing as this seems to have no actionables.


If you want to learn more about the work of the technical committee, our product vision and how you can become a member of the dCA, you can find all information here:

- [The Technical Committee of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/tech-committee/about.md)
- [Technical Roadmap and Product Vision for django CMS](https://github.com/django-cms/django-cms-mgmt/blob/master/django-cms/roadmap.md)
- [How to become a member of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/association/about.md)

We are looking forward to every companion who would like to shape the future of django CMS together with us! 

If you have any questions, feel free to reach out to Nicolai, our Community Manager: nicolai@django-cms.org 


Sign up for the Association now!

**Comment by stuaxo** [comment]
Fair enough.  I don't think I'm going to get time to join the community association unless I get another role working on a djangocms project because I have too many projects already.

In case any one is, it would be good if DCMS:
- Has a principle that any new database APIs should work in batch mode.  (i.e., they are query objects that multiple items by default), this will enable composability.

Cheers for the info, and definitely may come back to this one day.
