### ISSUE TITLE
Multiple static placeholders in single page throws error.

### ISSUE THREAD

**Issue by agajankush** [django-cms/django-cms#6729]
### Environment

* Python version:
* Django version:
* django CMS version:

**Comment by agajankush** [comment]
The error is, 
**ValueError: Cannot assign "1": "StaticPlaceholder.site" must be a "Site" instance.**
I fixed the issue in my project by changing below thing in "cms/templatetags/cms_js_tags.py" in function "render_cms_structure_js" line 49.

**Before** 
kwargs['site'] = renderer.current_site.pk

**After**
kwargs['site_id'] = renderer.current_site.pk

This kwargs is used in get_or_create(**kwargs) function below which is a standard django function and it requires either the site object or the site_id for getting or creating StaticPlaceholder object. 
Hope this helps someone !!!!

**Comment by Aiky30** [comment]
This appears to have been resolved, I'm assuming that this was probably caused by the use of a different Django version than what was supported. Closing for now.
