### ISSUE TITLE
Page is not redirecting properly if it has different slug for each language

### ISSUE THREAD

**Issue by tgckpg** [django-cms/django-cms#6742]
### Summary
Setup
Create a Page "A" in CMS
- Set slug for the page of "A" for lang en to `a`
- Set slug for the page of "A" for lang not-en to `b`

### Expected behaviour
Page `/b/` ( since this is a `not-en` specific slug ) should be redirected to `/a/`

### Actual behaviour
Page `/b/` is showing as `/a/`

Here a gif I've recorded. The last `/b/` should be redirected to `/a/`
![should-be-a](https://user-images.githubusercontent.com/5273654/66253298-99081600-e798-11e9-8740-aa1eff7417f8.gif)

### Suggested fix
Since this is a two-staged bug. First bug refers to [this ticket](https://code.djangoproject.com/ticket/30272) in django.
- i.e., apply [this patch](https://github.com/django/django/pull/11123/commits/eaaa07ca971c2d19bc166e0750d043a49ba575fd) first
- then, in `cms/utils/page.py` function `get_page_from_path`, replace the following line in the for loop
```diff
    for title in titles.iterator():
        if title.page.node.site_id != site.pk:
            continue
        if published_only and not _page_is_published(title.page):
            continue
-       title.page.title_cache = {title.language: title}
+       title.page._get_title_cache( None, False, True )
```
This is to cause a reload in `title_cache` so that when calling `get_absolute_path` in `cms/views.py` it won't fallback to the only language predefined before.

### Environment

* Python version: 3.6
* Django version: 2.2.5
* django CMS version: 3.4.7

**Comment by Zeerooth** [comment]
Are you still experiencing this issue? I do, but in my case redirection works a little different:
I'm able to change language to correct language and slug, but i have to do it twice as for the first time only language prefix is changing and for the second time - the slug itself

**Comment by tgckpg** [comment]
YMMV, there's another bug if you are using session db ( e.g. redis ) which is caused by some race conditions.

It goes on like this:

1. User change language
2. Server store lang into session db
3. User request the page. At the time session db has not updated yet. **Returns an old value**.
4. Now the page display is in old lang but with new lang's URI. Everything goes funny for this instance. ( for this first time )
5. User refresh the page again ( this time session db returns the correct lang ). Everything goes normal.

To fix this you'll need to modify `django/utils/translation/trans_real.py`.
There should be a line: `if hasattr(request, 'session')`. Remove the entire block. This causes django to lookup the lang using user provided cookie.

IIRC this bug is fixed in master.

**Comment by Zeerooth** [comment]
Thanks for the reply! 
Unfortunately, I don't use any session db yet, so I don't think this is the issue.
I checked how my site goes through this block and the lang_code isn't even returned there - it comes from `request.COOKIES.get(settings.LANGUAGE_COOKIE_NAME)` which, in some requests, doesn't return proper language code, so the issue may actually lay there (maybe in cookies?) 

Anyway, our bugs have different origin then, probably
