### ISSUE TITLE
Multilanguage page - changes are also applied to default language when editing a page in different language while LANGUAGE_CODE is not set to 'en' (English)

### ISSUE THREAD

**Issue by Zeerooth** [django-cms/django-cms#6750]
### Summary

To start things off, I followed the guides on translations on Django and djangocms documentations, set up middleware in correct order, correctly specified LANGUAGE_CODE, USE_I18N, USE_L10N, CMS_LANGUAGES and LANGUAGES in settings.py, configured i18n_patterns in urls.py etc.
Tested the presence of this bug both on new and existing projects.
While editing multilanguage page using front-end, the language doesn't correctly switch (except for the multilingual slug and /admin/) and changes in every page are also being applied to default language that is not English. When English is enabled as default, django-cms works without issues.

### Expected behaviour

When setting LANGUAGE_CODE to something other than 'en' django-cms should still work correctly and separate content of different language versions of every page. Content added on English, Spanish, Polish etc. sites should be independent and not be duplicated on page that corresponds to current default language  

### Actual behaviour

While editing multilanguage page with plugins using front-end and then publishing the changes content from the edited page is also pasted in corresponding placeholders on default language's page when it's set to something else than English

### Environment

* Python version: 3.7.3
* Django version: 1.11.25
* django CMS version: 3.7.0

**Comment by Zeerooth** [comment]
I'm also experiencing an issue similar to this one: #6742

**Comment by pawelmarkowski** [comment]
hi, can anybody take a look into that issue? I can confirm that the problem exists.
