### ISSUE TITLE
[bug] Toolbar does not detect static plugin changes - and thus publication is not possible

### ISSUE THREAD

**Issue by petrklus** [django-cms/django-cms#6754]
### Summary

A custom application is using static placeholders to populate its sidebar contents. The changes to the sidebar are not detected, yet editing works as expected and toggling between "view published" and "edit" modes work.

### Expected behaviour

The publish button should appear when static placeholders are altered.

### Actual behaviour

The publish button never appears in the toolbar. As a workaround, we had created a CMS page with a template that features all static placeholders one after another - there the changes are detected correctly (even if only static placeholders are altered).

### Environment

* Python version: 3.6.8
* Django version: 1.11
* django CMS version: 3.7 (running on Divio)

**Comment by marksweb** [comment]
I feel like this got fixed.
