### ISSUE TITLE
Page permissions is broken on Django 1.11 and DjangoCMS>=3.6

### ISSUE THREAD

**Issue by sephii** [django-cms/django-cms#6774]
## Description

Page permissions modal doesn't have any "add" button in the permissions inlines. This means you can't add page permissions.

![screenshot](https://user-images.githubusercontent.com/754333/69714131-27987400-1106-11ea-8605-5d86728c3e7e.png)

There is already https://github.com/divio/django-cms/issues/6689 which concluded "upgrade to Django 2", but since the docs mention DjangoCMS to work with Django 1.11, I think it can be considered as a bug.

## Steps to reproduce

1. Install DjangoCMS 3.6 or 3.7 with Django 1.11
2. Open a page, go to the Page > Permissions menu
3. You'll see you can't add page permissions

## Expected behaviour

There is a button to add permissions. Or it is mentioned in the docs that DjangoCMS>=3.6 doesn't support Django 1.11.

## Actual behaviour

There is no way to add page permissions.

## Additional information

Python 3.7.3
Django 1.11.26
DjangoCMS 3.7.1

**Comment by jgadelange** [comment]
Having the same issue here
