### ISSUE TITLE
Page tree layout broken due to a translation override

### ISSUE THREAD

**Issue by adrien-delhorme** [django-cms/django-cms#6783]
## Description

The layout of the admin page tree is broken:
- the title of the "home" page, actions links and menu are hidden
- on the children pages, collapse arrows are hidden or misplaced

![djangocms-admin-pagetree-broken](https://user-images.githubusercontent.com/1597706/70907780-068eb900-200a-11ea-976e-a0a0891c6157.png)

This is caused by unintended overriding of translation of the string "Home" by a string containing a single quote ("Home" can be translated in french by "Page d'accueil").

This issue has been resolved in 2016, but resurfaced since then.

## Steps to reproduce

1. in your project, add a translatable string "Home" (for example `{% trans "Home" %}`)
2. translate the string with something containing a single quote (for example "Page d'accueil")

## Expected behaviour

The admin  page tree is not broken.

## Actual behaviour

The admin  page tree is broken.

## Additional information

A quick fix might be to add a context on the "Home" translatable string in django-cms. Escaping single quotes might be a cleaner solution, but the `{% filter espacejs %}` that was present in 2016, has been replaced by `{% autoescape on %}` which does nothing with single quotes.

**Comment by Aiky30** [comment]
Next steps for this issue are to verify whether the issue still exists, if it is still an issue then propose a fix.

**Comment by wfehr** [comment]
I am also having the described problem.

Versions:
- django-cms: 3.8.0
- django: 3.1.8

Problem is also a overriden "Home"-translation:
```
msgid "Home"
msgstr "À la page d'accueil"
```

![pagetree_error](https://user-images.githubusercontent.com/24782511/119933550-9b7a3d80-bf84-11eb-822c-e9d63345a54e.png)

**Comment by goutnet** [comment]
I can fix that in the translation

**Comment by goutnet** [comment]
in the French translation the string "Home" does not map to something with a quote in there (with that said we should really fix the escaped string ).

Can you check if you still have this issue on 3.9.0rc2 ?

**Comment by goutnet** [comment]
in the last translations (on 3.9):

```
msgid "Home"
msgstr "Accueil"
```

**Comment by wfehr** [comment]
The problem is still present and it's not because of the default translation for "Home" (as you pointed out, there is no single quote in there).

As long as you override "Home" with a string containing a single quote, the problem occurs.

That said: I made a workaround in my system by changing the translation from "Home" to something different (e.g. "foo Home"), then the page-tree works as it should.
