### ISSUE TITLE
Unable to use database router with single writer and many readers

### ISSUE THREAD

**Issue by awiddersheim** [django-cms/django-cms#6785]
## Description

Trying to use a database router that will help support many readers and a single writer. When adding a plugin like text, it fails with an exception.

## Steps to reproduce

Setup a database router similar to the following:

```
class DatabaseRouter:
    """
    A router that is configured for a master/slave setup.
    """

    def db_for_read(self, model, **hints):
        """ Point all read operations to a read-slave. """
        return 'default'

    def db_for_write(self, model, **hints):
        """ Point all write operations to the master """
        return 'writer'

    def allow_relation(self, obj1, obj2, **hints):
        """ Because we have master-slave replication, any relation is allowed. """
        return True

    def allow_migrate(self, db, app_label, **hints):
        """
        All models that have not been migrated to another DB get
        migrated to master only. Read-replication takes care of
        populating the tables on the replicas.
        """
        if hints.get('target_db', None) == settings.WRITER_DB:
            return True
        if db == settings.WRITER_DB:
            return True
        return False
```

## Expected behaviour

This should just work without issue AFAIK.

## Actual behaviour

The following exception is observed:

```
web_1    | Traceback (most recent call last):
web_1    |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
web_1    |     response = get_response(request)
web_1    |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
web_1    |     response = self.process_exception_by_middleware(e, request)
web_1    |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
web_1    |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1    |   File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
web_1    |     response = view_func(request, *args, **kwargs)
web_1    |   File "/usr/local/lib/python3.6/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
web_1    |     response = view_func(request, *args, **kwargs)
web_1    |   File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 224, in inner
web_1    |     return view(request, *args, **kwargs)
web_1    |   File "/usr/local/lib/python3.6/site-packages/django/views/decorators/clickjacking.py", line 39, in wrapped_view
web_1    |     resp = view_func(*args, **kwargs)
web_1    |   File "/usr/local/lib/python3.6/site-packages/cms/admin/placeholderadmin.py", line 341, in add_plugin
web_1    |     response = plugin_instance.add_view(request)
web_1    |   File "/usr/local/lib/python3.6/site-packages/django/views/decorators/clickjacking.py", line 39, in wrapped_view
web_1    |     resp = view_func(*args, **kwargs)
web_1    |   File "/usr/local/lib/python3.6/site-packages/djangocms_text_ckeditor/cms_plugins.py", line 305, in add_view
web_1    |     request, form_url, extra_context
web_1    |   File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1509, in add_view
web_1    |     return self.changeform_view(request, None, form_url, extra_context)
web_1    |   File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 67, in _wrapper
web_1    |     return bound_func(*args, **kwargs)
web_1    |   File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
web_1    |     response = view_func(request, *args, **kwargs)
web_1    |   File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 63, in bound_func
web_1    |     return func.__get__(self, type(self))(*args2, **kwargs2)
web_1    |   File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1409, in changeform_view
web_1    |     return self._changeform_view(request, object_id, form_url, extra_context)
web_1    |   File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1454, in _changeform_view
web_1    |     return self.response_add(request, new_object)
web_1    |   File "/usr/local/lib/python3.6/site-packages/cms/plugin_base.py", line 354, in response_add
web_1    |     return self.render_close_frame(request, obj)
web_1    |   File "/usr/local/lib/python3.6/site-packages/cms/plugin_base.py", line 300, in render_close_frame
web_1    |     'plugin_structure': get_plugin_tree_as_json(request, plugins),
web_1    |   File "/usr/local/lib/python3.6/site-packages/cms/toolbar/utils.py", line 70, in get_plugin_tree_as_json
web_1    |     plugin_tree = build_plugin_tree(plugins)
web_1    |   File "/usr/local/lib/python3.6/site-packages/cms/utils/plugins.py", line 138, in build_plugin_tree
web_1    |     root_depth = min(plugin.depth for plugin in plugins)
web_1    | ValueError: min() arg is an empty sequence
```

## Additional information

Using `python3.6` with `django-cms==3.5.2`.

**Comment by awiddersheim** [comment]
Just to add to this, you don't actually need two DBs to reproduce just two separately configured ones that can still point the same database.

```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'cms',
        'USER': 'foo',
        'PASSWORD': 'bar',
        'HOST': 'localhost',
        'PORT': 3306,
    },
    'writer': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'cms',
        'USER': 'foo',
        'PASSWORD': 'bar',
        'HOST': 'localhost',
        'PORT': 3306,
    },
}

DATABASE_ROUTERS = [
    'some.db.router',
]
```

**Comment by jrief** [comment]
In my opinion, this doesn't have to do anything with your database replication. Btw. what's the purpose of using the same database, as well for the master, as for their replicas? Anyway, it looks more like a version mismatch between django-CMS and djangocms-ckeditor. Did you check that?

**Comment by awiddersheim** [comment]
It's a common pattern to spread requests out over many read-replicas and write to only a single master. It is even an documented example in the Django docs:

https://docs.djangoproject.com/en/2.1/topics/db/multi-db/#an-example

I'm mentioned that it is possible to reproduce using the same underlying database but defined multiple times in Django to make it easier for people to troubleshoot. Basically, you don't need to go setup a large DB infrastructure to see the same things I am. That said, in a production scenario they would be different.

I was able to get my router (see below) to a point where I could create plugins but this then broke creating new pages. It doesn't seem to even generate any exception that I can find, just eventually times out with a `502`.

```
from django.conf import settings


class DatabaseRouter:
    def db_for_read(self, model, **hints):
        """ Route read operations. """

        # NOTE(awiddersheim): If no `instance` was passed in the `hints`,
        # send the operation to the read replicas. If an instance was
        # passed, fall through to the default router which will either
        # use the suggested database or route to the `default` which is
        # the `writer`.
        # https://docs.djangoproject.com/en/2.1/topics/db/multi-db/#hints
        if hints.get('instance') is None:
            return settings.READER_DB


    def allow_relation(self, obj1, obj2, **hints):
        """ Because we have replication, any relation is allowed. """
        return True
```

**Comment by awiddersheim** [comment]
After spending a few hours tracing this back I think I see the issue, at least when adding plugins but there could be other places where this crops up with my specific use case and transactions specifically.

When adding a plugin eventually you hit this code in Django proper:

https://github.com/django/django/blob/master/django/contrib/admin/options.py#L1520-L1522

This starts a transaction for the `djangocms_text_ckeditor.models.Text` model for example on whatever the DB router says is the `writer`. In my use case it is the `master` DB in my single writer and many reader architecture. Later, in the django-cms code, a query set is used without specifically using the writer DB or without any `hint` provided for the DB router to use so it will get processed by the `read-replicas` while still in a transaction on the `master`:

https://github.com/divio/django-cms/blob/develop/cms/utils/plugins.py#L277
https://github.com/divio/django-cms/blob/develop/cms/plugin_base.py#L173-L174

Since this then queries the database without the on-going transaction, nothing is returned resulting in the exception above. If we were to change this line to be something like which more closely matches what Django proper is doing above, things work:

```
return cls.model._default_manager.using(router.db_for_write(cls)).all()
```

I'm far from a Django expert so I'm not sure if there are better ways to do this or if there is something I could change on my end to circumvent these issues without adjusting the django-cms code base to handle transactions better and my use case of single writer and many readers.

**Comment by dherbst** [comment]
Because the django-cms is a third party I'm not familiar with how to do the transaction management with the readonly vs writing.

**Comment by Tisagh** [comment]
Was this resolved?

I came looking for MongoDB support but figured I'd be better off trying a router.
