### ISSUE TITLE
StructureBoard-position does not update if 'right' would become 0

### ISSUE THREAD

**Issue by wkleinheerenbrink** [django-cms/django-cms#6792]
## Description
The StructureBoard receives a `right: ${scrollBarWidth }` when `scrollBarWidth !== 0`. This makes sense, because the StructureBoard would be mis-positioned otherwise. If the `scrollBarWidth` changes after page load in such a way that `scrollBarWidth === 0`, `right`-property is never updated.

## Steps to reproduce
1. Add the following (inline) style to body: `<body style="display: none">`
2. Add a script-tag: `<script>setTimemout(() => $('body').css({ 'display': 'initial' }), 2000</script>`
3. Open StructureBoard once the page appears

What happens:

*Step 1* there is no body. Therefore the width of the CMS Toolbar will be zero. The CMS is initiating the structureboard. It will run the following lines of code:

https://github.com/divio/django-cms/blob/75c39582ec5a58bee70fc5d67a72f90c47fc4b98/cms/static/cms/js/modules/cms.structureboard.js#L359-L360

The `innerWidth` of the window is the actual width of the page (eg. 1240px). The `width` of the toolbar is 0. Therefor the `scrollBarWidth` is a negative number (eg. -1240).

The next lines of code will apply this negative scrollBarWidth:

https://github.com/divio/django-cms/blob/75c39582ec5a58bee70fc5d67a72f90c47fc4b98/cms/static/cms/js/modules/cms.structureboard.js#L366-L368

*Step 2* will reveal the body and CMS Toolbar. Now the width of the toolbar is the same as the width of the window.

*Step 3* will show the structureboard and run the same code as in step 1.

https://github.com/divio/django-cms/blob/75c39582ec5a58bee70fc5d67a72f90c47fc4b98/cms/static/cms/js/modules/cms.structureboard.js#L359-L360

This time the result is `scrollBarWidth = 0` which is correct. The `right` property should be changed to `right = 0`. But!

https://github.com/divio/django-cms/blob/75c39582ec5a58bee70fc5d67a72f90c47fc4b98/cms/static/cms/js/modules/cms.structureboard.js#L366-L368

The `if(scrollBarWidth)` (ie. `if (0)`) prevents this line from being executed.

## Expected behaviour

`this.ui.toolbar.css('right', scrollBarWidth);` should be 0.

## Actual behaviour
`this.ui.toolbar.css('right', scrollBarWidth);` remains negative.

## Additional information

The easy fix would be to always execute `this.ui.toolbar.css('right', scrollBarWidth);` (no check if it is zero). I do not know why this line is added, so I'm not sure it can just be removed.

**Comment by Aiky30** [comment]
Next steps for this issue is to first validate / check that the issue exists and then create a solution.
