### ISSUE TITLE
Documentation: django.urls.exceptions.NoReverseMatch (and other Documentation issues)

### ISSUE THREAD

**Issue by davidshumway** [django-cms/django-cms#6831]
## Description 

Using the tutorial found here: [http://docs.django-cms.org/en/latest/introduction/05-apphooks.html](http://docs.django-cms.org/en/latest/introduction/05-apphooks.html). Up to step 5, there has not been any major issue. However, when completing the steps in step 5, the following error appears:

> django.urls.exceptions.NoReverseMatch: 'polls' is not a registered namespace

Screenshot available here: [https://imgur.com/6i0hnTG](https://imgur.com/6i0hnTG).

This is after completing step `5.1.3 Restart the runserver`.

## Steps to reproduce

Followed tutorial up to step 5.1.3.

## Expected behaviour

Should not cause 500.

## Actual behaviour

Causes 500.

## Additional information

Any page with the following causes the 500 error to be raised:

`<form action="{% url 'polls:vote' instance.poll.id %}" method="post">`

However, I can also add back to urls.py the following, which fixes the error (although I believe this is not the purpose of the documentation tutorial):

`url(r'^', include('polls.urls', namespace="polls")),`

Also, in step 9 (http://docs.django-cms.org/en/latest/introduction/09-third_party.html), aldryn_reversion is suggested to install. However, aldryn_reversion requires django < 1.11, whereas in step 1 (http://docs.django-cms.org/en/latest/introduction/01-install.html) django >= 1.11 is required! Migrate does not work if `reversion` or `aldryn_reversion` are included in settings.py.

Environment:
Python version: 3.7.6
Django version: 2.2.11
django CMS version: 3.7.1

**Comment by XxHedonistxX** [comment]
set app_name = 'polls' in your polls/urls.py . That will solve the problem

**Comment by JupiterWalker** [comment]
I got the same issue T_T

**Comment by fsbraun** [comment]
Added the need for `app_name = polls` to the docs!

**Comment by thurlstone** [comment]
Hi, this issue still persists for me, on removing the line **re_path(r'^polls/', include('polls.urls')),** I start getting **'polls' is not a registered namespace** on any page I have added a poll to.

in polls/urls.py i have the line **app_name = 'polls'** and in my installed apps I have **polls**. I have tried **app_name = 'polls'** and **app_name = "polls"**

I am running **django-cms==3.11.4** and **Django==3.2** and following the instructions at https://docs.django-cms.org/en/release-3.10.x/introduction/05-apphooks.html (specifically section 5.1.12)

FYI, leaving that line in, does not result in the error **URL namespace 'polls' isn't unique. You may not be able to reverse all URLs in this namespace.** as indicated in the docs.

Is there something I am missing here?

**Comment by imjokey** [comment]
I got the same issue T_T
