### ISSUE TITLE
Proposal: do not hide restricted pages

### ISSUE THREAD

**Issue by adrien-delhorme** [django-cms/django-cms#6857]
## Description

When an authenticated user try to visit a page that he is not allowed to: he gets a 404 not found.
It is confusing because the page exists.
The CMS should instead redirect the user to the login page, so that he can authenticate with another account.

## Steps to reproduce

- add view restriction on page A to allow only user Alice to view the page
- login with user Bob
- visit page A --> page not found

## Expected behaviour

- visit page A --> redirect to login page (allowing Bob to authenticate with a different account)

## Actual behaviour

page A is not found

## Additional information

https://github.com/divio/django-cms/blob/fb886f6e61f5ce72b4195e2032db76b80359f6ba/cms/page_rendering.py#L26-L27

I can make a pull request if this proposal is accepted.

**Comment by FinalAngel** [comment]
any feedback welcome @yakky :)

**Comment by adrien-delhorme** [comment]
I just need a validation for this proposal, then I can submit a pull request to fix this, please reopen this issue 🙏

**Comment by marksweb** [comment]
@adrien-delhorme If a user is already logged in, I personally think a redirection to a login page is confusing. I know by default django's login doesn't redirect authenticated users away from the login page, but `django-allauth` does by default redirect away from login.

My preference on this would be a 403 response with a message to say that they don't have permission to access the page.

It'd be worth discussing this either on the technical committee slack channel and/or on one of our Friday calls.
