### ISSUE TITLE
I have to click 3 times on the button top right to open menu in cms -TypeError: this.ui.container.data(...).push is not a function

### ISSUE THREAD

**Issue by chuck180** [django-cms/django-cms#6889]
## Description
`
Uncaught TypeError: this.ui.container.data(...).push is not a function
    at s.initialize (bundle.toolbar.min.js:formatted:16209)
    at new s (bundle.toolbar.min.js:formatted:4754)
    at bundle.toolbar.min.js:formatted:17044
    at Array.forEach (<anonymous>)
    at Function.xe._updateRegistry (bundle.toolbar.min.js:formatted:17036)
    at Object.<anonymous> (bundle.toolbar.min.js:formatted:15509)
    at u (bundle.toolbar.min.js:formatted:2048)
    at Object.fireWith [as resolveWith] (bundle.toolbar.min.js:formatted:2104)
    at Object.<anonymous> (bundle.toolbar.min.js:formatted:2137)
    at u (bundle.toolbar.min.js:formatted:2048)`

https://github.com/divio/django-cms/blob/aab6a4a5177407cf5cdd56d282e996f73c07646c/cms/static/cms/js/modules/cms.plugins.js#L103

## Steps to reproduce
It seems if the first placeholder is a static placeholder, js isnt working as intended

## Expected behaviour
1 click to open cms menu

## Actual behaviour
I have to click exactly 3 times on the button top right to open menu in cms, seems like the container isnt loaded at first

## Additional information
Django 2.2 / CMS 3.7

**Comment by FinalAngel** [comment]
Hello @chuck180 are you using the latest versions of Django and django CMS? It seems more like that in your static files old cached files are used. Can you check that cache is emptied and you are served the correct files?

**Comment by chuck180** [comment]
hej @FinalAngel im looking into it if i got a minute, thank you for your replay

**Comment by chuck180** [comment]
I ran collectstatic after deleteing browser cache and static directory

Both are static_placeholder, top one is in the header and the bottom one in the footer

![w](https://user-images.githubusercontent.com/35873720/90786130-7d9bf000-e303-11ea-87cc-286d127c85db.PNG)

![nw](https://user-images.githubusercontent.com/35873720/90786145-81c80d80-e303-11ea-8106-b18787929b7d.PNG)

![basepy](https://user-images.githubusercontent.com/35873720/90786562-0024af80-e304-11ea-85cc-96237b2d81da.PNG)
base.py

I am ambivalent, if that provides any useful information.

cheers Oliver

**Comment by slikker09** [comment]
Hello,
I have the same problem,
I have to click 3 or 4 times for it to show the first time, then it works fine.

Django==2.2.15
django-cms==3.7.4
Python==3.8.5


ERROR

2 times:
 `Uncaught TypeError: this.ui.container.data(...).push is not a function
    at s.initialize (bundle.toolbar.min.js:1)
    at new s (bundle.toolbar.min.js:1)
    at bundle.toolbar.min.js:1
    at Array.forEach (<anonymous>)
    at Function.xe._updateRegistry (bundle.toolbar.min.js:1)
    at Object.<anonymous> (bundle.toolbar.min.js:1)
    at u (bundle.toolbar.min.js:1)
    at Object.fireWith [as resolveWith] (bundle.toolbar.min.js:1)
    at Object.<anonymous> (bundle.toolbar.min.js:1)
    at u (bundle.toolbar.min.js:1)

initialize @ bundle.toolbar.min.js:1
s @ bundle.toolbar.min.js:1
(anonymous) @ bundle.toolbar.min.js:1
xe._updateRegistry @ bundle.toolbar.min.js:1
(anonymous) @ bundle.toolbar.min.js:1
u @ bundle.toolbar.min.js:1
fireWith @ bundle.toolbar.min.js:1
(anonymous) @ bundle.toolbar.min.js:1
u @ bundle.toolbar.min.js:1
fireWith @ bundle.toolbar.min.js:1
n @ bundle.toolbar.min.js:1
e @ bundle.toolbar.min.js:1
XMLHttpRequest.send (async)
send @ bundle.toolbar.min.js:1
ajax @ bundle.toolbar.min.js:1
value @ bundle.toolbar.min.js:1
(anonymous) @ bundle.toolbar.min.js:1
setTimeout (async)
(anonymous) @ bundle.toolbar.min.js:1
i @ bundle.toolbar.min.js:1
dispatch @ bundle.toolbar.min.js:1
g.handle @ bundle.toolbar.min.js:1
load (async)
add @ bundle.toolbar.min.js:1
(anonymous) @ bundle.toolbar.min.js:1
each @ bundle.toolbar.min.js:1
each @ bundle.toolbar.min.js:1
on @ bundle.toolbar.min.js:1
one @ bundle.toolbar.min.js:1
value @ bundle.toolbar.min.js:1
t @ bundle.toolbar.min.js:1
(anonymous) @ (index):2781
u @ bundle.toolbar.min.js:1
fireWith @ bundle.toolbar.min.js:1
ready @ bundle.toolbar.min.js:1
h @ bundle.toolbar.min.js:1`

**Comment by slikker09** [comment]
Video illustrating the error

https://vimeo.com/user108400530/review/455273888/576ec630c4

Thank!

**Comment by chuck180** [comment]
your link isnt working @slikker09

**Comment by slikker09** [comment]
> your link isnt working @slikker09

Sorry,

https://vimeo.com/455273888

**Comment by Will-Hoey** [comment]
@slikker09 @chuck180 I've also encountered this problem when recently upgrading a django-cms project. Turns out that this error can occur when there are multiple static placeholders that have the same name. So I'd double check that all your placeholders have unique names :)

**Comment by chuck180** [comment]
> @slikker09 @chuck180 I've also encountered this problem when recently upgrading a django-cms project. Turns out that this error can occur when there are multiple static placeholders that have the same name. So I'd double check that all your placeholders have unique names :)

they do as you can see on the screenshot

**Comment by Will-Hoey** [comment]
> > @slikker09 @chuck180 I've also encountered this problem when recently upgrading a django-cms project. Turns out that this error can occur when there are multiple static placeholders that have the same name. So I'd double check that all your placeholders have unique names :)
> 
> they do as you can see on the screenshot

Sorry, I missed out some information. It wasn't necessarily the fact that the placeholders had the same name. It was that they were rendered twice in the template. So I had two `{% static_placeholder 'placeholder' %}`, even though they were in separate blocks. Hope this helps.

**Comment by chuck180** [comment]
> > > @slikker09 @chuck180 I've also encountered this problem when recently upgrading a django-cms project. Turns out that this error can occur when there are multiple static placeholders that have the same name. So I'd double check that all your placeholders have unique names :)
> > 
> > 
> > they do as you can see on the screenshot
> 
> Sorry, I missed out some information. It wasn't necessarily the fact that the placeholders had the same name, it was that they were rendered twice in the template. So I had two `{% static_placeholder 'placeholder' %}`, even though they were in separate blocks. Hope this helps.

that is also not the case

**Comment by VeshRaazThapa** [comment]
Has anyone got any solutions ? i am also facing the same issue

**Comment by vivazzi** [comment]
I have the same problem - this bug appears when template has two or more static_placeholder with same names.

I used my workaround: 

I copied `/path_to_env_of_my_project/lib/python3.8/site-packages/cms/static/cms/js/dist/3.8.0/bundle.toolbar.min.js` file to `/path_to_my_project/static/cms/js/dist/3.8.0/bundle.toolbar.min.js`.

Then I fixed `bundle.toolbar.min.js`, added `if (Array.isArray(this.ui.container.data("cms")))` before `this.ui.container.data("cms").push(this.options)...`, where bug is appeared.

Note, I used django-cms == 3.8.0, so my path consists of `3.8.0` folder.
It works for me, but my solution does not guarantee that it will be good in your project, but you can try :)

More details: bug appears when this.ui.container.data("cms") is not Array, but Object, that has not `push()` method. I do not know why sometimes `this.ui.container.data("cms")` may be object, but adding `if (Array.isArray(this.ui.container.data("cms")))` we exclude this error (and it seems do not break anything)
