### ISSUE TITLE
TypeError: argument of type 'WindowsPath' is not iterable

### ISSUE THREAD

**Issue by AhmedSalam22** [django-cms/django-cms#6894]
this error face me when I am trying install  Django-cms manually 
http://docs.django-cms.org/en/latest/how_to/install.html

I use Django 3.0 and django-cms-3.7.4
![Screenshot (298)](https://user-images.githubusercontent.com/35177448/91603802-eae7fa80-e96d-11ea-8907-12d2869adfa6.png)

**Comment by AhmedSalam22** [comment]
I have solved the problem in setting.py I replaced 
`        'NAME': BASE_DIR / 'db.sqlite3',
`
with 
`        'NAME': str(BASE_DIR / 'db.sqlite3'),
`

**Comment by FinalAngel** [comment]
👍  did you find a reference like this in the documentation? Because we normally recommend ``os.path.join()``

**Comment by AhmedSalam22** [comment]
> path

No, you should put this in documentation

**Comment by FinalAngel** [comment]
That is in the documentation, to use ``os.path.join()`` that is. :)

**Comment by AhmedSalam22** [comment]
> os.path.join()

![Screenshot (300)](https://user-images.githubusercontent.com/35177448/91729306-a85c3300-eba4-11ea-9e93-18be04266b90.png)

there is no mention in the documentation about to use os.path.join() just only for media root but there is no mention to use it in the database and I have solved the problem in setting.py I replaced
'NAME': BASE_DIR / 'db.sqlite3',
with
'NAME': str(BASE_DIR / 'db.sqlite3'),


this point in documentation should be clear for a newbie like me and Thank's for replay

**Comment by rasyidev** [comment]
I got the same error message. It is because I'm not in the right environment. So I just get into the right environment and it works.

**Comment by goutnet** [comment]
merged in develop (and will be released on 3.9.0) see #6919 

thanks!
