### ISSUE TITLE
Exception while resolving variable 'xxx' in template 'xxx'

### ISSUE THREAD

**Issue by ebugge** [django-cms/django-cms#6895]
## Description

I get a lot of **Exception while resolving variable** in the logs of my application. The exceptions does not seem to disturb page loads - the end users sees the site perfectly fine with any 500 errors.

## Steps to reproduce

The log entries occur on every page load. In some cases, I get an error 500 when I edit some content on the page, fx. add a new plugin.

## Expected behaviour

I expect to see no errors in the logs.

## Actual behaviour

Here are some of the log entries. The entries in this example is from a single page load.

`2020-08-30 11:47:01,246: Exception while resolving variable 'debug' in template 'cms/toolbar/toolbar_javascript.html'.
Traceback (most recent call last):
  File "/home/myapp/.virtualenvs/myapppy35/lib/python3.5/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
  File "/home/myapp/.virtualenvs/myapppy35/lib/python3.5/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'debug'`

`2020-08-30 11:47:01,256: Exception while resolving variable 'login_form' in template 'cms/toolbar/toolbar_javascript.html'.
Traceback (most recent call last):
  File "/home/myapp/.virtualenvs/myapppy35/lib/python3.5/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
TypeError: 'CMSToolbar' object is not subscriptable`

`2020-08-30 11:47:01,258: Exception while resolving variable 'cms_toolbar_login_error' in template 'cms/toolbar/toolbar_javascript.html'.
Traceback (most recent call last):
  File "/home/myapp/.virtualenvs/myapppy35/lib/python3.5/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
  File "/home/myapp/.virtualenvs/myapppy35/lib/python3.5/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'cms_toolbar_login_error'`

`2020-08-30 11:47:01,279: Exception while resolving variable 'redirect_url' in template 'menu/dummy.html'.
Traceback (most recent call last):
  File "/home/myapp/.virtualenvs/myapppy35/lib/python3.5/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'redirect_url'`

etc.

## Additional information

Django CMS: 3.7.0
Django: 2.1.13
Python: 3.5.2

**Comment by FinalAngel** [comment]
@ebugge please mind that Django 2.1 is not officially supported anymore by the Django community. Is the issue also happening on 2.2? /cc @victor-yunenko and @Aiky30 maybe you have more insights.

**Comment by ebugge** [comment]
I will try it with django 2.2. 
I have, however, realised that the errors only occur in the production environment (Pythonanywhere) and not on my local computer. Apart from the fact that I have Python 3.5.3 on my local computer, they use the same versions of the software given above.

**Comment by Aiky30** [comment]
@ebugge Does this issue still occur with Django 2.2? You should ideally be using 2.2 for production now anyway. 

The only thing that stands out to me is that maybe a template context processor is missing or not in the correct order. Do you have different configurations / settings files for dev and production? If so do the settings match for the template context processors section?

**Comment by ebugge** [comment]
I have now upgraded to Django 2.2.15 and Django CMS 3.7.4. Unfortunately, the problem persists.
I do have a dev-specific settings.py, but it defines no template context processors - so these should be the same in dev and production. The list is:

'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'django.template.context_processors.request',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'sekizai.context_processors.sekizai',
                'cms.context_processors.cms_settings',
                'myapp.context_processors.site_processor',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],

Let me know if you need more information

**Comment by Aiky30** [comment]
@ebugge Do any of the following context processors error or override anything assigned in this file: https://github.com/divio/django-cms/blob/release/3.7.x/cms/context_processors.py

'myapp.context_processors.site_processor',
'social_django.context_processors.backends',
'social_django.context_processors.login_redirect',

I'm not sure if it matters but the sekizai processor is normally declared last.

**Comment by Aiky30** [comment]
FYI: cms_tags.py has not had many changes which is why I'm looking at context related things.

**Comment by ebugge** [comment]
@Aiky30 I am not sure what you mean by "do any of the following context processors error" but they don't seem to override anything from that file. I will paste the three context processor methods in here, so you can see for yourself.

I have tried placing the sekizai processor at the end of the list, but the problem persists.

The admin seems to be working fine.

Thanks for looking into this!

```python

# From social_django.context_processors:
def backends(request):
    """Load Social Auth current user data to context under the key 'backends'.
    Will return the output of social_core.backends.utils.user_backends_data."""
    return {'backends': LazyDict(lambda: user_backends_data(request.user,
                                                            BACKENDS,
                                                            Storage))}

# From social_django.context_processors:
def login_redirect(request):
    """Load current redirect to context."""
    value = request.method == 'POST' and \
                request.POST.get(REDIRECT_FIELD_NAME) or \
                request.GET.get(REDIRECT_FIELD_NAME)
    if value:
        value = urlquote(value)
        querystring = REDIRECT_FIELD_NAME + '=' + value
    else:
        querystring = ''

    return {
        'REDIRECT_FIELD_NAME': REDIRECT_FIELD_NAME,
        'REDIRECT_FIELD_VALUE': value,
        'REDIRECT_QUERYSTRING': querystring
    }

# From myapp.context_processors:
def site_processor(request):
    '''
    Add objects to the template context, so they are available directly form template files.
    '''
    return { 'site': Site.objects.get_current(),
             'site_configuration' : SiteConfiguration.objects.get() }
```

**Comment by ebugge** [comment]
@Aiky30 I found the reason for the exceptions not being found in my local log (dev): My local settings file suppressed the log level, setting it to INFO. In prod, the log level is currently DEBUG. If I set it to DEBUG locally as well, I get the following entries when I load my front page. I pasted the log contents from the first exception I found. As you can see, the exceptions are being logged with "DEBUG" label (not sure why). The first exception says that the 'login_form' variable is not found when rendering the 'toolbar_javascript.html'. Does that make sense to you?

```
DEBUG 2020-09-13 12:49:12,874 31787 django.db.backends.execute: (0.000) SELECT `djangocms_page_sitemap_pagesitemapproperties`.`id`, `djangocms_page_sitemap_pagesitemapproperties`.`public_extension_id`, `djangocms_page_sitemap_pagesitemapproperties`.`extended_object_id`, `djangocms_page_sitemap_pagesitemapproperties`.`changefreq`, `djangocms_page_sitemap_pagesitemapproperties`.`priority`, `djangocms_page_sitemap_pagesitemapproperties`.`include_in_sitemap`, `djangocms_page_sitemap_pagesitemapproperties`.`noindex`, `djangocms_page_sitemap_pagesitemapproperties`.`noarchive`, `djangocms_page_sitemap_pagesitemapproperties`.`robots_extra` FROM `djangocms_page_sitemap_pagesitemapproperties` WHERE `djangocms_page_sitemap_pagesitemapproperties`.`extended_object_id` = 28; args=(28,)
DEBUG 2020-09-13 12:49:12,893 31787 django.template._resolve_lookup: Exception while resolving variable 'login_form' in template 'cms/toolbar/toolbar_javascript.html'.
Traceback (most recent call last):
  File "/home/esben/virtualenvs/myapp_python3.5/lib/python3.5/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
TypeError: 'CMSToolbar' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/esben/virtualenvs/myapp_python3.5/lib/python3.5/site-packages/django/template/base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'CMSToolbar' object has no attribute 'login_form'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/esben/virtualenvs/myapp_python3.5/lib/python3.5/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'login_form'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/esben/virtualenvs/myapp_python3.5/lib/python3.5/site-packages/django/template/base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [login_form] in <cms.toolbar.toolbar.CMSToolbar object at 0x7f94db903fd0>
DEBUG 2020-09-13 12:49:12,893 31787 django.template._resolve_lookup: Exception while resolving variable 'cms_toolbar_login_error' in template 'cms/toolbar/toolbar_javascript.html'.
Traceback (most recent call last):
  File "/home/esben/virtualenvs/myapp_python3.5/lib/python3.5/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
  File "/home/esben/virtualenvs/myapp_python3.5/lib/python3.5/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'cms_toolbar_login_error'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/esben/virtualenvs/myapp_python3.5/lib/python3.5/site-packages/django/template/base.py", line 835, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'Context' has no attribute 'cms_toolbar_login_error'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/esben/virtualenvs/myapp_python3.5/lib/python3.5/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'cms_toolbar_login_error'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/esben/virtualenvs/myapp_python3.5/lib/python3.5/site-packages/django/template/base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [cms_toolbar_login_error] in ...
```

**Comment by Aiky30** [comment]
@ebugge For some reason your project doesn't seem to be getting the toolbar context defined here: https://github.com/divio/django-cms/blob/release/3.7.x/cms/toolbar/toolbar.py#L453

Do you have any custom toolbar logic? I can see that you have djangocms-page-sitemap installed but I don't think it is that at fault.

**Comment by ebugge** [comment]
I have this custom logic defined in [cms_toolbars.py](https://github.com/divio/django-cms/files/5220477/cms_toolbars.py.txt). But it makes no difference if I remove it - the problem persists.

This is the middleware section of my settings.py. I have some toolbar middleware in there, but I am not sure if that affects anything:

```python
MIDDLEWARE = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware', # needed for localization
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware', # Debug toolbar
    'django.middleware.security.SecurityMiddleware', # SSL redirect
    
    # django-cms
    'django.contrib.messages.middleware.MessageMiddleware',
    'cms.middleware.user.CurrentUserMiddleware',
    'cms.middleware.page.CurrentPageMiddleware',
    'cms.middleware.toolbar.ToolbarMiddleware',
    'cms.middleware.language.LanguageCookieMiddleware',
    
    # custom redirects with reg ex from https://github.com/maykinmedia/django-regex-redirects
    'regex_redirects.middleware.RedirectFallbackMiddleware',
    
    # Set updated-by user
    'myapp.middleware.SetUpdatedMiddleware',
    
    # Handling errors during social authentication
    'myapp.middleware.SocialAuthExceptionMiddlewareCmsRedirect',
)
```

**Comment by Aiky30** [comment]
@ebugge 

Cross check that you have the templates context processor settings: http://docs.django-cms.org/en/latest/how_to/install.html#context-processors

Cross check that all of your settings are in order defined here: http://docs.django-cms.org/en/latest/how_to/install.html#sekizai

Does your base template have the correct tags added for the CMS? {% load cms_tags sekizai_tags %}

**Comment by ebugge** [comment]
@Aiky30 - finally got to look into this again. 

- The context processor settings are there. 
- The settings are all there and in the right order. 
- The `cms_tags` and `sekizai_tags` are loaded in the base template, yes.

I found that if I remove the `cms_toolbar` and `show_menu` tags from my base template, there are a lot less of these errors, but they are not entirely gone. I can make them all disappear, if I create an empty page without any plugins (and without the mentioned tags).

I have tried looking at the specific "Exception while resolving variable" errors:

**Exception while resolving variable 'login_form' in template 'cms/toolbar/toolbar_javascript.html'**
**Exception while resolving variable 'cms_toolbar_login_error' in template 'cms/toolbar/toolbar_javascript.html'**
**Exception while resolving variable 'url' in template 'cms/toolbar/items/menu.html'**
All occur when using the `cms_toolbar` tag on my page.

**Exception while resolving variable 'redirect_url' in template 'menu/dummy.html'**
Occurs when I have the `show_menu` tag on my page.

**Exception while resolving variable 'name' in template 'unknown'**
Seems to occur when I have plugins on the page.

Any ideas?

**Comment by Aiky30** [comment]
@ebugge Is the occurrence when adding plugins from every plugin or just some plugins? Example it doesn't occur with the text plugin but it does with another plugin?

It's a very strange issue to have where the templates aren't receiving the correct context. There has to be something modifying the context.

It might be worth starting a fresh project with the minimal setup to see if the issue still occurs, then add each addon, setting piece by piece until the issue occurs again. That's the only way I can think of properly debugging this now.

**Comment by jmrobles** [comment]
The same thing is happening to me. 
I'm going to see if I can debug it.

**Comment by sachin-metacube** [comment]
Same issue here

django.template.base.VariableDoesNotExist: Failed lookup for key [exception_type]

**Comment by rfrancois** [comment]
I've got the same problem on Django 4.2.3
