### ISSUE TITLE
Plugin restrictions not checked when pasting in whole placeholder contents

### ISSUE THREAD

**Issue by petrklus** [django-cms/django-cms#6904]
##   Description

Copy&paste correctly checks for plugin class on individual basis, however, whole-placeholder operations do not check if plugins can indeed be pasted into the destination placeholder. This then allows pasting in of any plugin type, bypassing the restrictions.

## Steps to reproduce

1. Create placeholder with plugin A only (only plugin type allowed)
2. Create placeholder with plugin B only (only plugin type allowed)
3. Create a plugin in the placeholder A and use the "Copy all" function to copy and paste into B. 
4. Plugin gets copied.

Video of the behaviour is here: https://www.youtube.com/watch?v=vTkcYoLRQe8

## Expected behaviour

The action should fail, ideally with an error message explaining that not all plugins in the clipboard can be pasted in.

## Actual behaviour

Plugin gets pasted in despite not being allowed in the placeholder.

## Additional information

The example above has the following configuration:

```
CMS_PLACEHOLDER_CONF = {
    "content" : {
        'name': "Only text plugin allowed",
        "plugins": [
            "TextPlugin"
        ],
    },
    "snippet" : {
        'name': "Only snippet plugin allowed",
        "plugins": [
            "SnippetPlugin"
        ],
    },
}
```

Tested on Django 2.2.16.1 and Django CMS 3.7.4.1 (clean install). Reproduced on multiple different projects.

**Comment by FinalAngel** [comment]
@Aiky30 @victor-yunenko is this something you could have a look into?

**Comment by Aiky30** [comment]
This has been seen recently on one of our projects too. I will attach myself. A possible solution to follow soon .....
