### ISSUE TITLE
Fresh installed django-cms TypeError at /admin/cms/page/1/advanced-settings/

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [django-cms/django-cms#6908]
## Description

Empty fresh installed django-cms fail to show advanced page settings.

## Steps to reproduce
Step 1) 
python -m venv venv
source venv/bin/activate
pip install djangocms-installer

djangocms -f websiteroot
cd websiteroot
rm -f project.db
./manage.py makemigrations
./manage.py migrate
./manage.py createsuperuser --username admin --skip-checks

change USE_I18N = False in settings.py
./manage.py runserver 0:8000

Step 2) 
login to admin using admin username and password 
create 1st page , Fill Title , Slug and Content.
Press save
Clieck Menu 
Page-> Advanced settings . Got error

## Expected behaviour

have to work

## Actual behaviour

```
TypeError at /admin/cms/page/3/advanced-settings/

__str__ returned non-string (type __proxy__)

Request Method: 	GET
Request URL: 	http://127.0.0.1:8000/admin/cms/page/3/advanced-settings/?language=en&cms_path=/?edit
Django Version: 	3.0.10
Exception Type: 	TypeError
Exception Value: 	

__str__ returned non-string (type __proxy__)

Error during template rendering

In template /home/ktoto/PycharmProjects/svetawebnew/venv/lib/python3.8/site-packages/django/forms/templates/django/forms/widgets/select_option.html, error at line 1
__str__ returned non-string (type __proxy__)
1 	<option value="{{ widget.value|stringformat:'s' }}"{% include "django/forms/widgets/attrs.html" %}>{{ widget.label }}</option>
2 	
```

## Additional information

After some quick investigation i found that issue because of bug in handling **USE_I18N = False** in settings.py. Such setting used to avoid search system rank penalty due to useless redirect on sites which does not have multiply languages.

**Comment by FinalAngel** [comment]
@Aiky30 @victor-yunenko would be great if someone could also test the behaviour and provide feedback.

**Comment by Aiky30** [comment]
@FinalAngel @victor-yunenko  We'll need to spin up a project to investigate this further.

**Comment by jpVm5jYYRE1VIKL** [comment]
3.8.0 also affected by this issue.

**Comment by jpVm5jYYRE1VIKL** [comment]
Well after some investigation i found workaround of such issue. May be it will help somebody. If you want to use CMS using single laguage and avoid redirects. Not need to touch  option USE_I18N. 

```
urlpatterns += i18n_patterns(
    url(r'^admin/', admin.site.urls),  # NOQA
    url(r'^', include('cms.urls')),
    prefix_default_language=False
)
```

Using prefix_default_language options is not solve issue but at least masquerade it.

**Comment by FinalAngel** [comment]
Probably something that should be checked and documented

**Comment by pupattan** [comment]
I am also facing the same issue. Is prefix_default_language=False the only option here ?

**Comment by idrum4316** [comment]
I think I am also running into this same issue. I can mostly work around it by setting `USE_I18N = True` and `prefix_default_language=False`.

My site has a couple of cms pages that have redirects configured in the advanced settings, and those are still getting the language code prepended to the URL I set in the redirect field. For example, I have a page that is configured to redirect to "/portal", but it is now redirecting to "/en/portal" and showing the user a 404 error.

**Comment by mbi** [comment]
This looks like a dupe of #6687 (which was fixed a couple months ago)
