### ISSUE TITLE
Edit on Github in footer broken

### ISSUE THREAD

**Issue by pau1a** [django-cms/django-cms#6909]
## Description

There are many flaws with the documentation which need to be updated but in order to do that they must be editable on github. This link at the footer of pages such as this: [http://docs.django-cms.org/en/latest/reference/plugins.html](http://docs.django-cms.org/en/latest/reference/plugins.html) is broken

## Steps to reproduce

Load page, click link

## Expected behaviour

Link should not be a 404

## Actual behaviour

Link is a 404

## Additional information

None

**Comment by evildmp** [comment]
All the documentation is in the [django CMS GitHub repository](https://github.com/divio/django-cms/tree/develop/docs). Contributions with fixes and improvements are welcome, as described in [Contributing documentation](https://docs.django-cms.org/en/latest/contributing/documentation.html)

**Comment by marksweb** [comment]
The part of the theme which builds this link is here; https://github.com/divio/docs-theme/blob/master/src/furo/theme/furo/page.html#L113

```
              {% if check_meta and 'github_url' in meta %}
                <a href="{{ meta['github_url'] }}"> {{ _('Edit on GitHub') }}</a>
              {% else %}
                <a href="https://{{ github_host|default("github.com") }}/{{ github_user }}/{{ github_repo }}/{{ theme_vcs_pageview_mode|default("blob") }}/{{ github_version }}{{ conf_py_path }}{{ pagename }}{{ suffix }}"> {{ _('Edit on GitHub') }}</a>
              {% endif %}
```

**Comment by marksweb** [comment]
Closing this as the new docs theme doesn't have this option.
