### ISSUE TITLE
cms check command confused by Sekizai with_data block

### ISSUE THREAD

**Issue by greyhare** [django-cms/django-cms#6911]
## Description

If the `<head>` section of a CMS page template (usually a base template it's extended from) has a `{% with_data %}` block in it, `./manage.py cms check` will erroneously generate an error.

## Steps to reproduce

Put one of the following in the `<head>` section of a template that originally passes `./manage.py cms check`, and run `./manage.py cms check`:

    {% with_data "google-fonts" as fonts %}{% if fonts %}
    <link href="https://fonts.googleapis.com/css?family={{ fonts|join:',' }}" rel="stylesheet">
    {% endif %}{% end_with_data %}

or

    {% with_data "google-fonts" as fonts %}{% end_with_data %}

I used a Django project generated by Django-CMS Installer for testing.

## Expected behaviour

```
********************************
Checking django CMS installation
********************************

Sekizai
=======

  - Sekizai is installed [OK]
  - Sekizai template context processor is installed [OK]
  - Sekizai namespaces 'js' and 'css' found in 'fullwidth.html' [OK]
  - Sekizai namespaces 'js' and 'css' found in 'sidebar_left.html' [OK]
  - Sekizai namespaces 'js' and 'css' found in 'sidebar_right.html' [OK]

Sekizai configuration okay [OK]
```

## Actual behaviour

```
********************************
Checking django CMS installation
********************************

Sekizai
=======

  - Sekizai is installed [OK]
  - Sekizai template context processor is installed [OK]
  - Sekizai namespaces 'js' and 'css' not found in 'fullwidth.html' [ERROR]
  - Sekizai namespaces 'js' and 'css' not found in 'sidebar_left.html' [ERROR]
  - Sekizai namespaces 'js' and 'css' not found in 'sidebar_right.html' [ERROR]

Sekizai configuration has errors [ERROR]

```

## Additional information

Python version 3.6, Django 2.2, Django CMS 3.7.4

**Comment by greyhare** [comment]
So is there some specific reason you need me to fix this, or is this standard practice? Because I don't have the first clue how `cms check` works internally.

**Comment by macolo** [comment]
Hi @greyhare it is standard practice. We are actively looking for contributors, anyone can contribute. :)

**Comment by greyhare** [comment]
So what does Divio do, then?

**Comment by NicolaiRidani** [comment]
Hi @greyhare the django CMS project is now backed by the django CMS Association, an organization that was formed by the django CMS community. In other words: the django CMS project is now maintained and managed by the django CMS community. That's the reason why we are inviting everyone to contribute to the project. You can learn more about our contributor program [here](https://www.django-cms.org/en/become-community-hero/). And you can even [win rewards](https://www.django-cms.org/en/bounty-program/) for Github contributions. You are also welcome to join us on [Slack](www.django-cms.org/slack) to keep updated and get in touch with the community.

**Comment by greyhare** [comment]
Just ran into this again, looked it up on GitHub, and wow, deja vu.

Kind of amazing nobody else had this problem.

So does anyone know where to find the code that handles this stuff? Documentation on `cms check`? Anything?

**Comment by greyhare** [comment]
All that "how to be a contributor" stuff is personnel management. What I need is recommended debugging processes. What tools you use to instrument code. Recommended practices. That kind of thing.

**Comment by crydotsnake** [comment]
Hello @greyhare,

Have a look at our documentation about the CLI: https://docs.django-cms.org/en/latest/reference/cli.html

**Comment by greyhare** [comment]
That documentation's entire coverage of the `cms check` command:

> cms check
>
> Checks your configuration and environment.

Django itself, meanwhile, has a [good example of the](https://docs.djangoproject.com/en/4.0/topics/checks/) [kind of thing I'm looking for](https://docs.djangoproject.com/en/4.0/ref/checks/).

Anyway, I managed to determine [it's a sekizai bug](https://github.com/django-cms/django-sekizai/issues/118), so you can breathe easy.

**Comment by greyhare** [comment]
P.S. If anyone else find this on Google and needs a way to skip the check until it works, put this in your `settings.py`:

```python
SEKIZAI_IGNORE_VALIDATION = True
```

**Comment by greyhare** [comment]
Did I miss a fix for this?

**Comment by marksweb** [comment]
@greyhare not that I'm aware of.

**Comment by greyhare** [comment]
Stale or not, it's still not fixed in sekizai.

**Comment by fsbraun** [comment]
I know this does not solve your issue but there's a workaround so you can at least use check for other checks:

```
SEKIZAI_IGNORE_VALIDATION = True
```

in `settings.py` disables the sekizai template check.

**Comment by greyhare** [comment]
Yea, [I'm aware.](https://github.com/django-cms/django-cms/issues/6911#issuecomment-1023835546)

**Comment by fsbraun** [comment]
Sorry, also only now saw: https://github.com/django-cms/django-sekizai/issues/118#issuecomment-1262650522 😒

**Comment by fsbraun** [comment]
OK, I have a suggestion: https://github.com/django-cms/django-sekizai/pull/142
