### ISSUE TITLE
Use `refresh_from_db()` instead of self implemented `reload()` methods

### ISSUE THREAD

**Issue by jrief** [django-cms/django-cms#6914]
(This is neither a bug nor a feature request, therefore I didn't know how to classify it.)

Django, since at least version 1.8, offers a method to reload / [refresh an object from the database](https://docs.djangoproject.com/en/1.8/ref/models/instances/#refreshing-objects-from-database).
For better readability and code cleanness, Django-CMS should use that method instead of re-implementing this functionality itself.

Occurrences found here:

https://github.com/divio/django-cms/blob/develop/cms/models/pagemodel.py#L116
https://github.com/divio/django-cms/blob/develop/cms/models/pagemodel.py#L1559
https://github.com/divio/django-cms/blob/develop/cms/models/pluginmodel.py#L269

I assume that in earlier versions of django-CMS `Model.refresh_from_db(using=None, fields=None, **kwargs)`
didn't exist yet, therefore these methods were implemented at the time.

Shall I create a pull request?

**Comment by FinalAngel** [comment]
@victor-yunenko or @Aiky30 feedback welcome :)

**Comment by Aiky30** [comment]
@jrief Sounds sane to me, I would say that if tests don't exist for the refresh feature we should implement them. The original _reload and reload methods can be kept as it looks like whoever built them new that the Django change was coming, it also provides an api for third parties to hook into forcing a reload.

**Comment by macolo** [comment]
@jrief sounds reasonable to me. I labelled this as "needs contribution".

**Comment by marksweb** [comment]
I feel like this got done but I may be wrong

**Comment by creyD** [comment]
I tried to do this, but it doesn't work, as the reload method returns a new object from the database and the refresh_from_db returns the same object, which means a lot of the tests are failing.
