### ISSUE TITLE
"Cannot delete or update a parent row" when making changes to page with specific plugin

### ISSUE THREAD

**Issue by ebugge** [django-cms/django-cms#6916]
## Description

A plugin on my page is causing problems: When I try to publish any change on the page I get an error saying (my app is called "oekf"):

```
ERROR 2020-09-28 20:55:42,085 6 django.request.log_response: Internal Server Error: /da/admin/cms/page/7/delete/
Traceback (most recent call last):
  File "/home/oekf/.virtualenvs/oekfpy35/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/oekf/.virtualenvs/oekfpy35/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/oekf/.virtualenvs/oekfpy35/lib/python3.5/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/oekf/.virtualenvs/oekfpy35/lib/python3.5/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/oekf/.virtualenvs/oekfpy35/lib/python3.5/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.IntegrityError: (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`oekf$default`.`oekf_contactinfo`, CONSTRAINT `oekf_contactinfo_cmsplugin_ptr_id_e68f18e6_fk_cms_cmsplugin_id` FOREIGN KEY (`cmsplugin_ptr_id`) REFERENCES `cms_cmsplugin` (`id`))')
```

My plugin, `oekf_contactinfo` is a simple, custom plugin that displays some contact information from data retrieved from my Django models.

## Steps to reproduce

The error occurs every time I try to publish something on the page, even changes in other plugins. I have tried to delete the plugin from my page but get the same error. I have even tried to delete the page, but still I get the same error.

## Expected behaviour

See above.

## Actual behaviour

See above

## Additional information

I am using

Django 2.2.15
Django CMS 3.7.4
Python 3.5

**Comment by Aiky30** [comment]
@ebugge Can you please post your plugin in cms_plugns.py and the model in models.py?

**Comment by ebugge** [comment]
@Aiky30 Is it the CMSPlugin model you want to see? Because I have that in cms_plugins.py along with the plugin declaration:

```python
from cms.models.pluginmodel import CMSPlugin
from cms.plugin_base import CMSPluginBase
from cms.plugin_pool import plugin_pool
from django.db import models
from django.utils.translation import ugettext_lazy as _

from oekf.models import *

import logging
logger = logging.getLogger(__name__)

class ContactInfo(CMSPlugin):
    redirect_title = models.CharField(max_length=50)
    male_header = models.CharField(max_length=50, null=True)
    female_header = models.CharField(max_length=50, null=True)

class ContactInfoPlugin(CMSPluginBase):
    model = ContactInfo
    render_template = "components/contact_info.html"
    name = _("Contact_info")
    cache = False
    
    def render(self, context, instance, placeholder):        
        context['instance'] = instance
        coaches = Coach.objects.select_related('team', 'coach').all()
        male_teams = {}
        female_teams = {}
        for coach in coaches:
            if coach.team.gender is Gender.Male:
                if not coach.team.id in male_teams:
                    male_teams[coach.team.id] = { 'team': coach.team, 'coaches': [] }
                male_teams[coach.team.id]['coaches'].append(coach)
            elif coach.team.gender is Gender.Female:
                if not coach.team.id in female_teams:
                    female_teams[coach.team.id] = { 'team': coach.team, 'coaches': [] }
                female_teams[coach.team.id]['coaches'].append(coach)

        context['male_teams'] = sorted(list(male_teams.values()), key=lambda x: x['team'].contact_info_order)
        context['female_teams'] = sorted(list(female_teams.values()), key=lambda x: x['team'].contact_info_order)
        context['team_types'] = Team.Type.values
        context['coach_types'] = Coach.Type.values

        return context

plugin_pool.register_plugin(ContactInfoPlugin)
```

**Comment by Aiky30** [comment]
@ebugge This is a very strange issue to be getting on a simple plugin. 

Has the plugins migrations been created and ran fully? 
Also has this plugin been working in the past and then the issue just started?

**Comment by ebugge** [comment]
@Aiky30 

This is a new plugin I've just created and put on a page. I saw the error the first time I tried to edit the page where the plugin is used, so it seems like it has been there from the beginning. I have checked the migrations table and the table/column changes that were made when the migration-scripts were applied and everything seems to be in order.

You write that this is a strange issue for this type of plugin. What does the error message tell you (aside from the obvious that the fk constraint fails)?

**Comment by Aiky30** [comment]
@ebugge My apologies for the delayed reply, I missed your reply somehow. I find this strange because the model structure looks ok. I can only think that the plugin model is duplicated / reused somewhere else hence why it is not allowed to be deleted.

Does the issue occur on a new page when you add the plugin from fresh? I ask this to see if the page with the issue contains an instance where you had past changes.

**Comment by ebugge** [comment]
Don't apologize :)

I just tested it on a new page and it works. I then went back to does some changes to the page where the problem originally came up and now it works on this page too! I have now idea what fixed it because I haven't worked on the site for some time now.

In any case, it works now and I can't get reproduce the error on any pages, so I am closing this issue. Thanks for your inputs anyway @Aiky30

**Comment by ebugge** [comment]
Reopening this as it has occurred again, when I created a new plugin.

The error is the same:

`django.db.utils.IntegrityError: (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`oekf$default`.`oekf_youtubevideo`, CONSTRAINT `oekf_youtubevideo_cmsplugin_ptr_id_c9b10230_fk_cms_cmsplugin_id` FOREIGN KEY (`cmsplugin_ptr_id`) REFERENCES `cms_cmsplugin` (`id`))')`
