### ISSUE TITLE
Overwrite url field is not checked

### ISSUE THREAD

**Issue by jbpenrath** [django-cms/django-cms#6934]
## Description
Overwrite url field value is not checked.
If I want to rewrite the url of a page and I fill the related field with a wrong value, I can save changes then site will encount error `NoReverseMath at <...>`. Furthermore if the concerned page is included in the main nav that appears on each page, this is the whole site that raises error.

## Steps to reproduce
1. Go to advanced settings of a page
2. Fill field "overwrite url" with an invalid value (e.g: https://mysite.com/en/help)
3. Save your changes
4. Try to go to the page

## Expected behaviour
In advanced settings, when I click to save my changes, a message should warn me if I fill overwrite url field with an invalid value.

## Actual behaviour
In advanced settings, if I fill overwrite url field with an invalid value, I can save changes then my site raises NoReverseMatch exception.

## Additional information

This is an error easy to fix for a technical person but really disappointing and little hard to understand for non technical people.

I created a divio to reproduce the error:
https://django-cms-slug-crash-stage.us.aldryn.io/en/

**Comment by greengoaxe** [comment]
Hi Ravinda Gupta,
thank you for your issue and your contribution. dCA appreciated it.
May you provide your fix creating a pull request, if you have any?
Thank you in advance for your cooperation.
Kind regards,
greengoaxe

**Comment by marksweb** [comment]
Closing this as the linked PR has been merged.
