### ISSUE TITLE
django.db.migrations.exceptions.InvalidBasesError: Cannot resolve bases for [<ModelState: 'cms.PageUser'>]

### ISSUE THREAD

**Issue by pupattan** [django-cms/django-cms#6936]
I am using custom user for my app.
But while migrating i am facing the below issue

django.db.migrations.exceptions.InvalidBasesError: Cannot resolve bases for [<ModelState: 'cms.PageUser'>]

**Comment by mike667** [comment]
Same error, please help.

[StackOverflow Topic](https://stackoverflow.com/questions/38701151/custom-user-model-with-django-cms-cannot-resolve-bases-for-cms-pageuser) didn't help.

**Comment by mike667** [comment]
I had same issue, but this [article](https://vivazzi.pro/en/it/cannot-resolve-bases-for-pageuser/) help me.

**Comment by Aiky30** [comment]
This looks like a migration dependancy order issue. You can control the order by ensuring that your custom migration file runs before the cms migration that adds PageUser. The following documentation describes this in detail: https://docs.djangoproject.com/en/3.1/howto/writing-migrations/#controlling-the-order-of-migrations 

The article in the post above is a hack around this issue. If any other user installs your custom package (like any other package for Django) then it will fail with the same problem. Solve it correctly by mapping the correct migrations.
