### ISSUE TITLE
DjangoCMS Toolbar doesn't show up without adding ?edit in the URL

### ISSUE THREAD

**Issue by gauravdutt13** [django-cms/django-cms#6938]
## Description

I have done djangocms setup using djangocms-installer . once my site is up I try to access it using http://domainname:8000/ and I can see the toolbar. But when I share the same URL with someone else , they can not see the toolbar and cannot edit as well anything . 

I have added CMS_INTERNAL_IPS = []  and ALLOWED_HOSTS = ["*"] in settings.py . I am handling static and media files like below 
STATIC_URL = '/static/'
MEDIA_URL = '/media/'

MEDIA_ROOT = "/apps/static_media_files/media"
STATIC_ROOT = "/apps/static_media_files/static"

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'apps', 'static'),
)

I am using AWS RDS postgress as my database.
after adding CMS_INTERNAL_IPS , if I add ?edit in the url , It works as expected . http://domainname:8000/en/?edit. I can see toolbar.

**I want to know is there any possible ways that I can remove dependency of adding ?edit in the URL and it shows toolbar.**

## Steps to reproduce

Install djangocms-installer.
Run djangocms apps
create directory apps/static_media_files
Run python manage.py collectstatic
Run python manage.py createsuperuser
Run gunicorn --bind 0.0.0.0:8000 apps.wsgi

wsgi.py file 
```
"""
WSGI config for apps project.
It exposes the WSGI callable as a module-level variable named ``application``.
For more information on this file, see
https://docs.djangoproject.com/en/3.0/howto/deployment/wsgi/
"""

import os

from django.core.wsgi import get_wsgi_application

# from django.apps.wsgi import get_wsgi_application
from dj_static import Cling

# application = Cling(get_wsgi_application())

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'apps.settings')

application = get_wsgi_application()
application = Cling(get_wsgi_application())
```

Access URL http://IP:8000 and create some pages . Once done ask other user to access same URL  . User will not be able to see the toolbar.  But once they add ?edit , http:IP:8000/en/?edit , they will be able to view toolbar. 
## Expected behaviour

I expect URL to work in the same way for everyone . It should show toolbar to users. 

## Actual behaviour

Other users are not able to view the toolbar if they don't hit url by adding ?edit in the end of the URL.

## Additional information

dj-database-url==0.5.0
dj-static==0.0.6
Django==3.0.11
django-classy-tags==2.0.0
django-cms==3.7.4
django-filer==2.0.2
gunicorn==20.0.4
psycopg2==2.8.6

**Comment by Aiky30** [comment]
@gauravdutt13 This is by design, we wouldn't want a site visitor to know that the toolbar exists, this can only happen if the admin user is already logged in. The toolbar should show if the user is already logged in and they open the link.

**Comment by gauravdutt13** [comment]
I have somehow forced the url to redirect to /?edit which solved my issue. I made changes in base.html which enables a login button for the users. they can login and can access the toolbar.

But Now I have integrated this setup with ADFS. when I try to login with some users to the CMS site, again the toolbar is getting disappeared . Can you tell me what settings to be enabled for admin users in ADFS related settings so that when they login to CMS page , they get to see the toolbar .
