### ISSUE TITLE
Dynamic SITE_IDs and the Advanced Settings "Template" choices

### ISSUE THREAD

**Issue by wesbroadway** [django-cms/django-cms#6940]
Hi there, I think I may have run into a quirk related to using a single running instance of the CMS to serve multiple sites. In my case, I achieve this by dynamically altering the `settings.SITE_ID` value with some middleware, like so:

    class SiteIDMiddleware(MiddlewareMixin):
        def process_request(self, request):
            hostname = request.headers.get('Host').split(':')[0]

            try:
                settings.SITE_ID = settings.ALLOWED_HOSTS.index(hostname) + 1
            except ValueError:  # raised when value is not found in list
                pass

            return self.get_response(request)

This causes one small problem though, and that is related to the template choices presented for the `PageAdmin.template` field. Those values are established at runtime (see `cms.models.pagemodel.Page`, line ~166 is where `template_choices` are initialized), and that's it - they are not sensitive to a *dynamic* `SITE_ID` value. In my case, it just shows me the templates that are associated with my site that has an ID of 1 (which makes sense, that's my "primary" site.) 

I should note that the correct template names show up in the CMS menu toolbar, so I *am* able to select the correct templates from *there* - but not from the Advanced Settings page.

Fixing this is as simple as updating `cms.forms.AdvancedSettingsForm.__init__`, and adding this somewhere in the function:

    self.fields['template'].widget.choices = get_cms_setting('TEMPLATES')

I'd be glad to contribute this if it would be welcome, but I have some questions about testing it - mainly I'm just not sure where those tests should go, so a little guidance on where to start would be super-helpful. Thanks very much!

**Comment by Aiky30** [comment]
Hi @wesbroadway,

The ability to use multiple sites is not a problem that the CMS core aims to achieve. There are packages designed for this purpose, the most popular and by far the most stable is: https://github.com/nephila/djangocms-multisite

With regards to contribution, the tests in the cms can be found here: https://github.com/django-cms/django-cms/tree/develop/cms/tests

For additional support, and further knowledge on changes to django CMS the following information on the django CMS Association (dCA) may be helpful:


If you want to learn more about the work of the technical committee, our product vision and how you can become a member of the dCA, you can find all information here:

- [The Technical Committee of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/tech-committee/about.md)
- [Technical Roadmap and Product Vision for django CMS](https://github.com/django-cms/django-cms-mgmt/blob/master/django-cms/roadmap.md)
- [How to become a member of the django CMS Association](https://github.com/django-cms/django-cms-mgmt/blob/master/association/about.md)

We are looking forward to every companion who would like to shape the future of django CMS together with us! 

If you have any questions, feel free to reach out to Nicolai, our Community Manager: nicolai@django-cms.org 


Sign up for the Association now!

**Comment by wesbroadway** [comment]
@Aiky30 thank you! I was not actually aware of the multisite project, so I appreciate the suggestion. Thanks again and I'll close this issue. Best regards!
