### ISSUE TITLE
Bootstrap css and and js not getting included in the template

### ISSUE THREAD

**Issue by rg2609** [django-cms/django-cms#6941]
## Description
I am new to this` django-csm `, my use case is to create a form template for that m using the `Django-cms` and along with this using the 'aldryn-form` for form building. I created a simple form using `djangocms-bootstrap` and `aldryn-forms`, but the styling not getting included in the UI. 

![image](https://user-images.githubusercontent.com/20682661/98672537-f8f9c480-237b-11eb-9b42-3fa408982849.png)
This now including any css class and jquery script
![image](https://user-images.githubusercontent.com/20682661/98672779-5726a780-237c-11eb-9379-ccab164cb63e.png)
Is that handled in `djangocms-bootstrap` plugins or we have to add in the base.html of the `Django-cms`.

## Additional information
**Versions:**
Django-cms: 3.8
Django: 3.1
Python:3.6
aldryn-forms: [6.2.0.rc4](https://github.com/divio/aldryn-forms/releases/tag/6.2.0.rc4)

**Comment by Aiky30** [comment]
@rg2609 Which package of djangocms-bootstrap are you using (djangocms-bootstrap, djangocms-bootstrap3, djangocms-bootstrap4)? 

It looks to me that the js and css files are not being included in the template. The way that this is done varies from projects i.e. djangocms-bootstrap vs djangocms-bootstrap3 vs djangocms-bootstrap4.

**Comment by falconyue** [comment]
I got same problem

**Comment by crydotsnake** [comment]
Hello @falconyue and @rg2609 !.

Try to include bootstrap itself in your project.

**Comment by crydotsnake** [comment]
> I got same problem with djangocms_bootstrap4

The djangocms_bootstrap4 package does not include the styling for bootstrap. 

djangocms_bootstrap4 README:

`django CMS Bootstrap 4 does not add the styles or javascript files to your frontend, these need to be added at your discretion.`
https://github.com/django-cms/djangocms-bootstrap4/

You will need to include the bootstrap core in your project (and also in your template of course)

**Comment by falconyue** [comment]
I included resource of bootstrap 4 in my template files, and it works. thanks @crydotsnake

**Comment by crydotsnake** [comment]
> I included resource of bootstrap 4 in my template files, and it works. thanks @crydotsnake

Glad i could help :) !

**Comment by goutnet** [comment]
closing this issue, as solutino was provided by @crydotsnake
