### ISSUE TITLE
Site header randomly changing to another site's header when navigating through pages

### ISSUE THREAD

**Issue by davidgomezcol** [django-cms/django-cms#6947]
## Description
The bug is annoying, when navigating through pages the header changes to the one of another site configured on Django CMS. I haven't found a solution for this. (the other site it's configured with different domain)

## Steps to reproduce
Navigate through the site

## Expected behaviour
Keep the same header, except when navigating on the other site configured on Django CMS.

## Actual behaviour
The bug is annoying, when navigating through pages the header changes to the one of another site configured on Django CMS. I haven't found a solution for this. (the other site it's configured with different domain)

## Additional information
Django 1.11.8
Django CMS 3.4.7

**Comment by NarenderRajuB** [comment]
I would keep the plugins inside the header in static placeholder , here static placeholders will be bound to a site.

**Comment by greengoaxe** [comment]
Hi David Gomez,
thank you for your issue and your contribution. dCA appreciated it. 
I read that you're using Django 1.11.8 and Django CMS 3.4.7. May you check if the issue persist again on the latest version of Django and django-cms?
Thank you in advance for your cooperation.
Kind regards,
greengoaxe

**Comment by marksweb** [comment]
@davidgomezcol Can you include some template code or more details as to how the header is built & used on the site?

For example, are you using a static placeholder, and are you passing the site object to that?

```
{% static_placeholder 'header' site %}
```
