### ISSUE TITLE
Color input width broken by djangocms-admin.css

### ISSUE THREAD

**Issue by fallenflint** [django-cms/django-cms#6957]
## Description

Input type=color seems to be broken by djangocms-admin.css
![image](https://user-images.githubusercontent.com/6457827/101520997-44f95280-3996-11eb-9091-05de605cd067.png)
I've got color picker without color inside. A little investigation shown that issue connected to css rule `width: auto` for 
`button, input, select, textarea`. Disabling it fixes color input.

## Steps to reproduce

Simply use anything that renders to input type="color" on admin page.

## Expected behaviour

![image](https://user-images.githubusercontent.com/6457827/101521659-32334d80-3997-11eb-881e-ff98688fdd29.png)

Normal color input look.

## Actual behaviour

Broken color input without selected color visible

**Comment by yakky** [comment]
@fallenflint thanks for reporting this. Could you open this issue on https://github.com/django-cms/djangocms-admin-style?

**Comment by fallenflint** [comment]
> @fallenflint thanks for reporting this. Could you open this issue on https://github.com/django-cms/djangocms-admin-style?

Ok, thanks for advice, will open it there

**Comment by yakky** [comment]
@fallenflint thanks
closing this, linked to the new one at https://github.com/django-cms/djangocms-admin-style/issues/429
