### ISSUE TITLE
Django cms does not work with Content Security Policy without "unsafe-inline" in script-src

### ISSUE THREAD

**Issue by Danfeng-tmx** [django-cms/django-cms#6959]
In order to support CSP, we cannot use 'unsafe-inline' in script-src , but if we do not add 'unsafe-inline' (script-src: 'self' ), it will show error on each<script data-cms> div.

## Steps to reproduce
login to django cms, the main page will show the error is console.

## Expected behaviour
We would like to make CSP working without 'unsafe-inline' in script-src.

## Actual behaviour
if there is no 'unsafe-inline' in script-src, it shows error for each <script data-cms>

## Additional information
Could someone please have a check? Thank you

**Comment by DmytroLitvinov** [comment]
Hi @macolo ,
Any status on that issue?)

**Comment by marksweb** [comment]
It would be fantastic to support CSP, but the work involved is significant.
