### ISSUE TITLE
[BUG] Treebeard 4.5 leads to major issue

### ISSUE THREAD

**Issue by jbpenrath** [django-cms/django-cms#6980]
## Description

Release of `django-treebeard` 4.5 seems introduce breacking change from `django-cms`.

```
IntegrityError at /en/admin/cms/page/add-plugin/

duplicate key value violates unique constraint "cms_cmsplugin_path_4917bb44_uniq"
DETAIL:  Key (path)=() already exists.
```

## Steps to reproduce

1. Install a fresh django-cms or update your dependencies to have treebeard 4.5 installed
2. Create a page with no content
3. Publish it
4. Edit it then add a plugin
5. Save our plugin content
6. Then boom !

## Expected behaviour

I should be able to add a plugin without error.

## Actual behaviour

An error occured when I try to save a plugin.

## Screenshots

<img width="1510" alt="Capture d’écran 2021-02-18 à 12 05 53" src="https://user-images.githubusercontent.com/9265241/108349172-f7456580-71e2-11eb-85a9-e0e37d2a60d0.png">

## Additional information (CMS/Python/Django versions)

Python: 3.6.11
Django-CMS: 3.8.0

I reproduced this error on a fresh install from Divio.

**Quick workaround : Rollback to treebeard 4.4**

We identify the following change as potential source of this issue. django-treebeard/django-treebeard#192

**Comment by srinathganesh** [comment]
We have the exact same error in a new deployment.

**Comment by VeshRaazThapa** [comment]
mine worked by rolling back to djang-treebeard==3.1.1
django==3.1.7
django-cms==3.8.0

**Comment by PhilFuster** [comment]
I am also experiencing this. This is after the install of 4.5.1.
![image](https://user-images.githubusercontent.com/15935874/108844909-b5ce0500-75aa-11eb-94e3-b9289adf8a1f.png)

**Comment by yml** [comment]
It is interesting to note that wagtail was also impacted by the recent changes https://github.com/wagtail/wagtail/issues/6820.
It looks like this ticket (  https://github.com/django-treebeard/django-treebeard/issues/211) assumes that the version `4.5.1` resolving this issue which is not what I observe (\cc @PhilFuster ).

**Comment by DonkeyOatie** [comment]
I am seeing something I believe is related and is stopping us from publishing pages

```
  File "/opt/venv/lib/python3.6/site-packages/cms/utils/plugins.py", line 213, in copy_plugins_to_placeholder
    new_plugin = CMSPlugin.add_root(instance=new_plugin)
  File "/opt/venv/lib/python3.6/site-packages/treebeard/mp_tree.py", line 617, in add_root
    This method saves the node in database. The object is populated as if via:
  File "/opt/venv/lib/python3.6/site-packages/treebeard/mp_tree.py", line 326, in process
    # adding the new root node as the last one
treebeard.exceptions.NodeAlreadySaved: Attempted to add a tree node that is already in the database
```

I have tried rolling back to treebeard 4.3.1 and 4.4.0 (running fix-tree at each stage) and nothing seems to resolve the issue.

**Comment by PhilFuster** [comment]
@DonkeyOatie I was working with a fresh install so I created the project over. By uninstalling treebeard and installing the 4.3.1 version of treebeard as @VeshRaazThapa said, I got it to work. 
NOTE: Uninstall and install correct version of treebeard before first runserver or makemigrations/migrate command.

**Comment by DonkeyOatie** [comment]
@PhilFuster thanks for the suggestion.  That is pretty hard to do for us as we are running inside a docker container on a managed platform. I will see if I can script this to happen before the app starts.  Thanks for the info.

**Comment by PhilFuster** [comment]
Glad I could help @DonkeyOatie ! How about instead of beers, could I trouble you for some time in the future to discuss what your experiences with djangocms are? This is my first time using it for a marketing site I am building and there are some things I don't understand how I would implement.

**Comment by DonkeyOatie** [comment]
Anytime @PhilFuster my email is on my profile

**Comment by andychoi** [comment]
I tried to modify as below with **try except**.
```
    def str2int(self, num):
        """Converts a string into an integer.

        radix, alphabet = self.radix, self.alphabet
        if radix <= 36 and alphabet[:radix].lower() == BASE85[:radix].lower():
            try: return int(num, radix)
            except: return 0
```
