### ISSUE TITLE
[BUG]Font awesome icons not rendering properly.

### ISSUE THREAD

**Issue by skini-galaxia** [django-cms/django-cms#6992]
## Description
The default font awesome icon pack is not rendering properly on the CMS page.

## Steps to reproduce
1. Click on edit
2. Select the Icon widget
3. Select Icon
4. Select any icon from the 'Font awesome regular' icon pack
5. Save it 

## Expected behaviour
The icons should render properly.

## Actual behaviour
Icons not rendering properly.

## Screenshots
![image](https://user-images.githubusercontent.com/76421853/110932596-b65bef00-8351-11eb-939b-94dd59836360.png)

## Additional information (CMS/Python/Django versions)
django-cms==3.8

**Comment by marksweb** [comment]
Because you've got your own template here, you'll need to load font awesome yourself, it won't be loaded/provided by the CMS automatically.

https://fontawesome.com/start

**Comment by marksweb** [comment]
I'm closing this based on my current assumptions of what's going on.

@skini-galaxia if you could ensure that fontawesome is included in your template & test again. Failing that post here so we can open this again.
