### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by NicolaiRidani** [django-cms/django-cms#6997]
This is a placeholder issue for tracking planned improvements to documentation by @[TiredFingers](https://github.com/TiredFingers)

# Work to be done 

* [ ] Rename section “Development & Community” to “Contribute” 
* [ ] Rename “django CMS’s development community” to “Contributor Community”
* [ ] Create new sub-section under parent "Contribute" called "How to contribute"
* [ ] Move sub-sections "Contributing Code" "Contributing documentation" "Contributing translation" under "How to contribute"
* [ ] Remove “Using django CMS” section entirely -> will be reused in a separate user documentation 

# Commits/PRs

* add your commit or PR here

**Comment by TiredFingers** [comment]
https://github.com/django-cms/django-cms/pull/6999

**Comment by Aiky30** [comment]
This PR was failing on the Tests, why was it merged? Failures should never be merged!

**Comment by macolo** [comment]
@NicolaiRidani something that needs to be done here? Was the failing test resolved?

**Comment by victor-yunenko** [comment]
I'm assuming the tests have been fixed, @NicolaiRidani, can we close this one now?

**Comment by victor-yunenko** [comment]
Looks like it has been handled, please feel free to reopen if needed.
