### ISSUE TITLE
[BUG] When adding plugin inside text element's table, plugin cannot be unfocused when clicking inside the table and table is non editable

### ISSUE THREAD

**Issue by nichoski** [django-cms/django-cms#7003]
## Description
When adding a plugin inside text element's table, the plugin cannot be unfocused when clicking inside the table. This makes the table non editable. User has to click outside the table to unfocus the inserted plugin. This is bad because in many cases, especially when the table is large, the user might not come up with the idea to click outside the table, and think the whole text plugin has become non editable.

## Steps to reproduce
1. Create a page
2. Add a text element to the page, and create a text table inside it using the editor's buttons. Make the table have multiple rows and columns.
3. Inside any of the table's cells insert a plugin, using the dropdown menu in the editor for adding plugins, for example code, or icon.
4. Since the inserted plugin's element is focused/selected, click outside it, but still in the table, for example on another cell of the table.
5. Verify that the element is not getting unselected/unfocused, and trying to edit any of the other cells of the table does not work. 

## Expected behavior

At step 4 from the steps to reproduce, as long as the user clicks outside the inserted element, even if they click inside the table, the inserted element should be unfocused, and the table should be editable again.

## Actual behavior
The only way to unselect the inserted element and to be able to continue editing the table is to click anywhere outside the table, which can be inconvenient and in many cases the user cannot think of doing so, and end up thinking their whole text plugin has become non editable.

**Comment by greengoaxe** [comment]
Hi nichoski,
thank you for your effort. 
We could face this unpleasant behavior in 2 steps:
1) Now: Improve our documentation setting a warning for this unpleasant behavior
2) In one of next releases, we can fix that.

Kind regards,

**Comment by greengoaxe** [comment]
Hi nichoski,
are you using ckeditor5 table or django-cms one(i.e. no plug-in)?

Kind regards,
greengoaxe
