### ISSUE TITLE
[BUG]  Incomplete command on Readme-quickstart section

### ISSUE THREAD

**Issue by greengoaxe** [django-cms/django-cms#7008]
### Incomplete command reported

On the [Readme file](https://github.com/django-cms/django-cms/blob/develop/README.rst), Quick start section, the current, and incomplete, command reported is :
> **(env) $ python manage.py**

The right command is:
> **(env) $ python manage.py runserver**

## Expected behaviour

To add the word "runserver" so to fix the command

**Comment by TiredFingers** [comment]
Hi @greengoaxe thanks for the issue. PR is prefered =)
