### ISSUE TITLE
Django 3.2 use HttpResponse.headers in place of ._headers

### ISSUE THREAD

**Issue by pcolmant** [django-cms/django-cms#7015]
Hello,

As in the release notes of Django 3.2 (https://docs.djangoproject.com/en/3.2/releases/3.2/#requests-and-responses) using repsonse.headers in place of response._headers resolve 

  File "xxxxx/lib/python3.9/site-packages/cms/cache/page.py", line 84, in set_page_cache
    response._headers,
AttributeError: 'TemplateResponse' object has no attribute '_headers'

https://github.com/django-cms/django-cms/blob/e2c684a2710738de2d86e659038c59513e865e6a/cms/cache/page.py#L84

Thanks !

**Comment by gertjanvg** [comment]
We are encountering the same issue. In addition we found another place where this breaks in the page admin:

https://github.com/django-cms/django-cms/blob/develop/cms/admin/pageadmin.py#L419

**Comment by vinitkumar** [comment]
> We are encountering the same issue. In addition we found another place where this breaks in the page admin:
> 
> https://github.com/django-cms/django-cms/blob/3c08d36bd21e66e12f474c2bd2353c560ccaed67/cms/admin/pageadmin.py#L419

These and some other known issues has been fixed in this PR:
https://github.com/django-cms/django-cms/pull/7018/files

Could you please try this branch and check if you encounter anymore bugs? Thanks

**Comment by RNCTX** [comment]
> Could you please try this branch and check if you encounter anymore bugs? Thanks

Works for me.  Oddly the issue was only in Chrome.  Safari worked okay (on OSX Big Sur).

**Comment by robertpro** [comment]
Is this code going to be released soon?

**Comment by NicolaiRidani** [comment]
Hi @robertpro, if you want to stay up to date on the release process, I would suggest joining the official django CMS [ Slack](www.django-cms.org/slack). We have a workgroup dedicated to the release management process. Their Slack channel is #workgroup-release-management - I'm sure they'll be happy to answer your questions. 

Best
Nicolai

**Comment by robertpro** [comment]
@NicolaiRidani Thank you!

**Comment by magicproductions** [comment]
Hi, I have this issue but when I copied the cms file from her and past it to my packages I override the existing one it solved the issue, but I'm using django 3.2 already. is this version not live yet? or how to install django=3.2 with this issue solved please?

**Comment by marksweb** [comment]
@magicproductions django-cms 3.9 brought support for Django 3.2 so you should upgrade.
3.10.1 is the latest release but we're close to 3.11 hopefully.
