### ISSUE TITLE
[BUG] In language cookie many token such as LANGUAGE_COOKIE_HTTPONLY, LANGUAGE_COOKIE_SECURE, LANGUAGE_COOKIE_PATH etc. are not being read and set in the language cookie

### ISSUE THREAD

**Issue by sudo-hemant** [django-cms/django-cms#7022]
## Description

In language cookie many token such as LANGUAGE_COOKIE_HTTPONLY, LANGUAGE_COOKIE_SECURE, LANGUAGE_COOKIE_PATH etc. are not being read and set in the language cookie 

## Steps to reproduce
1. Go to this URL : https://github.com/django-cms/django-cms/blob/release/3.8.x/cms/middleware/language.py
2. Scroll to the 21st line (i.e., response.set_cookie(.....) )
3. You will see that the token such as LANGUAGE_COOKIE_HTTPONLY and other tokens which must be read from the settings file, are not being read and set properly.

## Expected behaviour
the code should look like the following -

response.set_cookie(
    settings.LANGUAGE_COOKIE_NAME, 
    language, 
    expires=expires,
    max_age=settings.LANGUAGE_COOKIE_AGE,
    domain=settings.LANGUAGE_COOKIE_DOMAIN,
    httponly=settings.LANGUAGE_COOKIE_HTTPONLY, 
    path=settings.LANGUAGE_COOKIE_PATH,
    samesite=settings.LANGUAGE_COOKIE_SAMESITE,
    secure=settings.LANGUAGE_COOKIE_SECURE,
)

## Actual behaviour

response.set_cookie(settings.LANGUAGE_COOKIE_NAME, language, expires=expires)

## Additional information (CMS/Python/Django versions)

the CMS version is 3.8, but I think this is an issue in all the versions

**Comment by marksweb** [comment]
Hi @sudo-hemant I don't think this is an issue for CMS.

`LANGUAGE_COOKIE_HTTPONLY` is a django setting, not django-cms setting.

The feature ticket from django is here; https://code.djangoproject.com/ticket/30304

And the commit into django is here; https://github.com/django/django/commit/19fc6376ce67d01ca37a91ef2f55ef769f50513a
