### ISSUE TITLE
[BUG] Delete only site leads to 'Site matching query does not exist.' 

### ISSUE THREAD

**Issue by soerendip** [django-cms/django-cms#7023]
I followed the documentation https://docs.django-cms.org/en/latest/introduction/01-install.html to install django-cms manually.

I added a superuser and was able to login. 

When going to `/admin/sites` and deleting `example.com` I run into this error:

```
Request Method: | GET
-- | --
http://localhost:8000/admin/sites/site/
3.2
DoesNotExist
Site matching query does not exist.
/usr/local/lib/python3.9/site-packages/django/db/models/query.py, line 435, in get
/usr/local/bin/python
3.9.4
['/app/app',  '/usr/local/lib/python39.zip',  '/usr/local/lib/python3.9',  '/usr/local/lib/python3.9/lib-dynload',  '/usr/local/lib/python3.9/site-packages']
Thu, 15 Apr 2021 18:41:52 +0000
```

from which it seems impossible to recover without manual database manipulation. 

I would expect an empty table with the option to create a site.

**Comment by soerendip** [comment]
Sorry, I actually did not add the label `priority high`.

**Comment by TiredFingers** [comment]
Hi, @soerendip thanks for the bug report. I tested it and have same effect. Need some discuss

**Comment by marksweb** [comment]
Hi @soerendip, while this does cause an error, it's not an error from django-cms.

This is an error from django itself, and I would expect an error here.

To confirm, here's the stacktrace;

```
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.8/site-packages/django/contrib/sites/shortcuts.py", line 13, in get_current_site
    return Site.objects.get_current(request)
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.8/site-packages/django/contrib/sites/models.py", line 58, in get_current
    return self._get_site_by_id(site_id)
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.8/site-packages/django/contrib/sites/models.py", line 30, in _get_site_by_id
    site = self.get(pk=site_id)
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/mwalker/Sites/consoles/.venv/lib/python3.8/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
django.contrib.sites.models.Site.DoesNotExist: Site matching query does not exist.
```

Django generally operates using `Site` objects, you'll notice `django.contrib.sites` in your `INSTALLED_APPS` if you're using the framework. Django creates the first `Site` object using the domain `example.com` after migrations are ran.

Generally, if you check your settings file, you'll see `SITE_ID = 1` (unless you're running a multisite project). So what you've done is delete the site matching the ID in your settings file, so django can't load it's own `Site` object anymore.

**Comment by soerendip** [comment]
I thought that is what I did. Though, if the interface becomes unusable if a user by accident or by curiosity deleted the object, maybe it would be wise to hide that functionality or at least add a comment. Or better would be to catch it.

________________________________

**Comment by marksweb** [comment]
Yeah, I don't disagree @soerendip, but any change would be for django itself, not django-cms.

There's nothing we can do about that in this app. I'm going to close this as it's a third party issue.

**Comment by soerendip** [comment]
You cannot remove it from the admin pannel, for example, and set the site name with an environment variable, or a variable in settings?

**Comment by TiredFingers** [comment]
> Yeah, I don't disagree @soerendip, but any change would be for django itself, not django-cms.
> 
> There's nothing we can do about that in this app. I'm going to close this as it's a third party issue.

Actually we can restrict deletion of the last site

**Comment by marksweb** [comment]
> You cannot remove it from the admin pannel, for example, and set the site name with an environment variable, or a variable in settings?

Remove the sites section?

Yeah you could do that. You'd just have to unregister the model from admin. Basically the opposite of how you get your models in there.

**Comment by marksweb** [comment]
> > Yeah, I don't disagree @soerendip, but any change would be for django itself, not django-cms.
> > 
> > There's nothing we can do about that in this app. I'm going to close this as it's a third party issue.
> 
> Actually we can restrict deletion of the last site

While that may be true, it would be something better done at a project level if the developers wanted to do that.
