### ISSUE TITLE
 The file 'cms/fonts/3.8.0rc1/django-cms-iconfont.eot' could not be found

### ISSUE THREAD

**Issue by pcolmant** [django-cms/django-cms#7026]
## Description

The file 'cms/fonts/3.8.0rc1/django-cms-iconfont.eot' could not be found.
It is referenced in django-cms/cms/static/cms/css/3.8.0rc1/cms.base.css

url(../../fonts/3.8.0rc1/django-cms-iconfont.eot);src:url(../../fonts/3.8.0rc1/django-cms-iconfont.eot#iefix)

Are the 3.8.0rc1 directories still needed?

**Comment by marksweb** [comment]
Ironically #6996 just removed similar files.

What version are you seeing this in? I can't see any refs to this path in the develop branch.

**Comment by marksweb** [comment]
I've removed the high priority label as I can't see any sign of these files in the develop branch.

**Comment by goutnet** [comment]
@pcolmant I just grepped the code, and could not find any occurrence of `3.8.0rc1`  in the code.

Can we close this?

**Comment by goutnet** [comment]
Can not reproduce on develop
