### ISSUE TITLE
[BUG] User has permissions, but cannot use it.

### ISSUE THREAD

**Issue by ReminoR** [django-cms/django-cms#7029]
## Description
We've created a new user (leader_project) and added his in group "leaders_project". The next permissions were setup for the group:
cms | page | Can add page
cms | page | Can change page
cms | page | Can delete page
cms | page | Can publish page
cms | page | Can view page
 
and also the permissions of pages
![image](https://user-images.githubusercontent.com/31583955/117003144-b0a9d680-ad0e-11eb-9250-30fe6fad2ea0.png)

The user "leader_project" can create, page, edit the early created pages, but when "leader_project" created a new page, he cannot to change, move and publish it.
![image](https://user-images.githubusercontent.com/31583955/117003948-b05e0b00-ad0f-11eb-859e-bf71a049d32d.png)

After this, if "leader_project" update his own permissions in any other available for his page, the new page became available for publishing and moving. Just update, nothing else.

![image](https://user-images.githubusercontent.com/31583955/117005027-fbc4e900-ad10-11eb-8a18-1a3f63718628.png)

and he can change and move the new page.
![image](https://user-images.githubusercontent.com/31583955/117005201-2c0c8780-ad11-11eb-8b45-28a6324607e2.png)

## Expected behaviour
If user "project_leader" has permissions to add, delete, update and publish pages, then he has to have it without update his permissions.

## Actual behaviour
The user "project_leader" cannot use the permissions which he has without updating.

## Additional information (CMS/Python/Django versions)
Versions:
Django-cms: 3.8
Django: 2.2
Python:3.8.3

**Comment by goutnet** [comment]
Hi does this behavior persist for any new page created after the first point?

**Comment by goutnet** [comment]
Another question, would you be able to reproduce this with an earlier version of Django? (you are currently running 2.2)

**Comment by marksweb** [comment]
@ReminoR  When you say that they cannot use their permissions, what do they actually see? Are they able to login via admin & see the CMS toolbar?

**Comment by ReminoR** [comment]
> Hi does this behavior persist for any new page created after the first point?

Yes, this behavior persist after creation a new page, but it's good after relogin of user.

![image](https://user-images.githubusercontent.com/31583955/119439851-67690780-bd4d-11eb-85cc-5dd6ac1ba01e.png)

**Comment by ReminoR** [comment]
> @ReminoR When you say that they cannot use their permissions, what do they actually see? Are they able to login via admin & see the CMS toolbar?

Yes, they can see the CMS toolbar and even they can edit page, but cannot publish it, cannot move it, cannot edit advanced settings.

![image](https://user-images.githubusercontent.com/31583955/119440320-43f28c80-bd4e-11eb-8897-96fd3eb2ca29.png)

**Comment by ReminoR** [comment]
> Another question, would you be able to reproduce this with an earlier version of Django? (you are currently running 2.2)

I will try use the newest Django as soon as posible. We hope it will decide the problem.

**Comment by goutnet** [comment]
ah!! that's interesting feedback, sounds like this is an issue lying in the session Handling. Let us know if you can reproduce this on a newer version of Django, if yes we will have to investigate :)

**Comment by ReminoR** [comment]
> ah!! that's interesting feedback, sounds like this is an issue lying in the session Handling. Let us know if you can reproduce this on a newer version of Django, if yes we will have to investigate :)

Dear Goutnet, I'm checked the issue on local machine, with pure installation, on the newest Django (3.1.11) and Djangocms (3.8.0). The problem was repeated. Please, look screenshot.

![image](https://user-images.githubusercontent.com/31583955/120465789-8a885c80-c3c8-11eb-9533-62a1ab981c14.png)

**Comment by goutnet** [comment]
Hi, ok we will have to get a look at it.

For information though, the latest version of djangoCMS is `3.9.0rc2` and
django would be `3.2` at that point, but I don't see much that would have
changed in the session handling between 3.8 and 3.9 so it is likely still
there.

Let us check.
-- 

Florian Delizy

**Comment by crydotsnake** [comment]
I can also confirm the bug for djangoCMS Version 3.9.0-RC2

**Comment by gabrielcandrade** [comment]
@ReminoR 

Hello Reminor, sorry about the delay for reaching with some others questions. But can you detail how you create these pages?

They are created by code, just like:

`page = create_page(**kwargs)?`

I'm asking this, because with create_page() method, there's some others functions that need to be called to publish their pages. Maybe this is one of the problems that you are suffering. After that, I just need to know too, how you set the page permissions? It's by code, or manually?

**Comment by goutnet** [comment]
@gabrielcandrade based of the comments before, I think they create those pages by the UI.

**Comment by barsch** [comment]
have the same issue above - pages are created via UI in the django backend by a non-admin (having all cms permissions needed). I tested to re-login the user after creating the page but no success - however over time this issue resolved and the user could move the page around etc.

so playing with some settings I figured out that setting the permission cache duration zero seems to solve the issue:

CMS_CACHE_DURATIONS = {
    "content": 60 * 5,
    "menus": 60 * 5,
    "permissions": 0,
}

not very useful in productive environment but maybe it helps to figure out the issue ...
