### ISSUE TITLE
[BUG] All docs.django-cms.org pages "Edit on GitHub" links lead to 404

### ISSUE THREAD

**Issue by victor-yunenko** [django-cms/django-cms#7031]
## Steps to reproduce
- open any page on https://docs.django-cms.org/en/latest/
- scroll to the bottom of the page and click on the "Edit on GitHub" link
- it leads to https://github.com/django-cms/django-cms//develop/docs/index

**Comment by marksweb** [comment]
I saw this recently @victor-yunenko

I assume its a slash in a setting that doesn't need to be there. Perhaps in RTD for the branch name.

Need someone with access to RTD settings to have a look over them.

**Comment by victor-yunenko** [comment]
Hi @NicolaiRidani, perhaps you can ask Anatoliy to take a look?

**Comment by crydotsnake** [comment]
Would love to help out here, but its hard to test it local. Because locally you dont have the "Edit on GitHub" Button.

**Comment by marksweb** [comment]
I can't see any settings on RTD that would have caused this so it's still a bit of a mystery.

However it seems that the new docs theme doesn't have this link, so I'm going to close this.
