### ISSUE TITLE
[BUG] 3.9rc1: wrong bundled js folder

### ISSUE THREAD

**Issue by mbi** [django-cms/django-cms#7048]
## Description

The Javascript static files in the 3.9rc1 PyPI release are bundled in [dist/3.8.0](https://github.com/django-cms/django-cms/tree/release/3.9.x/cms/static/cms/js) instead of `dist/3.9rc1`, so both the page tree admin and editing of content doesn't work because all javascript static URLs return a 404.

## Steps to reproduce

Try to edit a page or list pages in the admin.

## Expected behaviour

See pages in the admin.

## Actual behaviour

No pages are listed, javascript errors in the console, 404 on all javascript files, e.g.

``` 
 "GET /static/cms/js/dist/3.9.0rc1/bundle.admin.base.min.js HTTP/1.1" 404 -
``` 

## Additional information (CMS/Python/Django versions)

Did this to temporarily fix the the problem 
``` 
ln -s $VIRTUAL_ENV/lib/python3.8/site-packages/cms/static/cms/js/dist/3.8.0  $VIRTUAL_ENV/lib/python3.8/site-packages/cms/static/cms/js/dist/3.9.0rc1
``` 

Django CMS 3.9rc1 
Django 3.2

**Comment by goutnet** [comment]
checking this now

**Comment by goutnet** [comment]
confirmed, this is a problem with the release script and invalidates RC1.

Let me fix this now

**Comment by goutnet** [comment]
I fixed it on the branch, can you check on release/3.9.x branch?

Here is a bulid of the release:

[dist.zip](https://github.com/django-cms/django-cms/files/6519689/dist.zip)

**Comment by mbi** [comment]
Checked by installing the wheel in the zip, confirmed it fixes the problem, thanks for the quick fix! :+1:

**Comment by goutnet** [comment]
Ok, I am releasing RC2 right now with this fix!

**Comment by mbi** [comment]
Awesome: tested the RC2, all good :+1:
Thank you for the quick fix!
