### ISSUE TITLE
[BUG] Copy-paste of structure content between sites does not always work (random behavior)

### ISSUE THREAD

**Issue by fp4code** [django-cms/django-cms#7072]
## Description

On two different sites, sharing the same database served through the same nginx, two different uwsgi,
I do a "Copy all" in structure mode from a page of the first site, and then a "Paste" in structure mode to a page of the other site. Sometimes, it's working, sometimes, for another destination page on the same second site, it's not working.

Method: 	POST
Request URL: 	https://destination-subsite.site.fr/en/admin/cms/page/move-plugin/?cms_path=%2Fen%2Fmembers%2Ffoo-bar%2F%3Fedit
Raised by: 	cms.admin.placeholderadmin.move_plugin

No CMSPlugin matches the given query.

## Additional information (CMS/Python/Django versions)

CMS: 3.8.0 (with Fix: Bad Title.path in Multilanguage sites if parent slug is created or modified (#6968))
Python: 3.8.5
Django: 3.1.8

## I will investigate

I will appreciate any guidelines about how structure-mode copy-paste is implemented.

**Comment by fp4code** [comment]
It is a mistake if I put the priority: high. I think it is more a medium priority. How to change that?

**Comment by CruiseDevice** [comment]
@fp4code On the right below Assignees, there is Labels. You can edit them..

**Comment by fp4code** [comment]
> @fp4code On the right below Assignees, there is Labels. You can edit them..

If I click on it, I obtain the list of all high priority issues.

**Comment by vinitkumar** [comment]
> > @fp4code On the right below Assignees, there is Labels. You can edit them..
> 
> If I click on it, I obtain the list of all high priority issues.
> I don't have the gear button on the right, as described here: https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels#applying-a-label
> It is reserved to authorized members.
> I suggest any authorized member to decrease the priority of this issue. Copy-pasting between sites is useful, but not widely used.

I changed the status to priority:medium as you wanted.
