### ISSUE TITLE
[BUG] Unable to edit custom plugin although permissions are set 

### ISSUE THREAD

**Issue by pupattan** [django-cms/django-cms#7080]
## Description
Unable to edit plugin although permissions are set 

## Steps to reproduce

- Create user with staff 
- `User.objects.create_user(email, email, password, first_name=first_name, last_name=last_name, is_staff=True)`
- Add all CMS permissions 
- Create pages and add plugins (custom) using api 
- CMS_PERMISSION = True is set 

## Expected behaviour
User should be able to edit  plugins

## Actual behaviour
User not  able to edit plugins

## Screenshots
![image](https://user-images.githubusercontent.com/19246595/123380952-b654c780-d5ad-11eb-8a7c-299cfd8f0d8a.png)

All permissions are set 
![image](https://user-images.githubusercontent.com/19246595/123381010-c79dd400-d5ad-11eb-8ad4-6bc06ca1c3dd.png)

## Additional information (CMS/Python/Django versions)
django-cms==3.7.4

Note: Same issue with creating group also. Not sure if I am missing something

**Comment by crydotsnake** [comment]
And if you try to upgrade your djangoCMS version?

**Comment by victor-yunenko** [comment]
Hi @pupattan, thank you for raising this!

Could it be related to #6801? CMS permissions seem to not work at the moment in general. Or do you mean that it affects only custom plugins, not the default ones?
