### ISSUE TITLE
[BUG] Django CMS 3.9 Isn't Supported on Python 3.6

### ISSUE THREAD

**Issue by gopackgo90** [django-cms/django-cms#7091]
## Description

According to the [Django/Python compatibility table](https://github.com/django-cms/django-cms/blame/3.9.0/docs/index.rst#L166), Django CMS 3.9 isn't supported on Python 3.6. This seems odd as it currently lists that every Django CMS from 3.4.5 through 4.0 support Python 3.6, _except_ Django CMS 3.9. Also the Python 3.6 classifier is still listed in the [setup.py](https://github.com/django-cms/django-cms/blob/3.9.0/setup.py#L27) for Django CMS 3.9. So either the documentation or the setup.py is wrong.

## Steps to reproduce

1. Go to https://github.com/django-cms/django-cms/blame/3.9.0/docs/index.rst#L166
2. Observe that Django CMS 3.9 is listed as not being compatible with Python 3.6.
3. Then go to https://github.com/django-cms/django-cms/blob/3.9.0/setup.py#L27, which still lists the Python 3.6 classifier is still listed.

## Expected behaviour

The documentation should be consistent with the setup.py classifiers.

## Actual behaviour

The documentation is not consistent with the setup.py classifiers.

## Additional information (CMS/Python/Django versions)

Django CMS 3.9.0
Python 3.6

**Comment by goutnet** [comment]
@marksweb thoughts?

**Comment by marksweb** [comment]
@goutnet Tests run against current python and the 2 previous so 3.7, 3.8, 3.9. ([here](https://github.com/django-cms/django-cms/blob/release/3.9.x/.github/workflows/test.yml))

Given that 3.9 didn't officially exist when I modified this table, I imagine I set the table against that. It will work in 3.6, but if we're not testing it, it shouldn't really go on that table.

That said, 3.9 does have as far back as 3.5 in the classifiers. I'll assign this to myself & await your thoughts, but I think we drop 3.5 from `setup.py` & add python 3.9, then I can add 3.6 to the tests as I imagine it's still the most common version in use.

FYI @gopackgo90

**Comment by goutnet** [comment]
On this IMO, we should follow supported Django policy in term of python support, not sure which version is supported @marksweb ?

**Comment by gopackgo90** [comment]
Django's Python support policy is described at https://docs.djangoproject.com/en/3.2/faq/install/#what-python-version-can-i-use-with-django.

**Comment by goutnet** [comment]
From that page:

Django version | Python versions
-- | --
2.2 | 3.5, 3.6, 3.7, 3.8 (added in 2.2.8), 3.9 (added in 2.2.17)
3.0 | 3.6, 3.7, 3.8, 3.9 (added in 3.0.11)
3.1 | 3.6, 3.7, 3.8, 3.9 (added in 3.1.3)
3.2 | 3.6, 3.7, 3.8, 3.9

 Seems we have to keep 3.5 & 3.6 since we didn't discard Django 2.2 support, right? @marksweb

**Comment by marksweb** [comment]
@goutnet I'd argue we can drop 3.5 because of it's age & not follow django exactly. Especially given that 3.9 brought in 3.2 support where django then drops 3.5.

If people really want to use python 3.5, we've got older releases of cms that support it (any release up to now).

**Comment by goutnet** [comment]
works for me then :)

as for the fix, I think this should be applied on develop, so that we pick everything from there on next release :) (targetting somewhere around August for next release, either 3.9.1 or 3.10.0 depending on what is in the pipe) :)
