### ISSUE TITLE
Potential performance optimization for fetching Page titles

### ISSUE THREAD

**Issue by zkne** [django-cms/django-cms#7099]
Hi everyone, sorry for not using a template but this is not for a bug template.

I have a technical question regarding performance optimizations for CMS. I’ve noticed that retrieving titles of the pages are not optimized and I’m wondering is there a reason why it was implemented like this. Here is an example:

`[page.get_title() for page in Page.objects.filter(id__in=[1, 2, 3, 4, 5, 6, 7])]`

Creates 8 queries to the database, but if you add a prefetch_related to the query set it also does 8+1 queries (one is for retrieving all the titles for these pages):

`[page.get_title() for page in Page.objects.prefetch_related("title_set").filter(id__in=[1, 2, 3, 4, 5, 6, 7])]`

This can be optimized if we change the way the title cache is populated on the line:
https://github.com/django-cms/django-cms/blob/develop/cms/models/pagemodel.py#L1434.

Instead of doing
`titles = Title.objects.filter(page=self)`
we could do
`titles = self.title_set.all()`

And this will create only two queries, and the number of queries won’t increase linearly with the number of pages.
I’m wondering is there a reason why titles are fetched this way?

I could create a PR if DjangoCMS core contributors agree on the change.

**Comment by victor-yunenko** [comment]
Hi @zkne, thank you for the proposition! Indeed there are a lot of easy opportunities to improve the caching mechanism.

Probably the main reason is that the typical django CMS website isn't tremendously large, and current those issues aren't highly apparent. But I agree with your idea and a PR from you would be warmly welcome!

**Comment by Aiky30** [comment]
@jrief Maybe worth using one of your large projects to test the performance improvements on v3.

**Comment by fsbraun** [comment]
@marksweb I think this was fixed in #7177
