### ISSUE TITLE
Flake8 checks being ignored

### ISSUE THREAD

**Issue by marksweb** [django-cms/django-cms#7102]
Looking over a PR I've submitted I've noticed we're running `flake8`, but ignoring any errors. (using the `--exit-zero` flag)

This seems a bit pointless.

It's certainly something we should run, but clearly it needs better configuration. If the current state of the project is acceptable, the current failures should be added to the excluded list & the exit zero flag removed from the linting action.

**Comment by Aiky30** [comment]
Agreed, I've not seen any of the projects actively ignoring flake8 errors. If there are errors / warnings that should be ignored they are normally added to the setup.cfg file.

**Comment by marksweb** [comment]
@Aiky30 I'll go over things, make some sensible choices over ignoring things & changing code 👍
