### ISSUE TITLE
[BUG] django cms mode switcher disappears after plugin save

### ISSUE THREAD

**Issue by SteveGZr** [django-cms/django-cms#7108]
## Description
When saving plugin while structure is open the mode switcher button disappears.

## Steps to reproduce
1. Log in as a staff user
2. Go to any site in the cms
3. Open the structure
4. Edit a plugin
5. Save it
6. Wait for cms-content-refresh
7. Structure Button disappears

## Expected behaviour
The Button should not disappear.

## Actual behaviour
The Button disappears.
The div `<div class="cms-toolbar-item-cms-mode-switcher">` is completely gone.

## Additional information (CMS/Python/Django versions)
CMS 3.8.0
Python 3.9
Django 3.1.12

**Comment by SteveGZr** [comment]
Additional Information:

The problem does not occur when the user has the permission to edit static placeholders.

**Comment by NicolaiRidani** [comment]
> How can I contribute?

Hi @shahzaib-92 thx we always welcome contributions. First, you should check out our [contributor guidelines](https://docs.django-cms.org/en/latest/contributing/index.html) and also join our [Slack](https://www.django-cms.org/slack) - #contributors channel. I can then guide you through the next steps.

**Comment by marksweb** [comment]
I think we fixed this recently so I'll close this.
