### ISSUE TITLE
[BUG] Publish button disappears after plugin editing

### ISSUE THREAD

**Issue by nichoski** [django-cms/django-cms#7113]
## Description
The publish button blinks after editing plugins on some projects, and completely disappears on others.

## Steps to reproduce
Use django newer than 2.2.19 and any django-cms version newer than September 2014. Create a text plugin. Edit the text plugin. In most cases you will notice the publish button blink. In rare occasions (in some project not so rare, almost always) the publish button disappears and does not return until you refresh the page.

## Expected behaviour
Editing plugins should not make the publish button disappear or blink.

## Technical Description
After editing a plugin, django-cms' frontend makes two requests to the server. One to get the toolbar, and one to get the current page's contents. Using the response from both of them, the toolbar's contents are being replaced. The toolbar contents are replaces twice, I don't know why. The request that fetches the toolbar alone is broken and lacks the publish button in its response. The one that fetches the current page's contents is ok. These requests are executed asynchronously. Almost always, the request that fetches the toolbar finishes first, and the request that fetches the entire page's contents finishes second. This usually hides the problem with the missing publish button from the request that fetches the toolbar. You can notice the publish button blinking after editing a text plugin for example. But on some projects they finish in reversed order, and the page ends up missing the publish button. 

The request that fetches the toolbar contents needs to be fixed. I have a working solution, but I want to avoid breaking other things, so I need your input. I will first explain below what and why is happening.

The request that fetches the toolbar contents is supplying a list of placeholders in the url's GET variables. As a solution to issue [3404](https://github.com/django-cms/django-cms/issues/3404), all the [`&` characters in the URL are replaced with `&amp;`](https://github.com/django-cms/django-cms/blob/develop/cms/static/cms/js/modules/cms.base.js#L333). This worked for a time, mainly due to luck, but since django 2.2.19 it doesn't anymore. When `placeholders[]=12&placeholders[]=13&placeholders[]=14` is replaced with `placeholders%5B%5D=12&amp;placeholders%5B%5D=13&amp;placeholders%5B%5D=14`, the GET variables on django's side used to be parsed to this `{'placeholders[]': ['12', '13', '14'], 'amp': ['', '', '']}` because both the "&" and the ";" characters were used as query separators. And the request was working properly. But in Django version 2.2.19, ";" [was removed](https://github.com/django/django/commit/fd6b6afd5959b638c62dbf4839ccff97e7f7dfda) as a query separator, and since then, this feature is broken. The example from above ends up being parsed like this: `{'placeholders[]': ['12'], 'amp;placeholders[]': ['13', '14']}` and I can see some other weird contents in there, but it seems they aren't breaking anything yet.

## Proposed solution
Do not replace "&" with "&amp" in the full URL string. Would this bring back the problems of issue [3404](https://github.com/django-cms/django-cms/issues/3404)? I have created a PR with this change. I have tested it and was unable to reproduce the problem reported in issue 3404. Please review this and let me know if you have other suggestions.

## Additional information
This happens on django versions newer than 2.2.19, and django-cms versions since September 2014.

**Comment by marksweb** [comment]
Just looking at this with;

```
django==2.2.24
django-cms==3.9.0
djangocms-text-ckeditor==3.10.0
```

Upon saving the text plugin, I can see that the plugin button is removed, but it does return. What you're saying about the two requests makes sense, but I'm not familiar with the details here.

Have you located where the two requests are triggered for the toolbar & page contents? I'd like to take a look at these.

**Comment by nichoski** [comment]
> Just looking at this with;
> 
> ```
> django==2.2.24
> django-cms==3.9.0
> djangocms-text-ckeditor==3.10.0
> ```
> 
> Upon saving the text plugin, I can see that the plugin button is removed, but it does return. What you're saying about the two requests makes sense, but I'm not familiar with the details here.
> 
> Have you located where the two requests are triggered for the toolbar & page contents? I'd like to take a look at these.

@marksweb yes, in `cms/static/cms/js/modules/cms.structureboard.js` in `invalidateState` method, we call `_loadToolbar()`, and `updateContent()`. The `_loadToolbar()` function is the one refreshing the toolbar, i.e. the broken one.

**Comment by dkoenigroer** [comment]
Hi,
anyone still working on https://github.com/django-cms/django-cms/pull/7114 / https://github.com/django-cms/django-cms/pull/7115 ?

We got the same issue here where sometimes, sometimes not the "Publish" Button switches to the "Show published version" button after saving a plugin and the following reload.

**Comment by marksweb** [comment]
Believe this was resolved
