### ISSUE TITLE
[feat] Identify external links in the toolbar

### ISSUE THREAD

**Issue by marksweb** [django-cms/django-cms#7137]
#7101 introduced a new menu in the toolbar for link to external resources. I believe this is the first time there have been external links in the toolbar.

It'd be good if external links were identified, preferably by a font awesome icon;
https://fontawesome.com/v5.15/icons/external-link-alt?style=solid

The python side of this is fairly straightforward;

`cms_toolbars.py` contains `add_help_menu()` and here calls to `add_link_item()` need to pass a new kwarg. I'd suggest `external` (set to `True`).

In `cms/toolbar/items.py`, `add_link_item()` needs a new kwarg matching the above, defaulting to `False`. And this is passed through to `LinkItem` where it becomes an instance attribute and is passed into the context.

I think the final thing then becomes a conditional in the template to render the icon. That's `templates/cms/toolbar/items/item_link.html`.

The last part, where I'm not so familiar with the best approach is to get the icon to align to the right of the menu.

Doing the above should result in something like this;

![Screenshot 2021-10-15 at 21 53 01](https://user-images.githubusercontent.com/1461191/137559191-cd3cb73b-e975-422d-bae9-e070dfe4f0f1.png)

**Comment by sumit-158** [comment]
Hi, @marksweb Is anyone is working on this, if not can I work on this? Can you please guide me too how to setup this locally cuz this would be my first contribution to this open source.

**Comment by crydotsnake** [comment]
> Hi, @marksweb Is anyone is working on this, if not can I work on this? Can you please guide me too how to setup this locally cuz this would be my first contribution to this open source.

Hello 👋🏽 
I'm working on this right now. There is already draft PR for it: #7283 

But I had no time to continue working on this so far.
