### ISSUE TITLE
[feat] Open external toolbar links in a new tab/window

### ISSUE THREAD

**Issue by marksweb** [django-cms/django-cms#7138]
#7101 introduced a new menu in the toolbar for link to external resources. I believe this is the first time there have been external links in the toolbar.

In #7137 we're looking to identify external links. The remaining thing would be to have these external links open in a new tab or window.

Adding `target"_blank"` to the links doesn't work here. Likely due to the way the toolbar renders. Therefore this may require some javascript to get links to open in a new tab or window.

**Comment by tacc-wbomar** [comment]
To open DjangoCMS menu links in new window, I wrote a JavaScript module:
https://github.com/TACC/Core-CMS/blob/554b408/taccsite_cms/static/site_cms/js/modules/setTargetForExternalLinks.js


_That might not be a permalink, because I could replace my solution with Python via a `templatetag`._
