### ISSUE TITLE
[BUG] Django CMS 3.9.0 page_attribute meta_description doesn't work

### ISSUE THREAD

**Issue by mike667** [django-cms/django-cms#7141]
https://docs.django-cms.org/en/latest/reference/templatetags.html?highlight=meta_description#page-attribute
Does meta_description work in version 3.9.0? Because all the fields related to description and keywords have disappeared in my admin panel.

How did I read they were removed in release 3.0?
https://docs.django-cms.org/en/latest/upgrade/3.0.html#cms-seo-fields

I can't figure out what the end result is. Manually setting all description og:description tags and so on is not convenient via django-page-meta.

Can you give some advice? @nephila

**Comment by mike667** [comment]
I remember when all the meta settings were in the page settings. Now they are missing.
![Screen Shot 2021-11-02 at 10 23 20](https://user-images.githubusercontent.com/9371245/139811080-842c1c2a-8ca0-4868-acd3-f1528376b23e.png)
![Screen Shot 2021-11-02 at 10 23 36](https://user-images.githubusercontent.com/9371245/139811082-955fd0a1-0ad9-46f5-874a-d26168f49cae.png)

django==3.2.8
django-cms==3.9.0

I did a clean install a year ago, it seems to have been version 3.8.
I'll do the test again, install DCMS again and look at the admin panel.

Can you show me how meta editing looks like for you?

**Comment by marksweb** [comment]
I can confirm that I've got the meta description working as it does in django-cms 3.7 also in 3.9 having just upgraded the project between those versions.

This is what the basic page settings look like;

![Screenshot 2022-01-26 at 01 25 23](https://user-images.githubusercontent.com/1461191/151087511-32c201c9-a2b9-4bc6-a029-60016b3d9a0b.png)

The HTML uses

```
<meta name="description" content="{% page_attribute "meta_description" %}">
```

This renders

```
<meta name="description" content="SuperHalfs series">
```
