### ISSUE TITLE
[DOCS] 3.9.0 docs do not explain how to install the tutorial site 

### ISSUE THREAD

**Issue by sureshvv** [django-cms/django-cms#7146]
The "Templates and Placeholders" section refers to the tutorial site. Is this forked from github, may be?

## Do you want to help fix this issue?

* [ ] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. 
* [ ] No, I only want to report the issue.

**Comment by NicolaiRidani** [comment]
> According to the Install section, the CMS_TEMPLATES is set as follows:
> 
> ```
> CMS_TEMPLATES = [
>     ('home.html', 'Home page template'),
> ]
> ```
> 
> This is changed in the Templates & Placeholders section to:
> 
> ```
> CMS_TEMPLATES = (
>     ## Customize this
>     ('fullwidth.html', 'Fullwidth'),
>     ('sidebar_left.html', 'Sidebar Left'),
>     ('sidebar_right.html', 'Sidebar Right')
> )
> ```
> 
> This makes it a bit confusing. It may help to discuss this a little more. Then we could just remove the tutorial reference.

Hi @sureshvv thx. Not really sure why this is supposed to be confusing. The manual installation instructions are separate from the Getting Started Tutorial.
