### ISSUE TITLE
[BUG] Releases json not up to date 

### ISSUE THREAD

**Issue by andre-dasilva** [django-cms/django-cms#7150]
I found that in the djangocms-admin-style package the url: 
https://raw.githubusercontent.com/divio/django-cms/releases/releases.json 
is used to check for the latest django-cms version. 

Two things are wrong in the json:
1. 3.9.0 is missing (latest version) 
2. the links to the docs don't work anymore (are probably old)

Will this be updated? I would be glad to help if possible, I just didn't find it in the repo 😅

**Comment by vinitkumar** [comment]
@andre-dasilva You are looking at the wrong repo. Divio doesn't maintain DjangoCMS any more, it's django-cms org.

So if you didn't find that file, it's because it's not present any more in the official repo.

**Comment by andre-dasilva** [comment]
@vinitkumar thanks for the reply. i made a PR: https://github.com/django-cms/django-cms/pull/7156 for it. and will close this issue
