### ISSUE TITLE
[BUG] CSS in <noscript> is loaded when saving plugins

### ISSUE THREAD

**Issue by fsimonjetz** [django-cms/django-cms#7160]
## Description

In my project, I added some fallback CSS to be loaded in case the user has JavaScript disabled. Enclosed in a `<noscript>` HTML tag, the CMS should never do anything with it. However, after editing a plugin and saving it, the stylesheet defined within the `<noscript>`-tag is loaded. It happens in my own project and I can reproduce it with the Django-CMS quickstart repo.

## Steps to reproduce

For example, in the Django-CMS Quickstart project:
- Add a CSS file to `static/css/noscript.css` containing
```
  body {
      border: 5px solid red;
  }
```
- In `templates/minimal_page.html`, add `static` to the `{% load %}` template tag and add the following lines to the `<head>`:
```
<noscript>
<link rel="stylesheet" href="{% static 'css/noscript.css' %}">
</noscript>
```
- Add a new page, open structure mode, add a text plugin (or another plugin) and save the changes.
- The red border appears.

## Expected behavior

Whatever is defined within `<noscript>` shouldn't become active when using the CMS because using the CMS implies having JavaScript enabled.

## Actual behavior
The styles defined in the `<noscript>` tag are applied to the document just like usual CSS.

## Additional information
Reloading the page fixes it, but in my case it completely broke the behavior of JS-controlled collapsing elements, which is a poor UX for the editor. For the time being, wrapping the `<noscript>` in `{% if not request.toolbar.show_toolbar %}<noscript>...</noscript>{% endif %}` seems to fix it.

**Comment by marksweb** [comment]
Thanks for the thorough bug report @fsimonjetz.

This feels like it'd be the fault of the browser, because it should be in control of what's being displayed & identify that `<noscript>` tag & ignore it because it knows javascript is enabled.
