### ISSUE TITLE
[DOC] Please resurrect the targeted 'Integrate django CMS into an existing project' page.

### ISSUE THREAD

**Issue by changeling** [django-cms/django-cms#7161]
## Description

It would be a tremendous asset to update/bring back the [Integrate django CMS into an existing project
](https://github.com/django-cms/django-cms/blob/3.0.12/docs/how_to/integrate.rst), separately from the install by hand section, which assumes project creation. I suspect there are quite a few potential adopters (like myself) out there who already have established projects and want to begin integrating Django-CMS, rather than creating a new project. This has the added benefit of giving such users exposure and recruiting them into the fold.

Having a distinct page that directly, quickly and with less mental gymnastics on their part than the install by hand page asks of them addresses their needs clearly would raise the profile of Django-CMS. And help them (and me) out. :D

## Screenshots

N/A

## Additional information (CMS/Python/Django versions)

From what I can tell, this page disappeared after version 3.0.12 of Django-CMS.

## Do you want to help fix this documentation issue?

* [ ] Yes, I want to help fix this issue and I will join #workgroup-documentation on [Slack](https://www.django-cms.org/slack) to confirm with the team that a PR is welcome. 

* [x] No, I only want to report the issue.

**Comment by NicolaiRidani** [comment]
thx @changeling our voluntary documentation workgroup will look into it.

**Comment by changeling** [comment]
Thank you, @NicolaiRidani. This is the single most useful thing I'd like to see, a streamlined integration flow, to try Django-CMS on one of my own sites as a potential blog backend. I really appreciate how responsive y'all are.

**Comment by changeling** [comment]
Has this issue been addressed?

**Comment by marksweb** [comment]
@changeling not yet as far as I'm aware.

**Comment by changeling** [comment]
Any progress on this?

**Comment by fsbraun** [comment]
No, so far not. Would you like to give it a stab?
