### ISSUE TITLE
Fix Django requirements (not compatible with Django 4 yet)

### ISSUE THREAD

**Issue by nferrari** [django-cms/django-cms#7179]
https://github.com/django-cms/django-cms/blob/a412870ce780c383379eb33776a0017b658b6991/setup.py#L9

Django-CMS is not Django 4 compatible. This line needs to be fixed OR the project needs to become compatible (I'm not pretty familiar with the strategy).

**Comment by marksweb** [comment]
#7128 has started to look at django 4.0 support.

**Comment by TiredFingers** [comment]
Same issue. If user will follow getting started docs and just installs django-cms - it will fail and will not work

**Comment by marksweb** [comment]
This is now in the 3.10 RC1.
