### ISSUE TITLE
django.core.exceptions.FieldError: Local field 'created_by' in class 'PageUser' clashes with field of the same name from base class custom user.

### ISSUE THREAD

**Issue by gopimarket** [django-cms/django-cms#7214]
Any work around for this?

**Comment by marksweb** [comment]
Hi @gopimarket

This sounds specific to your project setup. Do you have a custom user model with the same field name perhaps?

**Comment by gopimarket** [comment]
> Hi @gopimarket
> 
> This sounds specific to your project setup. Do you have a custom user model with the same field name perhaps?

Yes

**Comment by marksweb** [comment]
@gopimarket in that case, defining a related name may help.
https://docs.djangoproject.com/en/3.2/ref/models/fields/#django.db.models.ForeignKey.related_name

**Comment by gopimarket** [comment]
> @gopimarket in that case, defining a related name may help. https://docs.djangoproject.com/en/3.2/ref/models/fields/#django.db.models.ForeignKey.related_name

No, I tried it did not worked. I used **related_name="%(app_label)s_%(class)s_created_by"** for by custom user model.

**Comment by marksweb** [comment]
@gopimarket in that case I think the only solution would be to remove the field from your user model.
