### ISSUE TITLE
[BUG] djangoCMS 3.10.0RC1 structure tree doesn't open

### ISSUE THREAD

**Issue by crydotsnake** [django-cms/django-cms#7216]
## Description
The structure tree in djangoCMS 3.10.0RC1 doesn't open anymore.

## Steps to reproduce

- Install djangoCMS 3.10.0rc1
- Login to the djangoCMS backend and try to open the structure tree

![djangocms3 10 0rc1](https://user-images.githubusercontent.com/39345336/152661867-b021fd9c-99e5-4f5f-8f37-487b69a3c8c0.gif)

## Expected behaviour
The structure tree should open and list all the plugins.

## Actual behaviour
The structure tree doesn't open. (see the GIF above)

## Additional information (CMS/Python/Django versions)
djangoCMS 3.10.RC1
Python 3.9.7
Django: 2.2

**Comment by fsbraun** [comment]
If I try, the structure tree appears if I reduce the window size beyond some breakpoint. CSS issue?

**Comment by goutnet** [comment]
@vinitkumar @marksweb  this might be related to the new build system?  can you help check?

Does this replicates also on `develop` ?

**Comment by crydotsnake** [comment]
@fsbraun and I can confirm that the toolbar becomes visible when you minimize the browser window to a certain breakpoint. So it might be a CSS issue here.

![djangocms-toolbar-resize-window](https://user-images.githubusercontent.com/39345336/152699381-872e78f8-7cc5-42a7-89d0-685ef69bc9a6.gif)

**Comment by fsbraun** [comment]
@crydotsnake @goutnet A little inspection shows that on a wide screen the class `.cms-structure` gets annotated by an inline style `right: -1031px;` (the particular number seems to vary but is large negative) which makes the structure view disappear to the left:

    <div class="cms-structure cms-structure-condensed" style="right: -1031px; display: block;">
        ...
    </div>

In 3.9. this reads `right: -15px` which seems fine.

I could image that there is a JS routine at work where the inline style is calculated which for whatever reason has gone stale.

**Comment by MacLake** [comment]
The breakpoint is 2^10. If the viewport width is 1024 px or less, the structure board becomes visible and takes the whole width instead of just a part.

Btw.: Since 3.5.3 I’ve been encountering a strange bug when opening the structure board, most likely it’s not related, but who knows?
https://github.com/django-cms/django-cms/issues/6600

**Comment by fsbraun** [comment]
It seems `this.ui.toolbar.width()` returns `0` resulting in `-this.ui.window[0].innerWidth ` being written to the `right` inline style. I have to give up here, since I do not know a thing on the inner workings of the toolbar.

**Comment by marksweb** [comment]
Just to back up what @fsbraun has said here, I'm seeing the same thing;

https://user-images.githubusercontent.com/1461191/152898690-8f407f24-f17c-4658-b265-eb72809f12d0.mov

The only change to the structure board since 2018 was in #6699 but that will have been in 3.9

I think it's time to add the expert opinion label & maybe @FinalAngel could help us out.

**Comment by fsbraun** [comment]
@marksweb There's been a change to `cms.toolbar.js `, however. Also affected is line 739:

https://github.com/django-cms/django-cms/blob/04e843337d18afe64478d09f00051ed13a49ff55/cms/static/cms/js/modules/cms.toolbar.js#L736-L740

Could it be that the DOM is changed without updating the reference in `this.ui.toolbar` leaving the latter pointing to something that is not displayed and hence has the width 0? Also, as far as I understand, `this.ui.toolbar` here belongs to the `Toolbar` class. Besides this shortcut also the similar shortcut in `cms.structureboard.js` might need to be updated. 

It seems that before the change the DOM was patched and not replaced potentially leaving the pointers in tact.

**Comment by MacLake** [comment]
Hmm, I don’t want to spoil the party, but I still have the bug, and I even checked that the updated file has made it into my test installation.

**Comment by fsbraun** [comment]
Hi @MacLake !  Thanks for testing. Indeed, if I install the current develop branch using git, the bug is there and the updated `cms.toolbar.js` file is present. The bundle file is hard to read but it seems not to reflect the fix.

@marksweb Could it be that the bundled js files are not up to date? 

@MacLake Do you have the opportunity to run the build process to check if the bug then goes away? (clone the repository, `npm install`, `gulp bundle`, then installing `pip -e /path/to/the/clone`)

**Comment by marksweb** [comment]
@fsbraun @MacLake the static bundle is built during the release process so those files don't exist in develop.

**Comment by fsbraun** [comment]
If I install from the develop branch, there's a a folder `cms/js/dist/3.9.0` in `static` which contain bundles. It seems to me that they get accessed. Using `./manage.py runserver` my test installation gets `http://localhost:8000/static/cms/js/dist/3.9.0/bundle.toolbar.min.js`. 

@marksweb Maybe this Is this an artifact? Obviously, if you just install `pip install https://github.com/django-cms/django-cms/archive/develop.zip` you do not build the bundles and are served these outdated bundles. Btw. the same is apparently true for css: `static/cms/css/3.9.0`.

**Comment by marksweb** [comment]
@MacLake ok that's not really a problem, so run `nvm use && gulp bundle` to ensure the static files have been built. Then check if it's fixed.

**Comment by MacLake** [comment]
@fsbraun @marksweb Thanks for explaining! I just took a small look into it. I can’t find a `package.json`, so `npm install`fails. What do need ǹvm`(Node Version Manager) for? Maybe we just need a bit more documentation on that bundling, or I have missed something. I’ll check it later.

**Comment by crydotsnake** [comment]
You need NodeJS 16. And the package.json is in the root folder.

**Comment by MacLake** [comment]
Weeks later… I have taken a look at it and it worked to create a bundle without downgrading nodel,js with nvm. Should it be exactly node.js 16 or at least 16? I have 17.6.0.

**Comment by crydotsnake** [comment]
I would try it with nodejs 16. Just to be on the safe side.

**Comment by marksweb** [comment]
> Weeks later… I have taken a look at it and it worked to create a bundle without downgrading nodel,js with nvm. Should it be exactly node.js 16 or at least 16? I have 17.6.0.

I'd recommend the use of nvm

https://github.com/nvm-sh/nvm

We have an nvmrc file which allows you to run `nvm use` to switch to the correct node version.

You can also have multiple versions installed and move between them.
