### ISSUE TITLE
[BUG] Toolbar issue when on a custom page - structure mode empty when CMS page with the same slug exists.

### ISSUE THREAD

**Issue by petrklus** [django-cms/django-cms#7220]
## Description

When on a custom App (say /my-url/) with static placeholders, all works fine UNTIL there is a CMS page with a slug matching the custom app is created. Then, structure mode comes up empty.

## Steps to reproduce

1. Create a custom app that uses custom placeholders
2. Test out they work correctly
3. Now, create a CMS page with a slug matching the page
4. Structure mode is now empty, even though the content still renders correctly.

## Expected behaviour

Custom App to take priority and show structure mode, regardless whether a CMS page with a matching slug exists.

## Actual behaviour

Custom App CMS content still renders (if configured previously), even double-clicking on plugins work, however, structure mode is empty.

I have looked into this further and it seems that the toolbar uses request.current_page to determine which content renderer to use. The `LegacyRenderer` (working one) get replaced with `ContentRenderer` when CMS page with the same slug is present. I think this is due to the request.current_page being incorrectly populated with a page even when on a third-party URL.

## Additional information (CMS/Python/Django versions)

Django CMS 3.9.0 on Django 3.2.12.

**Comment by amourousias** [comment]
I'm experiencing this issue also, Django CMS 3.11.0 on Django 3.2.13

**Comment by amourousias** [comment]
Interestingly using a custom Toolbar and setting uses_legacy_structure_mode to True and content_renderer to LegacyRenderer doesn't fix the issue

**Comment by jan-szejko-steelseries** [comment]
I'm in the same team as @amourousias. It turned out that the problem in our project had nothing to do with this issue and instead was caused by a stale template override of `cms/toolbar/toolbar.html`.
