### ISSUE TITLE
[BUG] Copying a plugin hides the "Publish page changes" and breaks "View published" button

### ISSUE THREAD

**Issue by petrklus** [django-cms/django-cms#7222]
## Description

On a page with pending changes, using the "Copy" plugin function breaks the "View published" button and hides the "Publish changes" button.

## Steps to reproduce

1. Load up a CMS page with unpublished changes
2. Open the structure mode
3. Select "Copy" for any of the plugins
4. Toolbar updates with the buttons as per the issue above

## Expected behaviour

For the "View published" button to continue working and the publication button to not disappear.

## Actual behaviour

"View published" button breaks (wrong URL) and publication button disappears.

## Screenshots

[Screen recording](https://youtu.be/zInXtFXr5pc)

## Additional information (CMS/Python/Django versions)

Django 3.2.12.0, Django CMS 3.9.0.5

**Comment by fsbraun** [comment]
A similar but different issue is found in django CMS v4.0.0rc11. There a the toolbar shows "Edit" despite having the structure board open:
<img width="1157" alt="image" src="https://user-images.githubusercontent.com/16904477/159787350-adeb2802-99de-4fdc-975b-eb3a4024c220.png">

**Comment by fsbraun** [comment]
Fixed in version 3.10
