### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by michalnik** [django-cms/django-cms#7258]
## Description

running djangocms is stopped because of "ModuleNotFoundError: No module named 'pytz'" after start

## Steps to reproduce

1) python3.7 -m venv env
2) source env/bin/activate
3) pip install --upgrade pip
4) pip install djangocms-installer
5) djangocms

## Expected behaviour

Stopped after start because of "djangocms: error: the following arguments are required: project_name"

## Actual behaviour

Stopped after start because if "ModuleNotFoundError: No module named 'pytz'"

## Additional information (CMS/Python/Django versions)

python3.7, djangocms-installer 2.0.0, pip 22.0.3, 

## Do you want to help fix this issue?

Add additional requirement to setup.py or to requirements - pytz

* [x] No, I only want to report the issue.

**Comment by marksweb** [comment]
Hi @michalnik

It sounds like something in your project depends on pytz but it's not installed.

Simply add pytz to your requirements to ensure its installed.

You may also find it quicker and easier to start with our quick start project: https://github.com/django-cms/django-cms-quickstart

**Comment by michalnik** [comment]
I have nothing except django-cms installed. So if something depends on pytz it is django-cms.

**Comment by michalnik** [comment]
But it is possible and it is the clue that django-cms depends on django and it depends on pytz. But I did not inquire these possibilities in depth. Should I?

**Comment by michalnik** [comment]
Ooops, I reported the bug to wrong project. I am appologize. It belongs to djangocms-installer ...

**Comment by marksweb** [comment]
@michalnik I'd just put pytz in your requirements.

There is a tool that can show you what your installed packages depend on

https://pypi.org/project/pipdeptree/
