### ISSUE TITLE
[DOC] Can't clone repository with ssh public key error

### ISSUE THREAD

**Issue by TiredFingers** [django-cms/django-cms#7305]
## Description

Can't clone repo with `git@github.com:django-cms/django-cms-quickstart.git`

## Do you want to help fix this documentation issue?

* [x] Yes, I want to help fix this issue and I will join #workgroup-documentation on [Slack](https://www.django-cms.org/slack) to confirm with the team that a PR is welcome.

**Comment by TiredFingers** [comment]
Is it for everybody? Or this is only for me? 

The error is `git@github.com: Permission denied (publickey).`

My proposal is change it to https link

**Comment by crydotsnake** [comment]
You need a SSH Key: https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

**Comment by TiredFingers** [comment]
> You need a SSH Key: https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

Sure, thank you! But maybe we can change link to code with http and for installation it will be easier?

**Comment by crydotsnake** [comment]
> You need a SSH Key: https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

I believe it would be better to add a note about this in the README.
