### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by snehlata08** [django-cms/django-cms#7310]
On editing source on "text" plugin of cms loses some of the data and changes it to something else.  

## Steps to reproduce

1.  Create a cms page
2.  Click on the add plugin button and  add `Text`  plugin. 
3.  Click on the source button and put the source below 

```<ul style="color: white;">
	<li>
	<h4>
       <a href="https://www.google.com" target="_blank">Google</a> 
       <a class="padding-left-5px" href="https://mail.google.com/" title="Gmail"> <i class="fa fa-envelope" aria-hidden="true"></i></a>
    </h4>
	</li>
</ul>


   ```

## Expected behaviour
![image](https://user-images.githubusercontent.com/79985986/165894654-74734b2a-d411-410c-af65-a8dee265a25a.png)

## Actual behaviour

![image](https://user-images.githubusercontent.com/79985986/165894663-d0e19d77-314e-46dc-ac0c-b2eba3d40686.png)

This works fine and as expected 
 
Now if we do the above steps and

1.  Click on `Text` plugin again and try to edit it. It removes the font-awesome code which was written earlier . 
```  <ul style="color: white;">
	<li>
	<h4><a href="https://www.google.com" target="_blank">Google</a> <a class="padding-left-5px" href="https://mail.google.com/" title="Gmail"> </a></h4>
	</li>
</ul>
``` 
It looks like this after that. 

Now since the font awesome icon is removed if i save this again.   It becomes something like below 
![image](https://user-images.githubusercontent.com/79985986/165895021-b076190a-ec0c-445f-85ad-72353ff433cf.png)

So my question is why the fontawesome code is getting removed.

**Comment by marksweb** [comment]
This is expected behaviour.

You need to explicitly allow the i tag using the `TEXT_ADDITIONAL_TAGS` setting.
