### ISSUE TITLE
Django/Python compatibility table out of date (Q2 2022)

### ISSUE THREAD

**Issue by macolo** [django-cms/django-cms#7312]
- adding django 4
- adding python 3.10
- adding django-cms 3.10, 3.11 (future) and 4.2 (future)

## further considerations
- 3.11 should be LTS compatible with django 3.2 (dropping support for anything below django 3.2)
- python 3.6 is end of life, dropping support right away
- TBD

**Comment by macolo** [comment]
Also see https://github.com/django-cms/django-cms/issues/7056

**Comment by marksweb** [comment]
To confirm, django-cms 3.10 dropped python 3.6, added python 3.10

I can't remember where django 4 support is up to.

**Comment by macolo** [comment]
hi @Aiky30 I accepted the requested changes, @marksweb I updated dcms 3.10 according to your comment. Do you guys think this reflects reality? In that case I would then finalize the PR.

**Comment by Aiky30** [comment]
@macolo I've reviewed and accepted on the basis that the v4 requirements are correct.

**Comment by PeterW-LWL** [comment]
The documentation page https://docs.django-cms.org/en/latest/ is still not up to date.

**Comment by fsbraun** [comment]
@PeterW-LWL Documentation is up to date now (though showing outdated version number - fixed in #7472)
