### ISSUE TITLE
[BUG] After following 'How to install django CMS by hand' getting error 'TypeError: issubclass() arg 1 must be a class'

### ISSUE THREAD

**Issue by charris-msft** [django-cms/django-cms#7319]
## I followed https://docs.django-cms.org/en/latest/how_to/install.html exactly (I believe).

When I ran `manage.py cms check` I got the error:
`TypeError: issubclass() arg 1 must be a class`

I got the same error when running `manage.py runserver`

## Steps to reproduce

1. Follow the install instructions exactly: https://docs.django-cms.org/en/latest/how_to/install.html
2. Run `python manage.py cms check`
3. See error

## Expected behaviour

I expect to see no error, but I have never seen it run successfully so I'm not sure what to expect for the success case.

## Additional information (CMS/Python/Django versions)

I'm using Django 3.2 as the instructions state.
I'm running on Windows 11 with Python 3.10

## Do you want to help fix this issue?

* [X] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. But I'm going to be away from my keyboard next week so I'll have to connect after that.
* [ ] No, I only want to report the issue.

**Comment by marksweb** [comment]
What version of django-cms are you using please?

**Comment by charris-msft** [comment]
I am using version 3.10.0.

**Comment by marksweb** [comment]
Thanks for confirming @charris-msft.

I wanted to confirm that I don't have an issue with this same setup, so we'll need to reach out to the wider community on slack.

```
% python --version            
Python 3.10.3
% pip freeze | grep "Django=="
Django==3.2.13
% pip freeze | grep "django-cms=="
django-cms==3.10.0
% python manage.py cms check      

********************************
Checking django CMS installation
********************************

...
```

**Comment by charris-msft** [comment]
I posted this issue on the django-cms slack channel and got the following advice:

> [How to install django CMS by hand](https://docs.django-cms.org/en/latest/how_to/install.html#templates)
> The easiest way to install django CMS is by using the automated django CMS installer. This is the recommended way to start with new projects, and it’s what we use in the tutorial section of this doc...

I found some good instructions for installing and using the djangocms-installer here: [Installing django CMS](https://djangocms.readthedocs.io/en/latest/introduction/install/#installing-django-cms)
