### ISSUE TITLE
[BUG] 500 when invalid overwrite url is filled in

### ISSUE THREAD

**Issue by jgadelange** [django-cms/django-cms#7344]
## Description

From time to time some of our clients manage to put random (invalid) strings as slug in the overwrite url (in advanced settings) which results in 500s. 

## Steps to reproduce

1. Go to Advanced settings
2. Enter an overwrite url containing an invalid character (for instance a space)

## Expected behaviour

A validation error is raised that says it is an invalid url.

## Actual behaviour

The cms starts raising errors.:

```
NoReverseMatch: Reverse for 'pages-details-by-slug' with keyword arguments '{'slug': 'this is an invalid slug'}' not found. 1 pattern(s) tried: ['(?P<slug>[0-9A-Za-z-_.//]+)/$']
```

## Do you want to help fix this issue?

* [x] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. 
* [ ] No, I only want to report the issue.

**Comment by jgadelange** [comment]
Ah, apparently this also holds for the `slug` field, not just the overwrite url.

**Comment by vinitkumar** [comment]
I agree, I have noticed these errors too.

**Comment by kat0016-k** [comment]
I would like to solve this issue please assign me.

**Comment by marksweb** [comment]
Oh good point @jgadelange. I once had a client do this & I don't think I could fix it. I think the page just had to be hidden away in the tree.

**Comment by vinitkumar** [comment]
@kat0016-k Are you fixing it Or have a PR that fixes it? 
Else, I will look into fixing this issue.

**Comment by kat0016-k** [comment]
I want you to look for now. I met with an accident recently. sorry:( but please keep me updated.

**Comment by rblcoder** [comment]
Hi, I am new to this repo, can you give guidance on how this issue can be fixed?

**Comment by marksweb** [comment]
@rblcoder hi, this solution should be validation of the advanced settings form to ensure the url provided is valid.

The fact an invalid url throws a no reverse error means the validation should try to reverse the provided value and if it fails in the same way, the form should return a validation error for that field.

**Comment by dhirensr** [comment]
@marksweb : when I'm testing locally, it's validating the advanced_setting url and also giving the message `    You entered an invalid URL.` 

should we resolve this issue before someone else also spends sometime trying to fix it like I was trying to do?

**Comment by marksweb** [comment]
@dhirensr if you have something that's working feel free to raise a PR and reference this issue so people can see there's a linked PR.

**Comment by dhirensr** [comment]
@marksweb : I wanted to work on this issue. but when I'm trying to reproduce, it seems like url's are already getting validated.
maybe the issue is already resolved and outdated then?

**Comment by marksweb** [comment]
@dhirensr Ok thanks, what version of django-cms are you using?

**Comment by dhirensr** [comment]
@marksweb : 
```
django-cms            3.11.1
```
