### ISSUE TITLE
[DOC] No changes for version 3.10.1 in CHANGELOG.md

### ISSUE THREAD

**Issue by DmytroLitvinov** [django-cms/django-cms#7351]
https://github.com/django-cms/django-cms/blob/develop/CHANGELOG.rst

**Comment by marksweb** [comment]
Correct, you'll notice the version is also not 3.10.1

There's an open PR for these changes.

**Comment by DmytroLitvinov** [comment]
Hi @marksweb ,

I see there is a version 3.10.1 at PyPI: https://pypi.org/project/django-cms/#history

**Comment by marksweb** [comment]
That's correct. I built and released it last night.
