### ISSUE TITLE
[BUG] CMS v4: Inconsistent behaviour when re-ordering plugins

### ISSUE THREAD

**Issue by marksweb** [django-cms/django-cms#7391]
## Description

I've got a page with 1 placeholder. Using `djangocms-frontend` to build content, first in a container for big displays, then a container for smaller displays. Generally using copy/paste to begin setting up the 2nd container.

https://user-images.githubusercontent.com/1461191/190281318-380f926e-166c-4549-a4bd-41fb807c5f44.mov

Although this isn't only happening to plugins which have been pasted. I've also created a new spacing plugin and tried to move this around the page;

https://user-images.githubusercontent.com/1461191/190282224-acdda3df-a8f9-4edb-86d6-6b7bc61fee6f.mov

Also a text plugin. While the text plugin was moved amongst the two first level containers, it moved without issue. But once moved within a container, re-ordering didn't always result in the plugin being where I dragged it.

Focusing on the plugins at the bottom of the 2nd container;

| id      | position | parent | note
| ----------- | ----------- | ----------- | ----------- |
| 4823      | 186       | None | top level 2nd container
| 5081      | 260       | 4823 | 2nd level container
| 5085   | 263        | 5081 | First card
| 5096   | 264        | 5081 | Second card
| 5229   | 269        | 5081 | my-2 spacing
| 5108   | 270         | 5081 | py-4 spacing (1st)
| 5107   | 271          | 5081 | py-4 spacing (2nd)
| 5100   | 277          | 5081 | Third card

Here is a copy of the plugins table filtered to all plugins within the placeholder on this page;
[Playground-678.csv](https://github.com/django-cms/django-cms/files/9570705/Playground-678.csv)

## Additional information (CMS/Python/Django versions)

djangocms-frontend 0.9.4 & 1.0
django-cms 4.0 develop-4
django 3.2.15

## Do you want to help fix this issue?

* [x] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. 
* [ ] No, I only want to report the issue.

**Comment by marksweb** [comment]
Trying to recreate this scenario without using djangocms-frontend and I'm unable to with this plugin setup;

![Screenshot 2022-09-20 at 00 57 14](https://user-images.githubusercontent.com/1461191/191139213-d7180384-95f2-4340-83e6-e0d2cc2cceea.png)

**Comment by fsbraun** [comment]
I just recreated it using Text and Icon plugins (somehow):
![broken-moving](https://user-images.githubusercontent.com/16904477/191198496-49af6768-a709-4933-b276-01d673ebfa79.gif)
