### ISSUE TITLE
Freenode URLs still lingering in markdown files / IRC

### ISSUE THREAD

**Issue by deliciouslytyped** [django-cms/django-cms#7395]
It appears that there used to be an IRC channel on #django-cms on Freenode at some point, and some of the documentation files still seem to mention Freenode, but not visibly. (e.g. https://github.com/django-cms/django-cms/blame/6e4841e4cadc9820b296bbe1b093497bcaf32b99/docs/contributing/code.rst#L203 and https://github.com/django-cms/django-cms/blame/2a19342613ab2ea5147afa1ca29d3af79027de0c/docs/contributing/development-policies.rst#L235 )

Has the project considered moving to or having a channel on libera.chat, where most of Freenode has moved after the network changed hands?

**Comment by marksweb** [comment]
@deliciouslytyped i think slack has taken over from irc these days. References to irc should really be updated to slack.

**Comment by fsbraun** [comment]
Removed invisible free node mentions with #7401
