### ISSUE TITLE
[BUG] Move "login required" feature outside of permissions

### ISSUE THREAD

**Issue by corentinbettiol** [django-cms/django-cms#7399]
## Description

The `CMS_PERMISSIONS` setting needs to be to `True` in order to be able to access [the form](https://github.com/django-cms/django-cms/blob/b8750ebc0ebaa52ec51945f1d4824a80d806f479/cms/admin/forms.py#L787-L797) to restrict a CMS page to `login required`, even if "login required" do not [use the](https://github.com/django-cms/django-cms/blob/9e8eb17497edf8f40d68f7dcb53b1b2c3576313c/cms/utils/decorators.py#L15-L16) [permissions](https://github.com/django-cms/django-cms/blob/b8750ebc0ebaa52ec51945f1d4824a80d806f479/cms/views.py#L168-L169) at all.

Moving it to advanced page settings will made the use of this feature easier (I don't want to activate a whole CMS permissions framework only for this unrelated feature).

## Steps to reproduce

* do not set `CMS_PERMISSIONS` to `True` in your settings
* try to find the "Login required" option
* `¯\_(ツ)_/¯`

## Expected behaviour

* do not set `CMS_PERMISSIONS` to `True` in your settings
* find the "Login required" option in advanced page settings

## Additional information (CMS/Python/Django versions)

Since it's more like a feature request than a bug I think it's okay to leave this empty.

## Do you want to help fix this issue?

* [x] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. 
* [ ] No, I only want to report the issue.

**Comment by fsbraun** [comment]
As an additional thought: Might it be more consistent with the UX to leave the checkbox in the permissions modal. To be able to reach the "login required" option it could be a menu entry that can be toggled (like hide/show in menu). This way this permission setting would exactly to be found where the permissions modal would be found.

Here's a screenshot from a German installation. The red box indicates the menu entry that opens the permissions modal. This would be replaced by something like ("Make login required" and "Make login not required"). 
<img src="https://user-images.githubusercontent.com/16904477/191593832-36b046e1-a575-4585-a88f-806c098a65c1.png" width="200">
