### ISSUE TITLE
[BUG] Invalid block tag 'language chooser' on Django 4.1.3

### ISSUE THREAD

**Issue by ksh7** [django-cms/django-cms#7428]
## Description
On Django 4.1+ this error is being thrown while using [language chooser](https://docs.django-cms.org/en/latest/how_to/languages.html)  feature:
`TemplateSyntaxError at / Invalid block tag on line _: 'language_chooser'. Did you forget to register or load this tag?`

Although up to Django version 4.0.8 everything works fine.

## Steps to reproduce

1. Install `django==4.1.3` or anything above 4.1
2. Install the latest version of `django-cms`
3. Use internationalization feature `language_chooser` as described [here](https://docs.django-cms.org/en/latest/how_to/languages.html)
4. It throws this error: `TemplateSyntaxError at / Invalid block tag on line _: 'language_chooser'. Did you forget to register or load this tag?`, even though `{% load menu_tags %}` is added to the page.

## Expected behaviour

It should work and show the language switch menu as it shows in `Django==4.0.8`

## Actual behaviour

It throws this error: `TemplateSyntaxError at / Invalid block tag on line _: 'language_chooser'. Did you forget to register or load this tag?`, even though `{% load menu_tags %}` is added to the page.

## Screenshots

![bug-1](https://user-images.githubusercontent.com/85094137/200115397-71bc4c73-8e7b-4c7c-a982-d80dc88b5375.png)

## Additional information (CMS/Python/Django versions)

CMS: 3.11.0
Python: 3.10
Django: 4.1.3
## Do you want to help fix this issue?

* [ ] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome.

**Comment by fsbraun** [comment]
Thanks @ksh7 for reporting this! django CMS 3.11.0 **does not yet support Django 4.1**. Please use Django 4.0 for the time being. Django 4.1 support is coming soon through django CMS 3.11.1. Stay tuned!

**Comment by marksweb** [comment]
Thanks @ksh7

That's a thourouh bug report 👍

**Comment by fsbraun** [comment]
@ksh7 Django CMS 3.11.1 is brining Django 4.1 support. You may try the Release Candidate:  `pip install django-cms==3.11.1rc1`.
