### ISSUE TITLE
[BUG] develop_v4 static_placeholders are not working in plugin window.

### ISSUE THREAD

**Issue by jefffortune** [django-cms/django-cms#7442]
## Description
Using `{% static_placeholder  'footer' %}` in the template creates a new static placeholder in models but doesn't show on the plugin admin screen. After it is created and you look at the model no site is defined, doesn't matter if you add a site though still doesn't work.

## Steps to reproduce

1. Add  `{% static_placeholder  'footer' %}` in minimal template
2. Refresh page to register placeholder
3. Go to a content page and click edit
4. no thumbnail with static footer is available.

## Expected behaviour

I expected the static_placeholder to be available in the plugin admin area.

## Actual behaviour

It was missing. I created a super user so permissions I think should not be an issue.

## Screenshots

![image](https://user-images.githubusercontent.com/17855589/203180505-6b783f51-6b79-47e7-82e2-3dc3ea54d233.png)
![image](https://user-images.githubusercontent.com/17855589/203180747-29370356-2d8a-4d2a-8d43-e04ccd320f46.png)

## Additional information (CMS/Python/Django versions)
dev v4 / 3.9 / 3.2

## Do you want to help fix this issue?

* [ ] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. 
* [ x ] No, I only want to report the issue.

**Comment by marksweb** [comment]
@jefffortune Static placeholders were removed from v4.

The replacement for them is `djangocms-alias`. I've been using this in v4 where I would previously have used static placeholders.

https://github.com/django-cms/djangocms-alias

**Comment by jefffortune** [comment]
Thank you for the information I have swapped out tags and got the desired experience I needed.
