### ISSUE TITLE
KeyError at /xxxxx - After removing a plugin

### ISSUE THREAD

**Issue by cedricrabarijohn** [django-cms/django-cms#7449]
## Description

I have a plugin **NavbarPlugin** that I coded inside **cms_plugins.py.**
- The code :
```py
@plugin_pool.register_plugin
class NavbarPlugin(CMSPluginBase):
    model = CMSPlugin
    render_template = "frontend/inviso_plugins_templates/menu/inviso_navbar.html"
    name="Navbar plugin"
    module = "Inviso"
    def render(self, context, instance, placeholder):
        context = super().render(context, instance, placeholder)
        return context
```
I used this plugin inside a page that I created, then it worked well.

Then I decided to delete the plugin from the code inside **cms_plugins.py**, but I forgot to remove it from the page in the first place.
Then I got an error like :
```
KeyError at /actualites/
'NavbarPlugin'
```

I decided then to undo the suppression of the plugin from **cms_plugins.py**, but then it turned out that there's always the same error again and again. I searched on the internet and all but I didn't got what I searched for.
Thanks

## Steps to reproduce

- Create a plugin in **cms_plugins.py**
- Use the plugin in a page
- Delete the plugin code in **cms_plugins.py**
- Refresh the page (or the project)
- Getting an error
- Rewritting the same plugin code in **cms_plugins.py**
- Refresh the page (or the project)
## Expected behaviour

After rewritting the plugin code in **cms_plugins.py**, the plugin should be seen by the application and no errors should occur anymore.
## Actual behaviour
The same error that occurs after deleting the plugin code from **cms_plugins.py** persists

## Do you want to help fix this issue?

* [ ] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. 
* [ ] No, I only want to report the issue.

**Comment by marksweb** [comment]
This is how missing plugins have always been handled & I don't think we should change that at this point.

**Comment by fsbraun** [comment]
As of django CMS version 4.1+ there will be graceful fallback.
