### ISSUE TITLE
[BUG] `diff-dom` freezing on CMS content refresh

### ISSUE THREAD

**Issue by petrklus** [django-cms/django-cms#7460]
## Description

We are experiencing issues with the CMS refresh. For certail plugin configurations and post-plugin modification, the browser tab first freezes, later to crash due to out of memory error. We have confirmed the same on Google Chrome / Mozilla Firefox.

## Steps to reproduce

1. Trigger content/structure board refresh
2. Tab crashes

## Expected behaviour

The page content to update.

## Actual behaviour

The diff between incoming document and actual document freezes up:

https://github.com/django-cms/django-cms/blob/develop/cms/static/cms/js/modules/cms.structureboard.js#L1291

Only tab restart fixes the issue.

## Screenshots

<img width="1211" alt="image" src="https://user-images.githubusercontent.com/1115667/208675313-8022ee9c-09f7-4d90-b1b3-809c68b65eb2.png">

## Additional information (CMS/Python/Django versions)

Django CMS 3.11.0 or 1, Django 3.2.

Tested on Mozilla Firefox and Google Chrome

## Do you want to help fix this issue?

We have looked into this further and the issue seems to be down to DiffDOM version 2.5.1. We have tried upgrading to the latest version 4.2.8, which works in debug mode, however, is not compatible with the current UglifyJS config.

* [x] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. 
* [ ] No, I only want to report the issue.

**Comment by Rogell** [comment]
This issue happened to me also and I can confirm that upgrading to the latest DiffDOM (version 5.0.4) fixes the problem.
I will not create a pull request as I don't have time to read all contribution requirements so if anyone wants to fix it here are my changes.

**Details:**
Branch: release/3.11.x
Python version: 3.11
NPM version: 6.14.4
System: Ubuntu 20.04.2 LTS on WSL2

**Changes:**
`package.json:52` -> `"diff-dom": "5.0.4",`
`cms/static/cms/js/modules/cms.structureboard.js:11` -> `import { DiffDOM } from 'diff-dom';`

**Comment by petrklus** [comment]
@fsbraun would you know of anyone with the CMS editor code experience who can look into this?

**Comment by marksweb** [comment]
@petrklus whats happening with the plugins that might give us a clue on how to reproduce this?

**Comment by fsbraun** [comment]
@petrklus Can you reopen #7461 ? So far, I have not been able to make the tests pass with the updated diffdom dependency.

**Comment by fsbraun** [comment]
@petrklus I think I have a solution (#7599) for v4:

* ChromeHeadless (using puppeteer) instead of PhantomJS
* (What kept me from succeeding at first were insufficient viewport dimensions in ChromeHeadless.)
* Update of karma

Do you think you can transfer the changes of #7599 to #7461 to see if we get tests running.

**Comment by DmytroLitvinov** [comment]
Hey @fsbraun ,
We struggled in our project with the same issue:
* DjangoCMS 3.11.3
* Django 3.2

After swapping to `develop` version in our staging, we see there is no issue. 
(In `develop` branch we have such commit https://github.com/django-cms/django-cms/commit/d8e9c527eb261719b88ee8d7d8067400d161003c

## Helpful links:
* [Compare changes between branches 3.11.3 and develop](https://github.com/django-cms/django-cms/compare/3.11.3...develop)
* [fix: add updates same as PR: #7599](https://github.com/django-cms/django-cms/pull/7600)


Do you think we can release new minor version of DjangoCMS like 3.11.4 with such fix? I am ready to provide help here with a contribution and I am really would be glad to do that.

**Comment by fsbraun** [comment]
I am literally working on it at the moment :-)

**Comment by fsbraun** [comment]
@DmytroLitvinov Out now!

**Comment by DmytroLitvinov** [comment]
Wow. Thank you 🤩
Going to deploy it to staging and production new minor version.

**Comment by fsbraun** [comment]
One after the other!

**Comment by fsbraun** [comment]
Fixed in django CMS version 3.11.4
