### ISSUE TITLE
[BUG] Messages popup not displaying background color

### ISSUE THREAD

**Issue by knkski** [django-cms/django-cms#7464]
## Description

I'm seeing the `cms-messages` popup as not displaying a background color. Here's a screenshot of the behavior:

![image](https://user-images.githubusercontent.com/20422884/209862854-12e1def3-248d-4670-b6f6-df16c2ea8009.png)

The purple-ish color is the color for the page, and the white is from the Django CMS toolbar. The popup message does not have any background color.

Inspecting the `.cms-messages` element, I see that the SCSS bit [here](https://github.com/django-cms/django-cms/blob/05b6d834/cms/static/cms/sass/components/_toolbar.scss#L365) resolved to `background: rgba(var(--dca-black),.74);`, which Firefox says is valid CSS. However, if I look at the computed properties tab for that element, I see a background-color of `rgba(0, 0, 0, 0)`. Here's a screenshot of Firefox's dev tools:

![image](https://user-images.githubusercontent.com/20422884/209863322-4aa8cf83-84fe-4114-8639-2fbf5e30ce3a.png)

For some reason, even though Firefox says that the CSS property is valid, the element is displayed without a background color. What's really odd though is that if I change the property to have a value of say `var(--dca-black)`, everything works as expected.

I'm also not seeing a background in Chromium, so it would appear that it's not just a Firefox issue. Based on [this SO answer](https://stackoverflow.com/a/41265350), it does appear that `var()` inside of `rgba()` should work.

## Steps to reproduce

1. Do something that triggers a popup message with the `.cms-messages` element.
2. Note that the `.cms-messages` element has no background color

## Expected behaviour

The `.cms-messages` element should have a background color

## Actual behaviour

The `.cms-messages` element does not have a background color

## Screenshots

Screenshots displayed inline above

## Additional information (CMS/Python/Django versions)

Python 3.10

django == 4.0.8
django-cms == 3.11.0

## Do you want to help fix this issue?

* [ ] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. 
* [x] No, I only want to report the issue.

In general, I'd like to help fix this issue, however I've reached the limits of my knowledge of modern CSS. I can provide more screenshots/debugging aid as necessary, though.

**Comment by fsbraun** [comment]
Thanks @knkski for pointing this out. It actually is a bug since only decimal color vars are valid inside Reba but `--dca-black` is defined as hex `#000`. I've created a PR to fix this: #7465
