### ISSUE TITLE
[BUG] Wizard create page doesnt work

### ISSUE THREAD

**Issue by svandeneertwegh** [django-cms/django-cms#7482]
## Description
When i start new. I get the wizard with 'new page'. I get the message in red "Please choose an option from below to proceed to the next step.".

## Steps to reproduce

I used this docs: https://django-cms-docs.readthedocs.io/en/latest/how_to/01-install.html
To setup django-cms v4.

## Expected behaviour

That when you choose a option in the wizard the form comes in front.

## Actual behaviour

When choosing an option i get in red "Please choose an option from below to proceed to the next step."

## Screenshots

<img width="1375" alt="Schermafbeelding 2023-01-22 om 12 01 49" src="https://user-images.githubusercontent.com/34129243/213912639-352a1761-08a6-4c2a-92cb-31aad98bd552.png">

## Additional information (CMS/Python/Django versions)

Python 3.9
Django 4.1.5
Django CMS 4.1.0rc1

## Do you want to help fix this issue?

* [ + ] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. 
* [ ] No, I only want to report the issue.

**Comment by svandeneertwegh** [comment]
I found out that when you add `django.template.context_processors.i18n` to the context_processors from TEMPLATES. The problem goes away.

**Comment by svandeneertwegh** [comment]
Problem is gone when following `https://django-cms-docs.readthedocs.io/en/latest/how_to/01-install.html#context-processors`.

**Comment by svandeneertwegh** [comment]
The problem is only from django-cms v4.. Why it is a necessary?

**Comment by fsbraun** [comment]
@svandeneertwegh Could you pin down what causes this issue?
