### ISSUE TITLE
[DOC] Removing django CMS from the project isn't documented

### ISSUE THREAD

**Issue by gorkemarslan** [django-cms/django-cms#7490]
## Description
I want to remove django CMS completely from the project. For this reason, the related CMS and CMS plugins tables should be dropped from the database. I find only the documentation for [uninstalling django CMS plugins](https://docs.django-cms.org/en/latest/reference/cli.html#cms-uninstall). So how can I safely remove django CMS from the project? At the end of the day, I. shouldn't touch the database manually. Instead, a corresponding change in the migration file should do that.

## Do you want to help fix this documentation issue?

* [ ] Yes, I want to help fix this issue and I will join #workgroup-documentation on [Slack](https://www.django-cms.org/slack) to confirm with the team that a PR is welcome. 
* [x] No, I only want to report the issue.

**Comment by fsbraun** [comment]
@gorkemarslan Django CMS is a Django app like any other. See here on how to uninstall a Django app: https://stackoverflow.com/questions/3329773/django-how-to-completely-uninstall-a-django-app

Probably you'd also have to remove django CMS from your project's `urls.py`.
