### ISSUE TITLE
[BUG] in django-cms4 'edit mode' goes off when go to other page

### ISSUE THREAD

**Issue by svandeneertwegh** [django-cms/django-cms#7492]
## Problems for django-cms4
- when in edit mode of a page when you switch to another page, it does not go in an already edit mode but you have to click each page for editing.
- When creating a page with the wizard is goes not in edit mode for the newly page...

## Additional information (CMS/Python/Django versions)

python==3.9
django==4.1.5
django=cms=4.1.0rc1

## Do you want to help fix this issue?

* [ ] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. 
* [ ] No, I only want to report the issue.

**Comment by fsbraun** [comment]
For published, unpublished or archived versions of a page there is no edit mode. We would need to specify what should happen if the editor navigates from a draft to an object (Page). Clearly this should not necessarily create a new draft version.

A reasonable behavior could be:
```
Preview mode     => Preview mode (ok)
Edit mode        => Preview mode (for published, unpublished or archived versions)
                 => Edit mode (for draft versions)
```

I am, however, not sure if different modes depending on the available versions do not make the editing experience more unreliably (you cannot know if you'll be in edit mode or preview mode when clicking a link).
