### ISSUE TITLE
Can't edit slug[BUG]

### ISSUE THREAD

**Issue by mj8arrett** [django-cms/django-cms#7506]
## Description

The slug field is not editable.

## Steps to reproduce

I'm finding this hard to reproduce but I have one site where it has happened and we can't now edit any slugs.

## Expected behaviour

When you edit the Page Settings, the slug should be editable.

## Actual behaviour

The field is not editable, it isn't possible to add the curser to the field.

## Screenshots

<img width="1680" alt="2023-02-17_10-47-23" src="https://user-images.githubusercontent.com/38863140/219624761-7fc5eb87-6ad1-4b9c-8458-115c9ccbece5.png">

## Additional information (CMS/Python/Django versions)

DjangoCMS 4

## Do you want to help fix this issue?

* [] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. 
* [x] No, I only want to report the issue.

**Comment by fsbraun** [comment]
@mj8arrett Can this be closed?
