### ISSUE TITLE
Improve French translations by using only one token for action buttons

### ISSUE THREAD

**Issue by wasertech** [django-cms/django-cms#7515]
## Description

![image](https://user-images.githubusercontent.com/79070834/228305444-a21be45c-4fa4-4519-84df-16c896587508.png)

There are three issues with translations in French.

1. "Nouveau Page" is two tokens "New" and "Page".  But it's "une page" so it should be "Nouvelle Page". It also can happen anytime an object name is feminine. (quite a lot in the french language)

https://github.com/django-cms/django-cms/blob/9e33167701b65ce4fb7675d61e452e62792556e3/cms/locale/fr/LC_MESSAGES/django.po#L1057-L1062

2. We could improve "Ajouter page maintenant." with "Ajouter *une* page maintenant."

3. We should improve « il n’y a pas encore page » with « il n’y a pas encore *de* page ».

https://github.com/django-cms/django-cms/blob/9e33167701b65ce4fb7675d61e452e62792556e3/cms/locale/fr/LC_MESSAGES/django.po#L1102-L1109

## Steps to reproduce

With Django-CMS configured in French,

Go to Administration > Django CMS > Pages

Note: Adding only one token for new objects will probably also fix those kind of issues in other languages than french if they also distinguish genres.

# More examples

![image](https://user-images.githubusercontent.com/79070834/228308762-cfe03536-0682-447b-a39e-79a22ccacdba.png)

"Ajouter *une* page type", « il n’y a pas encore *de* page type » and "Nouvelle Page Type". 

Note 2: This issue probably affects plugins too.

Note 3: This will facilitate the production of accurate translations since the context will be given.

**Comment by fsbraun** [comment]
That's a good point. Same issue with German. I see no way, however, of predicting the genus of the `%(object)s`. It can be pages, aliases, blog posts, html snippets or whatever in future.

Can a solution be that "Page" becomes a name and we change the text to: `New "Page" object`. Then new would refer to object and hopefully have its genus.

**Comment by wasertech** [comment]
> I see no way, however, of predicting the genus of the %(object)s. It can be pages, aliases, blog posts, html snippets or whatever in future.

Exactly!

> we change the text to: `New "Page" object`

It would be easier but it's not really elegant: "Nouvel objet page" (if you notice we would have the same issue here since object starts with an "o", it's not "nouveau" but "nouvel" in this case - Yes french is annoying -).

My solution would require changing the code so to have a new translatable sentence for the action to create the object.

So instead of using "New" and `%(object)s` to make the button text, we would have to make a new sentence to create the object for every class.

I know it's much less easier to implement but I feel it's the correct way to deal with such cases in the long run.

**Comment by wasertech** [comment]
This:
https://github.com/django-cms/django-cms/blob/9e33167701b65ce4fb7675d61e452e62792556e3/cms/templates/admin/cms/page/tree/base.html#L137-L144

Into something like:
```html
{# INFO: "new page" button #} 
{% if has_add_permission %} 
    <a href="{% url opts|admin_urlname:'add' %}" class="cms-pagetree-header-create cms-btn cms-btn-toolbar cms-btn-action"> 
        {% blocktrans with opts.verbose_create_name|title as create_name %} 
            {{ create_name }} 
        {% endblocktrans %} 
    </a> 
{% endif %} 
```

It would require to explicitly declare `verbose_create_name`...

**Comment by fsbraun** [comment]
Since the snippet comes from the page tree we might need to think of dropping the general strings idea here and actually hard-code "New page" into the translations. This does not solve Django's general problem with verbose names of model objects (which only have singular or plural, no genus or case).

**Comment by wasertech** [comment]
> Since the snippet comes from the page tree we might need to think of dropping the general strings idea here and actually hard-code "New page" into the translations.

Even easier then.

> This does not solve Django's general problem with verbose names of model objects (which only have singular or plural, no genus or case).

No and for that I really have no solution but I think that's a ticket for Django to figure out :P

**Comment by fsbraun** [comment]
I just checked: The new page issue is already fixed in django CMS version 4.x
