### ISSUE TITLE
[BUG] __version__ is not found in cms namespace 

### ISSUE THREAD

**Issue by robomike** [django-cms/django-cms#7516]
/lib/python3.9/site-packages/cms/utils/conf.py", line 9, in <module>
    from cms import __version__, constants
ImportError: cannot import name '__version__' from 'cms'

Django 4.1.7
django-cms 3.11.1

in the IDE when performing the 
import cms
__version__ doesn't appear in cms.

How do we resolve this issue?

**Comment by robomike** [comment]
For some reason, this file was blank upon PiP install:

https://github.com/django-cms/django-cms/blob/6443da8d2f34cc936df011ef858243356e92d036/cms/__init__.py

**Comment by fsbraun** [comment]
This file should not be empty! Did you try reinstalling using `pip`. I just double-checked and it worked...
