### ISSUE TITLE
[BUG]action menu stops working

### ISSUE THREAD

**Issue by supsucc** [django-cms/django-cms#7531]
## Description

new installed 3.11.2 when new page created, hover to right side action menu there are items like copy, cut, paste, delete and advanced settings this menu stops works

## Screenshots
![image](https://user-images.githubusercontent.com/25978824/233683380-ee6f2c48-2f6f-4fa8-994e-b9ec5402dc74.png)

## Additional information (CMS/Python/Django versions)
**cms 3.11.2, django 4.2 pytho3.8.10 django 4.2**

## Do you want to help fix this issue?

* [x] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome.

**Comment by supsucc** [comment]
This bug in actions_driopdown.html line 108, doubled {{ for {%

**Comment by fsbraun** [comment]
@supsucc Thank you so much for reporting this so promptly! 

Your analysis is correct: There is a typo that prevents the content of the action menu to be rendered. It has been fixed here: #7529 . If you install the current development version it should work: `pip install git+https://github.com/django-cms/django-cms@develop`.

**Comment by supsucc** [comment]
@fsbraun thank you for the effort, I am new to django and django cms, have a long journey to learn
