### ISSUE TITLE
[ENHANCEMENT] Add user to choose in toolbar auto/light/dark

### ISSUE THREAD

**Issue by svandeneertwegh** [django-cms/django-cms#7555]
Now i have set:
```
CMS_COLOR_SCHEME = "auto"

CMS_COLOR_SCHEME_TOGGLE = True
```

I'd like to give the logged in user the choice to set it on auto or fixed dark/light mode.
Now with the TOGGLE setting to True it shows in toolbar options light/dark.
I would like to add auto to it.

## Steps to reproduce
Django==3.2.18
Django-cms==3.11.3

## Screenshots

<img width="406" alt="Schermafbeelding 2023-05-11 om 22 33 00" src="https://github.com/django-cms/django-cms/assets/34129243/3b5c9fae-0cc2-4f02-9311-86763eb87f35">

## Do you want to help fix this issue?

* [x] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. 
* [ ] No, I only want to report the issue.

**Comment by fsbraun** [comment]
#7549 did add the auto option to the toggle. I am not sure whether it also covered fixing the color scheme with `CMS_COLOR_SCHEME = "auto"`.

**Comment by fsbraun** [comment]
Fixed with #7556 and #7549
