### ISSUE TITLE
[BUG] Cannot disable/unpublish/hide a page, when not using djangocms-versioning

### ISSUE THREAD

**Issue by benzkji** [django-cms/django-cms#7567]
## Description

I cannot hide/unpublish/disable a page, when not using djangocms-versioning. Hide means to me: external visitors will get a 404. So, hide from menu is not an option.

## Steps to reproduce

- install django-cms
- create a page
- it's status icon is green, it is immediatly public

## Expected behaviour

Pages should have a published/not published state, this has nothing to do with versioning. I was looking forward to 
use the cms without versioning, for simple sites. But without disabled pages, this is more or less unusable IMHO.

## Actual behaviour

I cannot see a way to hide/disable a page?

## Additional information (CMS/Python/Django versions)

- cms 4.1rc3
- django 4.2

## Do you want to help fix this issue?

* [ ] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. 
* [x] No, I only want to report the issue.

**Comment by fsbraun** [comment]
Hi @benzkji ! That's exactly correct. Up to version 4 versioning was built into the core in a particularly opinionated way. As of version 4 versioning is a separate package which you can (I'd argue: should) use:
* It is more powerful (full history, archive, ...)
* It can share the versioning capabilities to all models which intend to use it, such as blog posts, ...
* You could actually change it (if you care to) to a method more suitable for you.

Using django-cms 4 without any versioning in my opinion is no real-life option.
