### ISSUE TITLE
[BUG] The force_text function has been removed in Django 3.1 and later versions, but it is used in django-cms-4.1.0rc3

### ISSUE THREAD

**Issue by MShirazAhmad** [django-cms/django-cms#7582]
in django-cms-4.1.0rc3, the following import is used:
from django.utils.encoding import force_text
I am using Django 4.1.9, which now use force_str instead of force_text

on https://pypi.org/project/django-cms/4.1.0rc3/#description it says django-cms-4.1.0rc3 support Django 4.1.9, but in actual django-cms-4.1.0rc3 has dependencies on force_text

**Comment by fsbraun** [comment]
@MShirazAhmad Thanks for reporting this. Can you point me to the place where you've found `force_text`?

**Comment by MShirazAhmad** [comment]
Paths:
- venv/lib/python3.9/site-packages/cms/static/cms/js/dist/3.11.3/bundle.admin.pagetree.min.js
- venv/lib/python3.9/site-packages/cms/static/cms/js/libs/jstree/jstree.min.js

I installed cms through 
`pip install django-cms`

**Comment by fsbraun** [comment]
Correct. Those are compiled JavaScript files which are independent of the Python-Django machine. In particular, they do not import anything from Django. These occurrences of `force_text` are the result of the JavaScript babel and webpack build process.
