### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jrief** [django-cms/django-cms#7588]
## Description

`cms.admin.ContentForm` overwrites attributes of slug widget.

## Steps to reproduce

When setting the attributes of a slug widgets, these attributes are overwritten in
https://github.com/django-cms/django-cms/blob/3e3a86b4f09c021bb4548add090f441b300a4a9e/cms/admin/forms.py#L222
This is unexpected behavior.

## Additional information (CMS/Python/Django versions)

Branch `develop-4`. Latest commit hash: 52e6f8751e2d28db7c2abb6bdbbbc9c9909ba03d
All Django/Python versions.

## Do you want to help fix this issue?

I have a patch. PR upcoming.

* [x] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. 
* [ ] No, I only want to report the issue.

**Comment by fsbraun** [comment]
@jrief Can we close this?
