### ISSUE TITLE
[BUG] Fix release v3.8.1 does not ship css assets in the right path

### ISSUE THREAD

**Issue by sveetch** [django-cms/django-cms#7592]
## Description

Release v3.8.1 seems to have been done without to rename asset paths in static directory.

Digging into the static file tree i've seen all path with release version are still in 3.8.0:

https://github.com/django-cms/django-cms/tree/3.8.1/cms/static/cms

## Steps to reproduce

1. Install DjangoCMS==3.8.1
2. Run server
4. Almost all static assets are resulting to a 404 since the expected paths should include 3.8.1

## Expected behaviour

All directory named after release should follows the current release version.

## Actual behaviour

Packaged static have a directory named 3.8.0 instead of expected 3.8.1

## Do you want to help fix this issue?

* [ ] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. 
* [x] No, I only want to report the issue.

I'm not very confident with the asset management in this project, i imagine their path is not hand crafted, it's probably built from an asset builder. Also i don't know if there is some versionning  inside the asset that would need some changes also.

**Comment by fsbraun** [comment]
@sveetch Thank you for reporting this. What an obvious mistake. 

Can you please check that installing from 

`pip install git+https://github.com/fsbraun/django-cms@release/3.8.x#egg=django-cms==3.8.2`

works?

**Comment by fsbraun** [comment]
You could load assets, right? Then I'll release this as 3.8.2

**Comment by sveetch** [comment]
@fsbraun sorry i missed your reply, yes i've tested it on a real project and logged in as an admin, and tried some page in edition mode. All versionned ressources url from cms admin are properly tagged with 3.8.2

**Comment by vinitkumar** [comment]
@sveetch Any reasons not to switch to the latest 3.11.x release? It contains many bugfixes and is the recommended update.

**Comment by sveetch** [comment]
@vinitkumar Old projects that customers did not agree to pay for periodical maintenance and upgrade

**Comment by vinitkumar** [comment]
> @vinitkumar Old projects that customers did not agree to pay for periodical maintenance and upgrade

Okay, that's good as reason as any. Except in the future, the cost of keeping that branch up to date becomes more than spending time to upgrade. But yeah, you do as you see fit.

**Comment by sveetch** [comment]
I totally agree, it is just than the 3.8.1 included a regression and broken so many pipeline, we started to downgrade/pin to 3.8.0 but the bug deserved an issue for history

**Comment by fsbraun** [comment]
I take credit for that bug. The only change is that the django-treebeard is pinned to a version compatible with 3.8
