### ISSUE TITLE
[BUG] InvalidCacheKey (memcached) with Key-length ~249

### ISSUE THREAD

**Issue by wfehr** [django-cms/django-cms#7595]
Recently came across this: When the internal CMS-cache-key for placeholders has a length of 249, an `InvalidCacheKey` error is raised.
I used `memcached` for the backend.

Reason:
- CMS hashed `length > 250`: [cms.cache.placeholder.py#L130](https://github.com/django-cms/django-cms/blob/3.11.1/cms/cache/placeholder.py#L130)
- django adds "version" itself: [django.core.cache.backends.base.py#L119](https://github.com/django/django/blob/main/django/core/cache/backends/base.py#L119)
 - this will be called through `cache.set(..)`

So if the key is 249 characters long, the cms-hashing won't be called (due to `if len(cache_key) > 250`) and `django` adds `:1` (or sth like that) which results in `> 250` characters leading to `InvalidCacheKey`-error.

Even if you would set `cache.set(key, value, version="")`, django would still add `: ` to it which results in same error when the "plain cms-cache-key" is exactly 250 characters long.

## Additional information (CMS/Python/Django versions)

- cms: 3.11.1
- django: 3.2.18
- python: 3.11

## Do you want to help fix this issue?

* [ ] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. 
* [x] No, I only want to report the issue.

**Comment by fsbraun** [comment]
@wfehr Can I interest you in creating a PR? The solution might be fairly simple. Since we do not know what future versions of Django will add to the cache key, I'd suggest always using a fast hash digest, something like 

```
   # No if len(cache_key) ...
   cache_key = '{prefix}|{hash}'.format(
        prefix=prefix,
        hash=hashlib.md5(cache_key.encode('utf-8')).hexdigest(),
    )
```

in https://github.com/django-cms/django-cms/blob/3.11.1/cms/cache/placeholder.py#L130. 

What do you think? Wouldn't it be great if you contributed the patch after having figured out the bug? 😎

**Comment by wfehr** [comment]
> @wfehr Can I interest you in creating a PR? The solution might be fairly simple. Since we do not know what future versions of Django will add to the cache key, I'd suggest always using a fast hash digest, something like
>  ...
> What do you think? Wouldn't it be great if you contributed the patch after having figured out the bug? 😎

Done -> #7657
