### ISSUE TITLE
[BUG] "Delete page translation" delete the wrong translation

### ISSUE THREAD

**Issue by adrien-delhorme** [django-cms/django-cms#7605]
## Description

On a page with two translations (for example: English and French) the CMS toolbar menu "Delete translation" does not always delete the selected translation (depending on query parameter `language` present in URL).

## Steps to reproduce

1. Go to CMS toolbar "\<Name of your site\>", then "Pages..."
2. Click on the 👁️ icon on a page with two translations (for example: English and French)
3. You are now on `https://your-domain.tdl/a-page-with-two-translations/?edit&language=en`
4. Go to "Language" menu on CMS toolbar, then "Delete translation", then choose "French..."

## Expected behaviour

A modal appears, asking a confirmation to delete **French** translation.

## Actual behaviour

A modal appears, asking a confirmation to delete **English** translation.

## Additional information (CMS/Python/Django versions)

- Django 3.2
- django-cms 3.11.3

## Do you want to help fix this issue?

* [ ] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. 
* [x] Sorry, I'm really short of time to work on this 😞 .

**Comment by adrien-delhorme** [comment]
This issue still exists.

**Comment by halitcelik** [comment]
I can confirm the bug.
Here are my observations:
When the user clicks on the `Delete translation > English` button while the page url contains `language=fr` a request is sent to the following URL: `http://127.0.0.1:8000/en/admin/cms/page/1/delete-translation/?language=fr&language=en&cms_path=/en/?edit` (language parameter is added twice)
Then in the view [here](https://github.com/django-cms/django-cms/blob/develop/cms/admin/pageadmin.py#L1235-L1237) we have `language` parameter in the request as a list ( ["fr", "en"] and `request.GET["language"]` is "en" which is wrong.
I think we need to change the parameter name to something else then "language" for the "Desired language to delete the translation for" and keep the "Actual page editing language" as "language". I hope it is clear enough. 
I can try to create a PR for this.
