### ISSUE TITLE
[BUG] Broken static bundle in 4.1.0rc3

### ISSUE THREAD

**Issue by stefanw** [django-cms/django-cms#7626]
## Description

It looks like the static bundle for 4.1.0rc3 is broken or incomplete. I noticed that the dark mode toggle in 4.1.0rc3 was no longer working.

Searching for "color-toggle" in the bundle versions:

- present in [3.11.3](https://raw.githubusercontent.com/django-cms/django-cms/develop/cms/static/cms/js/dist/3.11.3/bundle.toolbar.min.js)
- *not* present in [4.1.0rc3](https://raw.githubusercontent.com/django-cms/django-cms/develop-4/cms/static/cms/js/dist/4.1.0rc3/bundle.toolbar.min.js)

Rebuilding the bundle on `develop-4` fixes the color mode.

**Note**: To rebuild on current `develop-4` I had to fix [this line](https://github.com/django-cms/django-cms/blob/d71555aa8ec1b198159b1da8efd214096d0cdfbf/cms/static/cms/sass/components/_modal.scss#L226) where a SASS `darken` call is made on a CSS custom property (`var(--dca-primary`) which doesn't work and breaks `gulp sass`.

## Steps to reproduce

1. Install Django CMS 4.1.0rc3 
2. Notice dark mode not working

## Expected behaviour

Dark mode is working like in 3.11.

## Actual behaviour

Toolbar icon for dark mode toggle is added but without an icon, clicking it in the toolbar does nothing.

## Additional information (CMS/Python/Django versions)

Python 3.10 / Django 4.2.4

## Do you want to help fix this issue?

No, but I would appreciate a new RC release with a fixed build.

**Comment by fsbraun** [comment]
@stefanw Thanks for pointing this out!

The static bundle for 4.1.0rc3 is fine. Dark mode has been added _after_ the release rc3. rc4 is on its way and will include dark mode and bug fixes.

Dark mode will be changing in 3.11 and 4.1 to reflect the behaviour of Django 4.2's admin dark mode toggle.

The sass failure apparently appeared when conflicts between two PR were not correctly resolved. Frontend tests now also run the `gulp sass` command to ensure the css is building correctly.

**Comment by stefanw** [comment]
Thanks for letting me know and thanks for your work!
