### ISSUE TITLE
[BUG] Resolving class-based view func

### ISSUE THREAD

**Issue by Will-Hoey** [django-cms/django-cms#7653]
## Description

Django 4.1 updated the `__name__` attribute for CBVs and now always returns `view` (As was referenced here https://github.com/django-cms/django-cms/pull/7404). I have a toolbar extension which attempts to reverse a path and retrieve the model from the CBV, which looks like
```
    def get_view_class(self):
        """
        Returns the view class/function associated with the current request.
        """
        resolver = resolve(self.request.path)
        view_func = resolver._func_path
        view = import_string(view_func)
        return view, resolver
```

NOTE: I reference CBV's mostly here but the same applies to FBV's.

## Steps to reproduce

1. Set up any ListView/DetailView at a given path
2. Use `django.urls.resolve` on this path
3. Note the `func` in the resolver won't include the actual CBV name

## Expected behaviour
The resolver should return the name of the CBV
```
>>> resolve("/events/")
ResolverMatch(func=events.views.EventListView, args=(), kwargs={}, url_name='index', app_names=['events'], namespaces=['events'], route='^events/\\Z')
```

## Actual behaviour
The resolver returns `appname.module_name.view`
```
>>> resolve("/events/")
ResolverMatch(func=events.views.view, args=(), kwargs={}, url_name='index', app_names=['events'], namespaces=['events'], route='^events/\\Z')
```

## Screenshots

![image](https://github.com/django-cms/django-cms/assets/48737592/43d39ac4-6979-48b1-b334-85f51fa094e0)

## Additional information (CMS/Python/Django versions)

Anything above django 4.1 after the change was introduced.
Django-cms = 3.11.4
Python 3.11

Currently I have monkeypatched https://github.com/django-cms/django-cms/blob/develop/cms/utils/decorators.py#L23 to include 
```
        if hasattr(func, "view_class"):
            inner.view_class = func.view_class
```
Which resolves the issue. Happy to pop that in a PR :)

## Do you want to help fix this issue?

* [ ] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. 
* [ ] No, I only want to report the issue.

**Comment by fsbraun** [comment]
@Will-Hoey Good catch! I'd greatly appreciate a PR! Can you also add a quick regression test (only to be run for Django>=4.1)?

**Comment by Will-Hoey** [comment]
> @Will-Hoey Good catch! I'd greatly appreciate a PR! Can you also add a quick regression test (only to be run for Django>=4.1)? A FBV's view function should be passed correctly, or did I miss something?

@fsbraun Of course.

My mistake on the FBVs. They are working fine with/without the monkeypatch.

**Comment by Will-Hoey** [comment]
@fsbraun I may be missing something here regarding the testing with versions, but there was a test added here https://github.com/django-cms/django-cms/blob/develop/cms/tests/test_apphooks.py#L310 which currently checks for "view". Do we want to update this test to just have
```        
        view_names = (
            ('sample-settings', 'sample_view'),
            ('sample-class-view', 'ClassView'),
            ('sample-class-based-view', 'ClassBasedView' ),
        )
```
Or keep the if statement in
