### ISSUE TITLE
[BUG] CMS4: Toolbar -> Page -> Template (invalid reset)

### ISSUE THREAD

**Issue by jrief** [django-cms/django-cms#7665]
## Description

This error occurs in CMS4.

The Template settings in the Toolbar resets itself spookily.

## Steps to reproduce

* Edit a page
* Toolbar -> Page -> Templates -> Select non-default template
* Toolbar -> Page -> Templates -> Check selected template, remains as selected
* (Do not publish page)
* Toolbar -> Open Structure Menu
* Toolbar -> Page -> Templates -> Check selected template, selected template changed spookily

## Expected behaviour

Well, that operation should be idempotent.

## Additional information (CMS/Python/Django versions)

Branch `releases/4.1.x` commit 121acf1cc1cc82cbdb7fc94cab31db466c3c9bc8

## Do you want to help fix this issue?

* [x] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. 
* [ ] No, I only want to report the issue.

**Comment by fsbraun** [comment]
I can confirm that the template dropdown shows the wrong template highlighted.

I cannot, however, confirm that the template actually has changed. @jrief Do you see a wrong template being displayed or just a wrong menu item highlighted?

Needs a patch in any case: I guess the wrong template is highlighted when the toolbar is reloaded upon opening the structure board.

**Comment by jrief** [comment]
> I cannot, however, confirm that the template actually has changed. @jrief Do you see a wrong template being displayed or just a wrong menu item highlighted?

No, the proper (selected) is used to render the page.

**Comment by fsbraun** [comment]
Solved in #7671
