### ISSUE TITLE
[BUG] Adding a new page via CMS wizard does not start in "edit" mode.

### ISSUE THREAD

**Issue by sparrowme** [django-cms/django-cms#7688]
## Description
Adding a new page via CMS wizard does not bring up the new page in "edit" mode.  It appears to be in preview mode.

## Steps to reproduce
Following the quick-start guide 
* Install / start new container
* Add the first new page 
* Click Save
* Page is in Preview mode.
* You now have to click [Edit] in order click Publish per the quick-start guide.

## Expected behaviour

User should land an their newly created page in Edit mode so they can Publish after saving from the modal dialog.
## Additional information (CMS/Python/Django versions)

CMS 4.1rc4

## Do you want to help fix this issue?

* [x] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. 
* [ ] No, I only want to report the issue.

**Comment by fsbraun** [comment]
@sparrowme Thanks for pointing this out! Can I interest you in creating a PR for this? You might want to have a look at line 147 of 

https://github.com/django-cms/django-cms/blob/5b592b96fe95a292c2b38ead4f1b54051811b538/cms/wizards/wizard_base.py#L128-L152

**Comment by sakhawy** [comment]
I was just thinking of this behavior and found this issue. I would like to work on it if nobody else is.

**Comment by fsbraun** [comment]
@sakhawy I would love it!
