### ISSUE TITLE
[BUG] ?edit does not show the toolbar login in 4.1rc4

### ISSUE THREAD

**Issue by benzkji** [django-cms/django-cms#7693]
## Description

I can only login with /admin/, adding ?edit to any url does not bring up to cms toolbar with login form.

## Steps to reproduce

add ?edit to any cms url.

## Expected behaviour

Toolbar with login form shown.

## Actual behaviour

Nothing.

## Additional information (CMS/Python/Django versions)

cms 4.1rc4

## Do you want to help fix this issue?

* [ ] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. 
* [x] No, I only want to report the issue.

**Comment by fsbraun** [comment]
@benzkji The toolbar appears with `?toolbar_on` as of version 4.

**Comment by benzkji** [comment]
THX!

So we teached our clients to use ?edit for ages...and...suddenly...they have to learn the underscore? Why change something so short and easy to understand? I vote to make it configurable! 

Or are there reasons I don't see?

**Comment by benzkji** [comment]
ha, it already is, right?
`CMS_TOOLBAR_URL__ENABLE`

**Comment by fsbraun** [comment]
It is. The reason is that the edit endpoint is **not** reached by logging in through the toolbar - unlike in v3.

**Comment by benzkji** [comment]
makes sense. thanks. I'll probably change it to "?login" then ;-)
