### ISSUE TITLE
[DOC] CMS_CACHE_PREFIX default value incorrect

### ISSUE THREAD

**Issue by DmytroLitvinov** [django-cms/django-cms#7700]
## Description

Documention is wrong about default value for `CMS_CACHE_PREFIX`.

Default value is: `f'cms_{__version__}_'` - [more details](https://github.com/django-cms/django-cms/blob/239dbf5d995bf3275db1dffe9eb55649e2a4a84a/cms/utils/conf.py#L61)

And in docs it says that the value is `cms-` - [more details](https://github.com/django-cms/django-cms/blob/239dbf5d995bf3275db1dffe9eb55649e2a4a84a/docs/reference/configuration.rst#cms_cache_prefix)

## Screenshots

<img width="971" alt="image" src="https://github.com/django-cms/django-cms/assets/16066485/90c02e47-815b-4520-a8fb-673638c12b69">

<img width="803" alt="image" src="https://github.com/django-cms/django-cms/assets/16066485/d06dd8a1-2179-4cd4-ac2b-183bb6bf8e59">

## Do you want to help fix this documentation issue?

* [X] Yes, I want to help fix this issue and I will join #workgroup-documentation on [Slack](https://www.django-cms.org/slack) to confirm with the team that a PR is welcome. 
* [ ] No, I only want to report the issue.

**Comment by fsbraun** [comment]
@DmytroLitvinov Good catch! Would you create a PR?

**Comment by DmytroLitvinov** [comment]
PR with fix was merged 2 weeks ago so we can close the issue.
