### ISSUE TITLE
Static placeholders are not being shown in the structure sidebar.

### ISSUE THREAD

**Issue by adlh** [django-cms/django-cms#7723]
## Description

I created the project from scratch from the instructions here: 
https://django-cms-docs.readthedocs.io/en/staging/introduction/01-install.html#install-django-cms-by-hand

And added some markup with normal placeholders and a placeholder in the footer.

When I open the sidebar on the right with the page structure, the normal placeholders are shown as expected but the static placeholders aren't.

After trying to find the root of the problem I can at least confirm, that the model instances for StaticPlaceholders are being correctly detected and automatically created for any static_placeholder items I have on the template(s), but they never get rendered in the sidebar, so it's not possible to add content to them.

**DISCLAIMER**: I know, there's already an eventually duplicate issue (#6570) open for version 3.5.3, but, because after trying to debug and find the cause of the problem and while comparing things with an older django cms 3.x project (where this is still working), it seems there are several differences on how static-placeholders are being collected/rendered on 4.x so I thought it might be better to open a new issue for this.

## Steps to reproduce

1. Create a new project as described in https://django-cms-docs.readthedocs.io/en/staging/introduction/01-install.html#install-django-cms-by-hand
2. If you created the `home.html` template as in the instructions, add a static-placeholder to it:
```html
{% load cms_tags sekizai_tags %}
<html>
    <head>
        <title>{% page_attribute "page_title" %}</title>
        {% render_block "css" %}
    </head>
    <body>
        {% cms_toolbar %}
        {% placeholder "content" %}
        <footer>
            <p>This is the footer</p>
            {% static_placeholder "footer" %}
        </footer>
        {% render_block "js" %}
    </body>
</html>
```
3. Create a new page and then click on edit on the top (if not already done that).
4. Open the structure sidebar.
5. The 'content' placeholder is shown, but the 'footer' placeholder is not there.

## Expected behaviour

In the structure sidebar there should be a 'footer' static placeholder below the 'content' placeholder.

## Actual behaviour

The static placeholder is missing.

## Screenshots
![Screenshot from 2023-12-20 13-21-51](https://github.com/django-cms/django-cms/assets/248528/44227a17-c501-4e68-a882-82ce07dca377)

## Additional information (CMS/Python/Django versions)
```
$ python --version
Python 3.10.12

$ pip freeze | grep cms
django-cms==4.1.0rc5
djangocms-admin-style==3.2.6
djangocms-alias==2.0.0rc2
djangocms-attributes-field==3.0.0
djangocms-frontend==1.2.0
djangocms-text-ckeditor==5.1.5
djangocms-versioning==2.0.0rc1
```

## Do you want to help fix this issue?

* [X ] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. 
* [ ] No, I only want to report the issue.

**Comment by fsbraun** [comment]
Static placeholders are not supported by django CMS 4. They are replaced by aliases which have their own versioning history. When installing as described, you will have djangocms-alias available. Use the alias plugin or its `{% static_alias %}` template tag (see [here](https://github.com/django-cms/djangocms-alias)).

Aliases can be versioned independently from static placeholders.

**Comment by adlh** [comment]
@fsbraun Ohh, sorry for the confusion, I tried to find more information on the docs and missed that part, that static placeholders were replaced by aliases.
