### ISSUE TITLE
[DOC] Frontend tests documentation is outdated

### ISSUE THREAD

**Issue by protoroto** [django-cms/django-cms#7725]
## Description

Frontend tests documentation states that Node 6 is needed to run tests, but `npm install` fails on Node 6. As CI tests are running with Node 18, maybe it could be a good idea to edit documentation and change correct Node version.

Also, it looks like that the command to run unit tests is outdated too (unit tests are run with `gulp unitTest` now), and no integration tests are run anymore. Should we change that too?

## Do you want to help fix this documentation issue?

* [x] Yes, I want to help fix this issue and I will join #workgroup-documentation on [Slack](https://www.django-cms.org/slack) to confirm with the team that a PR is welcome. 
* [ ] No, I only want to report the issue.

**Comment by fsbraun** [comment]
An update would be wonderful!

**Comment by protoroto** [comment]
@fsbraun Closing this as docs are updated now :) Thanks!
