### ISSUE TITLE
[DOC] command line for setup virtual environment is wrong in the 4.1 documentation

### ISSUE THREAD

**Issue by TLuesebrinck** [django-cms/django-cms#7733]
python3 -m .venv  # create a virtualenv

correct is:
python3 -m venv .venv  # create a virtualenv

**Comment by fsbraun** [comment]
@TLuesebrinck Well spotted! Can I ask you to create a PR against the `release/4.1.x` branch?

**Comment by TLuesebrinck** [comment]
Sorry, I'm not that familiar with github. I checked the PR option ,but I do not know what I have to do in detail.


________________________________
Von: Fabian Braun ***@***.***>
Gesendet: Mittwoch, 3. Januar 2024 22:45
An: django-cms/django-cms ***@***.***>
Cc: TLuesebrinck ***@***.***>; Mention ***@***.***>
Betreff: Re: [django-cms/django-cms] [DOC] command line for setup virtual environment is wrong in the 4.1 documentation (Issue #7733)


@TLuesebrinck<https://github.com/TLuesebrinck> Well spotted! Can I ask you to create a PR against the release/4.1.x branch?

**Comment by fsbraun** [comment]
No worries, I can do it for you.

**Comment by fsbraun** [comment]
Fixed in #7735
