### ISSUE TITLE
[DOC] How to use placeholders outside the CMS needs update for django CMS 4

### ISSUE THREAD

**Issue by fsbraun** [django-cms/django-cms#7736]
## Description

This piece of documentation needs to add information on how to register the model for frontend editing and adding the `get_template` method to the model.

## Reference

* #7712 
* https://docs.django-cms.org/en/latest/how_to/01-placeholders.html#placeholders-outside-cms

## Do you want to help fix this documentation issue?

* [ ] Yes, I want to help fix this issue and I will join #workgroup-documentation on [Slack](https://www.django-cms.org/slack) to confirm with the team that a PR is welcome. 
* [ ] No, I only want to report the issue.

**Comment by fsbraun** [comment]
Additional steps necessary to make a model frontend-editable:

* Declaration of the model as frontend-editable in `cms_config.py`
* Adding a `get_template()` method to the model
* Adding a structure mode template for identifying the placeholders (`{% load cms_tags %}{% placeholder "xyz" %}`)
* Adding a rendering method for the preview and edit endpoints (`def render_model(request, instance)`)
* Finally, to make the Preview and Edit buttons appear on the published URL: Add the product instance to the toolbar in the model's view

**Comment by makjaveli** [comment]
> Additional steps necessary to make a model frontend-editable:

Thank you so much!

With your changes the render placeholder test app is now working:
https://github.com/makjaveli/djangocms_apphook_renderplaceholder

To keep the placeholder tags and the actual rendering in separate template htmls is ok for us, making this required step makes it a bit more obvious. For better clarity would it not be better to declare the placeholder slots more explicit in the model itself (as with CMS version 3)?

To be honest with the current state (5th January 2024) of the documentation some of the steps are not identifiable and differ from the CMS 3 version. This changes were a show stopper for upgrading to CMS 4 for a larger update of our existing Django CMS app. 

Thank you so much for your help!

**Comment by fsbraun** [comment]
Yeah, this needs to be made explicit.

One of the positive aspects of the django CMS 4 structure is that you can now also have your templates define the placeholders (no need for them to be in the model) just as with placeholders on pages. **Maybe a nice extension might be to have a default implementation of `get_template` that actually just returns the declared slots in the model.**

**Comment by makjaveli** [comment]
Good idea! This would indeed be more convenient to make the get_template() implementation optional as it currently seems only required to extract the slot names from the html file?

I also not fully understand the requirement to change or to remove the placeholder_field syntax. Is it to declare the model placeholder getter methods as @cached_property?

Another inconvenience is that currently there seems to be two view methods required one for the actual view (with some sort of request parameter with object id) and one for rendering in the cms editing view without a object id in the url. I see the technical challenge, but it would be much easier to have the same view method for editing and viewing.

**Comment by fsbraun** [comment]
@makjaveli I have tried to quickly update the docs in this PR: #7742 . I'd appreciate any feedback you have for the documentation update. 

Maybe in a second step we can simplify the process as discussed above.

**Comment by fsbraun** [comment]
The reason for moving from `PlaceholderField` to `PlaceholderRelationField` is that now the placeholder contains a generic foreign key to the model. The cached properties simulate the reverse relation. (This is the correct way to model placeholders, since the model to placeholder slot relation is 1:n and not n:1.)
