### ISSUE TITLE
[BUG] Dark mode makes the pop-up messages from the admin interface unreadable.

### ISSUE THREAD

**Issue by TLuesebrinck** [django-cms/django-cms#7738]
When the Django-CMS admin run in dark mode, the pop messages are unreadable. The text is dark on a dark background.  I also think they should not disappear so fast. In case of an error, you have not enough time to read it.

![image](https://github.com/django-cms/django-cms/assets/16904477/cf25bd3a-9cc1-46b3-86aa-87af06834a62)

**Comment by fsbraun** [comment]
Fixed in #7739 and #7740
