### ISSUE TITLE
[BUG] Deleting a page sometimes impossible in languages other than English

### ISSUE THREAD

**Issue by jrief** [django-cms/django-cms#7745]
## Description

Deleting a page sometimes is impossible in languages other than English.

## Steps to reproduce

Setup Django-CMS with multiple languages.
Choose a language other than English.
Delete a page containing content, ie. filled placeholders.

* [x] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. 
* [ ] No, I only want to report the issue.

**Comment by fsbraun** [comment]
Fixed in #7745
