### ISSUE TITLE
error install djangocms-blog

### ISSUE THREAD

**Issue by pooria-ghorbani** [django-cms/django-cms#7762]
when install djangocms-blog - run migrate , return this error : 
`
django.db.utils.ProgrammingError: relation "djangocms_blog_blogconfig" does not exist
LINE 1: ...ace", "djangocms_blog_blogconfig"."app_data" FROM "djangocms...
`
* Python version: 3.8
* Django version: 5 
* django CMS version: 4.1

**Comment by fsbraun** [comment]
As of now, the current djangocms-blog 2.x is **incompatible** with django-cms 4.x. You can either
* Use django-cms 3.11 (the long-term-support version) with Django 4.2 
* Or use the experimental fork of djangocms-blog for django-cms 4.x at https://github.com/fsbraun/djangocms-blog@develop-4 

As a side note: Django 5.0 requires Python 3.10 or later.

**Comment by pooria-ghorbani** [comment]
ok thanks
