### ISSUE TITLE
[BUG] toolbar.obj is not set correctly in edit view when apphook landing page is a CMS page

### ISSUE THREAD

**Issue by Chilipp** [django-cms/django-cms#7765]
### Summary

consider a an apphook that does not define a landing page (i.e. at location `""`), then this page is filled by the CMS with a standard `cms.Page`. but it seems like, this page is getting uneditable.

### Expected behaviour

It should be possible to edit the page that holds the apphook

### Actual behaviour

When one creates a new draft, the toolbar is filled with the _published_ content object, not with the _draft_ content object. therefore all the links in the toolbar are not working because one is redirected to the _structure_ mode of the published content object (that is of course not editable anymore), and not to the real one. The reason is that we loose the `object_id` when the `view_func` is called in `cms.views.render_object_endpoint`

https://github.com/django-cms/django-cms/blob/c20b042edd717d46c585583010aef2c4ca395c5d/cms/views.py#L282-L294

for a page with an apphook that does not define a view at location `""`, this `view_func` resolves to the `cms.views.details` view. and `cms.views.details` uses the standard `page.get_content_obj` that always resolves to the _published_ page content

https://github.com/django-cms/django-cms/blob/c20b042edd717d46c585583010aef2c4ca395c5d/cms/views.py#L214

therefore the `toolbar` gets the wrong `obj` and generates the wrong urls

### Environment

* Python version: 3.11.4
* Django version: 3.2.23
* django CMS version: 4.1.0

**Comment by fsbraun** [comment]
@Chilipp Thanks for bringing this to attention.

Looks like `view_func` should only be called if it is different from `cms.views.details`, i.e. the apphook does not capture the page's URL. 

Can I encourage you to try out this:
```
...
view_func, args, kwargs = resolve(absolute_url) 
if view_func is not cms.views.detail:
     return view_func(request, *args, **kwargs) 
...
```

If this should work, I would be delighted if you could come up with a pull request, including a simple test?

**Comment by Chilipp** [comment]
Sure @fsbraun :smiley: thanks for the quick reply! Give me two to three hours and I have time to do so
