### ISSUE TITLE
[BUG] The sign up page https://www.django-cms.org/en/sign-up-work-contribution/  doesn't get pass the catchup

### ISSUE THREAD

**Issue by nzprog** [django-cms/django-cms#7773]
## Description
When attempting to sign up,  the sign up page displays a catchup but it's blank.  

## Steps to reproduce
fill in the form and click submit.

## Expected behaviour
something will happen.

## Actual behaviour
The catchup pops up but i assume there is suppose to be a tick box.

## Screenshots
![Untitled](https://github.com/django-cms/django-cms/assets/6001901/41017e18-b50c-4a06-9443-972183155879)

## Additional information (CMS/Python/Django versions)
Django Website   https://www.django-cms.org/en/sign-up-work-contribution/

## Do you want to help fix this issue?

* [ ] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. 
* [ X ] No, I only want to report the issue.

**Comment by fsbraun** [comment]
@nzprog Hm. I just tried and it worked for me. Can I invite you our Slack channel? I think it's the most direct way to become a contributor. Here's the link: https://www.django-cms.org/slack

**Comment by vinitkumar** [comment]
@fsbraun Since this link(https://www.django-cms.org/en/sign-up-work-contribution/) is not active anymore, we can safely close the ticket.
