### ISSUE TITLE
[BUG] 404 page not found error without a trailing slash for "/en" and "/en/admin" URLs.

### ISSUE THREAD

**Issue by erkesado** [django-cms/django-cms#7782]
## Description
Even though `/en/` and `/en/admin/` URLs work normally with a trailing slash, they throw a 404 page not found error without a trailing slash, `/en` and `/en/admin`.

## Steps to reproduce
1. Go to `http://localhost/en` or `http://localhost/en/admin` URLs without specifying a trailing slash.
2. 404 page not found error is thrown.

## Expected behavior
`/en` and `/en/admin` URLs without a trailing slash should work normally just like their `/en/` and `/en/admin/` counterparts with a trailing slash.

## Actual behavior
`/en` and `/en/admin` URLs without a trailing slash are throwing a 404 page not found error.

## Screenshots
The same URL with a trailing slash works              |  The same URL without a trailing slash doesn't work
:-------------------------:|:-------------------------:
![Screenshot from 2024-01-26 08-08-11](https://github.com/django-cms/django-cms/assets/18735647/b5f1414b-8143-4c10-a2db-1e83c317f208) | ![Screenshot from 2024-01-26 08-08-55](https://github.com/django-cms/django-cms/assets/18735647/90ab2ede-db0e-497c-a3fa-0d1de6f99507)

## Additional information (CMS/Python/Django versions)

CMS version: 4.1.0
Django version: 5.0.1
Python version: 3.11.7

## Do you want to help fix this issue?

* [x] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. 
* [ ] No, I only want to report the issue.

**Comment by fsbraun** [comment]
Super catch! I really needed to have a closer look at the error message to see that this was raised by serving the media files like static files.

Try adding `MEDIA_URL = "/media/"` to your `settings.py`. I have created a PR to update the project template used by the `djangocms` command: https://github.com/django-cms/cms-template/pull/4.
