### ISSUE TITLE
[BUG] Permission Denied exception when adding a page in a different language

### ISSUE THREAD

**Issue by jrief** [django-cms/django-cms#7826]
## Description

A Permission Denied exception is raised, if a non-superuser attempts to add a page in a different language.

## Steps to reproduce

* Site must be configured to be multi-lingual.
* Log in as a user with permission to add a page.
* That user shall navigate to a page where he page where he has edit permissions.
* In the CMS toolbar, navigate to Language and then to "Add translation…"
* Choose any alternative language.

This raises a Permission Denied exception.

## Do you want to help fix this issue?

* [x] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. 
* [ ] No, I only want to report the issue.

I already found the reason for this and prepared a patch. This error however seems to be a legacy from CMS3 and presumably more cleanup work is required.

This patch fixes the problem in a very hacky way:
https://github.com/jrief/django-cms/commit/4a47b6b91d86d7e7345f3e5350b151ade72f3382

**Comment by jrief** [comment]
> Can you comment briefly on your fix? I'm not sure if I understand what the clean-up work needed is.

If someone tries to add the translation of a page, a URL such as

`https://…/de/admin/cms/pagecontent/add/?cms_page=22458&language=fr`

is called. This resolves to the view `cms.admin.pageadmin.PageContentAdmin.add_view()`. Now, by evaluating the GET parameter `cms_page=22458` it should be clear where to attach the translated page. However, that named view evaluates the GET parameter `parent_node`, which was missing.

In my patch, I therefore just added that parameter to the request. This is somehow unnecessary, because `cms_page` and `parent_node` are related to each other and hence redundant. But I needed a quick fix for that problem.

**Comment by fsbraun** [comment]
@jrief The same code (without the `parent_node`) is present in djangocms-verisioning. 
https://github.com/django-cms/djangocms-versioning/blob/f726bc203c06ccbb8ba79dc9defb98d1b4e06a9d/djangocms_versioning/cms_toolbars.py#L369-L373
Do you know if that fix also works with djangocms-versioing?

**Comment by jrief** [comment]
We continuously experience permission denied errors when users click on the language tab. Therefore I'd like to propose another approach.

The language tab made sense in django-CMS < version 4, because it was connected to the `Page`-model editor. But with the introduction of the `PageContent`-model, it creates more confusion than benefit. If someone edits a page in a certain language, the page title, slug, and even the used template are now part of the `PageContent`-model. Then, why should a user ever have a need to switch between languages in the `PageContent`-model editor? This doesn't make any sense!

Therefore my proposal is to ditch those language tabs altogether. If a user wants to edit content in a different page, he must switch to that page in another language anyway.

**Comment by jrief** [comment]
This is related to the original issue.

Apart from the permission denied problem, this for me also is a user experience problem. When a user edits a page in a certain language, why should he be able to edit the page title, slug, etc. in other languages as well. This is really confusing and doesn't make any sense at all.

**Comment by fsbraun** [comment]
I cannot reproduce a permission denied.
