### ISSUE TITLE
[BUG] Unpublished page is shown instead of 404

### ISSUE THREAD

**Issue by jrief** [django-cms/django-cms#7849]
## Description

If a page exists in multiple languages, for instance German and English, and the English version is published but the German version is unpublished, then the German version does not show a "404 – not found page", as one would expect. 

## Steps to reproduce

**djangocms-versioning** is installed and enabled.

The CMS language configuration settings are:

```python
CMS_LANGUAGES = {
    1: [{
        'public': True,
        'code': 'de',
        'hide_untranslated': False,
        'name': "Deutsch",
        'redirect_on_fallback': True,
    }, {
        'public': True,
        'code': 'en',
        'hide_untranslated': True,
        'name': "English",
        'redirect_on_fallback': True,
    }],
    'default': {
        'fallbacks': [],
        'redirect_on_fallback': True,
        'public': True,
        'hide_untranslated': False,
    },
}
```

* Create a page somewhere in the page tree.
* Add content to the German page.
* Publish the German page.
* Create English content for that same page. The URL can be the same as for the German page. Example: `/en/path/to/page` vs. `/de/path/to/page`.
* Publish the English page.
* Switch back to the German page.
* Unpublish the German page.
* The URL `/de/path/to/page` still shows the existing content in German. This is even true for anonymous users.

## Actual & Expected behaviour

One would expect that an unpublished page does not show up and renders a "404 – Not found page"

I also tried to change the setting of `CMS_LANGUAGES['default']['fallbacks'] = ['de', 'en']`. The one would expect to see the English version of a page, because of the fallback value. However, that is not the case.

Btw. Pages which should show up as "404 – Not found page", actually are empty. This means that the template is rendered with empty placeholders.

## Additional information (CMS/Python/Django versions)

* Django-4.1.13
* Django-CMS-4.1 (HEAD on develop-4, commit 21d6a6defc5a6321bd691e43eb57c112508b952f)

## Do you want to help fix this issue?

* [x] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. 
* [ ] No, I only want to report the issue.

**Comment by jrief** [comment]
In my opinion the culprit is this line of code:
https://github.com/django-cms/django-cms/blob/21d6a6defc5a6321bd691e43eb57c112508b952f/cms/views.py#L228

shouldn't it be
```python
content = page.get_content_obj(language=content_language, fallback=False)
```
instead?

Or to ask in a different manner, what's the intention of serving an empty page in a language, instead of marking that page as "Not found"?

**Comment by fsbraun** [comment]
@jrief No, the CMS config can require a different fallback content object to be loaded. The page should not be "found" in the first place:
https://github.com/django-cms/django-cms/blob/21d6a6defc5a6321bd691e43eb57c112508b952f/cms/views.py#L96

**Comment by jrief** [comment]
> Maybe this is a cache invalidation issue?

No, currently an unpublished Page is just rendered with empty content, as long as that page exists in another language.

How can I render some default content? This for instance could be used to apologize and tell a visitor, that that page exists in a different language only.

**Comment by fsbraun** [comment]
I will look at this. In the meantime can you let me know außer the `languages` field of the page containes?

**Comment by jrief** [comment]
Okay, let's go into details:
* The page has two contents, one with `language='de'` and one with `language='en'`.
* The string `page.languages` is 'de,en`.
* The English content is published, the German is unpublished.
* If I reload the English page, it shows up as expected.
* If I reload the German page, the statement `content = page.get_content_obj(language=content_language)` returns the content object of the English page. I also checked the `id` – it is the same as for the English content object.
* This content object then is rendered by the given main template. Its content object finally is passed to the templatetag `{% placeholder "Main Content" %}`
* There the context is rendered by method `render_tag()` and the result is `content = renderer.render_obj_placeholder(…)`.
* For both languages, the context contains the same `current_content` object. However, when I render the English page, the resulting content string is filled with HTML, whereas when I render the German page it is the empty string. My assumption is that there is an issue with the plugin caches.

**Comment by jrief** [comment]
anyway, in my opinion the CMS should not render a page in an alternative language unless it is specified in the array

`CMS_LANGUAGES['default']['fallbacks'] = […]`,

otherwise it may happen that that page is rendered in a language nobody understands. In such a case a "404 – Page not found" would be the proper response.

**Comment by fsbraun** [comment]
Can you manually set `page.languages` to `en` to check if that produces the desired behavior. 
(My hypothesis: Upon first publishing the German page, `de` is added to the languages but then not removed again after unpublishing the German page.)

**Comment by jrief** [comment]
So, I `cms.views.details()` I have overwritten `page.languages = 'en'` before calling `self.render_placeholder(…)`. Does have no effect, the page's "Main Content" placeholder remains empty.

**Comment by fsbraun** [comment]
No, I meant to change it in the database. The code should never reach `render_placeholder()`. It should go to `_handle_no_page`.

**Comment by jrief** [comment]
Changing `languages = 'en'` on the page object in the database worked. Hurray!

**Comment by fsbraun** [comment]
Bad news: There appears to be a conceptual problem on how the Page model optimizes database access. It is incompatible with djangocms-versioning. I am looking for a solution!

**Comment by fsbraun** [comment]
Also, this should be tested by versioning.

**Comment by fsbraun** [comment]
After looking into the code-base I conclude that `.get_languages()` is used throughout the admin and toolbar. It therefore should contain any translations - independent if they are published or nor.

On the other side, the `views.details` only is concerned about published content. It needs to ignore `get_languages` and only rely on the page contents visible by the ORM. 

I will come up with a fix.

**Comment by fsbraun** [comment]
@jrief Can you try and test the above patch? Manually restore the `en,de` `page.languages` - should work now. 🤞
