### ISSUE TITLE
[BUG] Special characters in page title

### ISSUE THREAD

**Issue by jrief** [django-cms/django-cms#7859]
## Description

If a page title contains special characters, such as `&`, then this character is rendered as HTML-entity, for instance `&amp;`.
In browser tabs this does not look right.

## Steps to reproduce

* Create a page template where the page title is used. This usually is done by adding

```html
…
<meta>
  {% page_attribute "page_title" as page_title %}
  <title>{{ page_title}}</title>
  …
</meta>
…
```

* Create or edit a page and use `A & B` as the page title.
* Load the page.

The browser tab shows `A &amp; B`.

## Expected behaviour

The browser tab should show `A & B` as page title.

## Do you want to help fix this issue?

By patching the templatetag `cms.templatetags.cms_tags.PageAttribute` and [not escaping the value](https://github.com/django-cms/django-cms/blob/fa7b89ceec3bd22e031be8e9cf2328a3f9434b12/cms/templatetags/cms_tags.py#L411), this can be fixed easily. However, I don't know what security implications this fix may have.

I would exempt escaping the string, whenever the name is `page_title`, just as we do it with values of type `datetime`.

Any objections to this?

* [x] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. 
* [ ] No, I only want to report the issue.

**Comment by fsbraun** [comment]
@jrief Wouldn't it suffice to add `safe`? 
```
<meta>
  {% page_attribute "page_title" as page_title %}
  <title>{{ page_title|safe }}</title>
  …
</meta>
```
Obviously, this would open up a vulnerability to scripting attacks. Maybe a custom filter that removes any tags but keeps symbols is the right way to go?

**Comment by fsbraun** [comment]
Another thought: `<title>{{ page_title|striptags }}</title>`?

**Comment by jrief** [comment]
Unfortunately both of them do not work.

Problem is, that the string is already escaped before creating the rendering context.
This could be circumvented by unescaping that string again. However, Django does not provide any templatetag for this.

**Comment by fsbraun** [comment]
As a quick fix:
```
def unescape(value): 
    """Unescapes ampersands"""
    return str(value).replace("&amp;","&")
```

Still, I would expect `page_attribute` to deliver unescaped strings, which Django would autoescape if no `safe` filter is added. I'll have a look at the code...

**Comment by jrief** [comment]
I found a solution for that problem. It could be solved by applying this [patch](https://github.com/jrief/django-cms/commit/3750ae321bd6eb39670e675c0ff92e1961fde58f).

**Comment by fsbraun** [comment]
An alternative work-around is to use

```
<meta>
  <title>{{ request.current_page.get_paget_title|striptags }}</title>
  …
</meta>
```

**Comment by jrief** [comment]
`<title>{{ request.current_page.get_page_title|striptags }}</title>` is quite a lot of inderiction for an object for which we already have a canonical handle.

Shouldn't we disallow HTML tags in the `title`-field in the `clean()`-method before saving rather then on rendering?
