### ISSUE TITLE
[BUG] CMS 4.1 slug is readonly when changing Page title

### ISSUE THREAD

**Issue by aacimov** [django-cms/django-cms#7866]
## Description

On already existing page you can change the title afterwards but not its slug (it has a readonly attribute in HTML).

## Steps to reproduce

1. Create a page with title (slug gets prepopulated)
2. Create a new draft of the page (to be able to edit Page settings)
3. Go to page settings
4. Edit the title (works as expected)
5. Edit the slug (it's readonly - no success)

## Expected behaviour

You should be able to change the slug field or it should get prepopulated from the new title.

## Actual behaviour

Slug field is not editable.

## Additional information (CMS/Python/Django versions)

- Python 3.10
- Django CMS 4.1.0
- Django 4.2.11

## Do you want to help fix this issue?

* [x] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. 
* [ ] No, I only want to report the issue.

**Comment by jrief** [comment]
We experienced the same problem. This is caused by adding the language tabs to the admin detail view of `PageContent`.

In my opinion this does not make sense, because this is an editor opened for a specific page *in a specific language*. Therefore offering another tab to edit the page title in another language is confusion for other users.

I [patched this in our own version of django-CMS][https://github.com/jrief/django-cms/commit/2475e626be9ccd97bdf064308d65f7db2ac8e963], so that not language tabs are shown anymore.

I would suggest that we shall remove the language tabs in the upstream branch as well.

**Comment by aacimov** [comment]
I believe this was fixed in the latest develop-4. Correct me if I am wrong.

**Comment by fsbraun** [comment]
@jrief This is a separate problem. Switching the language tabs does result in the expected setting of read-only fields.

@aacimov For a draft page, the slug should be editable, however. It is not a django admin read-only field which would not render a widget. I find a text input widget which has the `readonly` attribute set. I'm investigating.

**Comment by fsbraun** [comment]
So far, I've failed to reproduce this on django CMS 4.1.1. @aacimov Can you try?

**Comment by aacimov** [comment]
> So far, I've failed to reproduce this on django CMS 4.1.1. @aacimov Can you try?

Working as expected. I do have only 1 language in my current project where I am testing. I will try to reproduce in a multilingual website and let you know.

**Comment by aacimov** [comment]
@fsbraun I can confirm this is still not working in 4.1.1. It seems to me I am getting a little crazy since I am sure it was working when I was using the latest develop-4 version.

**Comment by fsbraun** [comment]
@aacimov Can you verify the steps above. I tested with a brand new project (`djangocms testproj`), where I added a second language in the settings and am still not able to reproduce the issue.

**Comment by aacimov** [comment]
I am apparently going crazy. Tried again after upgrading PyCharm and now it works. I really don't know what to say. 
It's notable mentioning I did delete the `__pycache__` folder after upgrading, maybe that helped.

**Comment by fsbraun** [comment]
I found and fixed it :-)
