### ISSUE TITLE
[DOC] No explanation on using PlaceholderRelationField with classed based views

### ISSUE THREAD

**Issue by aacimov** [django-cms/django-cms#7869]
## Description

I am struggling with rewriting my old Posts app to work with v4.1 since there is no explanation on using `PlaceholderRelationField` with class based views - in my case `DetailView` where I am using the `get_context_data` method and returning all I need in the context. 

I get to the point where I have my detail rendered but clicking on Edit I am getting the TypeError exception: `View.__init__() takes 1 positional argument but 3 were given` most certainly because it expects the obj.

Any "point to the right direction" would be apreciated.

Attaching my code snippet screenshot.

## Screenshots

<img width="830" alt="Screenshot 2024-04-09 at 22 01 08" src="https://github.com/django-cms/django-cms/assets/912266/f02272e0-661e-47cb-a289-23240e42e1f4">

## Additional information (CMS/Python/Django versions)

- CMS 4.1
- Python 3.10
- Django 4.2.11

## Do you want to help fix this documentation issue?

* [x] Yes, I want to help fix this issue and I will join #workgroup-documentation on [Slack](https://www.django-cms.org/slack) to confirm with the team that a PR is welcome. 
* [ ] No, I only want to report the issue.

**Comment by fsbraun** [comment]
@aacimov I am not sure if I understand the question. What does this have to do with `PlaceholderRelationField`? 
How do you register your model for frontend editing?

**Comment by aacimov** [comment]
I am following the "How to guides" in the docs - replaced `post_content = PlaceholderField("slot_name")` with `post_content = PlaceholderRelationField() ` in my `models.py`. 

Added required methods to my `models.py`:

```python
@cached_property
def post_content_placeholder(self):
    return get_placeholder_from_slot(self.post_content, "post_content")

def get_template(self):
    return "posts/structure/post_structure.html"
```

Removed `PlaceholderAdminMixin` from `admin.py` as stated in the docs.

Added `cms_config.py` with the following:

```python
class PostsAppConfig(CMSAppConfig):
    cms_enabled = True
    cms_toolbar_enabled_models = [(models.Post, views.PostDetail)]
```

Note that PostDetail is a **class based** view.

In `post_structure.html`:

```python
{% load cms_tags %}
{% placeholder "post_content_placeholder" %}
```

In my post_detail template I am rendering the placeholder with:

`{% render_placeholder post.post_content_placeholder %}`

**Comment by fsbraun** [comment]
In the apphook config, you might need to use ` views.PostDetail.as_view()` . That might actually be a helpful hint in the docs!

**Comment by aacimov** [comment]
Getting there but now it expect a pk which I am getting through the self.kwargs parameter:

Error raised is: `Generic detail view PostDetail must be called with either an object pk or a slug in the URLconf`

How do I pass it to the as_view() method? In my first post you can see my logic.

**Comment by fsbraun** [comment]
Ah, I see. There is a signature difference between the views. Maybe it's easiest if you do something like this:

```
# views.py
def post_endpoint_view(request, post):
    return PostDetails.as_view()(request, pk=post.id)
```

Then you can use the `post_endpoint_view` in the `cms_config.py`.

**Comment by aacimov** [comment]
Yes, it works but not fully.

I had to change the method to match my url kwarg to:

```python
def post_endpoint_view(request, post):
    return PostDetail.as_view()(request, post_id=post.id)
```
since my URL kwarg is called `post_id`.

The Edit mode loads but I cannot add any plugins inside it. 

I am an admin user, not sure if I have to implement `has_perm ` method on it. Docs say that by defining permissions in the Auth model for staff members should work.

**Comment by fsbraun** [comment]
How does the failure to add plugins manifest itself?

**Comment by fsbraun** [comment]
Does editing work for post detail? 

What should be editable with the list apphool-page?

**Comment by aacimov** [comment]
> Does editing work for post detail?

Editing for post detail works but adding or pasting plugins does not (both buttons do nothing on click).

> What should be editable with the list apphool-page?

I just explained the environment. Nothing is editable on the AppHooked page, it just shows a PostList view as it should (defined in urls.py of my application).

**Comment by aacimov** [comment]
[UPDATE] I have tried rewriting to a function based view as described in the docs. Now I don't have the Edit button on my post_detail at all. 

I am using django-modeltranslation, could that be an issue? Of course `post_content = PlaceholderRelationField()` field is not registered as translatable in my translation.py.

My `cms_config.py`:

```python
class PostsAppConfig(CMSAppConfig):
    cms_enabled = True
    cms_toolbar_enabled_models = [(models.Post, views.render_post)]
```
My `views.py` - detail part:

```python
def render_post(request, pk):
    post = Post.objects.get(id=pk)
    return render(
        request,
        "posts/post_detail.html",
        {
            "post": post,
        },
    )


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)  # Get the object (here by id)
    request.toolbar.set_object(post)  # Announce the object to the toolbar
    set_language_changer(request, post.get_absolute_url)
    return render_post(request, post)  # Same as preview rendering
```
My `urls.py`:

```python
urlpatterns = [
    path('<int:pk>/', render_post, name='post_detail'),
    re_path(r'^', PostList.as_view(), name='posts_list'),
]
```

**Comment by fsbraun** [comment]
Shouldn't `render_post`be:

```
def render_post(request, post):
    return render(
        request,
        "posts/post_detail.html",
        {
            "post": post,
        },
    )
```

**Comment by aacimov** [comment]
> Shouldn't `render_post`be:
> 
> ```
> def render_post(request, post):
>     return render(
>         request,
>         "posts/post_detail.html",
>         {
>             "post": post,
>         },
>     )
> ```

It should but then it raises `render_post() got an unexpected keyword argument 'pk'`

**Comment by fsbraun** [comment]
... and `path('<int:pk>/', post_detail, name='post_detail'),` in the url patterns.

**Comment by aacimov** [comment]
> ... and `path('<int:pk>/', post_detail, name='post_detail'),` in the url patterns.

Absolutely correct. My mistake. Now Edit works with function based view but I still have the same issue with add/menu. No response whatsoever. No console log errors nor server response errors. Just a voided click.

I tried opening in Incognito, cleared site data etc. Nothing helps.

**Comment by aacimov** [comment]
OK, thanks to @fsbraun the class-based view works as follows:

**`models.py` (some unrelevant fields excluded):**
```python
class Post(models.Model):
    ...
    post_content = PlaceholderRelationField(verbose_name=_("Post content"))
    ....

    @cached_property
    def post_content_placeholder(self):
        return get_placeholder_from_slot(self.post_content, "post_content_placeholder")

    def get_template(self):
        return "posts/structure/post_structure.html" # Structure view template described below
```
**Structure view template (posts/structure/post_structure.html):**
```python
{% load cms_tags %}
{% placeholder "post_content_placeholder" %}
```
**`views.py` with DetailView (class-based):**
```python
class PostDetail(DetailView):
    model = Post
    template_name = 'posts/post_detail.html'
    pk_url_kwarg = 'post_id'

    def get_context_data(self, **kwargs):
        post_id = self.kwargs['post_id']
        request = self.request

        try:
            section = Section.objects.get(namespace=self.request.current_page.application_namespace)
        except:
            section = None

        post = get_object_or_404(Post, id=post_id)  # Get the object (here by post_id)
        request.toolbar.set_object(post)  # Announce the object to the toolbar

        context = {
            "post": post,
            "section": section,
            "request": request,
        }

        return context

def post_endpoint_view(request, post):
    return PostDetail.as_view()(request, post_id=post.id) # Called in cms_config.py
```
**`posts/post_detail.html` template (where the placeholder should be rendered):**
```python
...
{% render_placeholder post.post_content_placeholder %}
...
```
**`urls.py`:**
```python
path('<int:post_id>/<slug:post_slug>/', PostDetail.as_view(), name='post_detail'),
```
**`cms_config.py`:**
```python
class PostsAppConfig(CMSAppConfig):
    cms_enabled = True
    cms_toolbar_enabled_models = [(models.Post, post_endpoint_view)]
```
I have to find a way to put this in the docs in an understandable way but so far so good.
Hope it helps someone.
