### ISSUE TITLE
[BUG] Console error in browser when opening PageContentAdmin

### ISSUE THREAD

**Issue by jrief** [django-cms/django-cms#7879]
## Description

I'm experiencing this error in the console of the browser:

![Screenshot 2024-04-18 at 16 08 30](https://github.com/django-cms/django-cms/assets/1132472/7ec2beb0-d79f-4ae2-ae8a-7957b878da25)

Note that I bundled the client code using `gulp bundle --debug` to obtain more verbose information.

## Steps to reproduce

* Open the page tree.
* Chose a page which is published, ie. having a green bullet.
* Click on the PageContent editor (button with 3 sliders).

## Expected behaviour

No error in the browser console.

## Actual behaviour

Browser reports:
`window.CMS.Widgets._pageSmartLinkWidgets` is undefined.

Side note:

All the fields of that page's editor are readonly. If I open the editor of a page which is not published, then the editor opens with all the fields, but editable. Then this error does not occur.

## Additional information (CMS/Python/Django versions)

Branch `develop-4` current HEAD (92a1086decd082f1645e73bf6c8ab4d501b0e194)

## Do you want to help fix this issue?

* [ ] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. 
* [x] No, I only want to report the issue.

Since I'm not aware of the purpose of this, I probably can't fix this myself.

**Comment by fsbraun** [comment]
@jrief Can you check if #7880 solves your issue?
