### ISSUE TITLE
[BUG] Add plugin modal not working after migration

### ISSUE THREAD

**Issue by gonzalodelgado** [django-cms/django-cms#7881]
## Description

We have a Django codebase that's able to run two different sites (one in English, the other one in Spanish) using different settings. We're currently on Django CMS 3.11.5 and are migrating to 4.1.0.
I was able to migrate using djangocms-4-migration and the English site configuration works well enough.
But we found an issue on the Spanish site when editing a page: clicking on the "+" button from the structure slideout to add a plugin doesn't work.
Upon closer inspection it seems to be a problem in the Javascript side of things, when a the modal needs to be opened.
What's odd is opening the "Add Plugin" modal using the "+" button works perfectly when loading the structure page on its own (/admin/cms/placeholder/object/<id>/structure/<id>/)

## Steps to reproduce

I'm not sure if there's an easy way to reproduce the issue since it's happening on a specific migrated site. But I can try to create a test site with a similar configuration and see if the issue happens there if that helps.

## Expected behaviour

Pressing the "+" button from the structure slideout when editing a page should open the modal to add a plugin.

## Actual behaviour

Nothing happens when I click the button. Not even a Javascript error log in the browser console.

## Additional information (CMS/Python/Django versions)

I'm running Django 4.2 and Python 3.11

## Do you want to help fix this issue?

* [ ] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. 
* [X] No, I only want to report the issue.

**Comment by fsbraun** [comment]
@gonzalodelgado Thanks for reporting this!

It might be a double of https://github.com/django-cms/django-cms/issues/7841 . You could check by installing the `develop-4` branch on a test system.

**Comment by gonzalodelgado** [comment]
This turned out to be happening because of a custom middleware we have that deactivates translations on the admin, not a Django CMS issue.
