### ISSUE TITLE
[BUG] placeholders-outside-cms TemplateDoesNotExist

### ISSUE THREAD

**Issue by openHBP** [django-cms/django-cms#7892]
## Description

https://docs.django-cms.org/en/latest/how_to/01-placeholders.html#placeholders-outside-cms

Following the steps described "structure mode template" does not work.
Django does not find the template in any places: root templates folder, myapp/templates, myapp/templates/myapp

django.template.exceptions.TemplateDoesNotExist

## Additional information (CMS/Python/Django versions)
* Django==3.2.25
* django-cms==4.1.0
* Python==3.10

## Do you want to help fix this issue?

* [ ] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. 
* [x] No, I only want to report the issue.

**Comment by fsbraun** [comment]
Hi @openHBP ! Can you double-check your `get_template()` result and the template folders? I cannot reproduce this.

If `get_template()` returns `"my_app/my_model_structure.html"` the typical place for the template would be `my_app/templates/my_app/my_model_structure.html`.

**Comment by openHBP** [comment]
The template is indeed in `my_app/templates/my_app/my_model_structure.html` where `my_app` is `msg`
![image](https://github.com/django-cms/django-cms/assets/35601267/617ec865-605f-4b3a-969f-456af511f7e8)

Content of `msg.models.py`
```py
from cms.models.fields import PlaceholderRelationField
from cms.utils.placeholder import get_placeholder_from_slot

...
short_text3 = PlaceholderRelationField()
...

    def my_placeholder(self):
        return get_placeholder_from_slot(self.short_text3, "msgdet_slot")

    def get_template(self):
        return "msg/msgdet_model_structure.html"
```

Apart from that everything works fine. I can edit the placeholder text as if it was in the CMS

Here is the error (where /chapeau is the /admin path)
```
File "/home/pat/dev/pipenv/cpilote2/.venv/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/pat/dev/pipenv/cpilote2/.venv/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/pat/dev/pipenv/cpilote2/.venv/lib/python3.10/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/home/pat/dev/pipenv/cpilote2/.venv/lib/python3.10/site-packages/cms/templatetags/cms_js_tags.py", line 36, in render_cms_structure_js
    obj_placeholders_by_slot = rescan_placeholders_for_obj(obj)
  File "/home/pat/dev/pipenv/cpilote2/.venv/lib/python3.10/site-packages/cms/utils/placeholder.py", line 352, in rescan_placeholders_for_obj
    declared_placeholders = get_declared_placeholders_for_obj(obj)
  File "/home/pat/dev/pipenv/cpilote2/.venv/lib/python3.10/site-packages/cms/utils/placeholder.py", line 374, in get_declared_placeholders_for_obj
    return get_placeholders(obj.get_template())
  File "/home/pat/dev/pipenv/cpilote2/.venv/lib/python3.10/site-packages/cms/utils/placeholder.py", line 252, in get_placeholders
    compiled_template = get_template(template)
  File "/home/pat/dev/pipenv/cpilote2/.venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: /msg/msgdet_model_structure.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pat/dev/pipenv/cpilote2/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/pat/dev/pipenv/cpilote2/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pat/dev/pipenv/cpilote2/.venv/lib/python3.10/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/pat/dev/pipenv/cpilote2/.venv/lib/python3.10/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/pat/dev/pipenv/cpilote2/.venv/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "/home/pat/dev/pipenv/cpilote2/.venv/lib/python3.10/site-packages/cms/views.py", line 263, in render_object_structure
    return render(request, 'cms/toolbar/structure.html', context)
  File "/home/pat/dev/pipenv/cpilote2/.venv/lib/python3.10/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/pat/dev/pipenv/cpilote2/.venv/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/pat/dev/pipenv/cpilote2/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/home/pat/dev/pipenv/cpilote2/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: /msg/msgdet_model_structure.html
[29/Apr/2024 12:13:56] "GET /chapeau/cms/placeholder/object/53/structure/1271/ HTTP/1.1" 500 260510
```

**Comment by fsbraun** [comment]
When does the error happen? I would assume that the structure view is necessary to edit the content. So if that works, the template should be found. Maybe it is accessed elsewhere, too?

**Comment by fsbraun** [comment]
@openHBP Did this resolve?

**Comment by fsbraun** [comment]
I think I understand now, and your resolution is correct. With django CMS 4 you have to announce the frontend editable object to the toolbar using `set_object`.

**Comment by openHBP** [comment]
I checked again all pieces of code and I still get stuck with the "stucture template".
I did [add the slot to the model](https://docs.django-cms.org/en/latest/how_to/01-placeholders.html#adding-the-slots-to-the-model)
I did [add the structure mode template to the model](https://docs.django-cms.org/en/latest/how_to/01-placeholders.html#add-the-structure-mode-template-to-the-model)
And I [registered the model for frontend editing](https://docs.django-cms.org/en/latest/how_to/01-placeholders.html#registering-the-model-for-frontend-editing)

Yet I get the error "TemplateDoesNotExist at /admin/cms/placeholder/object/53/structure/1325/". Checking the Template-loader postmortem, the template path is correct.

The only subtlety I had to do is to convert my CBV Detail View to a FBV in order to avoid a Page not found (Raised by:	cms.views.render_object_edit) on edit of placeholder/plugin path "admin/cms/placeholder/object/53/edit/1325/"

Content of `msg/cms_config.py` file
```py
from cms.app_base import CMSAppConfig
from . import models, views_msgdet_edit
# from .views import MsgDetDetailView # use of CBV does not work here ! :-(


class MsgConfig(CMSAppConfig):
    cms_enabled = True
    # cms_toolbar_enabled_models = [(models.MsgDet, MsgDetDetailView.as_view())]
    cms_toolbar_enabled_models = [(models.MsgDet, views_msgdet_edit.msgdet_detail)]
```

Content of `msg/views_msgdet_edit.py`

```py
def msgdet_detail(request, obj):
    """
    Main call @click on "Modify" button once connected !!!
    """
    request.toolbar.set_object(obj)  # Announce the object to the toolbar
    context = get_context_data(request, obj)
    context.update(ctx)
    context.update({"object": obj})
    return render(
        request,
        "msg/msgdet_detail.html",
        context,
    )
```

Template does not exist error is raised during template rendering
In template /home/pat/dev/pipenv/cpilote/.venv/lib/python3.10/site-packages/cms/templates/cms/toolbar/structure.html, error at line 13

```html
3	<html class="cms-overflow">
4	<head>
5	    <meta charset="UTF-8">
6	    <title>{{ object.title }}</title>
7	    {% render_block "css" %}
8	</head>
9	<body>
10	    {% cms_toolbar %}
11	    {% render_block "js" %}
12	    {% language cms_toolbar.toolbar_language %}
13	    {% render_cms_structure_js cms_toolbar.structure_renderer object %}
14	    {% endlanguage %}
15	</body>
16	</html>
```

Here is the content of the HTML error output converted in md
[TemplateDoesNotExist at _chapeau_cms_placeholder_object_53_structure_1325_.md](https://github.com/user-attachments/files/16992920/TemplateDoesNotExist.at._chapeau_cms_placeholder_object_53_structure_1325_.md)

**Comment by fsbraun** [comment]
It says here that it cannot find the template where it should be:
```
*   `django.template.loaders.app_directories.Loader`: /home/pat/dev/pipenv/cpilote/source/odkdata2/templates/msg/msgdet\_model\_structure.html (Source does not exist)
```
Would you double check the file exists, and is readable for Django?

**Comment by openHBP** [comment]
Thanks for your quick answer.

odkdata2 is an other app than the one concerned by `PlaceholderRelationField` which is `msg`. So the template file should be located in `/source/msg/templates/msg`, which is the case.
But for the sake of testing I've copied the template file into `odkdata2/templates/msg` but it doesn't change anything.
I've also copied the template into the main templates folder => no change.

Content of `msgdet_model_structure.html`

```html
{% load cms_tags %}
{% placeholder "msgdet_slot" %}
```

**Comment by openHBP** [comment]
It WORKS!
In fact my template file `msgdet_model_stucture.html `was missing a r  msgdet_model_st**R**ucture.html
I'm really really sorry about that! And sorry for the time spent on that. This feature is magic. Many thanks for the all the job done.

**Comment by fsbraun** [comment]
@openHBP That's great to hear!!
