### ISSUE TITLE
[BUG] Window resize event triggers editing mode

### ISSUE THREAD

**Issue by jrief** [django-cms/django-cms#7906]
## Description

The Windows resize event triggers a function which put the page in edit mode.

## Steps to reproduce

* As user with editing permission, open any page.
* The toolbar must be active.
* Ensure that the page is in published mode, ie. the canonical URL of the page must be visible.
* Resize the window.

This immediately puts the page into edit mode, ie. the URL changes to something such as: 

`/de/admin/cms/placeholder/object/53/edit/72715/`

## Expected behaviour

Resizing the window should not have an effect in edit mode.

## Additional information (CMS/Python/Django versions)

Happens in version 4.1.1 with the latest bundle of `*.js` files.

I was able to drill down a little bit. If I debug the page using the developer tools I can see that the window resize event is registered twice, in `toolbar.js` and `bundle.toolbar.min.js`. If I remove the second event handler, this effect does not happen anymore.

Unfortunately, even rebundling the JS files using `gulp bundle --debug` doesn't show me the handler, where this happens.

## Do you want to help fix this issue?

* [ ] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. 
* [x] No, I only want to report the issue.

**Comment by fsbraun** [comment]
Hm. I cannot reproduce this. Do I understand correctly, that "Ensure that the page is in published mode, ie. the canonical URL of the page must be visible" means, there's 
* the canonical URL in the browser's address bar (no admin endpoint)
* Versioning offers a yellow "New Draft" button.

**Comment by jrief** [comment]
I now found out more about this issue.

I logged into Django from the same browser instance with the same user but in different Chrome profiles. Actually Version 126.0.6461.0 (Official Build) canary (arm64), but that doesn't matter.

In one browser profile this effect occurs, in the other it doesn't. Therefore my assumption is that the local storage must be the culprit, and indeed, this is how I'm able to reproduce it:

In the local storage there is a key named `cms_cookie` and this key has different values:

![Screenshot 2024-05-06 at 13 16 39](https://github.com/django-cms/django-cms/assets/1132472/07e00704-4fb3-4ee5-bed0-ce6d842517f9)
![Screenshot 2024-05-06 at 13 11 48](https://github.com/django-cms/django-cms/assets/1132472/669dcc91-7472-4a51-8c2f-adc4c16fc1b0)

The browser profile where this effect happens is light green, and where it does not happen is light red. I then edited the value in the green profile and changed `"mode" from `"structure"` to "edit"`, since this is the value from the red profile. Et voilà, now that effect does not occur anymore.

Now the question is, why does the key in `local storage > cms_cookie > mode` has different values, once `structure` and once `edit`?

**Comment by fsbraun** [comment]
Can you pls. compare the end point urls?

**Comment by jrief** [comment]
With endpoints you mean `/de/admin/cms/placeholder/object/53/edit/73244/` which is referenced in `edit`, `edit_off` and `structure`? This URL has nothing to do with the page currently edited/viewed. It actually points onto a completely different page.

In local storage, this endpoint does not even change, when accessing a different page.

**Comment by fsbraun** [comment]
So those might be "leftovers"?

**Comment by jrief** [comment]
Might be "leftovers". However, consider the second browser profile. Here the local storage also contains 3 endpoints, ie. `/de/admin/cms/placeholder/object/53/edit/74716/`. This also is a completely unrelated page.

**Comment by fsbraun** [comment]
Can you compare the `cms_cookie` values to `CMS.config.mode` and `CMS.config.settings.mode` value?

**Comment by jrief** [comment]
In Published View:

`"CMS.config.mode": "live"`

`"CMS.config.settings.mode": "edit"`

Local storage > cms_cookie > `"mode": "structure"`


In Edit View:

`"CMS.config.mode": "draft"`

`"CMS.config.settings.mode": "edit"`

Local storage > cms_cookie > `"mode": "structure"`

**Comment by jrief** [comment]
Apparently #7920 caused a regression and was partially reverted. The ramification of this is that this bug unfortunately reappeared.

**Comment by fsbraun** [comment]
@jrief Sorry, I cannot reproduce the error. Can you give more specifics?

**Comment by jrief** [comment]
Ups, might be my bad. I just rebundled (`gulp bundle`) and now everything works as expected.
