### ISSUE TITLE
[BUG] AppHooked page does not have New draft button

### ISSUE THREAD

**Issue by aacimov** [django-cms/django-cms#7909]
## Description

When AppHook is attached to a page, the page loses the *New draft* button. Workaround is to "de-attach" the AppHook, edit Page settings (e.g. if you wish to change the page title) and hook the AppHook again.

## Steps to reproduce

1. Create a page
2. Attach an AppHook in Advanced settings
3. Publish the page
4. Try changing Page settings (you should go to the page and click on *New draft* button which is not there)

## Expected behaviour

One should be able to change page settings of an AppHooked page.

## Actual behaviour

Creating new draft to be able to edit page settings is impossible.

## Screenshots

<img width="208" alt="Screenshot 2024-05-05 at 13 28 47" src="https://github.com/django-cms/django-cms/assets/912266/f189e56b-083e-49c0-be53-5e85172c435b">

*Stvori* equals to *Create* in English.

## Additional information (CMS/Python/Django versions)

Django 4.2.11
Django CMS 4.1.1
Python 3.10.6

## Do you want to help fix this issue?

* [x] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. 
* [ ] No, I only want to report the issue.

**Comment by fsbraun** [comment]
@aacimov To verify: The attached app serves the content for its "root" page?

**Comment by aacimov** [comment]
Yes, it serves the ListView. 

In `urls.py` the line is: `path('', PostList.as_view(), name='posts_list'),`

I am not sure if the List view should also be "announced" to the toolbar. Since there's no editing here for the actual app, from my point of view it should "act" as a normal page regarding Page settings and Advanced settings.

It's not deep into the app as for DetailView which we solved.

**Comment by fsbraun** [comment]
OK, I think this is a missing feature, really: The page content object is not available to the toolbar (and should or at least need not be). Nevertheless you need access to the settings, version list, "New draft" and "Publish" actions.

**Comment by aacimov** [comment]
> OK, I think this is a missing feature, really: The page content object is not available to the toolbar (and should or at least need not be). Nevertheless you need access to the settings, version list, "New draft" and "Publish" actions.

Exactly. It's time consuming detaching/attaching if only a simple change is needed, though it's not that often one will do such a change but still.

**Comment by fsbraun** [comment]
@aacimov Can you check if `git+https://github.com/fsbraun/django-cms@feat/page-setting-access` does make the Publish and New Draft buttons appear in the toolbar?

**Comment by aacimov** [comment]
> @aacimov Can you check if `git+https://github.com/fsbraun/django-cms@feat/page-settings-access` does make the Publish and New Draft buttons appear in the toolbar?

Still no Publish and New Draft buttons.

**Comment by aacimov** [comment]
After discussing with @fsbraun, we managed to find a solution which I am describing below.

A line was added in CMS's `views.py` fixing the issue, and will be applied in a next release.

**NOTE:**
In AppHooked page Toolbar should be called. This line should do:

```python
request.toolbar.set_object(request.current_page.pagecontent_set.get(page_id=request.current_page.id, language=language))
```
where language is retreived from the request:
```python
language = request.LANGUAGE_CODE
```
