### ISSUE TITLE
[BUG] PLACEHOLDER_CONF 'default_plugins' functionality removed.

### ISSUE THREAD

**Issue by Ceesvanmook** [django-cms/django-cms#7917]
## Description

We have recently migrated to Django-cms 4, and the placeholder conf settings for default_plugins seem to have been completely removed.
When looking at the source code, and comparing this with older projects running on CMS 3 it seems to have been removed.

We have also found a git commit where the code has been removed:
https://github.com/django-cms/django-cms/commit/eef5cbbfe3b4875b9b00db60611171d700c29ced

Despite it seemingly being removed, docs still have a reference to the PLACEHOLDER_CONF.default_plugins:
https://docs.django-cms.org/en/latest/reference/configuration.html#cms-placeholder-conf 

## Steps to reproduce

1. Upgrade to DjangoCMS 4
2. Create PLACEHOLDER_CONF with 'default_plugins' key.
3. Nothing happens when rendering the placeholder

## Expected behaviour

Fill the page with default plugins when the model is first created or the page is first rendered.

## Actual behaviour

Nothing, as the code is removed.

## Screenshots
When searching dependencies in DjangoCMS 3
![image (1)](https://github.com/django-cms/django-cms/assets/62257323/574a88d7-eacf-43dd-84a8-80602b8da6a9)

When searching dependencies in DjangoCMS 4
![image](https://github.com/django-cms/django-cms/assets/62257323/5a184905-ce30-46a2-9363-8298f59ef361)
 

## Additional information (CMS/Python/Django versions)

DjangoCMS version is 4.1.0

## Do you want to help fix this issue?

* [ ] Yes, I want to help fix this issue and I will join the channel #pr-reviews on [the Discord Server](https://discord-pr-review-channel.django-cms.org) to confirm with the community that a PR is welcome.
* [x] No, I only want to report the issue.

**Comment by fsbraun** [comment]
@Ceesvanmook I created a PR in #7919. Can you do me a favor and install it locally for testing:

```
pip install git+https://github.com/fsbraun/django-cms@feat/default-plugins
```

Let me know any feedback!

**Comment by Ceesvanmook** [comment]
@fsbraun thank you! I've installed it locally in my latest project and have done some testing with multiple models and placeholder configurations. On first glance, everything seems to be working as intended! I'll let you know if there are any updates on the matter.
