### ISSUE TITLE
Django 4.0+ does not Work With djangocms3.11

### ISSUE THREAD

**Issue by rdawad** [django-cms/django-cms#7942]
Django 4.2 Does not work with Django-cms==3.11.4 
it only works with djangocms==4 

Trid django-cms 3.11.3+ with Django4.2 it did not work and got me this error 
  raise NodeNotFoundError(self.error_message, self.key, origin=self.origin)
django.db.migrations.exceptions.NodeNotFoundError: Migration cms.0036_alter_cmsplugin_id_alter_globalpagepermission_id_and_more dependencies reference nonexistent parent node ('cms', '0035_auto_20230822_2208')

however as per https://www.django-cms.org/en/blog/2023/09/17/django-cms-3-11-4/
this release notes it says djangocms 3.11.4 works with django 4.2t

**Comment by fsbraun** [comment]
@rdawad Indeed, django CMS 3.11.4 works with Django 4.2. Though, I would suggest you update to django CMS 3.11.6 (the latest version of the 3.11 branch).

The error message you get does **not** originate from django CMS 3.11.4 (which does **not** include a migration called `0036_alter_cmsplugin_id_alter_globalpagepermission_id_and_more`.

It appears that you had temporarily installed the `develop-4` branch of django CMS and then created a migration yourself referencing the latest django CMS migration on the development branch. I would assume, the issue disappears if you delete `cms.migrations.0036_alter_cmsplugin_id_alter_globalpagepermission_id_and_more`.

**Comment by fsbraun** [comment]
@rdawad Any news on this?

**Comment by fsbraun** [comment]
Great! Good to know! Thanks for reporting back!
