### ISSUE TITLE
[BUG] About the refresh of the page permission cache

### ISSUE THREAD

**Issue by baloyou** [django-cms/django-cms#7962]
djangocms: 4.1.1

1. Create a user group
2. Add the user to the user group
3. In the advanced settings of the page, add the user group for View restrictions
At this point, the user should have permission to browse the page.
However, the user will see a 404 page (insufficient permissions)
4. Restart the service 'python manage.py runserver'
Users can access it normally

I'M NOT SURE IF IT'S INTENTIONAL DESIGN, OR IF IT'S A BUG. My current solution, though, is to manually flush the cache

@fsbraun :)

```
from cms.cache.permissions import clear_permission_cache
clear_permission_cache()
```

**Comment by fsbraun** [comment]
Hi @baloyou ! I've come up with a fix: #7963

**Comment by baloyou** [comment]
hi @fsbraun 

I've been working hard lately to get the site online and just came back to test the permissions issue.

My needs are: set access permissions for the page (visible to specified user groups)

I tested the two versions separately: https://github.com/django-cms/django-cms/pull/7963 and https://github.com/django-cms/django-cms/pull/7965

`python -m pip install git+https://github.com/django-cms/django-cms.git@43f8b71da66993f4bd986251575dc7ce98a9d51f`

Actual result: After the user joins the group, the page is still not visible in the navigation menu, but the page can be accessed by entering the URL (it can be accessed, but the menu will not be updated, maybe it is related to caching?). ）

**Comment by fsbraun** [comment]
@baloyou It seems we forgot to also clear the menu cache.

Can you check this:
```
python -m pip install git+https://github.com/fsbraun/django-cms@fix/menu-cache
```

**Comment by baloyou** [comment]
@fsbraun It works very well and thank you so much for your dedication and effort!!
