### ISSUE TITLE
Unable to see the sidebar through the admins.py-defined admin page (indicating insufficient permissions)

### ISSUE THREAD

**Issue by baloyou** [django-cms/django-cms#7964]
I wrote an app (activation) that needs to add the admin interface ('admin.py') to the admin module

```
from django.contrib import admin
class ActivationCodeAdmin(admin.ModelAdmin):
    ...
admin.site.register(ActivationCode, ActivationCodeAdmin)
```
It works.

However, I also needed a 'custom page', I added a button to the list page and created a 'generate_activation_codes' view function.

```
    change_list_template = 'admin/my_change_list.html'
    def get_urls(self):
        urls = super().get_urls()
        custom_urls = [
            path('generate_activation_codes/', self.admin_site.admin_view(self.generate_activation_codes), name='generate_activation_codes'),
        ]
        return custom_urls + urls
    def generate_activation_codes(self, request):
        ....
```

The problem arises, the page is accessible, but the menu in the sidebar says: "No permissions". This may not be a bug, am I doing something wrong?

Two days passed, and I still haven't figured out why. Hope to get some help, thank you very much.

![image](https://github.com/user-attachments/assets/1639320b-cc29-4d21-9371-88e240fad192)

**Comment by fsbraun** [comment]
@baloyou This sounds like a Django admin issue and probably does not belong here. 

Without going into much detail, it seems you have restricted all permissions for the admin. Have you overwritten the admin's methods `has_add_permission(self, request)`, `has_change_permission(self, request)`, `has_delete_permission(self, request)`, `has_view_permission(self.request)`? At least the view permission must be available.
