### ISSUE TITLE
Wrong colors when using data-theme=auto with system with dark theme preference

### ISSUE THREAD

**Issue by JanW-LWL** [django-cms/django-cms#7978]
Hello.

If the user's system prefers a dark theme and the dark mode toggle is set to automatic in the CMS toolbar, then some colors are different than in dark mode.

Is there a reason for this or is it a bug? 

`[data-theme="dark"]`

https://github.com/django-cms/django-cms/blob/59d50f2492b574f5ebd083093c846e04792a4049/cms/static/cms/sass/settings/_cms.scss#L44

https://github.com/django-cms/django-cms/blob/59d50f2492b574f5ebd083093c846e04792a4049/cms/static/cms/sass/settings/_cms.scss#L48

vs

`prefers-color-scheme: dark`

https://github.com/django-cms/django-cms/blob/59d50f2492b574f5ebd083093c846e04792a4049/cms/static/cms/sass/settings/_cms.scss#L63

https://github.com/django-cms/django-cms/blob/59d50f2492b574f5ebd083093c846e04792a4049/cms/static/cms/sass/settings/_cms.scss#L67

Additional informations:
django-cms==4.1.2 

/cc @PeterW-LWL

**Comment by fsbraun** [comment]
@JanW-LWL Looks like a bug to me. Let me verify.
