### ISSUE TITLE
[BUG] X Frame Options Removed from Advanced Form

### ISSUE THREAD

**Issue by syaiful6** [django-cms/django-cms#7981]
Hello Django CMS team, we recently upgraded our project from 3.11 to 4.1. The migrations work perfectly, but we noticed that X Frame Options in Advanced Page settings removed, I see this commit: https://github.com/django-cms/django-cms/pull/6503

## Description

X Frame Options in Advanced Page settings removed from Advanced Settings Form. I see this field available in PageContent model, but now it's not editable everywhere

## Steps to reproduce

1. Go to Page Tree
2. Select one page, then click "Advanced Settings" from hamburger menu
3. No X Frame Options displayed, previously we have one. 

## Expected behaviour

X Frame Options field available in Advance Settings Form.

## Actual behaviour

X Frame Options field not displayed in Advance Settings Form.

## Screenshots

Django 4.1

![Screenshot 2024-08-20 at 15 14 16](https://github.com/user-attachments/assets/86aaeaf6-4a69-4d96-b670-3811edb3d28d)

Django 3.11

![Screenshot 2024-08-20 at 15 15 09](https://github.com/user-attachments/assets/8f8038f9-b530-441a-b9f3-6ebca9b579bb)

## Additional information (CMS/Python/Django versions)

Python 3.11
Django 4.2
Django CMS 4.1

**Comment by fsbraun** [comment]
@syaiful6 Thanks for bringing this to attention. I'll look into it.

**Comment by saikethan27** [comment]
hi @fsbraun  where can I Know name of this html page because I am new to this project I want to contribute can you please let me know where can i find this page

**Comment by fsbraun** [comment]
Hey @saikethan27 ! Thanks for taking this up. To find the advanced settings, you will need to go to the admin -> page contents to see the page tree, create a page if there are none. The advanced settings are in the burger menu on right handside. 
<img width="685" alt="image" src="https://github.com/user-attachments/assets/6634242b-c848-46d0-93e1-61a39cc02a0e">

**Comment by lonewolve24** [comment]
Hello  @fsbraun can i take a look at this issue for the coming hacktoberfest

**Comment by fsbraun** [comment]
Hey @lonewolve24 !That would be awesome!
