### ISSUE TITLE
[BUG] No module named 'cms.utils.compat.warnings' when upgrading to 3.11.7

### ISSUE THREAD

**Issue by jsabater** [django-cms/django-cms#7992]
Just upgraded from 3.11.6 to 3.11.7 and this error prevents me from starting my Django application:

```console
ModuleNotFoundError
No module named 'cms.utils.compat.warnings'
```

The error is happening in `cms/utils/permissions.py`, in `has_page_permission()`, at line 196:

```python
from cms.utils.compat.warnings import RemovedInDjangoCMS43Warning
```

**Comment by fsbraun** [comment]
@jsabater Thanks for reporting! I'll have a look, but it seems an error introduced by backporting.

**Comment by fsbraun** [comment]
@jsabater Can you please check the traceback to see where `has_page_permission` is called?

For the moment, you might want to patch `has_page_permission`:
```
from cms.utils import permissions
from cms.utils.page_permissions import has_generic_permission

permissions.has_page_permission = (
    lambda user, page, action, use_cache=True: 
        has_generic_permission(page, user, action, site=None, check_global=False, use_cache=use_cache)
)
```
(sorry, untested)

**Comment by jsabater** [comment]
No worries, 3.11.8 is fine by me. I am not in a hurry. I have set `django-cms==3.11.6` in the `requirements.txt` file and that works fine. I'll monitor releases and wait patiently :-)

**Comment by fsbraun** [comment]
@jsabater 3.11.7 has been retracted and 3.11.8 is coming any minute now
