### ISSUE TITLE
Apphook Not Showing in Content Page (Multilingual Site)

### ISSUE THREAD

**Issue by sebbschbo** [django-cms/django-cms#8001]
## Description

I have extensive experience creating Django CMS projects and have successfully set up multiple apphooks in the past (Django CMS 3). However, in my current project (Django CMS 4), after setting up an apphook in cms_apps.py, it does not appear in the “Application” dropdown when trying to attach it to a content page.

## Steps to reproduce

1. Define an apphook in cms_apps.py using the following code:

```
from cms.app_base import CMSApp
from cms.apphook_pool import apphook_pool


@apphook_pool.register
class NewsApphook(CMSApp):
    app_name = "news_appname"
    name = "News Application"

    def get_urls(self, page=None, language=None, **kwargs):
        return ["news.urls"]
```

2.	Navigate to the Django CMS admin interface.
3.	Attempt to add the apphook to a content page via the “Advanced Settings” tab.

## Expected behaviour

The apphook should be visible in the “Application” dropdown, allowing it to be assigned to the content page.

## Actual behaviour

The “Application” dropdown is empty, and the apphook is not listed.

## Screenshots

<img width="1878" alt="Screenshot 2024-09-18 um 11 09 03" src="https://github.com/user-attachments/assets/c5201736-0759-4679-971f-91ee91ad7093">

## Additional information (CMS/Python/Django versions)

- The app is registered correctly in INSTALLED_APPS.
- All required CMS middleware is enabled.
- Migrations have been applied, and the server has been restarted.
- Cache has been cleared, but the issue persists.

requirements:

```
asgiref==3.8.1
chardet==5.2.0
crispy-bootstrap5==2024.2
cssselect2==0.7.0
Django==5.1.1
django-appconf==1.0.6
django-classy-tags==4.1.0
django-cms==4.1.2
django-compressor==4.5.1
django-crispy-forms==2.3
django-entangled==0.5.4
django-filer==3.2.2
django-formtools==2.5.1
django-fsm==2.8.2
django-parler==2.3
django-polymorphic==3.1.0
django-ranged-response==0.2.0
django-robots==6.1
django-sekizai==4.1.0
django-simple-captcha==0.6.0
django-treebeard==4.7.1
djangocms-admin-style==3.3.1
djangocms-alias==2.0.1
djangocms-attributes-field==3.0.0
djangocms-frontend==1.3.1
djangocms-text-ckeditor==5.1.5
djangocms-versioning==2.0.2
easy-thumbnails==2.10
html5lib==1.1
lxml==5.3.0
packaging==24.1
pillow==10.4.0
psycopg2-binary==2.9.9
rcssmin==1.1.2
reportlab==4.2.2
rjsmin==1.2.2
setuptools==73.0.1
six==1.16.0
sqlparse==0.5.1
svglib==1.5.1
tinycss2==1.3.0
webencodings==0.5.1
wheel==0.44.0
```

- Django: 5.1.1
- Django CMS 4.1.2
- Python: Python 3.12.6

## Request

Please advise on whether this might be a bug or if there are any additional configurations that need to be checked.

Thank you very much for your help!

**Comment by fsbraun** [comment]
@sebbschbo Your approach works fine for me. I have just tried the following with a 4.1.2 installation:

* `$ ./manage.py startapp news` to start a new app
* Copied your snippet into `news/cms_apps.py`
* Copied `urlpatters = []` into `news/urls.py`
* Added  `"news",` to `INSTALLED_APPS`

**Comment by sebbschbo** [comment]
@fsbraun
> * Copied your snippet into `news/cms_apps.py`

In the past, I always had a central **cms_apps.py** file in my main CMS app that handled all the Apphooks, rather than placing it in the corresponding ‘News app.’ However, it definitely makes more sense to keep it directly within the ‘News app.’

Thanks again for your help and have a nice day!
