### ISSUE TITLE
Redirects in Django CMS 4 (missing the "This page has no preview!"-message)

### ISSUE THREAD

**Issue by krosefield** [django-cms/django-cms#8012]
## Description

In Django CMS 3 when you configured a page as a redirect to another page (Page > Advanced Settings) the page showed a message _"This page has no preview! It is being redirected to: <path>"_ whenever you opened it in the frontend while being logged in. 

In Django CMS 4 this message is no longer available. When you open a redirecting-page it shows the (most likely empty) page if you are in the editing mode or it redirects to the configured target page if you are in preview mode. So while being in the editing mode, you don't get any indication that a redirect has been configured for the current page which seems a source for confusion for CMS editors.

## Suggested behavior

My suggestion is to reintroduce a similar behavior as in Django CMS 3. The message _"This page has no preview! (...)"_ should be displayed in both editing- **and** preview-mode and by that making it easier to edit the redirecting page.

## Do you want to help fix this issue?

* [x] Yes, I want to help fix this issue by testing a new version before its release.
* [ ] No, I only want to report the issue.

**Comment by riku-d** [comment]
@fsbraun please assign this issue to me under hactoberfest

**Comment by fsbraun** [comment]
Closed by #8056

**Comment by krosefield** [comment]
Thank you so much!
