### ISSUE TITLE
[BUG] Extended PageContent documentation wrong

### ISSUE THREAD

**Issue by Dece0** [django-cms/django-cms#8016]
## Description

I am attempting to extend the `PageContent` model following the example provided in the official django CMS documentation: [Extending PageContent Model](https://docs.django-cms.org/en/latest/how_to/18-extending_page_contents.html#pagecontent-model-extension-example). While everything works as expected, I am facing an issue with retrieving the page content extension in a template.

## Steps to reproduce

1. Follow the steps to extend the `PageContent` model as per the documentation linked above.
2. Add custom fields to the `PageContent` extension model.
3. Try to render the extended content in a template using the provided example.
4. Notice that the extended content is not being retrieved or rendered as expected in the template.

## Expected behaviour

The extended content fields added to the `PageContent` model should be accessible in the template, allowing for proper rendering of the extended fields' data.

## Actual behaviour

While the `PageContent` model extension works correctly in the admin interface, the extended content is not being retrieved in the template. The extended fields do not display or render as expected.

## Screenshots

_No screenshots available for this issue._

## Additional information (CMS/Python/Django versions)

- Django CMS version: 4.1.2
- Python version: 3.11
- Django version: 4.2.8
- Environment: local development
- Logs: No relevant logs were generated during the issue.

## Do you want to help fix this issue?

* [ ] Yes, I want to help fix this issue and I will join the channel #pr-reviews on [the Discord Server](https://discord-pr-review-channel.django-cms.org) to confirm with the community that a PR is welcome.
* [x] No, I only want to report the issue.

**Comment by fsbraun** [comment]
Can you share your setup, i.e. the template code that is not rendering as expected and the definition of the page content extension?

**Comment by Dece0** [comment]
Of course.

### models.py

```python
from django.db import models
from cms.extensions import PageContentExtension
from cms.extensions.extension_pool import extension_pool

from apps.vnet_frontend.models import PrettyJSONEncoder


class PageMetaExtension(PageContentExtension):
    json_ld = models.JSONField(
        'JSON linked data',
        blank=True,
        default=dict,
        encoder=PrettyJSONEncoder
    )

    keywords = models.CharField(max_length=2000, default="", blank=True)

    class Meta:
        verbose_name = 'Page meta (language-dependent)'
        verbose_name_plural = 'Page meta (language-dependent)'

    def __str__(self):
        return f'Page meta for Title ID: {self.extended_object.pk}'


extension_pool.register(PageMetaExtension)
```

### admin.py
```python
from django.contrib import admin
from cms.extensions import PageContentExtensionAdmin

from .models import PageMetaExtension


class PageMetaExtensionAdmin(PageContentExtensionAdmin):
    pass


admin.site.register(PageMetaExtension, PageMetaExtensionAdmin)
```

### cms_toolbars.py
```python
from cms.toolbar_pool import toolbar_pool
from cms.extensions.toolbar import ExtensionToolbar
from cms.utils import get_language_list

from .models import PageMetaExtension


@toolbar_pool.register
class PageMetaExtensionToolbar(ExtensionToolbar):
    model = PageMetaExtension

    def populate(self):
        current_page_menu = self._setup_extension_toolbar()

        if current_page_menu and self.toolbar.edit_mode_active:
            sub_menu = self._get_sub_menu(
                current_page_menu, 'submenu_label', 'Page meta', position=4
            )

            page = self._get_page()
            page_contents = page.pagecontent_set(manager="admin_manager").latest_content(language__in=get_language_list(page.node.site_id))

            nodes = [
                (*self.get_page_content_extension_admin(page_content), page_content.title)
                for page_content in page_contents
            ]

            for title_extension, url, title in nodes:
                sub_menu.add_modal_item(
                    'Page meta - %s' % title, url=url, disabled=not self.toolbar.edit_mode_active
                )
```
### meta.html
```html
{% if request.current_page.get_pagecontent_obj %}
  {% autoescape off %}
    <script type="application/ld+json">
      {{ request.current_page.get_pagecontent_obj.pagemetaextension.json_ld }}
    </script>
  {% endautoescape %}
{% endif %}
<meta name="keywords" content="{{ request.current_page.get_pagecontent_obj.pagemetaextension.keywords }}">
```
The template above renders correctly but without data

**Comment by Dece0** [comment]
When I tried to access **`request.current_page.get_pagecontent_obj`** from a Python file, I encountered the error: **`'Page' object has no attribute 'get_pagecontent_obj'`**. 

To resolve this, I created a custom template tag, which solved the issue:

```python
from django import template


register = template.Library()


@register.simple_tag(takes_context=True)
def get_page_meta(context, field_name: str):
    request = context['request']
    extension = request.current_page.get_page_content_obj_attribute(attrname='pagemetaextension')
    return extension.serializable_value(field_name=field_name)

**Comment by fsbraun** [comment]
At first glance, this looks good to me. Two things I noted:
* It's a page content extension, though it's called `PageMetaExtension`
* It will only find the extension of published pages - which I assume is what you want. If not, you could check for edit mode in the `get_page_meta` template tag, and use the toolbar object (if it is a `PageContent` instance).

I am not sure why this did not work in the template itself, but could it be that there was no published version of the page content object which would make `get_page_content_obj` return `None`?

**Comment by h-peters** [comment]
Hello. 
I have the same error. The page has been published but {{ request.current_page.get_pagecontent_obj }} returned nothing.

**Comment by fsbraun** [comment]
@h-peters, @Dece0  Shouldn't this be `{{ request.current_page.get_content_obj }}`, i.e. **get_content_obj** instead of **get_pagecontent_obj**?

**Comment by fsbraun** [comment]
I see the confusion now: The docs are wrong: https://github.com/django-cms/django-cms/blob/19ef774c1f17a75d1e5b4c6006ad089bfbb0abe0/docs/how_to/18-extending_page_contents.rst?plain=1#L270-L279

`get_pagecontent_obj` needs to be `get_content_obj`!

**Comment by weshy007** [comment]
Can I kindly work on correcting the documentation @fsbraun?

**Comment by Dece0** [comment]
@fsbraun  Thank you very much for fixing it in the docs. It works perfectly now!

**Comment by fsbraun** [comment]
All flowers go to @weshy007 !
