### ISSUE TITLE
[BUG] Field languages in model Page may be inconsistent

### ISSUE THREAD

**Issue by jrief** [django-cms/django-cms#8019]
## Description

I currently have no receipt to reproduce this, but apparently we have an inconsistency in our database regarding the field `languages` in model `Page`.

## Steps to reproduce

This currently is not reproducible, but I can explain what is happening using the Django shell:

```
>>> from cms.models.pagemodel import *
>>> page = Page.objects.get(id=21179)
>>> page.languages
'de'
>>> page.get_content_obj('de').language
'de'
>>> page.get_content_obj('en').language
'en'
```

## Expected behaviour

Since the German and English page content objects are published, I would expect that `page.languages == 'de,en'` 

## Actual behaviour

`page.languages == 'de'` 

## Additional information (CMS/Python/Django versions)

Django-CMS-4.1.1

## Do you want to help fix this issue?

Since this field is non-normalized, at least there should be a management command to fix it in case of data corruption.

* [x] Yes, I want to help fix this issue and I will join the channel #pr-reviews on [the Discord Server](https://discord-pr-review-channel.django-cms.org) to confirm with the community that a PR is welcome.
* [ ] No, I only want to report the issue.

**Comment by fsbraun** [comment]
I fear versioning might interfere with the proper update of the `languages` field. The information is clearly redundant and was a performance compromise in v3. Have you checked if `list(page_obj.page_content_cache.keys())` would work for you. If so, we should
* replace the `languages` field by a `@property` 
* replace the `get_languages` by the above expression

**Comment by fsbraun** [comment]
Something like:

```
def get_languages(self):
    self._get_page_content_cache(None, False, False)
    return list(self.page_content_cache.keys())

@property
def languages(self):
   return ",".join(self.get_languages())
```

**Comment by jrief** [comment]
if this doesn't hurt performance, it certainly would be a better solution.

What about using `@cached_property`?
