### ISSUE TITLE
[BUG] request.toolbar.set_object(obj) Breaks Language Switching on Detail Pages

### ISSUE THREAD

**Issue by OzodbekUSTECH** [django-cms/django-cms#8025]
## Description

When using **request.toolbar.set_object(obj)** in a DetailView, the CMS toolbar properly displays the "Edit" button as expected. However, this breaks language switching functionality on the detail view page. If I remove request.toolbar.set_object(obj), the language switcher works as expected, but the "Edit" button disappears from the CMS toolbar.

This appears to be a conflict between setting the CMS object for editing and handling language switching within the detail view. This issue seems to affect the functionality of multilingual sites when using the CMS toolbar in edit mode.

## Steps to reproduce

1. Set up a basic Django CMS project with multilingual support.
2. Add a DetailView for a model (in my case, NewsItem), and set the object in the toolbar using request.toolbar.set_object(obj) in the view.
3. Attempt to switch languages on the detail view page.
4. The URL doesn't change, and the language doesn't switch.
5. Remove request.toolbar.set_object(obj) from the view, and then attempt to switch languages again. The language switcher works, but the "Edit" button disappears from the toolbar.

## Expected behaviour

The expected behavior is that when request.toolbar.set_object(obj) is used to enable the CMS toolbar for editing, the language switcher should still function properly, allowing the URL to update with the selected language and display the correct content in that language.

## Actual behaviour

When request.toolbar.set_object(obj) is used in the view, the language switcher becomes non-functional. The URL does not update to reflect the language change, and the content remains in the current language. Removing request.toolbar.set_object(obj) resolves the language switching issue but hides the "Edit" button from the CMS toolbar.

## Additional information (CMS/Python/Django versions)

django CMS: 4.1.3
Django: 5.0.6
Python: 3.12

## Do you want to help fix this issue?

* [ ] Yes, I want to help fix this issue and I will join the channel #pr-reviews on [the Discord Server](https://discord-pr-review-channel.django-cms.org) to confirm with the community that a PR is welcome.
* [x ] No, I only want to report the issue.

**Comment by fsbraun** [comment]
@OzodbekUSTECH Thanks for bringing this to our attention.

As of django CMS 4.1, you will have to provide your own custom language switching for custom models. The CMS's switcher only works for pages. 

To implement your custom language switcher, you have to remove the CMS' language menu and add your own. You might have a look at djangocms-alias for an example.

We plan to resolve this for common cases in django CMS 4.2.

**Comment by OzodbekUSTECH** [comment]
Hi, thank you for the clarification. I'm still not entirely sure what I need to do in my case. Currently, I'm using a separate HTML template to switch languages with the following code:
```html
{% load i18n menu_tags static %}

{% if languages|length > 1 %}
<div class="header-nav__lang">
    <button class="header-nav__btn" id="lang">
        <!-- Show the current language -->
        <span>{{ current_language }}</span>
        <img loading="lazy" src="{% static 'images/icons/black-arrow.svg' %}" alt="arrow-icon"/>
    </button>

    <ul class="header-nav__lang-drop" id="lang-drop">
        <!-- Loop through available languages -->
        {% for language in languages %}
            {% if current_language != language.0 %}
                <li>
                    <a href="{% page_language_url language.0 %}">
                        <span>{{ language.0 }}</span>
                    </a>
                </li>
            {% endif %}
        {% endfor %}
    </ul>
</div>
{% endif %}
``` 

This code works for switching between languages, but I’m not sure if it’s what you are referring to. Could you please clarify what exactly I need to modify or improve here? Should I be looking into djangocms-alias, or is there a better way to handle language switching for custom models?

Thanks in advance!

**Comment by fsbraun** [comment]
This looks good to me. Maybe I did not understand the issue fully? Am I correct with the following statements:

* The above code works with your custom model if included in the preview page
* The toolbar's Language menu (I called this somewhat imprecisely "language switcher" above) does not work

**Comment by OzodbekUSTECH** [comment]
I’m working on a Django project that includes a News application, which has a detail view for individual news objects. When I access a URL like this:
`http://localhost:8000/en/news/today-september-24-an-event-full-of-heated-intellectual-debates-took-place-on-the-writers-alley-in-tashkent-2752/`
I’m unable to switch the language of the page. When I try to change the language, the page reloads, but the language remains the same.

After some investigation, I found that this issue occurs when I have request.set_object(obj) in the view. If I remove that line, the language switcher works correctly, and I’m able to change the language without any issues. However, removing request.set_object(obj) also causes the Edit button in the Django CMS toolbar to disappear, meaning I can no longer edit the page.

Interestingly, if I access a URL within the Django CMS admin interface, for example:
`http://localhost:8000/en/admin/cms/placeholder/object/106/edit/932/`
the language switcher works perfectly, and I can change the language without any issues.

It seems like the issue is related to how the page_language_url template tag interacts with request.set_object(obj) in the detail view. This conflict prevents the language from switching when I’m viewing the news object detail page, while the problem doesn’t occur in the admin interface.

**Comment by OzodbekUSTECH** [comment]
@fsbraun Here is the method get_absolute_url with a language parameter:

```python
    def get_absolute_url(self, language=None):
        if not language:
            language = get_language()
        if self.has_translation(language):
            slug = self.safe_translation_getter("slug", language_code=language)
            return reverse("news:news_detail", kwargs={"slug": slug})
        # no translation so fallback to all article list
        return reverse("news:news_list")
```

**Comment by fsbraun** [comment]
Have you checked this snippet works? Here's the code from django CMS
```
           # Toolbar object
            if self.request.toolbar.edit_mode_active:
                lang_obj = get_object_for_language(self.request.toolbar.obj, lang, latest=True)
                return '' if lang_obj is None else get_object_edit_url(lang_obj, language=lang)
            if self.request.toolbar.preview_mode_active:
                lang_obj = get_object_for_language(self.request.toolbar.obj, lang, latest=True)
                return '' if lang_obj is None else get_object_preview_url(lang_obj, language=lang)
            try:
                # First see, if object can get language-specific absolute urls (like PageContent)
                return self.request.toolbar.obj.get_absolute_url(language=lang)
            except (TypeError, NoReverseMatch):
                ...
```
In edit or preview mode, the CMS looks for the corresponding object (`get_object_for_language`). Otherwise, it calls `get_absolute_url` on the toolbar object and catches `TypeError` (if the method does not accept the language parameter) or `NoReverseMatch`. 

Would it be possible that your method throws a `NoReverseMatch` exception? Have you tried to wrap the `reverse` statement in a `with force_language(language):` block?

**Comment by OzodbekUSTECH** [comment]
@fsbraun Did I understand you correctly?
```python
def get_absolute_url(self, language=None):
    # If no language is provided, get the current active language
    if not language:
        language = get_language()
    
    try:
        # Temporarily switch to the provided language
        with force_language(language):
            # Check if a translation exists for the specified language
            if self.has_translation(language):
                # Get the 'slug' for the object in the specified language
                slug = self.safe_translation_getter("slug", language_code=language)
                # Return the URL for the news detail page with the translated slug
                return reverse("news:news_detail", kwargs={"slug": slug})
            # If no translation is found, fall back to the news list URL
            return reverse("news:news_list")
    
    except NoReverseMatch:
        # If the URL could not be reversed (e.g., missing slug or routing issues), 
        # fall back to the news list URL
        return reverse("news:news_list")
```

**Comment by fsbraun** [comment]
For debugging, I'd add a log entry to the `except` part. The `with` block probably only needs to encapsulate the `return reverse` statement, but should also do the trick as you have it (if `has_translation` and `save_translation_getter` does not depend on the current language).

**Comment by OzodbekUSTECH** [comment]
@fsbraun Thank you for the suggestion! Using with force_language works perfectly now. When I’m on the detail view of an object and switch to another language, if there’s no translation available, I get redirected to the list of objects without any issues.

However, I wanted to ask if it’s a good practice to use with force_language in this case. The code works fine even without the except NoReverseMatch block, and everything seems stable. Here’s the current version of the code that’s working:

```python
def get_absolute_url(self, language=None):
    if not language:
        language = get_language()
    with force_language(language):
        if self.has_translation(language):
            slug = self.safe_translation_getter("slug", language_code=language)
            return reverse("news:news_detail", kwargs={"slug": slug})
        # no translation so fallback to all article list
        return reverse("news:news_list")
```

Do you think it's a good approach, or is there a better way to handle this?

**Comment by fsbraun** [comment]
This looks good to me! I'm glad the issue is resolved! I think you need to use `force_language` since Django (which does execute the `reverse`) cannot know which language you are looking for.

**Comment by fsbraun** [comment]
@OzodbekUSTECH Reverse is the right way to go! No worries there!

I'm happy to help out. Please consider sponsoring the project (available from $2 per month!): https://github.com/sponsors/django-cms

Regarding the admin view, I'd suggest to either opening a new discussion or asking (with some more details on what you want to change) on our discord server: https://discord-support-channel.django-cms.org/
