### ISSUE TITLE
[BUG] Search functionality for PlaceholderRelationField in the user's selected language

### ISSUE THREAD

**Issue by OzodbekUSTECH** [django-cms/django-cms#8030]
## Description

I have a model that uses PlaceholderRelationField for a field (news_body), and I want to perform a search query that includes this placeholder field. Specifically, I need to search the content within the news_body placeholder by the language the user is currently viewing.

It’s unclear whether this is an issue with the documentation lacking examples on how to filter by PlaceholderRelationField, or if it’s a limitation or bug in django CMS's current functionality. I need to ensure that the search is performed based on the placeholder's content in the active language the user is searching in.

## Steps to reproduce

1. Create a model using PlaceholderRelationField (e.g., news_body = PlaceholderRelationField()).
2. Attempt to filter objects by content within the placeholder field in a view (e.g., NewsListView), ensuring the search is conducted in the language currently selected by the user.
3. Add a search parameter to the query and try to filter results based on the content in the placeholder (news_body) in the selected language.
```python
class NewsListView(ListView):
    model = News
    def get_queryset(self, **kwargs):
        qs = super().get_queryset().filter(published=True)
        search = self.request.GET.get("search", None)
        if search:
            qs = qs.filter(
                Q(translations__headline__icontains=search)
                | Q(translations__brief__icontains=search)
            ).distinct()
        return qs
```
4. No clear way to include filtering by the placeholder content (e.g., news_body) in the selected language.

## Expected behaviour

I expect to be able to filter the queryset based on the content inside the PlaceholderRelationField (news_body), in the language that the user is currently viewing, just like with other text fields such as headline and brief.

## Actual behaviour

There doesn't seem to be a documented or straightforward method to filter based on content within a PlaceholderRelationField, especially when considering language-specific searches. The get_queryset method is unable to search through the content of the news_body placeholder in the active language.

## Additional information (CMS/Python/Django versions)

django CMS: 4.1.3
Django: 5.0.6
Python: 3.12

## Do you want to help fix this issue?

* [ ] Yes, I want to help fix this issue and I will join the channel #pr-reviews on [the Discord Server](https://discord-pr-review-channel.django-cms.org) to confirm with the community that a PR is welcome.
* [x ] No, I only want to report the issue.

**Comment by fsbraun** [comment]
Can you clarify what field  `translations` and what fields `headline` and `brief` are? Are you trying to search model fields or plugins in a placeholder?

**Comment by OzodbekUSTECH** [comment]
@fsbraun Here is the model itself
```python
class NewsItem(TranslatableModel):
    created_at = models.DateTimeField(auto_now_add=True)
    translations = TranslatedFields(
        headline=models.CharField(
            verbose_name=_("Headline"),
            max_length=255,
            unique=True,
        ),
        slug=models.SlugField(
            verbose_name=_("Slug"),
            unique=True,
            db_index=True,
            max_length=255,
        ),
        brief=models.TextField(
            verbose_name=_("Brief"),
            blank=True,
            null=True,
            help_text=_(
                "Provide a brief description of the news item. No more than 20 words."
            ),
        ),
    )
    news_body = PlaceholderRelationField()

    @cached_property
    def news_body_placeholder(self):
        return get_placeholder_from_slot(self.news_body, "news_item_body")
```

**Comment by fsbraun** [comment]
@OzodbekUSTECH This means, you do **not** want to search the placeholder content but you just want to search `NewsItems`? 

Assuming you are using `django-parler` for your translations, you can query a specific language by[ using the `languages` method of the queryset](https://django-parler.readthedocs.io/en/stable/quickstart.html#filtering-translations):

```
qs = qs.translations(
    Q(headline__icontains=search) | Q(brief__icontains=search)
)
```

(note: I did not test this)

**Comment by OzodbekUSTECH** [comment]
@fsbraun, I also WANT TO search by the placeholder content, but I dont know how to do it properly :(

**Comment by fsbraun** [comment]
@OzodbekUSTECH Placholders can contain any kind of plugins with any custom model. If you're looking for a general search, I recommend [this blog article](https://www.django-cms.org/en/blog/2024/08/30/implementing-search-with-djangocms/). 

If you're fine only looking into text plugins only, consider searching their content (the `body` field contains HTML, tags can interfere with the filtering):
```python
language = get_language()
news_item_content_type = ContentType.objects.get_for_model(NewsItem)

# qs for news items that contain text plugins containing search in their body (if not obfuscated by HTML)
news_item_candidates = Text.objects.filter(
    language=language,
    body__icontains=search,
    placeholder__content_type=news_item_content_type
).values_list("placeholder__object_id", flat=True)  
qs = qs.filter(
    Q(translations__headline__icontains=search, translations__language_code=language)
    | Q(translations__brief__icontains=search, translations__language_code=language)
    | Q(pk__in=news_item_candidates)
).distinct()
```

**Comment by OzodbekUSTECH** [comment]
@fsbraun it's not working
```python
from django.contrib.contenttypes.models import ContentType
from django.utils.translation import get_language
from djangocms_text_ckeditor.models import Text

class NewsListView(TranslatableSlugMixin, ListView):
    model = NewsItem
    paginate_by = 20
    date_field = "news_date"
    allow_future = True
    allow_empty = True
    template_name = "news_list.html"

    def get_queryset(self, **kwargs):
        qs = super(NewsListView, self).get_queryset().filter(published=True)
        search = self.request.GET.get("search", None)
        if search:
            language = get_language()
            news_item_content_type = ContentType.objects.get_for_model(NewsItem)

            # qs for news items that contain text plugins containing search in their body (if not obfuscated by HTML)
            news_item_candidates = Text.objects.filter(
                language=language,
                body__icontains=search,
                placeholder__content_type=news_item_content_type
            ).values_list("placeholder__object_id", flat=True)
            qs = qs.filter(
                Q(translations__headline__icontains=search, translations__language_code=language)
                | Q(translations__brief__icontains=search, translations__language_code=language)
                | Q(pk__in=news_item_candidates)  # add the cadidates to the qs
            ).distinct()
        return qs
```

tried to print the news_item_candidates and it's empty :(
Besides, why did you use "pk__in", it should be like this: news_body__in or something like this

**Comment by fsbraun** [comment]
`news_item_candidates` is a list of `pk` of `NewsItem` objects containing placeholders with text plugins which in turn contain the search string.

The filter on the `Text` objects selects the language, the body containing the search string only if it belongs to a placeholder which is part of a `NewsItem` object. If it's empty, then your search did not find a text plugin with the searched content. 

As I said, I did not test it. I suggest playing around with the `news_item_candidates` QS in the Django shell to get a feel why it is empty.

**Comment by OzodbekUSTECH** [comment]
My bad,sorry! everything works! Thanks a lot!
