### ISSUE TITLE
[BUG] Clicking on “View on site” button in pages overview gets you to first instead of latest version

### ISSUE THREAD

**Issue by MacLake** [django-cms/django-cms#8037]
## Description

When opening a page, I expect the latest version to show up by default, which is what happens when I open a page via the front end menu. But when you open a page via the pages overview, you get to the first version. This is confusing for editors. And then they are tempted to click the blue highlighted “Revert” button without really knowing what this is doing: creating yet another version that is a copy of version 1.

## Steps to reproduce

1. Go to “Pages” overview with the page tree.
2. Click on the eye icon (“View on site”) of a page with multiple versions (djangocms-versioning).

## Expected behaviour

I expect to get to the latest version, no matter if published or not.

## Actual behaviour
The first version is shown, shown on the version menu: “Version #1 (Unpublished)”, on the top right there’s a blue “Revert” button.

## Additional information (CMS/Python/Django versions)

django CMS 4.1.3, django 5.1.2, Python 3.11

## Do you want to help fix this issue?

* [ ] Yes, I want to help fix this issue and I will join the channel #pr-reviews on [the Discord Server](https://discord-pr-review-channel.django-cms.org) to confirm with the community that a PR is welcome.
* [x] No, I only want to report the issue.

I might also help fixing the issue, but I currently don’t know where to look for.

**Comment by MacLake** [comment]
djangocms-versioning       2.0.2

The links on the versions list for the different versions of one page are like this:

- Draft: https://cms.passivehouse.com/en/admin/djangocms_versioning/pagecontentversion/1915/edit-redirect/
- …
- Version #8 https://cms.passivehouse.com/en/admin/cms/placeholder/object/352/preview/2734/
- Version #1, also linked on “Pages” overview: https://cms.passivehouse.com/en/admin/cms/placeholder/object/352/preview/2573/

**Comment by fsbraun** [comment]
That looks good. Can you try in the Django shell:
```
>>> from cms.models import PageContent
>>> page = PageContent.admin_manager.get(pk=2734).page
>>> PageContent.admin_manager.filter(page=page).latest_content().values_list("pk", flat=True)
<AdminContentAdminQuerySet [<some number>]>
```
What's the number shown? It should not be `2573` but rather be larger than `2734`.

**Comment by MacLake** [comment]
That looks good, too: 2735

```shell
>>> page = PageContent.admin_manager.get(pk=2734).page
>>> PageContent.admin_manager.filter(page=page).latest_content().values_list("pk", flat=True)
<AdminContentAdminQuerySet [2735]>
```

Btw: The version numbers in my last posting were converted to a symbol because of the `#`, I ’ve fixed that.
