### ISSUE TITLE
[BUG]Filled out the form to gain access to the Live Demo over 3 hours ago, and still no email.

### ISSUE THREAD

**Issue by pmi123** [django-cms/django-cms#8042]
## Description
Filled out the form to gain access to the Live Demo over 3 hours ago, and still no email.

## Steps to reproduce
Fill out form at https://www.django-cms.org/en/django-cms-demo/ and wait.

## Expected behaviour
"Receive a notification immediately with the link"

## Actual behaviour
crickets...also checked my SPAM folder

## Additional information (CMS/Python/Django versions)
Using Firefox 131.0.3

## Do you want to help fix this issue?
I wojld like to gain access to the live demo

* [ ] Yes, I want to help fix this issue and I will join the channel #pr-reviews on [the Discord Server](https://discord-pr-review-channel.django-cms.org) to confirm with the community that a PR is welcome.
* [ ] No, I only want to report the issue.

**Comment by macolo** [comment]
Hi @pmi123 - I see an email that went out to m****@p******g.biz at 23-10-2024 19:32:52?

**Comment by pmi123** [comment]
Hi @macolo !
That is correct. Sorry for the confusion. I just wanted to keep moving forward with my work. 

After I submitted the bug report, I filled out the form using Chromium web browser v 129.0.6668.100 and I received the email within a few minutes. I never received an email from the form I filled out using Firefox.

**Comment by macolo** [comment]
Thanks for the info. We will test and try to reproduce in firefox (most recent version).

**Comment by macolo** [comment]
We have tested the form on most recent versions of Chrome, Firefox and Safari (Mac OS X) and it appears to be working.

Google reCaptcha reports also do not show anything out of the ordinary and we have been receiving several hundred demo signups so far.

<img width="556" alt="image" src="https://github.com/user-attachments/assets/37d26e3d-3dcb-4b00-a3cd-7850faf9352e">

For now I'd like to close the issue. If you find additional info that can help us resolve your problem please let us know here and reopen the issue. Many thanks for you support and all the best, Mario
