### ISSUE TITLE
[BUG] `cms` command should not raise AttributeError

### ISSUE THREAD

**Issue by mrbazzan** [django-cms/django-cms#8045]
## Description

`python3 manage.py cms` raises `AttributeError: 'Namespace' object has no attribute 'settings'`.
Rather than raising an exception, informing the user to add one of the positional args should be better.

## Steps to reproduce

```python
cd django-cms
source .venv/bin/activate
python -m manage cms
```

## Actual behaviour
```
AttributeError: 'Namespace' object has no attribute 'settings'
```

## Expected behaviour
...

## Do you want to help fix this issue?

* [x] Yes, I want to help fix this issue and I will join the channel #pr-reviews on [the Discord Server](https://discord-pr-review-channel.django-cms.org) to confirm with the community that a PR is welcome.
* [ ] No, I only want to report the issue.

**Comment by fsbraun** [comment]
@mrbazzan Thanks for raising this! 

Are these two points related? If not, let us split this up into
1. A feature request
2. A bug report
