### ISSUE TITLE
[BUG] CMSApp without a name raises misleading error

### ISSUE THREAD

**Issue by halitcelik** [django-cms/django-cms#8055]
## Description
If a CMSApp is registered without a name we get an error saying "< is not supported between str and NoneType" which is kind of misleading and not very helpful. 
This is in apphook_pool we have a sorted function that sorts registered CMSApps with their names. I was wondering if we could fall back to class name, raise an error with another message or just leave it as it is.
## Steps to reproduce

1. Register a CMSApp without name
2. Runserver

## Expected behaviour
Either a fallback to class name or an error message indicating the "ClassName is missing a name"
## Actual behaviour
An error saying "< is not supported between str and NoneType" is raised.
This is in apphooks_pool.py line 82: https://github.com/django-cms/django-cms/blob/e8d1abf72034ea853f68c07a80e15bfea5babcb2/cms/apphook_pool.py#L82
Where we try to sort the registered apps with their names but one or more has None as name.
 

## Do you want to help fix this issue?

* [x] Yes, I want to help fix this issue and I will join the channel #pr-reviews on [the Discord Server](https://discord-pr-review-channel.django-cms.org) to confirm with the community that a PR is welcome.
* [ ] No, I only want to report the issue.

**Comment by fsbraun** [comment]
@halitcelik Thanks for reporting this and volunteering to fix it!

Maybe https://github.com/django-cms/django-cms/blob/e8d1abf72034ea853f68c07a80e15bfea5babcb2/cms/apphook_pool.py#L78

should just read
```
 hooks.append((app_name, app.name or app_name)) 
```
This would fall back to `app_name` if the `name` property is `None`.

**Comment by fsbraun** [comment]
For the user, it obviously improves the UX if they see a (potentially localized) app name.

**Comment by halitcelik** [comment]
I was thinking, at the moment there is an error raised when the name is not defined. Maybe we keep raising an error but raise it with a proper message so that if anywhere else in the code we assume this name not to be None, it will continue working but if we fall back silently we might encounter another place where we rely on the name. I was thinking of preparing somehting like this:
```python
if app.name is None:
    raise ImproperlyConfigured(
        'CMS application must define name '
        'but %r does not have one' % app_name
    )
```
So that we get the error during development.
