### ISSUE TITLE
[BUG] Sites not in pageadmin context. Dropdown for Sites is empty.

### ISSUE THREAD

**Issue by h-peters** [django-cms/django-cms#8063]
## Description

Hello. The dropdown for selecting sites in the pageadmin is empty. The tree context does not have key "sites" anymore.
But the template "admin/cms/page/tree/base.html" is trying to iterate over them `{% for site in tree.sites %}`

## Steps to reproduce

1. Go to /admin/cms/pagecontent/
2. Click on the three dots next to the search

## Expected behaviour

A list of sites

## Actual behaviour

An empty list of sites

## Additional information (CMS/Python/Django versions)

Django==5.1.2
django-cms==4.1.3

**Comment by fsbraun** [comment]
Oh, well spotted! I'll have a look! Thanks for reporting!
