### ISSUE TITLE
Stored XSS Vulnerability Found

### ISSUE THREAD

**Issue by iltoxsec** [django-cms/django-cms#8072]
Hi Django CMS Team,

I've discovered a stored XSS vulnerability in the product. Could you let me know where I can send the details securely?

Thanks.

**Comment by marksweb** [comment]
If you think you have discovered a security issue in our code, please report it privately, by emailing us at [security@django-cms.org](mailto:security%40django-cms.org).
Please do not raise it in any public forum until we have had a chance to deal with it.
