### ISSUE TITLE
Stored XSS Report

### ISSUE THREAD

**Issue by alii76tt** [django-cms/django-cms#8074]
Hi Django CMS Team,

I have discovered a stored XSS vulnerability in the product and previously reported it via email to [security@django-cms.org](mailto:security@django-cms.org). However, I have not yet received a response or seen any patch addressing the issue.

Could you please let me know the best way to securely send the full details of this vulnerability, or if there is an alternative method for reporting security issues?

Thanks.

**Comment by marksweb** [comment]
When did you send the email?

It's not filtered through to our shared comms yet.

**Comment by marksweb** [comment]
Ok found your message. We'll look into this. Thanks again.
