### ISSUE TITLE
Why I use it, after the installation, but there is no static files in it?

### ISSUE THREAD

**Issue by zongbb1983** [django-cms/django-cms#8083]
## Why I use it, after the installation, but there is no static files in it?

When I first finish it, all seemed well. But there is no static files and the css files are also missed. Why? Can you give your hand? Thanks very much! Really! 

* [ ] Yes, I want to help fix this issue and I will join the channel #pr-reviews on [the Discord Server](https://discord-pr-review-channel.django-cms.org) to confirm with the community that a PR is welcome.
* [x] No, I only want to report the issue.

**Comment by zongbb1983** [comment]
![image](https://github.com/user-attachments/assets/79a30beb-ddd8-4ec8-8fc9-aa012fec2906)

This is what my browser show. Thanks.

**Comment by marksweb** [comment]
What are you static file settings?

**Comment by zongbb1983** [comment]
You mean what I set the static file in the setting.py file?
"# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
"
It is just as the setting itself, no changed.

**Comment by zongbb1983** [comment]
> What are you static file settings?

What is the reason? There are no static files at all, just after I install the system. Is this the BUG? Thanks.

**Comment by fsbraun** [comment]
@zongbb1983 Serving static files differ depending on how you serve your project:
* `./manage.py runserver` should take the static files directly from the apps' static folders if `DEBUG = True`
* otherwise you need to run `./manage.py collectstatic` to copy static files into your static files root

How did you install django CMS?

**Comment by zongbb1983** [comment]
Well, I have excute the both commands, but still no static files was seen. . .

**Comment by zongbb1983** [comment]
"Installing django CMS by hand"

**Comment by fsbraun** [comment]
Can you share your settings?

**Comment by zongbb1983** [comment]
Of course! 

"""
Django settings for myproject project.

Generated by 'djangocms' command using django CMS 4.1.1 and Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of Django settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/

For the list of django CMS settings and their values, see
https://docs.django-cms.org/en/release-4.1.x/reference/configuration.html
"""

import os
from pathlib import Path

from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$@^s@pc2&k90yy0w$!vu^m69a)tig&l87m1t6rq06sc9#wf0b5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'djangocms_admin_style',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
     # CMS base apps
    'cms',
    'menus',

    'djangocms_text',
    'djangocms_alias',
    'djangocms_versioning',

    'sekizai',
    'treebeard',
    'parler',

    'filer',
    'easy_thumbnails',
    'djangocms_frontend',
    'djangocms_frontend.contrib.accordion',
    'djangocms_frontend.contrib.alert',
    'djangocms_frontend.contrib.badge',
    'djangocms_frontend.contrib.card',
    'djangocms_frontend.contrib.carousel',
    'djangocms_frontend.contrib.collapse',
    'djangocms_frontend.contrib.content',
    'djangocms_frontend.contrib.grid',
    'djangocms_frontend.contrib.icon',
    'djangocms_frontend.contrib.image',
    'djangocms_frontend.contrib.jumbotron',
    'djangocms_frontend.contrib.link',
    'djangocms_frontend.contrib.listgroup',
    'djangocms_frontend.contrib.media',
    'djangocms_frontend.contrib.navigation',
    'djangocms_frontend.contrib.tabs',
    'djangocms_frontend.contrib.utilities',

    # new added
    "djangocms_file",
    "djangocms_picture",
    "djangocms_video",
    "djangocms_googlemap",
    "djangocms_snippet",
    "djangocms_style",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django.middleware.locale.LocaleMiddleware",  # not installed by default
    'cms.middleware.user.CurrentUserMiddleware',
    'cms.middleware.page.CurrentPageMiddleware',
    'cms.middleware.toolbar.ToolbarMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'cms.middleware.language.LanguageCookieMiddleware',
    'cms.middleware.utils.ApphookReloadMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': ['templates'],
        'DIRS': [
            os.path.join(BASE_DIR, "myproject", "templates"),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'sekizai.context_processors.sekizai',
                'cms.context_processors.cms_settings',
            ],
        },
    },
]

THUMBNAIL_PROCESSORS = (
    'easy_thumbnails.processors.colorspace',
    'easy_thumbnails.processors.autocrop',
    'filer.thumbnail_processors.scale_and_crop_with_subject_location',
    'easy_thumbnails.processors.filters',
)

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ("en", _("English")),
    ("de", "German"),
    ("it", "Italian"),
    # Add additional languages here
]

TIME_ZONE = 'UTC'

USE_I18N = True
USE_L10N = True
USE_THOUSAND_SEPARATOR = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# This is a django CMS 4 template

CMS_CONFIRM_VERSION4 = True

# django CMS requires the site framework
# https://docs.django-cms.org/en/release-4.1.x/how_to/multi-site.html

SITE_ID = 1

# A base template is part of this setup
# https://docs.django-cms.org/en/release-4.1.x/reference/configuration.html#cms-templates

# CMS_TEMPLATES = (
#     ("base.html", _("Standard")),
# )

CMS_TEMPLATES = [
    ('home.html', 'Home page template'),
]

# Enable permissions
# https://docs.django-cms.org/en/release-4.1.x/topics/permissions.html

CMS_PERMISSION = True

# Allow admin sidebar to open admin URLs

X_FRAME_OPTIONS = 'SAMEORIGIN'

# Enable inline editing with djangocms-text
# https://github.com/django-cms/djangocms-text#inline-editing-feature

TEXT_INLINE_EDITING = True

# Allow deletion of version objects
# https://djangocms-versioning.readthedocs.io/en/latest/settings.html#DJANGOCMS_VERSIONING_ALLOW_DELETING_VERSIONS

DJANGOCMS_VERSIONING_ALLOW_DELETING_VERSIONS = True

# Add project-wide static files directory
# https://docs.djangoproject.com/en/5.0/ref/settings/#staticfiles-dirs

STATICFILES_DIRS = [
    BASE_DIR / "myproject" / "static",
]

INTERNAL_IPS = [
    "127.0.0.1",
]

# Add project-wide static files directory
# https://docs.djangoproject.com/en/5.0/ref/settings/#media-root

MEDIA_URL = "media/"
MEDIA_ROOT = str(BASE_DIR.parent / "media")

**Comment by fsbraun** [comment]
OK, that comes from the `djangocms myproject` command. I just tested this and it worked just fine. I assume you are using the `./manage.py runserver` command in the `myproject` dir. Do you see any error messages (404) on the runserver output? Something like
```
[22/Nov/2024 08:10:08] "GET /static/cms/css/4.1.4/cms.base.css HTTP/1.1" 404
```

`./manage.py collectstatic` should fail since you have not set `STATIC_ROOT` in your settings.

**Comment by zongbb1983** [comment]
Yeah, I have done this, but now it could not run again. "./manage.py collectstatic". What's the reason?

**Comment by zongbb1983** [comment]
It shows some errors, but I could not see clearly. Thanks.

**Comment by fsbraun** [comment]
Collect static copies the static files into a static root directory for production. From there they are typically served directly by the webserver for performance reasons. See https://docs.djangoproject.com/en/5.1/howto/static-files/deployment/ and more generally on static files: https://docs.djangoproject.com/en/5.1/howto/static-files/

With your settings.py this directory is not configured.

**Comment by zongbb1983** [comment]
Every request, there is a 304 error... 
![image](https://github.com/user-attachments/assets/4a29c2d7-c4d8-40b8-8bb2-cebb79eafd92)

**Comment by zongbb1983** [comment]
Every request, there is a 304 error... 
![image](https://github.com/user-attachments/assets/4a29c2d7-c4d8-40b8-8bb2-cebb79eafd92)

**Comment by fsbraun** [comment]
Interesting. Try clearing the browser cache!

**Comment by zongbb1983** [comment]
Now, it is done. But I can see the staitc file, but the computer could not find them. What is the reason? Should I change and variable in the settings.py file? Thanks.

**Comment by fsbraun** [comment]
Not sure what the reason was. Something got "stuck" with the browser cache. Maybe with a different project also served locally, (127.0.0.1)? No need to change anything. No bug here... 🙌

**Comment by zongbb1983** [comment]
I mean if I set the ROOT like this 

STATIC_URL = 'static/'
STATIC_ROOT = STATIC_URL

Is it okay? Thanks.
