### ISSUE TITLE
[DOC]Is the CMS so simple? I want to use it to build a website. But what I can see is just like this...

### ISSUE THREAD

**Issue by zongbb1983** [django-cms/django-cms#8091]
## Description
I want to use it to build a website. But what I can see is just like this... Are there any places to improve it? Thanks a lot. 

![image](https://github.com/user-attachments/assets/1d8fdcf3-79d4-441b-ab04-d77cc8628ccc)

* [* ] Yes, I want to help fix this issue and I will join the channel #documentation on our [Discord Server](https://discord-docs-channel.django-cms.org) to confirm with the team that a PR is welcome.
* [ ] No, I only want to report the issue.

**Comment by fsbraun** [comment]
@zongbb1983 Go to "page contents" and add a page. For a quick intro also see here: https://www.youtube.com/watch?v=wcCGTJhqPOE
