### ISSUE TITLE
[BUG] Language not being persisted for page placeholder preview and edit

### ISSUE THREAD

**Issue by CarwynNelson** [django-cms/django-cms#8100]
Related to https://github.com/django-cms/django-cms/issues/8087 where are now getting the same error message as before.

## Description
- When previewing a page in language other than users default language
- We get the above error
- However when set query param to the expected language the preview and edit work

## Steps to reproduce

1. Select a language from the language drop down that is not the user's default
2. Create a page, filling in the required fields
3. Click save, this will redirect back to the page list view
4. Click the eye (view on site) button
5. Observe the AttributeError "'EmptyPageContent' object has no attribute '_state'"

Video:

https://github.com/user-attachments/assets/895d675f-84ba-4952-b67e-f5f241dd11a4

## Expected behaviour

User is able to preview and edit page in the language they created it in

## Actual behaviour

User is shown an AttributeError "'EmptyPageContent' object has no attribute '_state'"

## Screenshots

![image](https://github.com/user-attachments/assets/4ab2e319-ced9-4efa-a0cc-8f94c61a26f4)

## Additional information (CMS/Python/Django versions)

Python: 3.11.9
Django: 4.2.17
Django CMS: 4.1.4

We have managed to work around this locally by patching the `cms.toolbar.utils.get_object_preview_url` and `cms.toolbar.utils.get_object_edit_url` functions to append `?language={language}` to the URL.

## Do you want to help fix this issue?

* [X] Yes, I want to help fix this issue and I will join the channel #pr-reviews on [the Discord Server](https://discord-pr-review-channel.django-cms.org) to confirm with the community that a PR is welcome.
* [ ] No, I only want to report the issue.

**Comment by fsbraun** [comment]
@CarwynNelson Thanks for the bug report and the detailed and helpful explanations. The fix for #8087 has not been released yet. Would you have a chance to test your scenario with the latest `release/4.1.x` branch? (You can install it locally using `pip install git+https://github.com/django-cms/django-cms@release/4.1.x`) 

If you can find the time, the feedback would help to see if the fix covers your case.

**Comment by CarwynNelson** [comment]
> @CarwynNelson Thanks for the bug report and the detailed and helpful explanations. The fix for #8087 has not been released yet. Would you have a chance to test your scenario with the latest `release/4.1.x` branch? (You can install it locally using `pip install git+https://github.com/django-cms/django-cms@release/4.1.x`)
> 
> If you can find the time, the feedback would help to see if the fix covers your case.

Ah my bad! I saw our version of django-cms get updated to 4.1.4 and had assumed that it included the fix you had put together.

I have tested on teh `release/4.1.x` branch and all appears to be working correctly. I will close this issue.

**Comment by fsbraun** [comment]
@CarwynNelson That's great news!
