### ISSUE TITLE
Tutorial in latest/develop may be in the incorrect order.

### ISSUE THREAD

**Issue by kezabelle** [django-cms/django-cms#816]
As part of the getting started tutorial, it is asked that the user add the _CMS_TEMPLATES_ directive to the settings file being used, but later on, it requires the user do 
`manage.py syncdb
manage.py migrate
manage.py runserver`

which should result in cms welcome page being displayed. Instead, the user should get an error (if this is reproducible, anyway) because the template hasn't been created yet:

**File "blah/blah/django/template/loader.py", line 138, in find_template
    raise TemplateDoesNotExist(name)
django.template.base.TemplateDoesNotExist: template_1.html**

Adding this file gets everything back on track.

**Comment by ynikitenko** [comment]
Followed the official tutorials.
Faced the same problem, but instead of removing the app's name, had to add that to the path.
