### ISSUE TITLE
NoReverseMatch

### ISSUE THREAD

**Issue by ghost** [django-cms/django-cms#82]
Reverse for 'pages-root' with arguments '()' and keyword arguments '{}' not found

Exception raises at "/admin/cms/page/add/" and "/admin/cms/page/1/"

"/admin/cms/page/" page works well.

urlpatterns = patterns(
    (r'^admin/(._)', admin.site.root),
    # to serve media static files 
    (r'^%s(?P<path>._)$' % settings.MEDIA_URL.lstrip('/'),
        django.views.static.serve, {'document_root': settings.MEDIA_ROOT}),
)

P.S. may be you should add coping of js-files into static folder in your installation instruction?

**Comment by Max201** [comment]
Why close. I have the same problem!
